import React, { useState } from "react";
import { Document } from "@/types/common";
import { AdminDocumentUpload } from "./AdminDocumentUpload";
import { AdminDocumentTable } from "./AdminDocumentTable";
import { DocumentCategoryGroup } from "./DocumentCategoryGroup";
import { EditDocumentDialog } from "./EditDocumentDialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { FilterX, Search, ArrowUpDown, Upload, ArrowLeft } from "lucide-react";
import { Input } from "@/components/ui/input";
import { useDocumentCategories } from "@/hooks/document-management/useDocumentCategories";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { convertToCommonCategories } from "@/utils/document/documentTypeUtils";
import { AdminSection } from "@/components/admin/ui/AdminPage";

interface Props { userId:string; userName:string; userEmail:string; documents:Document[]; isLoadingDocuments:boolean; loadingDocumentIds:Set<string>; handleDownload:(document:Document)=>Promise<void>; handleDeleteDocument:(documentId:string)=>Promise<void>; }

export const AdminDocumentManager:React.FC<Props>=({userId,userName,userEmail,documents,isLoadingDocuments,loadingDocumentIds,handleDownload,handleDeleteDocument})=>{
 const [activeTab,setActiveTab]=useState<'documents'|'upload'>('documents');
 const [sortOrder,setSortOrder]=useState<'asc'|'desc'>('desc'),[searchQuery,setSearchQuery]=useState(''),[filterCategory,setFilterCategory]=useState<string|null>(null);
 const [editingDocument,setEditingDocument]=useState<Document|null>(null),[isEditDialogOpen,setIsEditDialogOpen]=useState(false),[documentToDelete,setDocumentToDelete]=useState<Document|null>(null),[isDeleteDialogOpen,setIsDeleteDialogOpen]=useState(false);
 const {categories}=useDocumentCategories();const {toast}=useToast();const commonCategories=convertToCommonCategories(categories);
 const sortedDocuments=[...documents].sort((a,b)=>sortOrder==='desc'?new Date(b.uploaded_at).getTime()-new Date(a.uploaded_at).getTime():new Date(a.uploaded_at).getTime()-new Date(b.uploaded_at).getTime()).filter(doc=>(!searchQuery||[doc.name,doc.original_filename,doc.observations].some(v=>String(v||'').toLowerCase().includes(searchQuery.toLowerCase())))&&(!filterCategory||doc.category===filterCategory));
 const documentsByCategory=categories.reduce((acc,category)=>{acc[category.id]=sortedDocuments.filter(doc=>doc.category===category.id);return acc},{} as Record<string,Document[]>);
 const uncategorized=sortedDocuments.filter(doc=>!doc.category||!categories.some(cat=>cat.id===doc.category));
 const saveDocument=async(updated:Document)=>{const {error}=await supabase.from('documents').update({name:updated.name,category:updated.category,subcategory:updated.subcategory,observations:updated.observations,expires_at:updated.expires_at}).eq('id',updated.id);if(error)toast({variant:'destructive',title:'Erro ao salvar alterações',description:error.message});else toast({title:'Documento atualizado',description:'As alterações foram salvas com sucesso.'})};
 return <div className="ws-admin-polish space-y-4">
  <AdminSection className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="truncate text-sm font-semibold">{userName}</p>{userEmail&&<p className="truncate text-xs text-muted-foreground">{userEmail}</p>}</div>{activeTab==='documents'?<Button className="ws-stage4-primary-action" onClick={()=>setActiveTab('upload')}><Upload className="mr-2 h-4 w-4"/>Enviar documento</Button>:<Button variant="outline" className="h-11 px-5" onClick={()=>setActiveTab('documents')}><ArrowLeft className="mr-2 h-4 w-4"/>Voltar aos documentos</Button>}</div></AdminSection>
  {activeTab==='upload'?<AdminSection className="p-6"><AdminDocumentUpload userId={userId} onDocumentUploaded={()=>setActiveTab('documents')}/></AdminSection>:<AdminSection>
   <div className="flex flex-col gap-3 border-b border-border/50 p-4 lg:flex-row lg:items-center"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Buscar documentos..." className="pl-9"/></div><select value={filterCategory||''} onChange={e=>setFilterCategory(e.target.value||null)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">Todas as categorias</option>{categories.map(cat=><option key={cat.id} value={cat.id}>{cat.name}</option>)}</select><Button variant="outline" size="icon" onClick={()=>setSortOrder(v=>v==='desc'?'asc':'desc')} title="Alterar ordem"><ArrowUpDown className="h-4 w-4"/></Button><Button variant="ghost" size="sm" onClick={()=>{setSearchQuery('');setFilterCategory(null)}} disabled={!searchQuery&&!filterCategory}><FilterX className="mr-2 h-4 w-4"/>Limpar</Button></div>
   <div className="px-4 pt-3 text-xs text-muted-foreground">{sortedDocuments.length} documento{sortedDocuments.length===1?'':'s'}</div>
   <div className="p-4"><div className="hidden md:block">{Object.entries(documentsByCategory).filter(([,docs])=>docs.length).map(([id,docs])=>{const category=commonCategories.find(c=>c.id===id);return category?<DocumentCategoryGroup key={id} category={category} documents={docs} loadingDocumentIds={loadingDocumentIds} onDownload={handleDownload} onEdit={doc=>{setEditingDocument(doc);setIsEditDialogOpen(true)}} onDelete={doc=>{setDocumentToDelete(doc);setIsDeleteDialogOpen(true)}}/>:null})}{uncategorized.length>0&&<DocumentCategoryGroup category={{id:'uncategorized',name:'Sem categoria',color:'#6B7280',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}} documents={uncategorized} loadingDocumentIds={loadingDocumentIds} onDownload={handleDownload} onEdit={doc=>{setEditingDocument(doc);setIsEditDialogOpen(true)}} onDelete={doc=>{setDocumentToDelete(doc);setIsDeleteDialogOpen(true)}}/>}{sortedDocuments.length===0&&!isLoadingDocuments&&<div className="py-12 text-center text-sm text-muted-foreground">Nenhum documento encontrado.</div>}</div><div className="md:hidden"><AdminDocumentTable documents={sortedDocuments} isLoading={isLoadingDocuments} loadingDocumentIds={loadingDocumentIds} onDownload={handleDownload} onDelete={doc=>{setDocumentToDelete(doc);setIsDeleteDialogOpen(true)}} onEdit={doc=>{setEditingDocument(doc);setIsEditDialogOpen(true)}} sortOrder={sortOrder} onToggleSort={()=>setSortOrder(v=>v==='desc'?'asc':'desc')} categories={commonCategories}/></div></div>
  </AdminSection>}
  <EditDocumentDialog open={isEditDialogOpen} document={editingDocument} categories={commonCategories} onClose={()=>{setIsEditDialogOpen(false);setEditingDocument(null)}} onSave={saveDocument}/>
  <AlertDialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir documento?</AlertDialogTitle><AlertDialogDescription>O documento “{documentToDelete?.name}” será removido. Esta ação não pode ser desfeita.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={()=>{if(documentToDelete)void handleDeleteDocument(documentToDelete.id);setDocumentToDelete(null)}}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
};
