import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.0";
import { Buffer } from "node:buffer";
import { lerCertificado } from "npm:nfse-node@0.3.2/certificado";
import { buildNativeNfeXml } from "../dfe-issue-native/xml.ts";
import { signNfeXml } from "../dfe-issue-native/sign.ts";
import { authorizeNfeNative, parseAuthorization } from "../dfe-issue-native/sefaz.ts";
import { addNfceSupplement } from "../dfe-issue-native/qrcode.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const digits=(v:unknown)=>String(v??"").replace(/\D/g,"");
const num=(v:unknown)=>{const n=Number(String(v??"").replace(/\D/g,""));return Number.isFinite(n)?n:0};
function validCpf(value:unknown){const s=digits(value);if(s.length!==11||/^(\d)\1{10}$/.test(s))return false;const d=[...s].map(Number);let sum=0;for(let i=0;i<9;i++)sum+=d[i]*(10-i);let a=(sum*10)%11;if(a===10)a=0;if(a!==d[9])return false;sum=0;for(let i=0;i<10;i++)sum+=d[i]*(11-i);let b=(sum*10)%11;if(b===10)b=0;return b===d[10]}
function validCnpj(value:unknown){const s=digits(value);if(s.length!==14||/^(\d)\1{13}$/.test(s))return false;const d=[...s].map(Number),calc=(vals:number[],w:number[])=>{const r=vals.reduce((a,v,i)=>a+v*w[i],0)%11;return r<2?0:11-r};const a=calc(d.slice(0,12),[5,4,3,2,9,8,7,6,5,4,3,2]);const b=calc([...d.slice(0,12),a],[6,5,4,3,2,9,8,7,6,5,4,3,2]);return d[12]===a&&d[13]===b}
function validBrDocument(value:unknown){const s=digits(value);return s.length===11?validCpf(s):s.length===14?validCnpj(s):false}
async function loadCertificate(admin:any,p:any,orgId:string){const {data:bundle}=await admin.rpc("get_saas_certificate_bundle",{_org_id:orgId});if(bundle?.pfx_base64&&bundle?.password)return lerCertificado(Buffer.from(String(bundle.pfx_base64),"base64"),String(bundle.password));if(!p.certificate_storage_path)throw new Error("Configure o certificado A1");const {data:file,error:de}=await admin.storage.from("saas-private").download(p.certificate_storage_path);if(de||!file)throw new Error("Não foi possível carregar o certificado A1");const {data:pass,error:pe}=await admin.rpc("get_saas_certificate_password",{_org_id:orgId});if(pe||!pass)throw new Error("Senha do certificado não configurada");return lerCertificado(Buffer.from(await file.arrayBuffer()),String(pass))}
async function context(req:Request,orgId:string){const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const auth=req.headers.get("Authorization");if(!auth)throw new Error("Não autenticado");const {data:{user}}=await admin.auth.getUser(auth.replace("Bearer ",""));if(!user)throw new Error("Não autenticado");const {data:m}=await admin.from("organization_members").select("role,status").eq("organization_id",orgId).eq("user_id",user.id).eq("status","active").maybeSingle();if(!m||!["owner","admin","member"].includes(m.role))throw new Error("Sem permissão para emitir");const {data:p}=await admin.from("saas_company_fiscal_profiles").select("*").eq("organization_id",orgId).order("created_at").limit(1).maybeSingle();if(!p)throw new Error("Configure os dados fiscais da empresa");const cert=await loadCertificate(admin,p,orgId);return{admin,user,p,cert}}
function validate(raw:any,model:"55"|"65"){const e:string[]=[];if(!validCnpj(raw.cnpjEmitente))e.push("CNPJ do emitente inválido");if(!digits(raw.ie))e.push("Inscrição estadual obrigatória");if(!String(raw.razaoSocial||"").trim())e.push("Razão social obrigatória");if(digits(raw.codigoMunicipio).length!==7)e.push("Código IBGE do emitente inválido");if(digits(raw.ncm).length!==8)e.push("NCM deve ter 8 dígitos");if(digits(raw.cfop).length!==4)e.push("CFOP deve ter 4 dígitos");if(!(Number(raw.quantidade)>0))e.push("Quantidade inválida");if(!(Number(raw.valorUnitario)>0))e.push("Valor unitário inválido");const dest=digits(raw.destDocumento);if(model==="55"&&!dest)e.push("NF-e exige destinatário");if(dest&&!validBrDocument(dest))e.push(dest.length===14?"CNPJ do destinatário inválido":"CPF do destinatário inválido");if(model==="55"&&digits(raw.destCodigoMunicipio).length!==7)e.push("Código IBGE do destinatário inválido");if(model==="55"&&!String(raw.destUF||"").match(/^[A-Z]{2}$/))e.push("UF do destinatário inválida");return e}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});try{const body=await req.json(),orgId=String(body.organization_id||"");if(!orgId)return out({error:"Organização obrigatória"},422);const {admin,user,p,cert}=await context(req,orgId),environment=p.fiscal_environment==="production"?"production":"homologation",expected=String(body.expected_environment||"");if(expected&&expected!==environment)return out({error:`Ambiente fiscal mudou para ${environment==="production"?"produção":"homologação"}. Recarregue a emissão antes de transmitir.`},409);const model:"55"|"65"=body.model==="55"?"55":"65";const raw={...(body.data||{}),environment,cnpjEmitente:digits(p.tax_id||body.data?.cnpjEmitente),razaoSocial:p.legal_name||body.data?.razaoSocial,nomeFantasia:p.trade_name||p.legal_name||body.data?.nomeFantasia,ie:p.state_registration||body.data?.ie,crt:p.crt||body.data?.crt||"1",codigoMunicipio:p.city_ibge_code||body.data?.codigoMunicipio,nomeMunicipio:p.city||body.data?.nomeMunicipio,logradouro:p.street||body.data?.logradouro,numeroEndereco:p.street_number||body.data?.numeroEndereco,complemento:p.complement||body.data?.complemento,bairro:p.district||body.data?.bairro,cep:p.postal_code||body.data?.cep,telefone:p.phone||body.data?.telefone};const errors=validate(raw,model);if(errors.length)return out({error:"Corrija os dados fiscais antes de transmitir",errors},422);if(cert.titular.cnpj&&digits(cert.titular.cnpj)!==digits(raw.cnpjEmitente))return out({error:"CNPJ do certificado não corresponde ao emitente",errors:[`Certificado: ${digits(cert.titular.cnpj)} · Empresa: ${digits(raw.cnpjEmitente)}`]},422);
const docType=model==="55"?"nfe":"nfce",series=String(raw.serie||"1"),requested=num(raw.numeroNota);const {data:known}=await admin.from("saas_fiscal_emissions").select("number").eq("organization_id",orgId).eq("document_type",docType).eq("series",series).in("status",["authorized","cancelled"]);const maxKnown=Math.max(0,...(known||[]).map((x:any)=>num(x.number)));if(requested>0&&requested<=maxKnown)return out({error:"Numeração já utilizada",errors:[`A série ${series} já possui documento autorizado ou cancelado até o número ${maxKnown}. Use o número ${maxKnown+1} ou sincronize novamente o histórico fiscal.`],suggested_number:maxKnown+1,last_known_number:maxKnown},409);
const built=buildNativeNfeXml(model,raw),signed=addNfceSupplement(signNfeXml(built.xml,cert.chavePrivadaPem,cert.certificadoPem),model,built.chaveAcesso,environment),action=String(body.action||"preview");if(action==="preview")return out({ok:true,valid:true,model,environment,chaveAcesso:built.chaveAcesso,total:built.total,xml:signed,suggested_number:Math.max(requested,maxKnown+1)});if(action!=="issue")return out({error:"Ação inválida"},400);const remote=await authorizeNfeNative(cert,model,signed,environment),parsed=parseAuthorization(remote.text),key=parsed.protocol.chNFe||built.chaveAcesso,status=parsed.authorized?"authorized":"rejected";const {data:em,error:save}=await admin.from("saas_fiscal_emissions").insert({organization_id:orgId,user_id:user.id,document_type:docType,status,environment,number:String(raw.numeroNota||""),series,access_key:key,protocol:parsed.protocol.nProt||null,recipient_name:String(raw.destNome||"")||null,recipient_tax_id:digits(raw.destDocumento)||null,total:Number(built.total||0),payload:raw,response:parsed,xml:signed,authorized_at:parsed.authorized?new Date().toISOString():null,source:"system"}).select().single();if(save)console.error(save);if(parsed.authorized){const col=model==="55"?"next_number_nfe":"next_number_nfce",next=Math.max(requested+1,maxKnown+1);await admin.from("saas_company_fiscal_profiles").update({[col]:next,updated_at:new Date().toISOString()}).eq("id",p.id)}return out({ok:parsed.authorized,authorized:parsed.authorized,environment,chaveAcesso:key,total:built.total,protocol:parsed.protocol.nProt,response:parsed,xml:signed,emission:em,endpoint:remote.endpoint})}catch(e){console.error(e);return out({error:e instanceof Error?e.message:String(e)},500)}});