import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.0";
import forge from "npm:node-forge@1.3.1";
import { SignedXml } from "npm:xml-crypto@6.1.2";
import https from "node:https";
import { Buffer } from "node:buffer";

const E=new TextEncoder(),D=new TextDecoder(),B=(v:string)=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const dg=(v:unknown)=>String(v??"").replace(/\D/g,"");
async function vk(){const s=Deno.env.get("ACCOUNTING_ENGINE_SESSION_SECRET")||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!s)throw Error("secret_missing");const h=await crypto.subtle.digest("SHA-256",E.encode(`ws-fiscal-vault:${s}`));return crypto.subtle.importKey("raw",h,{name:"AES-GCM"},false,["decrypt"])}
async function dec(c:string,iv:string){return D.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:B(iv)},await vk(),B(c)))}
function pems(pfx64:string,pass:string){const p12=forge.pkcs12.pkcs12FromAsn1(forge.asn1.fromDer(forge.util.decode64(pfx64)),false,pass);let key:any=null;const certs:any[]=[];for(const sc of p12.safeContents)for(const bag of sc.safeBags){if(!key&&bag.key)key=bag.key;if(bag.cert)certs.push(bag.cert)}if(!key||!certs.length)throw Error("pfx_parse_failed");return{key:forge.pki.privateKeyToPem(key),cert:forge.pki.certificateToPem(certs[0])}}
function nowBr(){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Maceio',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date()),get=(t:string)=>parts.find(p=>p.type===t)?.value||'';return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}:${get('second')}-03:00`}
function sign(cnpj:string,ch:string,key:string,cert:string){const id=`ID210210${ch}01`,xml=`<envEvento xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><idLote>${Date.now()}</idLote><evento versao="1.00"><infEvento Id="${id}"><cOrgao>91</cOrgao><tpAmb>1</tpAmb><CNPJ>${cnpj}</CNPJ><chNFe>${ch}</chNFe><dhEvento>${nowBr()}</dhEvento><tpEvento>210210</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Ciencia da Operacao</descEvento></detEvento></infEvento></evento></envEvento>`,s=new SignedXml({privateKey:key,publicCert:cert});s.signatureAlgorithm='http://www.w3.org/2000/09/xmldsig#rsa-sha1';s.canonicalizationAlgorithm='http://www.w3.org/TR/2001/REC-xml-c14n-20010315';s.addReference({xpath:"//*[local-name()='infEvento']",transforms:['http://www.w3.org/2000/09/xmldsig#enveloped-signature','http://www.w3.org/TR/2001/REC-xml-c14n-20010315'],digestAlgorithm:'http://www.w3.org/2000/09/xmldsig#sha1'});s.computeSignature(xml,{location:{reference:"//*[local-name()='infEvento']",action:'after'}});return s.getSignedXml()}
function soap(x:string){return `<?xml version="1.0" encoding="utf-8"?><soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope"><soap12:Body><nfeRecepcaoEvento xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4"><nfeDadosMsg>${x}</nfeDadosMsg></nfeRecepcaoEvento></soap12:Body></soap12:Envelope>`}
const tags=(x:string,n:string)=>[...x.matchAll(new RegExp(`<(?:\\w+:)?${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:\\w+:)?${n}>`,'gi'))].map(m=>m[1].trim());
function postNode(host:string,path:string,pfx64:string,pass:string,body:string){return new Promise<{status:number;text:string;host:string}>((resolve,reject)=>{const req=https.request({hostname:host,port:443,path,method:'POST',pfx:Buffer.from(pfx64,'base64'),passphrase:pass,minVersion:'TLSv1.2',maxVersion:'TLSv1.3',rejectUnauthorized:false,servername:host,headers:{'Content-Type':'application/soap+xml; charset=utf-8; action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento"','Content-Length':Buffer.byteLength(body),'User-Agent':'WS-Gestao-Fiscal/3.0','Connection':'close'}},res=>{const chunks:Buffer[]=[];res.on('data',c=>chunks.push(Buffer.isBuffer(c)?c:Buffer.from(c)));res.on('end',()=>resolve({status:res.statusCode||0,text:Buffer.concat(chunks).toString('utf8'),host}))});req.setTimeout(45000,()=>req.destroy(new Error('timeout')));req.on('error',reject);req.write(body);req.end()})}
Deno.serve(async req=>{try{const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const{data:t}=await admin.from("_fiscal_sales_debug_token").select("token").eq("id",true).maybeSingle();if(req.headers.get("x-debug-token")!==String(t?.token||""))return J({error:"unauthorized"},403);const b=await req.json().catch(()=>({})) as any,cid=String(b.company_id||""),ch=dg(b.access_key);if(!cid||!/^\d{44}$/.test(ch))return J({error:"invalid_target"},400);const{data:rows,error:de}=await admin.from("fiscal_dfe_documents").select("id,full_xml,direction,recipient_cnpj,issuer_cnpj").eq("company_id",cid).eq("access_key",ch).limit(20);if(de)throw de;if(!rows?.length)return J({error:"document_not_found"},404);if(rows.some((d:any)=>d.full_xml))return J({ok:true,already_complete:true});const{data:c}=await admin.from("fiscal_companies").select("cnpj,status").eq("id",cid).maybeSingle(),cnpj=dg(c?.cnpj),recipient=rows.some((d:any)=>d.direction==='entrada'&&dg(d.recipient_cnpj)===cnpj&&dg(d.issuer_cnpj)!==cnpj);if(!c||c.status!=="ativa"||!recipient)return J({error:"not_recipient_document"},422);const{data:ce}=await admin.from("fiscal_certificates").select("certificate_ciphertext,certificate_iv,password_ciphertext,password_iv").eq("company_id",cid).eq("is_active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!ce)return J({error:"certificate_missing"},422);const pfx=await dec(ce.certificate_ciphertext,ce.certificate_iv),pass=await dec(ce.password_ciphertext,ce.password_iv),pem=pems(pfx,pass),payload=soap(sign(cnpj,ch,pem.key,pem.cert)),endpoints:[string,string][]=[["www.nfe.fazenda.gov.br","/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx"],["nfe.svrs.rs.gov.br","/ws/recepcaoevento/recepcaoevento4.asmx"]];let out:any=null;const diagnostics:any[]=[];for(const[host,path]of endpoints){try{const r=await postNode(host,path,pfx,pass,payload);diagnostics.push({host,http:r.status,bytes:r.text.length});if(r.text){out=r;const cs=tags(r.text,'cStat');if(cs.length)break}}catch(e){diagnostics.push({host,error:e instanceof Error?e.message:String(e)})}}if(!out?.text)return J({ok:false,error:"transport_unavailable",diagnostics},502);const cs=tags(out.text,'cStat'),ms=tags(out.text,'xMotivo'),cstat=cs.at(-1)||'',mot=ms.at(-1)||'',ok=['135','136','573'].includes(cstat);if(ok)await admin.from("fiscal_dfe_documents").update({parse_error:"xml_retry:manifestation_sent",updated_at:new Date().toISOString()}).eq("company_id",cid).eq("access_key",ch).eq("full_xml",false);return J({ok,cStat:cstat,xMotivo:mot,http:out.status,host:out.host,diagnostics},ok?200:422)}catch(e){console.error('fiscal-purchases-manifest-native',e);return J({error:e instanceof Error?e.message:String(e)},500)}});