import { useState } from "react";
import { FileKey2, Loader2, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";

type CertMeta={holder_cnpj:string;holder_name:string;valid_from?:string;valid_until?:string};
type ExistingCompany={id:string;cnpj:string};
const digits=(v:string)=>String(v||"").replace(/\D/g,"");
async function fileToBase64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
async function inspect(base64:string,password?:string){const{data,error}=await supabase.functions.invoke("fiscal-certificate-inspect",{body:{certificate_base64:base64,password:password||undefined}});if(error){let msg=error.message;try{const ctx=(error as {context?:Response}).context;if(ctx)msg=(await ctx.clone().json())?.error||msg}catch{};throw new Error(msg)}return data as {ok:boolean;needs_password?:boolean;matched_password_kind?:string;certificate?:CertMeta}}
async function vault(body:Record<string,unknown>){const{data,error}=await supabase.functions.invoke("fiscal-company-vault",{body});if(error){let msg=error.message;try{const ctx=(error as {context?:Response}).context;if(ctx)msg=(await ctx.clone().json())?.error||msg}catch{};throw new Error(msg)}return data}

export function SmartCertificateInput({editing,onFile,onPassword,onMetadata}:{editing?:boolean;onFile:(f:File|null)=>void;onPassword:(p:string)=>void;onMetadata:(m:CertMeta)=>void}){
 const[password,setPassword]=useState("");const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);
 const pick=async(file:File|null)=>{onFile(file);setStatus("");if(!file)return;setBusy(true);try{const b64=await fileToBase64(file);const r=await inspect(b64);if(r.ok&&r.certificate){const p=r.matched_password_kind==="padrao_1_a_8"?"12345678":r.matched_password_kind==="padrao_1_a_4"?"1234":"";setPassword(p);onPassword(p);onMetadata(r.certificate);setStatus(`Certificado identificado: ${r.certificate.holder_name}. Dados obrigatórios preenchidos automaticamente.`)}else setStatus("Senha não identificada automaticamente. Informe a senha do certificado.")}catch{setStatus("Senha padrão não funcionou. Informe a senha do certificado.")}finally{setBusy(false)}};
 const validateManual=async()=>{const file=(document.getElementById("ws-smart-cert") as HTMLInputElement)?.files?.[0];if(!file||!password)return;setBusy(true);try{const r=await inspect(await fileToBase64(file),password);if(r.ok&&r.certificate){onPassword(password);onMetadata(r.certificate);setStatus(`Certificado validado: ${r.certificate.holder_name}.`)}}catch(e){setStatus(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <div className="grid gap-4 sm:grid-cols-[1fr_220px]"><div><label className="text-xs font-medium text-muted-foreground">{editing?"Substituir certificado (.pfx/.p12)":"Certificado (.pfx/.p12)"}</label><Input id="ws-smart-cert" className="mt-1.5" type="file" accept=".pfx,.p12,application/x-pkcs12" onChange={e=>void pick(e.target.files?.[0]||null)}/></div><div><label className="text-xs font-medium text-muted-foreground">Senha do A1</label><div className="mt-1.5 flex gap-2"><Input type="password" value={password} onChange={e=>{setPassword(e.target.value);onPassword(e.target.value)}} placeholder={editing?"Só se necessário":"Senha"}/><Button type="button" variant="outline" size="icon" disabled={busy||!password} onClick={()=>void validateManual()}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<FileKey2 className="h-4 w-4"/>}</Button></div></div>{status&&<p className="sm:col-span-2 text-xs text-muted-foreground">{status}</p>}</div>
}

type Row={file:File;base64:string;name:string;status:"checking"|"ready"|"password"|"saving"|"saved"|"error";meta?:CertMeta;password:string;error?:string};
export function BulkCertificateImporter({companies,onDone}:{companies:ExistingCompany[];onDone:()=>void}){
 const[open,setOpen]=useState(false),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false);
 const pick=async(files:FileList|null)=>{if(!files)return;const initial:Row[]=await Promise.all([...files].map(async file=>({file,base64:await fileToBase64(file),name:file.name,status:"checking" as const,password:""})));setRows(initial);const checked=await Promise.all(initial.map(async row=>{try{const r=await inspect(row.base64);if(r.ok&&r.certificate){const p=r.matched_password_kind==="padrao_1_a_8"?"12345678":r.matched_password_kind==="padrao_1_a_4"?"1234":"";return{...row,status:"ready" as const,meta:r.certificate,password:p}}return{...row,status:"password" as const}}catch{return{...row,status:"password" as const}}}));setRows(checked)};
 const validateRow=async(i:number)=>{const row=rows[i];if(!row.password)return;setRows(v=>v.map((r,n)=>n===i?{...r,status:"checking"}:r));try{const x=await inspect(row.base64,row.password);if(!x.ok||!x.certificate)throw new Error("Senha inválida");setRows(v=>v.map((r,n)=>n===i?{...r,status:"ready",meta:x.certificate,error:undefined}:r))}catch(e){setRows(v=>v.map((r,n)=>n===i?{...r,status:"error",error:e instanceof Error?e.message:String(e)}:r))}};
 const saveAll=async()=>{setBusy(true);for(let i=0;i<rows.length;i++){const row=rows[i];if(row.status!=="ready"||!row.meta)continue;setRows(v=>v.map((r,n)=>n===i?{...r,status:"saving"}:r));try{const existing=companies.find(c=>digits(c.cnpj)===digits(row.meta!.holder_cnpj));await vault({action:"save",company:{id:existing?.id,cnpj:row.meta.holder_cnpj,razao_social:row.meta.holder_name,nome_fantasia:row.meta.holder_name,uf:"AL",regime_tributario:"simples_nacional",ambiente_padrao:"producao",status:"ativa",endereco:{}},certificate_base64:row.base64,certificate_password:row.password,certificate_name:row.name});setRows(v=>v.map((r,n)=>n===i?{...r,status:"saved"}:r))}catch(e){setRows(v=>v.map((r,n)=>n===i?{...r,status:"error",error:e instanceof Error?e.message:String(e)}:r))}}setBusy(false);onDone()};
 const pending=rows.filter(r=>r.status==="password"||r.status==="error").length,ready=rows.filter(r=>r.status==="ready").length;
 return <><Button variant="outline" onClick={()=>setOpen(true)}><Upload className="mr-2 h-4 w-4"/>Importar certificados</Button>{open&&<div className="fixed inset-0 z-[140] flex items-center justify-center bg-black/65 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-background shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><p className="text-xs uppercase text-muted-foreground">Importação em lote</p><h2 className="mt-1 text-xl font-semibold">Certificados digitais A1</h2><p className="mt-1 text-sm text-muted-foreground">O sistema testa primeiro 12345678 e depois 1234. Só pede senha manual para os certificados que não abrirem.</p></div><Button variant="ghost" size="icon" onClick={()=>setOpen(false)}><X className="h-4 w-4"/></Button></div><div className="p-5"><Input type="file" multiple accept=".pfx,.p12,application/x-pkcs12" onChange={e=>void pick(e.target.files)}/></div><div className="min-h-0 flex-1 overflow-auto px-5 pb-5"><table className="w-full text-sm"><thead className="sticky top-0 bg-background text-left text-xs uppercase text-muted-foreground"><tr><th className="py-3">Arquivo</th><th>Empresa / CNPJ</th><th>Status</th><th className="w-64">Senha</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.name}-${i}`} className={i%2?"bg-muted/[.08]":"bg-muted/[.02]"}><td className="px-2 py-3 font-medium">{r.name}</td><td className="px-2">{r.meta?<><div>{r.meta.holder_name}</div><div className="text-xs text-muted-foreground">{r.meta.holder_cnpj}</div></>:"—"}</td><td className="px-2 text-xs">{r.status==="checking"?"Analisando...":r.status==="ready"?"Pronto":r.status==="password"?"Senha necessária":r.status==="saving"?"Salvando...":r.status==="saved"?"Salvo":r.error||"Erro"}</td><td className="px-2"><div className="flex gap-2"><Input type="password" value={r.password} disabled={r.status==="saved"} placeholder={r.status==="password"||r.status==="error"?"Digite a senha":"Identificada automaticamente"} onChange={e=>setRows(v=>v.map((x,n)=>n===i?{...x,password:e.target.value,status:x.status==="saved"?"saved":"password"}:x))}/>{(r.status==="password"||r.status==="error")&&<Button size="sm" variant="outline" onClick={()=>void validateRow(i)}>Testar</Button>}</div></td></tr>)}</tbody></table>{!rows.length&&<div className="py-12 text-center text-sm text-muted-foreground">Selecione vários certificados para começar.</div>}</div><div className="flex items-center justify-between border-t p-5"><p className="text-xs text-muted-foreground">{ready} pronto(s) · {pending} aguardando senha</p><div className="flex gap-2"><Button variant="ghost" onClick={()=>setOpen(false)}>Fechar</Button><Button disabled={busy||ready===0} onClick={()=>void saveAll()}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Upload className="mr-2 h-4 w-4"/>}Salvar empresas prontas</Button></div></div></div></div>}</>
}
