import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.0";
const E=new TextEncoder(),D=new TextDecoder(),B=(v:string)=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json"}});
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function K(){const s=Deno.env.get("ACCOUNTING_ENGINE_SESSION_SECRET")||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!s)throw Error("secret_missing");const d=await crypto.subtle.digest("SHA-256",E.encode(`ws-fiscal-vault:${s}`));return crypto.subtle.importKey("raw",d,{name:"AES-GCM"},false,["decrypt"])}
async function dec(c:string,iv:string){return D.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:B(iv)},await K(),B(c)))}
const tag=(xml:string,n:string)=>xml.match(new RegExp(`<(?:\\w+:)?${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:\\w+:)?${n}>`,`i`))?.[1]?.trim()||"";
async function download(pfx:string,pass:string,key:string){const r=await fetch("https://ws-svrs-consit.vercel.app/api/download",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({certificate_base64:pfx,certificate_password:pass,access_key:key}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`bridge_http_${r.status}`);const o=await r.json().catch(()=>({})) as any;const all=String(o?.body_text||o?.body||"");const m=all.match(/var\s+stringJson\s*=\s*(\{[\s\S]*?\})\s*;/);if(!m)throw Error("xml_payload_not_found");let data:any;try{data=JSON.parse(m[1])}catch{throw Error("xml_payload_invalid_json")};const xml=String(data?.xml||"");if(!/<(?:nfeProc|procNFe|NFe)\b/i.test(xml)||xml.length<1000)throw Error("xml_not_returned");return xml}
function monthRange(code:string){const [y,m]=code.split("-").map(Number);const start=`${y}-${String(m).padStart(2,"0")}-01T00:00:00-03:00`;const endDate=new Date(y,m,0).getDate();const end=`${y}-${String(m).padStart(2,"0")}-${String(endDate).padStart(2,"0")}T23:59:59-03:00`;return{start,end}}
function defaultMonths(){const n=new Date(),y=n.getFullYear(),m=n.getMonth()+1;const prev=new Date(y,m-2,1);return [`${y}-${String(m).padStart(2,"0")}`,`${prev.getFullYear()}-${String(prev.getMonth()+1).padStart(2,"0")}`]}
Deno.serve(async req=>{try{const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const {data:t}=await admin.from("_fiscal_sales_debug_token").select("token").eq("id",true).maybeSingle();if(!t?.token||req.headers.get("x-debug-token")!==String(t.token))return J({error:"unauthorized"},403);const body=await req.json().catch(()=>({})) as any;const only=String(body.company_id||"");const targetKey=String(body.access_key||"").replace(/\D/g,"");const force=Boolean(body.force||targetKey);const batch=Math.min(8,Math.max(1,Number(body.batch||2)));let cq=admin.from("fiscal_companies").select("id,cnpj,created_by,status,fiscal_settings").eq("status","ativa");if(only)cq=cq.eq("id",only);const {data:companies,error:ce}=await cq;if(ce)throw ce;const out:any[]=[];for(const c of companies||[]){const {data:cert}=await admin.from("fiscal_certificates").select("certificate_ciphertext,certificate_iv,password_ciphertext,password_iv").eq("company_id",c.id).eq("is_active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!cert){out.push({company_id:c.id,error:"certificate_missing"});continue}const pfx=await dec(cert.certificate_ciphertext,cert.certificate_iv),pass=await dec(cert.password_ciphertext,cert.password_iv);let rows:any[]=[];if(targetKey){const {data,error}=await admin.from("fiscal_dfe_documents").select("id,access_key,source,note_number,series,status_code,status_text,issue_date,updated_at,parse_error").eq("company_id",c.id).eq("direction","entrada").eq("model","55").eq("access_key",targetKey).eq("full_xml",false).limit(1);if(error)throw error;rows=data||[]}else{const configured=Array.isArray(c?.fiscal_settings?.xml_background_months)?c.fiscal_settings.xml_background_months.map(String):defaultMonths();for(const code of configured){if(rows.length>=batch)break;const {start,end}=monthRange(code);let q=admin.from("fiscal_dfe_documents").select("id,access_key,source,note_number,series,status_code,status_text,issue_date,updated_at,parse_error").eq("company_id",c.id).eq("direction","entrada").eq("model","55").eq("full_xml",false).not("access_key","is",null).gte("issue_date",start).lte("issue_date",end).order("issue_date",{ascending:false}).order("note_number",{ascending:false}).limit(batch-rows.length);if(!force)q=q.or(`parse_error.is.null,parse_error.not.like.xml_retry:%`);const {data,error}=await q;if(error)throw error;rows.push(...(data||[]))}}
let saved=0,failed=0;for(const row of rows.slice(0,batch)){const key=String(row.access_key||""),now=new Date().toISOString();try{if(!/^\d{44}$/.test(key))throw Error("invalid_key");const xml=await download(pfx,pass,key);const issue=tag(xml,"dhEmi")||tag(xml,"dEmi")||null,total=Number(tag(xml,"vNF")||0),issuer=tag(tag(xml,"emit"),"CNPJ"),issuerName=tag(tag(xml,"emit"),"xNome"),recipient=tag(tag(xml,"dest"),"CNPJ"),nn=tag(xml,"nNF")||row.note_number,serie=tag(xml,"serie")||row.series;const patch:any={full_xml:true,xml,document_kind:"nfe",schema_name:"procNFe_v4.00",source:"xml_backfill_svrs_purchase",source_id:key,parse_error:null,updated_at:now};if(issue)patch.issue_date=issue;if(total)patch.value=total;if(issuer)patch.issuer_cnpj=issuer;if(issuerName)patch.issuer_name=issuerName;if(recipient)patch.recipient_cnpj=recipient;if(nn)patch.note_number=nn;if(serie)patch.series=serie;const {error}=await admin.from("fiscal_dfe_documents").update(patch).eq("id",row.id);if(error)throw error;saved++}catch(e){failed++;await admin.from("fiscal_dfe_documents").update({parse_error:`xml_retry:${e instanceof Error?e.message:String(e)}`,updated_at:now}).eq("id",row.id)}await sleep(500)}out.push({company_id:c.id,processed:rows.length,saved,failed,targeted:Boolean(targetKey)})}return J({ok:true,companies:out})}catch(e){return J({error:e instanceof Error?e.message:String(e)},500)}});