import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.0";
import forge from "npm:node-forge@1.3.1";
const E=new TextEncoder(),D=new TextDecoder(),B=(v:string)=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json"}});
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const digits=(v:unknown)=>String(v??"").replace(/\D/g,"");
const cutoff30=()=>new Date(Date.now()-30*24*60*60*1000).toISOString();
async function K(){const s=Deno.env.get("ACCOUNTING_ENGINE_SESSION_SECRET")||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!s)throw Error("secret_missing");const d=await crypto.subtle.digest("SHA-256",E.encode(`ws-fiscal-vault:${s}`));return crypto.subtle.importKey("raw",d,{name:"AES-GCM"},false,["decrypt"])}
async function dec(c:string,iv:string){return D.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:B(iv)},await K(),B(c)))}
const tag=(xml:string,n:string)=>xml.match(new RegExp(`<(?:\\w+:)?${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:\\w+:)?${n}>`,`i`))?.[1]?.trim()||"";
function pfxPem(pfx64:string,password:string){const der=forge.util.decode64(pfx64),asn=forge.asn1.fromDer(der),p12=forge.pkcs12.pkcs12FromAsn1(asn,false,password);let key:any=null;const certs:any[]=[];for(const sc of p12.safeContents)for(const bag of sc.safeBags){if(!key&&bag.key)key=bag.key;if(bag.cert)certs.push(bag.cert)}if(!key||!certs.length)throw Error("pfx_parse_failed");return{key:forge.pki.privateKeyToPem(key),cert:certs.map(c=>forge.pki.certificateToPem(c)).join("\n")}}
function parseDownloadHtml(all:string){const m=all.match(/var\s+stringJson\s*=\s*(\{[\s\S]*?\})\s*;/);if(!m){if(/CNPJ base do certificado digital[^<]*difere/i.test(all))throw Error("certificate_not_involved");throw Error("xml_payload_not_found")}let data:any;try{data=JSON.parse(m[1])}catch{throw Error("xml_payload_invalid_json")}const xml=String(data?.xml||"");if(!/<(?:nfeProc|procNFe|NFe)\b/i.test(xml)||xml.length<1000)throw Error("xml_not_returned");return xml}
async function downloadDirect(pfx:string,pass:string,key:string){const p=pfxPem(pfx,pass),client=Deno.createHttpClient({cert:p.cert,key:p.key,http1:true,http2:false} as any);try{const form=new URLSearchParams({sistema:"Nfe",OrigemSite:"SiteSefaz",Ambiente:"1",ChaveAcessoDfe:key});const r=await fetch("https://dfe-portal.svrs.rs.gov.br/BpeSSL/DownloadXmlDfe",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","accept":"text/html,application/xml,text/xml,*/*","user-agent":"Mozilla/5.0"},body:form.toString(),redirect:"manual",client,signal:AbortSignal.timeout(40000)} as any);const all=await r.text();if(!r.ok)throw Error(`direct_http_${r.status}`);return parseDownloadHtml(all)}finally{client.close()}}
async function downloadBridge(pfx:string,pass:string,key:string){const r=await fetch("https://ws-svrs-consit.vercel.app/api/download",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({certificate_base64:pfx,certificate_password:pass,access_key:key}),signal:AbortSignal.timeout(35000)});const o=await r.json().catch(()=>({})) as any;if(!r.ok)throw Error(`bridge_http_${r.status}:${String(o?.error||o?.message||"").slice(0,120)}`);return parseDownloadHtml(String(o?.body_text||o?.body||""))}
async function download(pfx:string,pass:string,key:string){let last="xml_download_failed";for(let attempt=0;attempt<2;attempt++){try{return await downloadDirect(pfx,pass,key)}catch(e){last=e instanceof Error?e.message:String(e);if(last==="certificate_not_involved")throw Error(last);if(attempt<1)await sleep(1200)}}for(let attempt=0;attempt<2;attempt++){try{return await downloadBridge(pfx,pass,key)}catch(e){last=e instanceof Error?e.message:String(e);if(last==="certificate_not_involved")throw Error(last);if(attempt<1)await sleep(1600)}}throw Error(last)}
Deno.serve(async req=>{try{const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const {data:t}=await admin.from("_fiscal_sales_debug_token").select("token").eq("id",true).maybeSingle();if(!t?.token||req.headers.get("x-debug-token")!==String(t.token))return J({error:"unauthorized"},403);const body=await req.json().catch(()=>({})) as any;const only=String(body.company_id||""),targetKey=digits(body.access_key),batch=Math.min(8,Math.max(1,Number(body.batch||2))),cutoff=cutoff30(),retryBefore=new Date(Date.now()-10*60000).toISOString();let cq=admin.from("fiscal_companies").select("id,cnpj,created_by,status").eq("status","ativa");if(only)cq=cq.eq("id",only);const {data:companies,error:ce}=await cq;if(ce)throw ce;const out:any[]=[];for(const c of companies||[]){const {data:cert}=await admin.from("fiscal_certificates").select("certificate_ciphertext,certificate_iv,password_ciphertext,password_iv").eq("company_id",c.id).eq("is_active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!cert){out.push({company_id:c.id,error:"certificate_missing"});continue}const pfx=await dec(cert.certificate_ciphertext,cert.certificate_iv),pass=await dec(cert.password_ciphertext,cert.password_iv),companyCnpj=digits(c.cnpj);let rows:any[]=[];const seen=new Set<string>();const addRows=(items:any[])=>{for(const row of items||[]){const key=digits(row.access_key);if(!/^\d{44}$/.test(key)||seen.has(key))continue;seen.add(key);rows.push(row);if(rows.length>=batch)break}};
if(targetKey){const {data,error}=await admin.from("fiscal_dfe_documents").select("id,access_key,source,note_number,series,status_code,status_text,issue_date,updated_at,parse_error,direction").eq("company_id",c.id).eq("model","55").eq("access_key",targetKey).eq("full_xml",false).gte("issue_date",cutoff).limit(1);if(error)throw error;addRows(data||[])}else{for(const phase of ["fresh","retry"] as const){if(rows.length>=batch)break;let q=admin.from("fiscal_dfe_documents").select("id,access_key,source,note_number,series,status_code,status_text,issue_date,updated_at,parse_error,direction").eq("company_id",c.id).eq("direction","entrada").eq("model","55").eq("full_xml",false).not("access_key","is",null).gte("issue_date",cutoff);if(phase==="fresh")q=q.or(`parse_error.is.null,parse_error.not.like.xml_retry:%`);else q=q.like("parse_error","xml_retry:%").lt("updated_at",retryBefore);const {data,error}=await (phase==="retry"?q.order("updated_at",{ascending:true}).order("issue_date",{ascending:false}):q.order("issue_date",{ascending:false}).order("note_number",{ascending:false})).limit(Math.max(batch*3,batch-rows.length));if(error)throw error;addRows(data||[])}}
let saved=0,failed=0;for(const row of rows.slice(0,batch)){const key=digits(row.access_key),now=new Date().toISOString();try{if(!/^\d{44}$/.test(key))throw Error("invalid_key");const xml=await download(pfx,pass,key);const issue=tag(xml,"dhEmi")||tag(xml,"dEmi")||null,total=Number(tag(xml,"vNF")||0),emit=tag(xml,"emit"),dest=tag(xml,"dest"),issuer=digits(tag(emit,"CNPJ")||tag(emit,"CPF")),issuerName=tag(emit,"xNome"),recipient=digits(tag(dest,"CNPJ")||tag(dest,"CPF")),nn=tag(xml,"nNF")||row.note_number,serie=tag(xml,"serie")||row.series,direction=issuer===companyCnpj?"saida":recipient===companyCnpj?"entrada":"relacionada";const patch:any={full_xml:true,xml,document_kind:"nfe",schema_name:"procNFe_v4.00",source:"xml_backfill_svrs_nfe",source_id:key,parse_error:null,direction,updated_at:now};if(issue)patch.issue_date=issue;if(total)patch.value=total;if(issuer)patch.issuer_cnpj=issuer;if(issuerName)patch.issuer_name=issuerName;if(recipient)patch.recipient_cnpj=recipient;if(nn)patch.note_number=nn;if(serie)patch.series=serie;const {error}=await admin.from("fiscal_dfe_documents").update(patch).eq("company_id",c.id).eq("access_key",key).eq("full_xml",false);if(error)throw error;saved++}catch(e){failed++;await admin.from("fiscal_dfe_documents").update({parse_error:`xml_retry:${e instanceof Error?e.message:String(e)}`,updated_at:now}).eq("company_id",c.id).eq("access_key",key).eq("full_xml",false)}await sleep(400)}out.push({company_id:c.id,processed:rows.length,saved,failed,targeted:Boolean(targetKey),cutoff})}return J({ok:true,companies:out,cutoff})}catch(e){return J({error:e instanceof Error?e.message:String(e)},500)}});