import { useCallback, useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { supabase } from '@/integrations/supabase/client';
import AnimatedExtractorIcon from '@/components/extractor/AnimatedExtractorIcon';

type Company={id:string;name:string;tradeName:string;cnpj:string;uf?:string;documents:number;entries:number;exits:number;fullXml:number;pendingXml:number};
type Props={companies:Company[];selectedCompanyId:string;onSelectCompany:(id:string)=>void;allowedFrom?:string|null;preview?:boolean};
type Doc={documentKind?:string;direction:string;accessKey?:string;model?:string;issueDate?:string|null;value:number;issuerCnpj?:string;issuerName?:string;recipientCnpj?:string;statusCode?:string;statusText?:string;fullXml:boolean};
const integer=new Intl.NumberFormat('pt-BR');const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const digits=(v:unknown)=>String(v||'').replace(/\D/g,'');const formatCnpj=(v:unknown)=>{const d=digits(v);return d.length===14?d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5'):String(v||'—')};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dayLabel=(s:string)=>{const d=new Date(`${s.slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})};
const chart={gold:'#d7b65a',blue:'#5b83ad',cyan:'#4b9e9d',green:'#5f987d',red:'#a86167',muted:'#485667',grid:'#1c2a3a',text:'#9aa9b8'};
const cancelled=(d:Doc)=>['101','151','155'].includes(String(d.statusCode||''))||/cancel/i.test(String(d.statusText||''));
const authorized=(d:Doc)=>['1','100','150'].includes(String(d.statusCode||''))||/autoriz|ativa/i.test(String(d.statusText||''));
const docType=(d:Doc)=>{const m=String(d.model||(/^\d{44}$/.test(String(d.accessKey||''))?String(d.accessKey).slice(20,22):''));const h=`${d.documentKind||''} ${m}`.toLowerCase();if(h.includes('nfse')||h.includes('nfs-e'))return'NFS-e';if(m==='65')return'NFC-e';if(m==='55')return'NF-e';return'Outros'};
const rowToDoc=(r:any):Doc=>({documentKind:r.document_kind||undefined,direction:r.direction==='saida'||r.direction==='outbound'?'saida':r.direction==='entrada'||r.direction==='inbound'?'entrada':'relacionada',accessKey:r.access_key||undefined,model:r.model||undefined,issueDate:r.issue_date||r.received_at||undefined,value:Number(r.value||0),issuerCnpj:r.issuer_cnpj||undefined,issuerName:r.issuer_name||undefined,recipientCnpj:r.recipient_cnpj||undefined,statusCode:r.status_code||undefined,statusText:r.status_text||undefined,fullXml:Boolean(r.full_xml)});
const reconToDoc=(r:any):Doc=>({documentKind:'nfe',direction:'saida',accessKey:r.access_key||undefined,model:String(r.model||'65'),issueDate:r.issue_date||undefined,value:0,statusCode:r.cstat||undefined,statusText:r.xmotivo||(r.status==='cancelled'?'Cancelada':r.status||'Fiscal'),fullXml:false});

export default function ExtractorReports({companies,selectedCompanyId,onSelectCompany,allowedFrom,preview=false}:Props){
 const company=companies.find(c=>c.id===selectedCompanyId)||companies[0]||null;const[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[effective,setEffective]=useState<{from:string;to:string}|null>(null);
 const start=allowedFrom||iso(new Date(Date.now()-30*86400000)),end=iso(new Date());
 const load=useCallback(async()=>{if(!company){setDocs([]);return}if(preview){setDocs(makePreviewDocs(company));setEffective({from:start,to:end});return}setLoading(true);setError('');const{data,error:e}=await(supabase as any).rpc('extractor_company_documents',{_company_id:company.id,_start:start,_end:end});if(e){setError(e.message||'Não foi possível carregar o relatório.');setDocs([])}else{const base=(data?.documents||[]).map(rowToDoc);const known=new Set(base.map((d:Doc)=>String(d.accessKey||'')).filter(Boolean));const extra=(data?.reconciliation||[]).filter((r:any)=>r.access_key&&!known.has(String(r.access_key))).map(reconToDoc);setDocs([...base,...extra]);setEffective({from:String(data?.effective_from||start),to:String(data?.effective_to||end)})}setLoading(false)},[company?.id,start,end,preview]);
 useEffect(()=>{void load()},[load]);
 const report=useMemo(()=>buildReport(docs),[docs]);
 if(!company)return <div className="extractor-page"><ReportHeading/><div className="extractor-empty">Adicione uma empresa com certificado A1 para gerar relatórios.</div></div>;
 return <div className="extractor-page extractor-report-rich">
  <div className="extractor-page-heading"><div><span className="extractor-eyebrow"><AnimatedExtractorIcon name="report"/>WS Extrator Fiscal</span><h1>Relatórios</h1><p>Análise fiscal da empresa ativa, calculada somente com documentos reais disponíveis no Extrator.</p></div><select className="extractor-company-select" value={company.id} onChange={e=>onSelectCompany(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.tradeName}</option>)}</select></div>
  <section className="extractor-report-company"><div><small>Empresa analisada</small><strong>{company.name}</strong>{company.tradeName!==company.name&&<span>{company.tradeName}</span>}<em>{formatCnpj(company.cnpj)}</em></div><div><small>Período disponível</small><strong>{effective?`${dayLabel(effective.from)} — ${dayLabel(effective.to)}`:'Carregando...'}</strong><span>{integer.format(report.total)} documentos considerados</span></div></section>
  {error&&<div className="extractor-notice error"><span>{error}</span></div>}
  <section className="extractor-kpis extractor-report-kpis">
   <Metric label="Vendas" value={currency.format(report.salesValue)} detail={`${integer.format(report.salesCount)} documento(s) · ticket ${currency.format(report.salesTicket)}`} icon="report"/>
   <Metric label="Compras" value={currency.format(report.purchaseValue)} detail={`${integer.format(report.purchaseCount)} documento(s) · ticket ${currency.format(report.purchaseTicket)}`} icon="document"/>
   <Metric label="Movimentação" value={currency.format(report.totalValue)} detail="Compras + vendas no período" icon="dashboard"/>
   <Metric label="XML integral" value={`${report.xmlCoverage}%`} detail={`${integer.format(report.fullXml)} completos · ${integer.format(report.pendingXml)} pendentes`} icon="certificate"/>
   <Metric label="Canceladas" value={integer.format(report.cancelled)} detail={`${integer.format(report.authorized)} autorizadas`} icon="history"/>
   <Metric label="Saldo comercial" value={currency.format(report.salesValue-report.purchaseValue)} detail="Vendas menos compras" icon="company"/>
  </section>
  {loading?<div className="extractor-report-loading">Carregando documentos fiscais...</div>:<>
   <section className="extractor-report-grid">
    <article className="extractor-panel extractor-report-span-2"><Head title="Movimento no período" sub="Quantidade e valor por dia" icon="report"/><div className="extractor-report-chart"><ResponsiveContainer><AreaChart data={report.timeline}><CartesianGrid vertical={false} stroke={chart.grid}/><XAxis dataKey="label" tick={{fill:chart.text,fontSize:10}} axisLine={false} tickLine={false}/><YAxis yAxisId="left" axisLine={false} tickLine={false} tick={{fill:chart.text,fontSize:10}}/><Tooltip content={<Tip/>}/><Area yAxisId="left" dataKey="vendas" name="Vendas" type="monotone" stroke={chart.gold} fill={chart.gold} fillOpacity={.11}/><Area yAxisId="left" dataKey="compras" name="Compras" type="monotone" stroke={chart.blue} fill={chart.blue} fillOpacity={.08}/></AreaChart></ResponsiveContainer></div></article>
    <article className="extractor-panel"><Head title="Documentos por modelo" sub="Composição fiscal" icon="document"/><div className="extractor-report-donut"><ResponsiveContainer><PieChart><Pie data={report.models} dataKey="value" nameKey="name" innerRadius={48} outerRadius={76} paddingAngle={2}>{report.models.map((_:any,i:number)=><Cell key={i} fill={[chart.gold,chart.blue,chart.cyan,chart.muted][i%4]}/>)}</Pie><Tooltip content={<Tip/>}/></PieChart></ResponsiveContainer><div><strong>{integer.format(report.total)}</strong><span>documentos</span></div></div><Legend rows={report.models}/></article>
    <article className="extractor-panel"><Head title="Situação fiscal" sub="Autorizadas, canceladas e demais" icon="certificate"/><div className="extractor-report-status"><Status label="Autorizadas" value={report.authorized} total={report.total} tone="green"/><Status label="Canceladas" value={report.cancelled} total={report.total} tone="red"/><Status label="Eventos/relacionadas" value={report.events} total={report.total} tone="gold"/><Status label="Outras situações" value={report.otherStatus} total={report.total} tone="blue"/></div></article>
    <article className="extractor-panel extractor-report-span-2"><Head title="Principais fornecedores" sub="Compras agrupadas pelo emitente" icon="company"/><div className="extractor-report-suppliers">{report.suppliers.length?report.suppliers.map((s:any,i:number)=><div key={`${s.key}-${i}`}><span><b>{i+1}</b><span><strong>{s.name}</strong><small>{s.cnpj?formatCnpj(s.cnpj):'CNPJ não informado'} · {integer.format(s.count)} documento(s)</small></span></span><strong>{currency.format(s.value)}</strong></div>):<p>Nenhuma compra com fornecedor identificado no período.</p>}</div></article>
    <article className="extractor-panel"><Head title="Cobertura XML" sub="Disponibilidade para download" icon="certificate"/><div className="extractor-report-coverage"><strong>{report.xmlCoverage}%</strong><div><i style={{width:`${report.xmlCoverage}%`}}/></div><span>{integer.format(report.fullXml)} integrais</span><span>{integer.format(report.pendingXml)} pendentes</span></div></article>
   </section>
  </>}
 </div>;
}

function buildReport(docs:Doc[]){const fiscal=docs.filter(d=>d.documentKind!=='evento'&&d.direction!=='relacionada'),sales=fiscal.filter(d=>d.direction==='saida'),purchases=fiscal.filter(d=>d.direction==='entrada');const salesValue=sales.reduce((a,d)=>a+d.value,0),purchaseValue=purchases.reduce((a,d)=>a+d.value,0),fullXml=fiscal.filter(d=>d.fullXml).length,pendingXml=Math.max(0,fiscal.length-fullXml),events=docs.length-fiscal.length,cancelledCount=fiscal.filter(cancelled).length,authorizedCount=fiscal.filter(authorized).length,otherStatus=Math.max(0,fiscal.length-authorizedCount-cancelledCount);const modelMap=new Map<string,number>();fiscal.forEach(d=>modelMap.set(docType(d),(modelMap.get(docType(d))||0)+1));const models=['NF-e','NFC-e','NFS-e','Outros'].map(name=>({name,value:modelMap.get(name)||0})).filter(x=>x.value>0);const timelineMap=new Map<string,{label:string;vendas:number;compras:number}>();fiscal.forEach(d=>{if(!d.issueDate)return;const key=String(d.issueDate).slice(0,10);const x=timelineMap.get(key)||{label:dayLabel(key),vendas:0,compras:0};if(d.direction==='saida')x.vendas++;if(d.direction==='entrada')x.compras++;timelineMap.set(key,x)});const timeline=[...timelineMap.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([,x])=>x);const suppliersMap=new Map<string,{key:string;name:string;cnpj:string;count:number;value:number}>();purchases.forEach(d=>{const key=d.issuerCnpj||d.issuerName||'nao-identificado';const x=suppliersMap.get(key)||{key,name:d.issuerName||'Fornecedor não identificado',cnpj:d.issuerCnpj||'',count:0,value:0};x.count++;x.value+=d.value;suppliersMap.set(key,x)});const suppliers=[...suppliersMap.values()].sort((a,b)=>b.value-a.value||b.count-a.count).slice(0,8);return{total:docs.length,salesCount:sales.length,purchaseCount:purchases.length,salesValue,purchaseValue,totalValue:salesValue+purchaseValue,salesTicket:sales.length?salesValue/sales.length:0,purchaseTicket:purchases.length?purchaseValue/purchases.length:0,fullXml,pendingXml,xmlCoverage:fiscal.length?Math.round(fullXml/fiscal.length*100):0,cancelled:cancelledCount,authorized:authorizedCount,events,otherStatus,models,timeline,suppliers}}
function makePreviewDocs(company:Company):Doc[]{const out:Doc[]=[];for(let i=0;i<30;i++){const date=iso(new Date(Date.now()-(29-i)*86400000));const sales=(i%5)+2,purchases=(i%3)+1;for(let j=0;j<sales;j++)out.push({documentKind:'nfe',direction:'saida',model:j%3===0?'65':'55',issueDate:date,value:260+j*48,statusCode:'100',statusText:'Autorizada',fullXml:(i+j)%5!==0,recipientCnpj:'12345678000100'});for(let j=0;j<purchases;j++)out.push({documentKind:'nfe',direction:'entrada',model:'55',issueDate:date,value:430+j*75,statusCode:'100',statusText:'Autorizada',fullXml:(i+j)%6!==0,issuerName:['Fornecedor Alfa','Distribuidora Nordeste','Comercial Central'][j%3],issuerCnpj:['11222333000144','22333444000155','33444555000166'][j%3]})}return out}
function Metric({label,value,detail,icon}:any){return <article className="extractor-metric" data-icon-hover><div><p>{label}</p><AnimatedExtractorIcon name={icon}/></div><strong>{value}</strong><span>{detail}</span></article>}
function Head({title,sub,icon}:any){return <div className="extractor-panel-head" data-icon-hover><div><AnimatedExtractorIcon name={icon}/><span><h2>{title}</h2><p>{sub}</p></span></div></div>}
function Tip({active,payload,label}:any){if(!active||!payload?.length)return null;return <div className="extractor-tooltip"><strong>{label}</strong>{payload.map((p:any,i:number)=><span key={i}>{p.name}: <b>{typeof p.value==='number'?integer.format(p.value):String(p.value)}</b></span>)}</div>}
function Legend({rows}:any){return <div className="extractor-legend">{rows.map((r:any,i:number)=><p key={r.name}><i style={{background:[chart.gold,chart.blue,chart.cyan,chart.muted][i%4]}}/><span>{r.name}</span><b>{integer.format(r.value)}</b></p>)}</div>}
function Status({label,value,total,tone}:any){const pct=total?Math.round(value/total*100):0;return <div className={`tone-${tone}`}><span><strong>{label}</strong><b>{integer.format(value)}</b></span><div><i style={{width:`${pct}%`}}/></div><small>{pct}% do total</small></div>}
function ReportHeading(){return <div className="extractor-page-heading"><div><span className="extractor-eyebrow"><AnimatedExtractorIcon name="report"/>WS Extrator Fiscal</span><h1>Relatórios</h1><p>Adicione uma empresa para começar a análise.</p></div></div>}
