import { gzip } from "npm:pako@2.1.0";
import { ICP_BRASIL_V10_PEM } from "./ca.ts";
export type CertificadoMtls={chavePrivadaPem:string;certificadoPem:string;cadeiaPem:string[]};
const SERPRO_SSL_V1_URL="http://repositorio.serpro.gov.br/cadeias/serprossl.crt",SERPRO_SSL_V1_SHA256="08fc942d5176e568acbef9c595f36a20de6acf9ea30c6f5fcedd48216ed5b070";let serproCaPromise:Promise<string>|null=null;
function pemDer(pem:string){const match=pem.match(/-----BEGIN CERTIFICATE-----([\s\S]*?)-----END CERTIFICATE-----/);if(!match)throw new Error("Certificado da CA SERPRO SSLv1 inválido.");return Uint8Array.from(atob(match[1].replace(/\s/g,"")),c=>c.charCodeAt(0))}
async function sha256Hex(bytes:Uint8Array){const digest=new Uint8Array(await crypto.subtle.digest("SHA-256",bytes));return[...digest].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function loadSerproSslV1(){if(!serproCaPromise)serproCaPromise=(async()=>{const response=await fetch(SERPRO_SSL_V1_URL);if(!response.ok)throw new Error(`Não foi possível carregar a CA SERPRO SSLv1: HTTP ${response.status}.`);const pem=(await response.text()).trim();if(await sha256Hex(pemDer(pem))!==SERPRO_SSL_V1_SHA256)throw new Error("Fingerprint da CA SERPRO SSLv1 não confere com o certificado oficial pinado.");return pem})().catch(e=>{serproCaPromise=null;throw e});return await serproCaPromise}
function gzipBase64(xml:string){const bytes=gzip(new TextEncoder().encode(xml));let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
async function postSoap(cert:CertificadoMtls,endpoint:string,namespace:string,operation:string,innerXml:string){const soap=`<?xml version="1.0" encoding="utf-8"?><soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope"><soap12:Body><cteDadosMsg xmlns="${namespace}">${innerXml}</cteDadosMsg></soap12:Body></soap12:Envelope>`,serproSslV1=await loadSerproSslV1(),client=Deno.createHttpClient({caCerts:[ICP_BRASIL_V10_PEM,serproSslV1],cert:[cert.certificadoPem,...cert.cadeiaPem].join("\n"),key:cert.chavePrivadaPem,http1:true});try{const action=`${namespace}/${operation}`,length=String(new TextEncoder().encode(soap).byteLength);const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":`application/soap+xml; charset=utf-8; action="${action}"`,"Content-Length":length},body:soap,client} as RequestInit&{client:Deno.HttpClient});const text=await response.text();if(!response.ok)throw new Error(`SVRS CT-e respondeu HTTP ${response.status}: ${text.slice(0,1200)}`);return text}finally{client.close()}}
function urls(environment:"homologation"|"production"){const production=environment==="production",base=production?"https://cte.svrs.rs.gov.br/ws":"https://cte-homologacao.svrs.rs.gov.br/ws";return{status:`${base}/CTeStatusServicoV4/CTeStatusServicoV4.asmx`,issue:`${base}/CTeRecepcaoSincV4/CTeRecepcaoSincV4.asmx`,tpAmb:production?"1":"2"}}
export async function statusCte(cert:CertificadoMtls,cUF="27",environment:"homologation"|"production"="homologation"){const u=urls(environment),xml=`<consStatServCTe xmlns="http://www.portalfiscal.inf.br/cte" versao="4.00"><tpAmb>${u.tpAmb}</tpAmb><cUF>${cUF}</cUF><xServ>STATUS</xServ></consStatServCTe>`,text=await postSoap(cert,u.status,"http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4","cteStatusServicoCTe",xml);return{endpoint:u.status,text}}
export async function authorizeCte(cert:CertificadoMtls,signedXml:string,environment:"homologation"|"production"="homologation"){const u=urls(environment),xml=signedXml.replace(/^<\?xml[^>]*\?>\s*/i,"").trim(),payload=gzipBase64(xml),text=await postSoap(cert,u.issue,"http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSincV4","cteRecepcao",payload);return{endpoint:u.issue,text}}
const all=(xml:string,tag:string)=>[...xml.matchAll(new RegExp(`<(?:\\w+:)?${tag}(?:\\s[^>]*)?>([^<]*)<\\/(?:\\w+:)?${tag}>`,`g`))].map(m=>m[1]);
export function parseCteResponse(xml:string){const cStats=all(xml,"cStat"),motivos=all(xml,"xMotivo"),chaves=all(xml,"chCTe"),protocolos=all(xml,"nProt"),cStat=cStats[cStats.length-1]||cStats[0]||null;return{authorized:cStat==="100",cStat,xMotivo:motivos[motivos.length-1]||motivos[0]||null,chCTe:chaves[chaves.length-1]||null,nProt:protocolos[protocolos.length-1]||null,raw:xml}}
