const esc=(v:unknown)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");
const digits=(v:unknown)=>String(v??"").replace(/\D/g,"");
const money=(v:unknown)=>Number(v||0).toFixed(2);
function mod11(base:string){let weight=2,sum=0;for(let i=base.length-1;i>=0;i--){sum+=Number(base[i])*weight;weight=weight===9?2:weight+1}const mod=11-(sum%11);return mod===10||mod===11?0:mod}
function cteDateTime(v?:unknown){if(v){const s=String(v).trim().replace(/\.\d{1,6}(?=[+-]\d{2}:\d{2}$)/,"").replace(/\.\d{1,6}Z$/, "Z");if(/Z$/.test(s)){const d=new Date(s);const local=new Date(d.getTime()-3*60*60*1000);return local.toISOString().slice(0,19)+"-03:00"}return s}const local=new Date(Date.now()-3*60*60*1000);return local.toISOString().slice(0,19)+"-03:00"}
export function buildCteXml(raw:Record<string,any>,issuerCnpj:string){
 const cUF=digits(raw.cUF||"27").padStart(2,"0"),dhEmi=cteDateTime(raw.dhEmi),aamm=dhEmi.slice(2,4)+dhEmi.slice(5,7),mod="57",serie=digits(raw.serie||"1").padStart(3,"0").slice(-3),nCT=digits(raw.numero||"1").padStart(9,"0").slice(-9),tpEmis=digits(raw.tpEmis||"1"),cCT=digits(raw.cCT||String(Date.now()).slice(-8)).padStart(8,"0").slice(-8),baseKey=`${cUF}${aamm}${issuerCnpj}${mod}${serie}${nCT}${tpEmis}${cCT}`,cDV=String(mod11(baseKey)),chave=baseKey+cDV,id=`CTe${chave}`,tpAmb=raw.environment==="production"?"1":"2",emit=raw.emit||{},rem=raw.rem||{},dest=raw.dest||{},carga=raw.carga||{},rod=raw.rodo||{},chNFe=digits(raw.chNFe),remIE=digits(rem.IE),destIE=digits(dest.IE),indIEToma=String(raw.indIEToma|| (remIE?"1":"9")),toma=String(raw.toma??"0");
 const xml=`<?xml version="1.0" encoding="UTF-8"?><CTe xmlns="http://www.portalfiscal.inf.br/cte"><infCte versao="4.00" Id="${id}"><ide><cUF>${cUF}</cUF><cCT>${cCT}</cCT><CFOP>${esc(raw.cfop||"5353")}</CFOP><natOp>${esc(raw.natOp||"PRESTACAO DE SERVICO DE TRANSPORTE")}</natOp><mod>57</mod><serie>${Number(serie)}</serie><nCT>${Number(nCT)}</nCT><dhEmi>${esc(dhEmi)}</dhEmi><tpImp>1</tpImp><tpEmis>${tpEmis}</tpEmis><cDV>${cDV}</cDV><tpAmb>${tpAmb}</tpAmb><tpCTe>0</tpCTe><procEmi>0</procEmi><verProc>WS-CTE-2.0</verProc><cMunEnv>${digits(emit.cMun)}</cMunEnv><xMunEnv>${esc(emit.xMun)}</xMunEnv><UFEnv>${esc(emit.UF)}</UFEnv><modal>01</modal><tpServ>0</tpServ><cMunIni>${digits(raw.cMunIni)}</cMunIni><xMunIni>${esc(raw.xMunIni)}</xMunIni><UFIni>${esc(raw.UFIni)}</UFIni><cMunFim>${digits(raw.cMunFim)}</cMunFim><xMunFim>${esc(raw.xMunFim)}</xMunFim><UFFim>${esc(raw.UFFim)}</UFFim><retira>1</retira><indIEToma>${esc(indIEToma)}</indIEToma><toma3><toma>${esc(toma)}</toma></toma3></ide><emit><CNPJ>${issuerCnpj}</CNPJ><IE>${digits(emit.IE)}</IE><xNome>${esc(emit.xNome)}</xNome><enderEmit><xLgr>${esc(emit.xLgr)}</xLgr><nro>${esc(emit.nro)}</nro><xBairro>${esc(emit.xBairro)}</xBairro><cMun>${digits(emit.cMun)}</cMun><xMun>${esc(emit.xMun)}</xMun><CEP>${digits(emit.CEP)}</CEP><UF>${esc(emit.UF)}</UF></enderEmit><CRT>${esc(emit.CRT||"1")}</CRT></emit><rem><CNPJ>${digits(rem.CNPJ)}</CNPJ>${remIE?`<IE>${remIE}</IE>`:""}<xNome>${esc(rem.xNome)}</xNome><enderReme><xLgr>${esc(rem.xLgr)}</xLgr><nro>${esc(rem.nro)}</nro><xBairro>${esc(rem.xBairro)}</xBairro><cMun>${digits(rem.cMun)}</cMun><xMun>${esc(rem.xMun)}</xMun><CEP>${digits(rem.CEP)}</CEP><UF>${esc(rem.UF)}</UF></enderReme></rem><dest><CNPJ>${digits(dest.CNPJ)}</CNPJ>${destIE?`<IE>${destIE}</IE>`:""}<xNome>${esc(dest.xNome)}</xNome><enderDest><xLgr>${esc(dest.xLgr)}</xLgr><nro>${esc(dest.nro)}</nro><xBairro>${esc(dest.xBairro)}</xBairro><cMun>${digits(dest.cMun)}</cMun><xMun>${esc(dest.xMun)}</xMun><CEP>${digits(dest.CEP)}</CEP><UF>${esc(dest.UF)}</UF></enderDest></dest><vPrest><vTPrest>${money(raw.vTPrest)}</vTPrest><vRec>${money(raw.vRec??raw.vTPrest)}</vRec></vPrest><imp><ICMS><ICMSSN><CST>90</CST><indSN>1</indSN></ICMSSN></ICMS></imp><infCTeNorm><infCarga><vCarga>${money(carga.vCarga)}</vCarga><proPred>${esc(carga.proPred||"CARGA GERAL")}</proPred><infQ><cUnid>01</cUnid><tpMed>PESO BRUTO</tpMed><qCarga>${Number(carga.qCarga||1).toFixed(4)}</qCarga></infQ></infCarga><infDoc>${chNFe?`<infNFe><chave>${chNFe}</chave></infNFe>`:""}</infDoc><infModal versaoModal="4.00"><rodo><RNTRC>${digits(rod.RNTRC)}</RNTRC></rodo></infModal></infCTeNorm></infCte></CTe>`;
 return{xml,chave,id,cDV}
}
export function validateCteInput(raw:Record<string,any>,issuerCnpj:string){const errors:string[]=[];if(issuerCnpj.length!==14)errors.push("Certificado sem CNPJ válido.");for(const[label,value,len]of[["IE do emitente",raw.emit?.IE,8],["Município do emitente",raw.emit?.cMun,7],["Município inicial",raw.cMunIni,7],["Município final",raw.cMunFim,7]] as Array<[string,unknown,number]>)if(digits(value).length<len)errors.push(`${label} inválido.`);if(!String(raw.emit?.xNome||"").trim())errors.push("Razão social do emitente obrigatória.");if(!String(raw.rem?.xNome||"").trim())errors.push("Remetente obrigatório.");if(!String(raw.dest?.xNome||"").trim())errors.push("Destinatário obrigatório.");if(!(Number(raw.vTPrest)>0))errors.push("Valor da prestação deve ser maior que zero.");if(!(Number(raw.carga?.vCarga)>0))errors.push("Valor da carga deve ser maior que zero.");if(!digits(raw.rodo?.RNTRC))errors.push("RNTRC obrigatório para modal rodoviário.");if(raw.chNFe&&digits(raw.chNFe).length!==44)errors.push("Chave da NF-e deve ter 44 dígitos.");return{valid:errors.length===0,errors}}
