import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import SaasEmissionHistory from "./SaasEmissionHistory";
import SaasDanfePreview,{printDanfe} from "./SaasDanfePreview";

const inputClass="mt-2 h-11 !border-[#d7dde5] !bg-white !text-[#10203e] dark:!bg-white dark:!text-[#10203e]";
const panel="saas-fiscal-card rounded-[12px] border border-[#dbe1e8] bg-white p-5 md:p-6";
const docs=["NF-e","NFC-e","NFS-e","CT-e","MDF-e"];
const MALVES_CNPJ="44454631000156";
const TEST_REMETENTE_CNPJ="12345678000195";
const TEST_DESTINATARIO_CNPJ="98765432000198";
const PLACEHOLDER_NFE_KEY="27260912345678000195550010000000011123456780";
const PLACEHOLDER_CTE_KEY="27260944454631000156570010000000021673862974";
const PLACEHOLDER_RNTRC="12345678";
const TEST_VEHICLE={plate:"MUI7179",driverName:"FABIO MARCOS MARTINS CAVALCANTE",driverCpf:"07359216443",tara:"6000",capacity:"12000"};
function digits(v:any){return String(v??"").replace(/\D/g,"")}
function Field({label,value,onChange,type="text",placeholder}:{label:string;value:any;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="text-sm font-medium text-[#263652]">{label}<Input type={type} value={value??""} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={inputClass}/></label>}
function Select({label,value,onChange,children}:{label:string;value:any;onChange:(v:string)=>void;children:any}){return <label className="text-sm font-medium text-[#263652]">{label}<select value={value??""} onChange={e=>onChange(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-[#cbd3dc] bg-white px-3 text-sm text-[#10203e]">{children}</select></label>}
function CatalogPicker({label,value,onChange,items,kind}:{label:string;value:string;onChange:(v:string)=>void;items:any[];kind:"product"|"service"}){const [open,setOpen]=useState(false),[q,setQ]=useState("");const chosen=items.find(x=>x.id===value);const filtered=items.filter(x=>String(`${x.name||""} ${x.code||""} ${x.ncm||""} ${x.service_code_national||""}`).toLowerCase().includes(q.toLowerCase())).slice(0,12);return <div className="catalog-picker"><label className="text-sm font-medium text-[#263652]">{label}</label><button type="button" className={`catalog-picker-trigger ${chosen?"has-value":""}`} onClick={()=>setOpen(v=>!v)}><span><strong>{chosen?.name||`Selecionar ${kind==="product"?"produto":"serviço"}`}</strong><small>{chosen?(kind==="product"?[chosen.code,chosen.ncm?`NCM ${chosen.ncm}`:null].filter(Boolean).join(" · "):[chosen.code,chosen.service_code_national?`Código ${chosen.service_code_national}`:null].filter(Boolean).join(" · ")):"Busque por nome, código ou classificação fiscal"}</small></span><span className="catalog-picker-price">{chosen?.sale_price!=null?Number(chosen.sale_price).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):""}</span></button>{open&&<div className="catalog-picker-popover"><Input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={`Buscar ${kind==="product"?"produto":"serviço"}...`} className="catalog-picker-search"/><div className="catalog-picker-list">{filtered.length?filtered.map(x=><button type="button" key={x.id} className="catalog-picker-option" onClick={()=>{onChange(x.id);setOpen(false);setQ("")}}><span><strong>{x.name}</strong><small>{kind==="product"?[x.code,x.ncm?`NCM ${x.ncm}`:null,x.stock_managed?`Estoque ${x.stock_quantity??0}`:null].filter(Boolean).join(" · "):[x.code,x.service_code_national?`Código ${x.service_code_national}`:null].filter(Boolean).join(" · ")}</small></span><b>{x.sale_price!=null?Number(x.sale_price).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):"—"}</b></button>):<div className="catalog-picker-empty">Nenhum item encontrado.</div>}</div></div>}</div>}
function pickParty(parties:any[],cnpj:string,fallbackIndex:number){return parties.find(x=>digits(x.tax_id)===cnpj)||parties[fallbackIndex]}
function scenarioPatch(f:any,parties:any[],hist:any[],force=false){
 const fill=(cur:any,val:any,dflt?:any)=>force?(val??cur):(cur===""||cur==null||(dflt!==undefined&&cur===dflt)?val:cur);
 const rem=pickParty(parties,TEST_REMETENTE_CNPJ,0),dest=pickParty(parties,TEST_DESTINATARIO_CNPJ,1)||parties.find((x:any)=>x.id!==rem?.id);
 const nfe=hist.find(x=>x.document_type==="nfe"&&x.status==="authorized"&&digits(x.access_key).length===44);
 const cte=hist.find(x=>x.document_type==="cte"&&x.status==="authorized"&&digits(x.access_key).length===44);
 const key=nfe?.access_key||PLACEHOLDER_NFE_KEY;
 const mdfeKey=cte?.access_key||PLACEHOLDER_CTE_KEY;
 return {...f,
  remetenteId:fill(f.remetenteId,rem?.id||f.remetenteId),
  destinatarioId:fill(f.destinatarioId,dest?.id||f.destinatarioId),
  cfopCte:fill(f.cfopCte,"5353","5353"),
  vTPrest:fill(f.vTPrest,"250.00"),
  vCarga:fill(f.vCarga,"5000.00"),
  qCarga:fill(f.qCarga,"1000.0000","1"),
  munIniCodigo:fill(f.munIniCodigo,rem?.city_ibge_code||"2701209"),
  munIniNome:fill(f.munIniNome,rem?.city||"Cacimbinhas"),
  ufIni:fill(f.ufIni,rem?.state||"AL","AL"),
  munFimCodigo:fill(f.munFimCodigo,dest?.city_ibge_code||"2704401"),
  munFimNome:fill(f.munFimNome,dest?.city||"Major Isidoro"),
  ufFim:fill(f.ufFim,dest?.state||"AL","AL"),
  chNFe:fill(f.chNFe,key),
  keys:fill(f.keys,mdfeKey),
  rntrc:fill(f.rntrc,PLACEHOLDER_RNTRC),
  plate:fill(f.plate,TEST_VEHICLE.plate),
  driverName:fill(f.driverName,TEST_VEHICLE.driverName),
  driverCpf:fill(f.driverCpf,TEST_VEHICLE.driverCpf),
  tara:fill(f.tara,TEST_VEHICLE.tara,"1000"),
  capacity:fill(f.capacity,TEST_VEHICLE.capacity,"5000"),
  unloadCode:fill(f.unloadCode,dest?.city_ibge_code||"2704401"),
  unloadName:fill(f.unloadName,dest?.city||"Major Isidoro"),
  cargoValue:fill(f.cargoValue,"5000.00"),
  cargoWeight:fill(f.cargoWeight,"1000.0000")};
}
function downloadXml(xml:string,name:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([xml],{type:"application/xml"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

export default function SaasEmission({organizationId,documentType,onChoose}:{organizationId:string|null;documentType:string|null;onChoose:(d:string|null)=>void}){
 const [profile,setProfile]=useState<any>(null),[customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[services,setServices]=useState<any[]>([]),[carriers,setCarriers]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[result,setResult]=useState<any>(null);
 const [form,setForm]=useState<any>({customerId:"",productId:"",serviceId:"",quantity:"1",unitPrice:"",series:"1",number:"1",payment:"01",cfop:"",description:"",value:"",serviceCode:"",municipioPrestacao:"",remetenteId:"",destinatarioId:"",carrierId:"",rntrc:"",chNFe:"",cfopCte:"5353",vTPrest:"",vCarga:"",qCarga:"1",munIniCodigo:"",munIniNome:"",ufIni:"AL",munFimCodigo:"",munFimNome:"",ufFim:"AL",plate:"",driverName:"",driverCpf:"",tara:"1000",capacity:"5000",unloadCode:"",unloadName:"",cargoValue:"",cargoWeight:"",keys:""});
 const set=(k:string,v:any)=>setForm((p:any)=>({...p,[k]:v}));
 const isTransportTest=digits(profile?.tax_id)===MALVES_CNPJ&&profile?.fiscal_environment!=="production";
 const displayProfile=profile;
 const load=async()=>{if(!organizationId)return;const [p,c,pr,s,ca,h]=await Promise.all([(supabase as any).from("saas_company_fiscal_profiles").select("*").eq("organization_id",organizationId).order("created_at").limit(1).maybeSingle(),(supabase as any).from("saas_fiscal_parties").select("*").eq("organization_id",organizationId).eq("party_type","customer").eq("status","active").order("legal_name"),(supabase as any).from("saas_fiscal_catalog_items").select("*").eq("organization_id",organizationId).eq("item_type","product").eq("status","active").order("name"),(supabase as any).from("saas_fiscal_catalog_items").select("*").eq("organization_id",organizationId).eq("item_type","service").eq("status","active").order("name"),(supabase as any).from("saas_fiscal_parties").select("*").eq("organization_id",organizationId).eq("party_type","carrier").eq("status","active").order("legal_name"),(supabase as any).from("saas_fiscal_emissions").select("*").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(50)]);setProfile(p.data);setCustomers(c.data||[]);setProducts(pr.data||[]);setServices(s.data||[]);setCarriers(ca.data||[]);setHistory(h.data||[]);const pp=p.data;const testScenario=digits(pp?.tax_id)===MALVES_CNPJ&&pp?.fiscal_environment!=="production";if(pp)setForm((f:any)=>{const base={...f,series:documentType==="NF-e"?pp.series_nfe||"1":documentType==="NFC-e"?pp.series_nfce||"1":documentType==="NFS-e"?pp.series_nfse||"1":documentType==="CT-e"?pp.series_cte||"1":pp.series_mdfe||"1",number:String(documentType==="NF-e"?pp.next_number_nfe||1:documentType==="NFC-e"?pp.next_number_nfce||1:documentType==="NFS-e"?pp.next_number_nfse||1:documentType==="CT-e"?pp.next_number_cte||1:pp.next_number_mdfe||1),cfop:pp.default_cfop_in_state||"5102",serviceCode:pp.default_nfse_service_code||"",municipioPrestacao:pp.city_ibge_code||"",munIniCodigo:f.munIniCodigo||pp.city_ibge_code||"",munIniNome:f.munIniNome||pp.city||"",ufIni:f.ufIni||pp.state||"AL"};return testScenario&&(documentType==="CT-e"||documentType==="MDF-e")?scenarioPatch(base,c.data||[],h.data||[]):base;});};
 useEffect(()=>{void load();setResult(null);setMsg("")},[organizationId,documentType]);
 const customer=customers.find(x=>x.id===form.customerId),product=products.find(x=>x.id===form.productId),service=services.find(x=>x.id===form.serviceId),rem=customers.find(x=>x.id===form.remetenteId),dest=customers.find(x=>x.id===form.destinatarioId),carrier=carriers.find(x=>x.id===form.carrierId);
 useEffect(()=>{if(product)setForm((f:any)=>({...f,unitPrice:String(product.sale_price??""),cfop:product.cfop_in_state||displayProfile?.default_cfop_in_state||f.cfop}))},[form.productId]);
 useEffect(()=>{if(service)setForm((f:any)=>({...f,value:String(service.sale_price??""),description:service.description||service.name,serviceCode:service.service_code_national||displayProfile?.default_nfse_service_code||f.serviceCode}))},[form.serviceId]);
 const environment=displayProfile?.fiscal_environment==="production"?"production":"homologation";
 const backendMatchesTransport=!isTransportTest||digits(profile?.tax_id)===MALVES_CNPJ;
 const latestAuthorizedNfe=history.find(x=>x.document_type==="nfe"&&x.status==="authorized"&&digits(x.access_key).length===44);
 const latestAuthorizedCte=history.find(x=>x.document_type==="cte"&&x.status==="authorized"&&digits(x.access_key).length===44);
 const applyTransportScenario=()=>{
   setForm((f:any)=>scenarioPatch(f,customers,history,true));
   setMsg(documentType==="MDF-e"?(latestAuthorizedCte?"Cenário de MDF-e carregado com CT-e autorizado do histórico.":"Cenário de MDF-e carregado. Em homologação, use CT-e autorizado para prestador de serviço."):(latestAuthorizedNfe?"Cenário de transporte carregado com uma NF-e autorizada do histórico. Confira o RNTRC real antes de transmitir.":"Cenário de transporte carregado com dados fictícios de homologação. Confira chave fiscal e RNTRC reais antes de transmitir."));
 };
 const usingPlaceholders=environment!=="production"&&(digits(form.chNFe)===PLACEHOLDER_NFE_KEY||String(form.keys||"").includes(PLACEHOLDER_NFE_KEY)||digits(form.rntrc)===PLACEHOLDER_RNTRC);
 const transportMissing=[!form.remetenteId&&"remetente",!form.destinatarioId&&"destinatário",!digits(form.rntrc)&&"RNTRC",documentType==="CT-e"&&digits(form.chNFe).length!==44&&"NF-e vinculada",documentType==="MDF-e"&&digits(form.keys).length<44&&"chave fiscal",documentType==="MDF-e"&&!form.plate&&"placa",documentType==="MDF-e"&&digits(form.driverCpf).length!==11&&"CPF do condutor"].filter(Boolean) as string[];
 const transportCanTransmit=backendMatchesTransport&&transportMissing.length===0;
 const readEdgeError=async(e:any)=>{try{const res=e?.context;if(res&&typeof res.json==="function"){const body=await res.clone().json();const parts=[body?.error,...(body?.errors||[])].filter(Boolean);if(parts.length)return parts.join(" · ")}}catch{/* ignore */}return e?.message||"Falha no processamento fiscal"};
 const invoke=async(name:string,body:any)=>{setBusy(true);setMsg("");setResult(null);try{const {data,error}=await supabase.functions.invoke(name,{body:{...body,organization_id:organizationId,expected_environment:environment}});if(error)throw error;if(data?.error){setMsg([data.error,...(data.errors||[])].join(" · "));setResult(data);return}setResult(data);setMsg(data?.authorized===false?"Documento rejeitado pelo autorizador.":body.action==="status"?`Status SEFAZ: ${data?.cStat||data?.response?.cStat||""} ${data?.xMotivo||data?.response?.xMotivo||""}`.trim():body.action==="preview"?"Prévia gerada e assinada para conferência.":"Processamento concluído.");if(body.action==="issue")await load()}catch(e:any){setMsg(await readEdgeError(e))}finally{setBusy(false)}};
 const productPayload=()=>({environment,cnpjEmitente:displayProfile?.tax_id,razaoSocial:displayProfile?.legal_name,nomeFantasia:displayProfile?.trade_name,ie:displayProfile?.state_registration,crt:displayProfile?.crt||"1",codigoMunicipio:displayProfile?.city_ibge_code,nomeMunicipio:displayProfile?.city,logradouro:displayProfile?.street,numeroEndereco:displayProfile?.street_number,complemento:displayProfile?.complement,bairro:displayProfile?.district,cep:displayProfile?.postal_code,telefone:displayProfile?.phone,serie:form.series,numeroNota:form.number,destDocumento:customer?.tax_id||"",destNome:customer?.legal_name||"CONSUMIDOR",destLogradouro:customer?.street,destNumero:customer?.street_number,destBairro:customer?.district,destCodigoMunicipio:customer?.city_ibge_code,destMunicipio:customer?.city,destUF:customer?.state,destCep:customer?.postal_code,codigoProduto:product?.code||"1",produto:product?.name||"PRODUTO",ncm:product?.ncm,cfop:form.cfop||product?.cfop_in_state,unidade:product?.unit||"UN",quantidade:Number(form.quantity),valorUnitario:Number(form.unitPrice),origem:product?.product_origin||"0",csosn:product?.csosn||"400",cst:product?.icms_cst||"00",formaPagamento:form.payment});
 const nfsePayload=()=>({environment,serie:form.series,numero:form.number,municipioEmissor:displayProfile?.city_ibge_code,municipioPrestacao:form.municipioPrestacao,codigoTributacao:form.serviceCode,descricao:form.description,valor:Number(form.value),tomadorDocumento:customer?.tax_id,tomadorNome:customer?.legal_name,simples:displayProfile?.tax_regime==="simples"?"1":"2",issRetido:Boolean(service?.iss_withheld)});
 const partyCte=(x:any)=>({CNPJ:String(x?.tax_id||"").replace(/\D/g,""),IE:x?.state_registration||"",xNome:x?.legal_name||"",xLgr:x?.street||"",nro:x?.street_number||"",xBairro:x?.district||"",cMun:x?.city_ibge_code||"",xMun:x?.city||"",CEP:x?.postal_code||"",UF:x?.state||"AL"});
 const ctePayload=()=>({environment,serie:form.series,numero:form.number,cfop:form.cfopCte,natOp:"PRESTACAO DE SERVICO DE TRANSPORTE",cUF:"27",cMunIni:form.munIniCodigo,xMunIni:form.munIniNome,UFIni:form.ufIni,cMunFim:form.munFimCodigo,xMunFim:form.munFimNome,UFFim:form.ufFim,vTPrest:Number(form.vTPrest),vRec:Number(form.vTPrest),emit:{IE:displayProfile?.state_registration,xNome:displayProfile?.legal_name,xLgr:displayProfile?.street,nro:displayProfile?.street_number,xBairro:displayProfile?.district,cMun:displayProfile?.city_ibge_code,xMun:displayProfile?.city,CEP:displayProfile?.postal_code,UF:displayProfile?.state||"AL",CRT:displayProfile?.crt||"1"},rem:partyCte(rem),dest:partyCte(dest),carga:{vCarga:Number(form.vCarga),proPred:"CARGA GERAL",qCarga:Number(form.qCarga)},chNFe:form.chNFe,rodo:{RNTRC:form.rntrc||carrier?.rntrc}});
 const mdfePayload=()=>({environment,serie:form.series,numero:form.number,rntrc:form.rntrc||carrier?.rntrc,placa:form.plate||carrier?.vehicle_plate,veiculoUf:carrier?.vehicle_state||displayProfile?.state||"AL",condutorNome:form.driverName,condutorCpf:form.driverCpf,tara:Number(form.tara),capacidadeKg:Number(form.capacity),ufIni:form.ufIni,ufFim:form.ufFim,munCarregaCodigo:form.munIniCodigo,munCarregaNome:form.munIniNome,munDescargaCodigo:form.unloadCode,munDescargaNome:form.unloadName,valorCarga:Number(form.cargoValue),pesoCarga:Number(form.cargoWeight),chaves:String(form.keys||"").split(/[\n,; ]+/).filter(Boolean)});
 const currentHistory=useMemo(()=>history.filter(x=>!documentType||x.document_type===({"NF-e":"nfe","NFC-e":"nfce","NFS-e":"nfse","CT-e":"cte","MDF-e":"mdfe"} as any)[documentType]),[history,documentType]);
 if(!documentType)return <div><h1 className="text-3xl font-semibold tracking-[-0.04em]">Emitir nova nota</h1><p className="mt-2 text-sm text-[#6d7a90]">Escolha o documento fiscal que deseja preencher.</p>{isTransportTest&&<div className="mt-5 rounded-lg border border-[#cfd6df] bg-white p-4 text-sm"><strong>Empresa de teste:</strong> MSILVA TRANSPORTES · CNPJ 44.454.631/0001-56 · Cacimbinhas/AL. Para o primeiro ciclo, use CT-e e MDF-e.</div>}<div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{docs.map(d=><button key={d} onClick={()=>onChoose(d)} className="min-h-[145px] rounded-lg border border-[#cfd6df] bg-white p-6 text-left hover:border-[#8b98a9]"><p className="text-2xl font-semibold">{d}</p><p className="mt-3 text-sm text-[#6d7a90]">Abrir fluxo de {d}.</p><p className="mt-7 text-xs font-semibold uppercase tracking-[.12em]">Continuar</p></button>)}</div></div>;
 const actions=(name:string,payload:any,extra:any={},transport=false)=><div className="saas-emission-actions"><Button variant="outline" className="saas-action-secondary" disabled={busy||(transport&&!transportCanTransmit)} onClick={()=>invoke(name,{action:"preview",data:payload,...extra})}>{busy?"Processando...":"Conferir documento"}</Button><Button disabled={busy||(transport&&!transportCanTransmit)} onClick={()=>invoke(name,{action:"issue",data:payload,...extra})} className="saas-action-primary">{busy?"Processando...":environment==="production"?"Emitir em produção":"Transmitir para homologação"}</Button></div>;
 return <div className="saas-emission-page space-y-5 pb-10"><div className="saas-emission-header"><button onClick={()=>onChoose(null)} className="saas-back-link mb-4 text-sm font-semibold text-[#58709a]">Voltar</button><h1 className="text-3xl font-semibold tracking-[-0.04em]">Emitir {documentType}</h1><p className="mt-2 text-sm text-[#6d7a90]">Preencha à esquerda e acompanhe o DANFE e o retorno fiscal ao lado.</p><div className={`mx-auto mt-3 w-fit rounded-md border px-3 py-1.5 text-xs font-semibold uppercase tracking-[.1em] ${environment==="production"?"border-red-300 bg-red-50 text-red-700":"border-slate-300 bg-white text-slate-600"}`}>Ambiente: {environment==="production"?"Produção":"Homologação"}</div></div>{isTransportTest&&(documentType==="CT-e"||documentType==="MDF-e")&&<section className="rounded-lg border border-[#cfd6df] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#6d7a90]">Cenário de homologação</p><p className="mt-1 font-semibold">MSILVA TRANSPORTES · Cacimbinhas/AL</p><p className="mt-1 text-xs text-[#6d7a90]">Rota, valores, veículo e condutor de teste podem ser preenchidos automaticamente. O sistema não inventa RNTRC nem chave fiscal.</p></div><Button onClick={applyTransportScenario}>Preencher cenário de transporte</Button></div>{!backendMatchesTransport&&<p className="mt-3 rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-medium text-amber-800">O perfil fiscal do backend ainda está vinculado à empresa anterior. A transmissão fica bloqueada até o A1 e o perfil da M ALVES SILVA estarem sincronizados no cofre.</p>}{usingPlaceholders&&<p className="mt-3 rounded-md border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-medium text-slate-700">Chave fiscal e/ou RNTRC preenchidos com dados fictícios exclusivos de homologação — podem ser rejeitados pelo autorizador. Substitua pelos dados reais antes de emitir em produção.</p>}{transportMissing.length>0&&<p className="mt-3 text-xs text-[#6d7a90]">Pendências para transmitir: {transportMissing.join(", ")}.</p>}</section>}{msg&&<div className="rounded-lg border border-[#cfd6df] bg-white px-4 py-3 text-sm">{msg}</div>}
 <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.08fr)_minmax(430px,.92fr)]"><div className="space-y-4">
 {(documentType==="NF-e"||documentType==="NFC-e")&&<><section className={panel}><h2 className="font-semibold">Destinatário e produto</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Cliente" value={form.customerId} onChange={v=>set("customerId",v)}><option value="">{documentType==="NFC-e"?"Consumidor não identificado":"Selecione"}</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><CatalogPicker label="Produto" value={form.productId} onChange={v=>set("productId",v)} items={products} kind="product"/><Field label="Quantidade" value={form.quantity} onChange={v=>set("quantity",v)} type="number"/><Field label="Valor unitário" value={form.unitPrice} onChange={v=>set("unitPrice",v)} type="number"/><Field label="CFOP" value={form.cfop} onChange={v=>set("cfop",v)}/><Field label="Série" value={form.series} onChange={v=>set("series",v)}/><Field label="Número" value={form.number} onChange={v=>set("number",v)} type="number"/><Select label="Pagamento" value={form.payment} onChange={v=>set("payment",v)}><option value="01">Dinheiro</option><option value="03">Cartão de crédito</option><option value="04">Cartão de débito</option><option value="17">PIX</option><option value="99">Outros</option></Select></div></section>{actions("saas-dfe-issue",productPayload(),{model:documentType==="NF-e"?"55":"65"})}</>}
 {documentType==="NFS-e"&&<><section className={panel}><h2 className="font-semibold">Tomador e serviço</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Cliente / tomador" value={form.customerId} onChange={v=>set("customerId",v)}><option value="">Selecione</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><CatalogPicker label="Serviço" value={form.serviceId} onChange={v=>set("serviceId",v)} items={services} kind="service"/><Field label="Valor" value={form.value} onChange={v=>set("value",v)} type="number"/><Field label="Código tributação nacional" value={form.serviceCode} onChange={v=>set("serviceCode",v)}/><Field label="Município da prestação (IBGE)" value={form.municipioPrestacao} onChange={v=>set("municipioPrestacao",v)}/><Field label="Série DPS" value={form.series} onChange={v=>set("series",v)}/><Field label="Número DPS" value={form.number} onChange={v=>set("number",v)} type="number"/><div className="md:col-span-2"><Field label="Descrição" value={form.description} onChange={v=>set("description",v)}/></div></div></section>{actions("saas-nfse-issue",nfsePayload())}</>}
 {documentType==="CT-e"&&<><section className={panel}><h2 className="font-semibold">Prestação de transporte</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Remetente" value={form.remetenteId} onChange={v=>set("remetenteId",v)}><option value="">Selecione</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Select label="Destinatário" value={form.destinatarioId} onChange={v=>set("destinatarioId",v)}><option value="">Selecione</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Select label="Transportadora" value={form.carrierId} onChange={v=>set("carrierId",v)}><option value="">Própria / manual</option>{carriers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Field label="RNTRC" value={form.rntrc} onChange={v=>set("rntrc",v)} placeholder={carrier?.rntrc||"RNTRC real da M ALVES SILVA"}/><Field label="CFOP" value={form.cfopCte} onChange={v=>set("cfopCte",v)}/><Field label="Chave NF-e vinculada" value={form.chNFe} onChange={v=>set("chNFe",v)}/><Field label="Valor da prestação" value={form.vTPrest} onChange={v=>set("vTPrest",v)} type="number"/><Field label="Valor da carga" value={form.vCarga} onChange={v=>set("vCarga",v)} type="number"/><Field label="Peso / quantidade carga" value={form.qCarga} onChange={v=>set("qCarga",v)} type="number"/><Field label="Município início IBGE" value={form.munIniCodigo} onChange={v=>set("munIniCodigo",v)}/><Field label="Município início" value={form.munIniNome} onChange={v=>set("munIniNome",v)}/><Field label="UF início" value={form.ufIni} onChange={v=>set("ufIni",v)}/><Field label="Município fim IBGE" value={form.munFimCodigo} onChange={v=>set("munFimCodigo",v)}/><Field label="Município fim" value={form.munFimNome} onChange={v=>set("munFimNome",v)}/><Field label="UF fim" value={form.ufFim} onChange={v=>set("ufFim",v)}/><Field label="Série" value={form.series} onChange={v=>set("series",v)}/><Field label="Número" value={form.number} onChange={v=>set("number",v)} type="number"/></div></section>{actions("saas-cte-issue",ctePayload(),{},true)}</>}
 {documentType==="MDF-e"&&<><section className={panel}><h2 className="font-semibold">Manifesto de transporte</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Transportadora" value={form.carrierId} onChange={v=>set("carrierId",v)}><option value="">Própria / manual</option>{carriers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Field label="RNTRC" value={form.rntrc} onChange={v=>set("rntrc",v)} placeholder={carrier?.rntrc||"RNTRC real da M ALVES SILVA"}/><Field label="Placa" value={form.plate} onChange={v=>set("plate",v)} placeholder={carrier?.vehicle_plate}/><Field label="Condutor" value={form.driverName} onChange={v=>set("driverName",v)}/><Field label="CPF do condutor" value={form.driverCpf} onChange={v=>set("driverCpf",v)}/><Field label="Tara (kg)" value={form.tara} onChange={v=>set("tara",v)} type="number"/><Field label="Capacidade (kg)" value={form.capacity} onChange={v=>set("capacity",v)} type="number"/><Field label="Município carga IBGE" value={form.munIniCodigo} onChange={v=>set("munIniCodigo",v)}/><Field label="Município carga" value={form.munIniNome} onChange={v=>set("munIniNome",v)}/><Field label="Município descarga IBGE" value={form.unloadCode} onChange={v=>set("unloadCode",v)}/><Field label="Município descarga" value={form.unloadName} onChange={v=>set("unloadName",v)}/><Field label="UF final" value={form.ufFim} onChange={v=>set("ufFim",v)}/><Field label="Valor da carga" value={form.cargoValue} onChange={v=>set("cargoValue",v)} type="number"/><Field label="Peso da carga" value={form.cargoWeight} onChange={v=>set("cargoWeight",v)} type="number"/><Field label="Série" value={form.series} onChange={v=>set("series",v)}/><Field label="Número" value={form.number} onChange={v=>set("number",v)} type="number"/><div className="md:col-span-2"><label className="text-sm font-medium">Chaves NF-e/CT-e<textarea value={form.keys} onChange={e=>set("keys",e.target.value)} rows={4} className="mt-2 w-full rounded-md border border-[#cbd3dc] bg-white p-3 text-sm" placeholder="Uma chave de 44 dígitos por linha"/></label></div></div></section>{actions("saas-mdfe-issue",mdfePayload(),{},true)}</>}
 </div><FiscalPreview documentType={documentType} environment={environment} profile={displayProfile} form={form} customer={customer} product={product} service={service} dest={dest} result={result}/></div>
 <SaasEmissionHistory items={currentHistory} documentType={documentType}/></div>;
}

function FiscalPreview({documentType,environment,profile,form,customer,product,service,dest,result}:{documentType:string;environment:string;profile:any;form:any;customer:any;product:any;service:any;dest:any;result:any}){
 const payload=documentType==="NFS-e"?{...profile,serie:form.series,numero:form.number,descricao:service?.name||form.description,valor:Number(form.value||0),tomadorNome:customer?.legal_name,tomadorDocumento:customer?.tax_id,codigoTributacao:form.serviceCode}:documentType==="CT-e"?{...profile,serie:form.series,numero:form.number,natOp:"PRESTACAO DE SERVICO DE TRANSPORTE",vTPrest:Number(form.vTPrest||0),dest:{xNome:dest?.legal_name,CNPJ:String(dest?.tax_id||"").replace(/\D/g,""),xLgr:dest?.street,nro:dest?.street_number,xBairro:dest?.district,xMun:dest?.city,UF:dest?.state},cfopCte:form.cfopCte}:documentType==="MDF-e"?{...profile,serie:form.series,numero:form.number,natOp:"MANIFESTO DE DOCUMENTOS FISCAIS",valorCarga:Number(form.cargoValue||0),munDescargaNome:form.unloadName}: {cnpjEmitente:profile?.tax_id,razaoSocial:profile?.legal_name,nomeFantasia:profile?.trade_name,ie:profile?.state_registration,logradouro:profile?.street,numeroEndereco:profile?.street_number,bairro:profile?.district,nomeMunicipio:profile?.city,serie:form.series,numeroNota:form.number,destDocumento:customer?.tax_id,destNome:customer?.legal_name,destLogradouro:customer?.street,destNumero:customer?.street_number,destBairro:customer?.district,destMunicipio:customer?.city,destUF:customer?.state,codigoProduto:product?.code,produto:product?.name,ncm:product?.ncm,cfop:form.cfop,unidade:product?.unit||"UN",quantidade:Number(form.quantity||0),valorUnitario:Number(form.unitPrice||0)};
 const xml=result?.xml||result?.xmlAssinado;
 return <aside className="saas-document-preview xl:sticky xl:top-[92px] space-y-3"><div className="flex flex-wrap justify-end gap-2"><button onClick={()=>printDanfe("live-danfe",`${documentType}-${form.number}`)} className="rounded-md border border-[#202833] bg-[#202833] px-3 py-2 text-xs font-semibold text-white">Imprimir / salvar PDF</button>{xml&&<button onClick={()=>downloadXml(xml,`${documentType}-${form.number}.xml`)} className="rounded-md border border-[#aeb8c5] bg-white px-3 py-2 text-xs font-semibold text-[#202833]">Baixar XML</button>}</div><SaasDanfePreview id="live-danfe" documentType={documentType} environment={environment} profile={profile} data={payload} result={result}/></aside>
}