import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Building2, CheckCircle2, FileBadge2, ImagePlus, MapPin, ReceiptText, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AdminPageHeader, AdminSection } from "@/components/admin/ui/AdminPage";
import { supabase } from "@/integrations/supabase/client";

type Props={organizationId:string|null;organizationName?:string;onLogoChanged?:(url:string|null)=>void};
const defaults:any={business_mode:"mixed",tax_regime:"",crt:"1",state_registration:"",municipal_registration:"",cnae_primary:"",fiscal_environment:"homologation",legal_name:"",trade_name:"",tax_id:"",phone:"",email:"",postal_code:"",street:"",street_number:"",complement:"",district:"",city:"",state:"AL",city_ibge_code:"",default_cfop_in_state:"5102",default_cfop_out_state:"6102",default_nfse_service_code:"",default_iss_rate:"",series_nfe:"1",next_number_nfe:1,series_nfce:"1",next_number_nfce:1,series_nfse:"1",next_number_nfse:1,series_cte:"1",next_number_cte:1,series_mdfe:"1",next_number_mdfe:1};
const inputClass="mt-2 h-10 border-border/60 bg-background text-foreground shadow-none focus-visible:ring-1 focus-visible:ring-foreground/15";
function Field({label,k,form,setForm,type="text"}:{label:string;k:string;form:any;setForm:any;type?:string}){return <label className="text-xs font-medium text-foreground/80">{label}<Input type={type} value={form[k]??""} onChange={e=>setForm((p:any)=>({...p,[k]:e.target.value}))} className={inputClass}/></label>}
function SectionHead({eyebrow,title,description,icon:Icon}:{eyebrow:string;title:string;description:string;icon:any}){return <div className="flex gap-3 border-b border-border/40 px-5 py-4"><div className="mt-0.5 rounded-xl bg-muted/45 p-2.5"><Icon className="h-4 w-4 text-muted-foreground"/></div><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-muted-foreground">{eyebrow}</p><h3 className="mt-1 font-medium">{title}</h3><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{description}</p></div></div>}
export default function SaasCompanyProfile({organizationId,organizationName,onLogoChanged}:Props){
 const [form,setForm]=useState<any>(defaults),[certificate,setCertificate]=useState(false),[logoUrl,setLogoUrl]=useState<string|null>(null),[logoPath,setLogoPath]=useState<string|null>(null),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false),[password,setPassword]=useState("");const logoRef=useRef<HTMLInputElement>(null);
 const load=async()=>{if(!organizationId)return;const {data,error}=await supabase.functions.invoke("saas-fiscal-config",{body:{action:"get",organization_id:organizationId}});if(error){setMsg(error.message);return}const p=data?.profile||{};setForm({...defaults,...p});setCertificate(Boolean(data?.certificate_configured));setLogoPath(p.logo_path||null);if(p.logo_path){const {data:s}=await supabase.storage.from("saas-private").createSignedUrl(p.logo_path,3600);setLogoUrl(s?.signedUrl||null)}};
 useEffect(()=>{void load()},[organizationId]);
 const save=async()=>{if(!organizationId)return;setSaving(true);setMsg("");const {data,error}=await supabase.functions.invoke("saas-fiscal-config",{body:{action:"save_profile",organization_id:organizationId,profile:form}});setSaving(false);if(error||data?.error)setMsg(data?.error||error?.message||"Erro ao salvar");else{setForm({...defaults,...data.profile});setMsg("Dados da empresa salvos com sucesso.")}};
 const uploadLogo=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!organizationId)return;setSaving(true);const ext=file.name.split(".").pop()?.toLowerCase()||"png",path=`${organizationId}/branding/company-logo-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("saas-private").upload(path,file,{upsert:false,cacheControl:"3600"});if(error){setMsg(error.message);setSaving(false);return}const {data:p}=await (supabase as any).from("saas_company_fiscal_profiles").select("id").eq("organization_id",organizationId).order("created_at").limit(1).maybeSingle();if(p?.id)await (supabase as any).from("saas_company_fiscal_profiles").update({logo_path:path,updated_at:new Date().toISOString()}).eq("id",p.id);else await (supabase as any).from("saas_company_fiscal_profiles").insert({organization_id:organizationId,logo_path:path});const {data:s}=await supabase.storage.from("saas-private").createSignedUrl(path,3600);setLogoPath(path);setLogoUrl(s?.signedUrl||null);onLogoChanged?.(s?.signedUrl||null);setMsg("Logomarca atualizada.");setSaving(false);e.target.value=""};
 const uploadCertificate=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!organizationId)return;if(!password){setMsg("Informe a senha do certificado antes de selecionar o arquivo.");return}const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(const b of bytes)binary+=String.fromCharCode(b);setSaving(true);const {data,error}=await supabase.functions.invoke("saas-fiscal-config",{body:{action:"save_certificate",organization_id:organizationId,certificate_base64:btoa(binary),certificate_password:password}});setSaving(false);if(error||data?.error)setMsg(data?.error||error?.message||"Erro ao salvar certificado");else{setCertificate(true);setPassword("");setMsg(`Certificado configurado até ${new Date(data.certificate.expires_at).toLocaleDateString("pt-BR")}.`)}};
 const status=[{label:"Cadastro fiscal",ok:Boolean(form.tax_id&&form.legal_name&&form.city_ibge_code),icon:Building2},{label:"Certificado A1",ok:certificate,icon:ShieldCheck},{label:"Endereço",ok:Boolean(form.street&&form.city&&form.state),icon:MapPin},{label:"Numeração fiscal",ok:Boolean(form.series_nfe&&form.series_nfce&&form.series_nfse),icon:ReceiptText}];
 return <div className="mx-auto w-full max-w-[1540px] space-y-5"><AdminPageHeader eyebrow="Configuração da conta" title="Minha Empresa" description="Identidade, dados fiscais, endereço, certificado e padrões usados em todas as emissões." actions={<Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar alterações"}</Button>}/>{msg&&<div className="rounded-xl border border-border/55 bg-card px-4 py-3 text-sm text-foreground shadow-sm">{msg}</div>}
 <AdminSection><div className="grid lg:grid-cols-[280px_1fr]"><div className="border-b border-border/40 p-5 lg:border-b-0 lg:border-r"><input ref={logoRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={uploadLogo}/><button onClick={()=>logoRef.current?.click()} className="group relative flex aspect-[4/3] w-full items-center justify-center overflow-hidden rounded-2xl border border-dashed border-border/70 bg-muted/20 transition hover:bg-muted/35">{logoUrl?<img src={logoUrl} alt="Logo da empresa" className="max-h-[72%] max-w-[78%] object-contain"/>:<div className="text-center text-muted-foreground"><ImagePlus className="mx-auto h-7 w-7"/><p className="mt-2 text-xs font-medium">Adicionar logomarca</p></div>}<span className="absolute bottom-3 rounded-full bg-background/90 px-3 py-1 text-[10px] font-medium text-muted-foreground opacity-0 shadow-sm transition group-hover:opacity-100">Alterar logo</span></button><p className="mt-4 text-[10px] font-semibold uppercase tracking-[.14em] text-muted-foreground">Empresa ativa</p><h2 className="mt-1 text-lg font-medium">{form.trade_name||form.legal_name||organizationName||"Sua empresa"}</h2><p className="mt-1 text-xs text-muted-foreground">{form.tax_id||"CNPJ ainda não informado"}</p></div><div className="grid gap-px bg-border/30 sm:grid-cols-2 xl:grid-cols-4">{status.map(({label,ok,icon:Icon})=><div key={label} className="bg-card p-5"><div className="flex items-center justify-between"><div className="rounded-xl bg-muted/45 p-2.5"><Icon className="h-4 w-4 text-muted-foreground"/></div>{ok?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<span className="h-2 w-2 rounded-full bg-muted-foreground/25"/>}</div><p className="mt-4 text-xs font-medium">{label}</p><p className="mt-1 text-[10px] text-muted-foreground">{ok?"Configurado":"Pendente"}</p></div>)}</div></div></AdminSection>
 <div className="grid gap-5 xl:grid-cols-2"><AdminSection><SectionHead eyebrow="Identificação" title="Dados da empresa" description="Informações cadastrais utilizadas nos documentos fiscais." icon={Building2}/><div className="grid gap-4 p-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Razão social" k="legal_name" form={form} setForm={setForm}/></div><Field label="Nome fantasia" k="trade_name" form={form} setForm={setForm}/><Field label="CNPJ" k="tax_id" form={form} setForm={setForm}/><Field label="Inscrição estadual" k="state_registration" form={form} setForm={setForm}/><Field label="Inscrição municipal" k="municipal_registration" form={form} setForm={setForm}/><Field label="CNAE principal" k="cnae_primary" form={form} setForm={setForm}/><Field label="CRT" k="crt" form={form} setForm={setForm}/><label className="text-xs font-medium text-foreground/80">Regime tributário<select value={form.tax_regime||""} onChange={e=>setForm((p:any)=>({...p,tax_regime:e.target.value}))} className="mt-2 h-10 w-full rounded-md border border-border/60 bg-background px-3 text-sm"><option value="">Selecione</option><option value="simples">Simples Nacional</option><option value="presumido">Lucro Presumido</option><option value="real">Lucro Real</option><option value="mei">MEI</option></select></label><label className="text-xs font-medium text-foreground/80">Atividade principal<select value={form.business_mode||"mixed"} onChange={e=>setForm((p:any)=>({...p,business_mode:e.target.value}))} className="mt-2 h-10 w-full rounded-md border border-border/60 bg-background px-3 text-sm"><option value="goods">Venda de produtos</option><option value="services">Prestação de serviços</option><option value="mixed">Produtos e serviços</option><option value="transport">Transporte</option><option value="communication">Comunicação</option></select></label></div></AdminSection>
 <AdminSection><SectionHead eyebrow="Localização" title="Endereço e contato" description="Dados reutilizados automaticamente na emissão." icon={MapPin}/><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="CEP" k="postal_code" form={form} setForm={setForm}/><Field label="Logradouro" k="street" form={form} setForm={setForm}/><Field label="Número" k="street_number" form={form} setForm={setForm}/><Field label="Complemento" k="complement" form={form} setForm={setForm}/><Field label="Bairro" k="district" form={form} setForm={setForm}/><Field label="Cidade" k="city" form={form} setForm={setForm}/><Field label="UF" k="state" form={form} setForm={setForm}/><Field label="Código IBGE" k="city_ibge_code" form={form} setForm={setForm}/><Field label="Telefone" k="phone" form={form} setForm={setForm}/><Field label="E-mail" k="email" form={form} setForm={setForm}/></div></AdminSection></div>
 <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><AdminSection><SectionHead eyebrow="Documentos" title="Numeração e padrões fiscais" description="Séries, próximas numerações e padrões tributários." icon={FileBadge2}/><div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-4"><Field label="Série NF-e" k="series_nfe" form={form} setForm={setForm}/><Field label="Próxima NF-e" k="next_number_nfe" form={form} setForm={setForm} type="number"/><Field label="Série NFC-e" k="series_nfce" form={form} setForm={setForm}/><Field label="Próxima NFC-e" k="next_number_nfce" form={form} setForm={setForm} type="number"/><Field label="Série NFS-e" k="series_nfse" form={form} setForm={setForm}/><Field label="Próxima NFS-e" k="next_number_nfse" form={form} setForm={setForm} type="number"/><Field label="Série CT-e" k="series_cte" form={form} setForm={setForm}/><Field label="Próximo CT-e" k="next_number_cte" form={form} setForm={setForm} type="number"/><Field label="Série MDF-e" k="series_mdfe" form={form} setForm={setForm}/><Field label="Próximo MDF-e" k="next_number_mdfe" form={form} setForm={setForm} type="number"/><Field label="CFOP dentro do estado" k="default_cfop_in_state" form={form} setForm={setForm}/><Field label="CFOP interestadual" k="default_cfop_out_state" form={form} setForm={setForm}/><Field label="Código NFS-e padrão" k="default_nfse_service_code" form={form} setForm={setForm}/><Field label="ISS padrão (%)" k="default_iss_rate" form={form} setForm={setForm} type="number"/></div></AdminSection>
 <AdminSection><SectionHead eyebrow="Segurança" title="Certificado digital A1" description="O certificado é usado para assinar e transmitir os documentos." icon={ShieldCheck}/><div className="p-5"><div className={`rounded-xl border px-4 py-3 text-sm ${certificate?"border-emerald-500/20 bg-emerald-500/5 text-emerald-700":"border-border/60 bg-muted/15 text-muted-foreground"}`}>{certificate?"Certificado configurado e disponível para emissão.":"Nenhum certificado configurado."}</div><div className="mt-4 space-y-3"><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha do certificado" className="h-10 border-border/60 bg-background"/><label className="flex h-10 cursor-pointer items-center justify-center rounded-md border border-border bg-background px-4 text-sm font-medium transition hover:bg-muted/50">Selecionar A1<input type="file" accept=".pfx,.p12,application/x-pkcs12" className="hidden" onChange={uploadCertificate}/></label></div></div></AdminSection></div>
 </div>;
}
