import { useEffect, useMemo, useRef, useState } from "react";
import JsBarcode from "jsbarcode";
import QRCode from "qrcode";
import { openPrintWindow, renderPrintableDocument } from "@/utils/security/print";

const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const digits=(v:any)=>String(v??"").replace(/\D/g,"");
const doc=(v:any)=>{const d=digits(v);if(d.length===14)return `${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`;if(d.length===11)return `${d.slice(0,3)}.${d.slice(3,6)}.${d.slice(6,9)}-${d.slice(9)}`;return String(v||"—")};
const key=(v:any)=>digits(v).replace(/(.{4})/g,"$1 ").trim();
const statusLabel=(s:any)=>s==="authorized"?"AUTORIZADA":s==="rejected"?"REJEITADA":s==="cancelled"?"CANCELADA":s==="error"?"ERRO":s?String(s).toUpperCase():"PRÉVIA";
const auxTitle=(t:string)=>t==="CT-e"?"DACTE":t==="MDF-e"?"DAMDFE":t==="NFS-e"?"DANFSe":t==="NFC-e"?"DANFE NFC-e":"DANFE";

export function printDanfe(elementId:string,title="Documento fiscal"){
 const node=document.getElementById(elementId);if(!node)return;
 const officialPdf=node.dataset.danfsePdf;
 if(officialPdf&&!node.classList.contains("nfse-template-master")){
  try{
   const binary=atob(officialPdf),bytes=new Uint8Array(binary.length);
   for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);
   const url=URL.createObjectURL(new Blob([bytes],{type:"application/pdf"}));
   const a=document.createElement("a");a.href=url;a.download=`${title.replace(/[^a-z0-9_-]+/gi,"-")||"DANFSe"}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);return;
  }catch(error){console.error("Não foi possível abrir o DANFSe oficial",error)}
 }
 const w=openPrintWindow("width=1080,height=900");if(!w)return;
 const styles=[...document.head.querySelectorAll('link[rel="stylesheet"],style')].map(el=>el.outerHTML).join("\n");
 const receipt=node.classList.contains("receipt-sheet");
 const escapedTitle=title.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
 renderPrintableDocument(w,`<!doctype html><html><head><meta charset="utf-8"/><title>${escapedTitle}</title>${styles}<style>*{box-sizing:border-box}html,body{background:#fff!important;color:#000!important}body{margin:0;padding:${receipt?"3mm":"6mm"};font-family:Arial,sans-serif}.danfe-actions,.saas-preview-toolbar{display:none!important}.danfe-sheet{width:100%!important;max-width:198mm!important;margin:0 auto!important;box-shadow:none!important}.nfse-template-master{width:200mm!important;max-width:200mm!important;margin:0 auto!important;padding:1.2mm!important;font-family:Arial,sans-serif!important;color:#000!important;background:#fff!important;box-shadow:none!important}.nfse-template-master *{box-sizing:border-box}.nfse-template-master .nfse-row{break-inside:avoid;page-break-inside:avoid}.nfse-template-master .nfse-label{font-size:6.1px!important;line-height:1.05!important;font-weight:700!important}.nfse-template-master .nfse-value{font-size:7px!important;line-height:1.08!important}.nfse-template-master .nfse-section-title{font-size:7.2px!important;line-height:1!important;font-weight:800!important}.nfse-template-master{width:200mm!important;max-width:200mm!important;margin:0 auto!important;padding:1.2mm!important;font-family:Arial,sans-serif!important;color:#000!important;background:#fff!important;box-shadow:none!important}.nfse-template-master *{box-sizing:border-box}.nfse-template-master .nfse-row{break-inside:avoid;page-break-inside:avoid}.nfse-template-master .nfse-label{font-size:6.1px!important;line-height:1.05!important;font-weight:700!important}.nfse-template-master .nfse-value{font-size:7px!important;line-height:1.08!important}.nfse-template-master .nfse-section-title{font-size:7.2px!important;line-height:1!important;font-weight:800!important}.receipt-sheet{width:80mm!important;max-width:80mm!important;margin:0 auto!important;box-shadow:none!important;border:0!important;padding:3mm!important}@page{size:${receipt?"80mm auto":"A4 portrait"};margin:${receipt?"2mm":"3mm"}}@media print{body{padding:0!important}.saas-preview-shell{background:#fff!important;border:0!important;padding:0!important}}</style></head><body>${node.outerHTML}</body></html>`);
}

function Barcode({value}:{value:string}){const ref=useRef<SVGSVGElement|null>(null);useEffect(()=>{if(!ref.current||digits(value).length<8)return;try{JsBarcode(ref.current,digits(value),{format:"CODE128",displayValue:false,height:44,width:1.15,margin:0})}catch{}},[value]);return digits(value).length>=8?<svg ref={ref} className="h-[48px] w-full" aria-label="Código de barras"/>:<div className="grid h-[48px] place-items-center border border-dashed border-black/30 text-[8px]">Código de barras disponível após autorização</div>}
function Qr({value,size=132}:{value:string;size?:number}){const [src,setSrc]=useState("");useEffect(()=>{let live=true;if(!value){setSrc("");return}QRCode.toDataURL(value,{width:size,margin:1,errorCorrectionLevel:"M"}).then(x=>live&&setSrc(x)).catch(()=>setSrc(""));return()=>{live=false}},[value,size]);return src?<img src={src} width={size} height={size} alt="QR Code" className="block"/>:<div style={{width:size,height:size}} className="grid place-items-center border border-black text-center text-[8px]">QR Code<br/>após autorização</div>}
function Cell({label,value,className=""}:{label:string;value:any;className?:string}){return <div className={`fiscal-box min-h-[34px] ${className}`}><div className="fiscal-label">{label}</div><div className="fiscal-value mt-1 break-words">{value||"—"}</div></div>}
function Section({title,children}:{title:string;children:any}){return <section className="fiscal-section"><div className="fiscal-section-title">{title}</div>{children}</section>}
function LogoBox({src}:{src?:string}){return <div className="fiscal-logo-box">{src?<img src={src} alt="Logomarca do emitente"/>:<span>LOGOMARCA<br/>DO EMITENTE</span>}</div>}

export default function SaasDanfePreview({id="danfe-preview",documentType="NF-e",environment="homologation",profile,data={},result=null,emission=null,showActions=false,mode="danfe"}:{id?:string;documentType?:string;environment?:string;profile?:any;data?:any;result?:any;emission?:any;showActions?:boolean;mode?:"danfe"|"receipt"}){
 const p=emission?.payload||data||{},emit=p.emit||{},dest=p.dest||{},carga=p.carga||{};
 const number=emission?.number||p.numeroNota||p.numero||p.nDPS||"—",series=emission?.series||p.serie||"—";
 const access=emission?.access_key||result?.chaveAcesso||result?.chave||result?.accessKey||result?.response?.chNFe||result?.response?.chMDFe||result?.response?.chCTe||result?.response?.protNFe?.infProt?.chNFe||"";
 const protocol=emission?.protocol||result?.protocol||result?.response?.nProt||result?.response?.protocol?.nProt||result?.response?.protNFe?.infProt?.nProt||"";
 const status=emission?.status||(result?.authorized===true?"authorized":result?.authorized===false?"rejected":result?.error?"error":"preview");
 const rejection=emission?.response?.protocol?.xMotivo||emission?.response?.xMotivo||result?.response?.protocol?.xMotivo||result?.response?.xMotivo||result?.error||"";
 const total=Number(emission?.total??(p.quantidade&&p.valorUnitario?Number(p.quantidade)*Number(p.valorUnitario):p.valor??p.vTPrest??p.valorCarga??0));
 const emitName=p.nomeFantasia||p.razaoSocial||emit.xNome||profile?.trade_name||profile?.legal_name||"Emitente",emitLegal=p.razaoSocial||emit.xNome||profile?.legal_name||emitName;
 const emitDoc=p.cnpjEmitente||emit.CNPJ||profile?.tax_id||"",emitIE=p.ie||emit.IE||profile?.state_registration||"";
 const emitAddress=[p.logradouro||emit.xLgr||profile?.street,p.numeroEndereco||emit.nro||profile?.street_number,p.bairro||emit.xBairro||profile?.district].filter(Boolean).join(", ");
 const emitCity=[p.nomeMunicipio||emit.xMun||profile?.city,emit.UF||profile?.state].filter(Boolean).join(" / ");
 const emitLogo=p.logo_url||p.logoUrl||profile?.logo_url||"";
 const recipient=emission?.recipient_name||p.destNome||p.tomadorNome||dest.xNome||p.munDescargaNome||"CONSUMIDOR NÃO INFORMADO",recipientDoc=emission?.recipient_tax_id||p.destDocumento||p.tomadorDocumento||dest.CNPJ||dest.CPF||"";
 const item=p.produto||p.descricao||carga.proPred||p.proPred||p.natOp||(documentType==="CT-e"?"Prestação de serviço de transporte":"Documento fiscal"),quantity=p.quantidade||carga.qCarga||p.qCarga||1;
 const date=useMemo(()=>new Date(emission?.external_issue_date||emission?.authorized_at||emission?.created_at||Date.now()).toLocaleString("pt-BR"),[emission]);
 const qrValue=p.qrCode||p.qrCodMDFe||p.qrCodCTe||result?.qrCode||result?.response?.qrCode||(access?`https://dfe-portal.svrs.rs.gov.br/${documentType.toLowerCase().replace(/[^a-z]/g,"")}/qrcode?ch=${digits(access)}&tpAmb=${environment==="production"?1:2}`:"");
 const imported=emission?.source==="imported";
 if(mode==="receipt"||documentType==="NFC-e")return <Receipt id={id} showActions={showActions} number={number} series={series} environment={environment} status={status} rejection={rejection} emitLogo={emitLogo} emitName={emitName} emitLegal={emitLegal} emitDoc={emitDoc} emitIE={emitIE} emitAddress={emitAddress} emitCity={emitCity} item={item} quantity={quantity} total={total} access={access} protocol={protocol} date={date} qrValue={qrValue}/>;
 if(documentType==="NFS-e")return <Nfse result={result} profile={profile} id={id} showActions={showActions} number={number} series={series} environment={environment} status={status} emitLogo={emitLogo} emitName={emitName} emitDoc={emitDoc} emitAddress={emitAddress} emitCity={emitCity} recipient={recipient} recipientDoc={recipientDoc} item={item} total={total} access={access} protocol={protocol} date={date} qrValue={qrValue} p={p}/>;
 return <div className="space-y-3">{showActions&&<Toolbar id={id} title={`${auxTitle(documentType)} ${number}`} meta={`${documentType} · série ${series} · ${statusLabel(status)}`}/>}<div className="saas-preview-shell"><div id={id} className="danfe-sheet fiscal-paper mx-auto w-full max-w-[860px] bg-white p-[7px] shadow-sm">
  {environment!=="production"&&<div className="mb-1.5 border-2 border-black px-2 py-1 text-center text-[9px] font-black">SEM VALOR FISCAL — EMITIDO EM AMBIENTE DE HOMOLOGAÇÃO</div>}
  {status==="rejected"&&<div className="mb-1.5 border-2 border-black bg-[#fff1f1] px-2 py-1 text-[9px]"><b>DOCUMENTO REJEITADO</b>{rejection?` — ${rejection}`:""}</div>}
  {imported&&<div className="mb-1.5 border border-black px-2 py-1 text-[8px]"><b>DOCUMENTO EXTRAÍDO</b></div>}
  <div className="grid grid-cols-[76px_1.15fr_.62fr_1.15fr] border-2 border-black"><div className="border-r-2 border-black p-2"><LogoBox src={emitLogo}/></div><div className="border-r-2 border-black p-3 text-center"><div className="text-[14px] font-black">{emitName}</div>{emitLegal!==emitName&&<div className="mt-1 text-[8px]">{emitLegal}</div>}<div className="mt-2 text-[8px]">{emitAddress||"—"}<br/>{emitCity||"—"}</div><div className="mt-1 text-[8px]">CNPJ {doc(emitDoc)} · IE {emitIE||"—"}</div></div><div className="flex flex-col items-center justify-center border-r-2 border-black p-2 text-center"><div className="text-[22px] font-black">{auxTitle(documentType)}</div><div className="mt-1 text-[8px] font-bold">DOCUMENTO AUXILIAR</div><div className="mt-2 text-[14px] font-black">{documentType}</div><div className="mt-1 text-[9px]">Nº {number}<br/>Série {series}</div></div><div className="p-2"><Barcode value={access}/><div className="mt-1 fiscal-label">CHAVE DE ACESSO</div><div className="mt-1 text-center text-[8px] font-bold leading-3">{access?key(access):"Disponível após autorização"}</div><div className="mt-2 grid grid-cols-2 gap-1"><Cell label="EMISSÃO" value={date}/><Cell label="STATUS" value={statusLabel(status)}/></div></div></div>
  <Section title="Natureza / protocolo"><div className="grid grid-cols-[1.4fr_.9fr]"><Cell label="NATUREZA DA OPERAÇÃO" value={p.natOp||p.naturezaOperacao||(documentType==="CT-e"?"PRESTAÇÃO DE SERVIÇO DE TRANSPORTE":documentType==="MDF-e"?"MANIFESTO ELETRÔNICO DE DOCUMENTOS FISCAIS":"VENDA")}/><Cell label="PROTOCOLO DE AUTORIZAÇÃO" value={protocol||"—"}/></div></Section>
  <Section title={documentType==="CT-e"?"Remetente / destinatário / tomador":documentType==="MDF-e"?"Percurso e carga":"Destinatário / remetente"}><div className="grid grid-cols-[1.5fr_.8fr_.65fr]"><Cell label="NOME / RAZÃO SOCIAL" value={recipient}/><Cell label="CNPJ / CPF" value={doc(recipientDoc)}/><Cell label="UF / DESTINO" value={p.destUF||dest.UF||p.ufFim||"—"}/></div><div className="grid grid-cols-[1.2fr_.9fr_.9fr]"><Cell label="ENDEREÇO / ORIGEM" value={p.destLogradouro||dest.xLgr||p.munIniNome||"—"}/><Cell label="MUNICÍPIO / DESTINO" value={p.destMunicipio||dest.xMun||p.munDescargaNome||p.munFimNome||"—"}/><Cell label="DOCUMENTO VINCULADO" value={p.chNFe||p.chCTe||p.chaves?.[0]||"—"}/></div></Section>
  {documentType==="MDF-e"&&<Section title="Modal rodoviário"><div className="grid grid-cols-4"><Cell label="RNTRC" value={p.rntrc}/><Cell label="PLACA" value={p.placa}/><Cell label="CONDUTOR" value={p.condutorNome}/><Cell label="CPF" value={doc(p.condutorCpf)}/></div></Section>}
  {documentType==="CT-e"&&<Section title="Valores da prestação"><div className="grid grid-cols-4"><Cell label="VALOR DA PRESTAÇÃO" value={money(p.vTPrest||total)}/><Cell label="VALOR A RECEBER" value={money(p.vRec||p.vTPrest||total)}/><Cell label="VALOR DA CARGA" value={money(carga.vCarga||p.vCarga)}/><Cell label="PRODUTO PREDOMINANTE" value={carga.proPred||p.proPred||item}/></div></Section>}
  {documentType==="NF-e"&&<><Section title="Totais"><div className="grid grid-cols-4"><Cell label="BASE CÁLC. ICMS" value={money(p.vBC)}/><Cell label="VALOR ICMS" value={money(p.vICMS)}/><Cell label="VALOR PRODUTOS" value={money(total)}/><Cell label="VALOR TOTAL NF-e" value={money(total)}/></div></Section><Section title="Dados dos produtos / serviços"><div className="grid grid-cols-[.5fr_1.9fr_.65fr_.55fr_.42fr_.5fr_.72fr] bg-[#efefef]"><Cell label="CÓDIGO" value={p.codigoProduto||"—"}/><Cell label="DESCRIÇÃO" value={item}/><Cell label="NCM" value={p.ncm||"—"}/><Cell label="CFOP" value={p.cfop||"—"}/><Cell label="UN" value={p.unidade||"UN"}/><Cell label="QTD" value={quantity}/><Cell label="TOTAL" value={money(total)}/></div><div className="min-h-[235px] border-t border-black"/></Section></>}
  {documentType==="MDF-e"&&<Section title="Carga"><div className="grid grid-cols-4"><Cell label="VALOR TOTAL DA CARGA" value={money(p.valorCarga||total)}/><Cell label="PESO TOTAL" value={p.pesoCarga||"—"}/><Cell label="PRODUTO PREDOMINANTE" value={p.xProd||p.proPred||item}/><Cell label="TIPO DE CARGA" value={p.tpCarga||"—"}/></div></Section>}
  {(documentType==="CT-e"||documentType==="MDF-e")&&<div className="mt-2 flex items-end justify-between border-2 border-black p-2"><div className="max-w-[70%] text-[8px] leading-3"><b>CONSULTA / AUTENTICIDADE</b><br/>A autenticidade deste documento pode ser verificada no portal fiscal por meio da chave de acesso ou pela leitura do QR Code.</div><Qr value={qrValue} size={105}/></div>}
  <Section title="Dados adicionais"><div className="min-h-[58px] p-2 text-[8px] leading-3">{p.informacoesComplementares||p.fiscal_notes||"Documento fiscal eletrônico gerado pelo WS Gestão Contábil."}</div></Section>
 </div></div></div>
}
function Toolbar({id,title,meta}:{id:string;title:string;meta:string}){return <div className="saas-preview-toolbar"><div><div className="saas-preview-toolbar-title">{title}</div><div className="saas-preview-toolbar-meta">{meta}</div></div><div className="saas-preview-actions"><button onClick={()=>printDanfe(id,title)} className="saas-action-primary h-9 px-4 text-xs">Imprimir / salvar PDF</button></div></div>}
function Receipt(p:any){return <div className="space-y-3">{p.showActions&&<Toolbar id={p.id} title={`NFC-e ${p.number}`} meta={`Série ${p.series} · ${statusLabel(p.status)}`}/>}<div className="saas-preview-shell"><div id={p.id} className="receipt-sheet fiscal-paper mx-auto w-[80mm] max-w-full bg-white px-[4mm] py-[4mm] font-mono text-[10px] leading-[1.35] shadow-sm"><div className="text-center"><div className="text-[13px] font-black">{p.emitName}</div>{p.emitLegal!==p.emitName&&<div className="mt-1 text-[9px]">{p.emitLegal}</div>}<div className="mt-1">CNPJ: {doc(p.emitDoc)} · I.E.: {p.emitIE||"—"}</div><div className="mt-1">{p.emitAddress}<br/>{p.emitCity}</div></div><div className="my-2 border-t border-black"/><div className="text-center text-[10px] font-black">DOCUMENTO AUXILIAR DA NOTA FISCAL DE CONSUMIDOR ELETRÔNICA</div><div className="my-2 border-t border-black"/><div className="grid grid-cols-[1fr_42px_62px] gap-1 border-b border-black pb-1 text-[8px] font-black"><span>CÓDIGO | DESCRIÇÃO</span><span className="text-right">QTDE</span><span className="text-right">TOTAL</span></div><div className="grid grid-cols-[1fr_42px_62px] gap-1 py-2"><span className="font-semibold">{p.item}</span><span className="text-right">{p.quantity}</span><span className="text-right">{money(p.total)}</span></div><div className="border-t border-black pt-2"><div className="flex justify-between font-black"><span>Qtde. Total de Itens</span><span>1</span></div><div className="mt-1 flex justify-between text-[12px] font-black"><span>Valor Total R$</span><span>{Number(p.total||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</span></div><div className="mt-1 flex justify-between text-[12px] font-black"><span>Valor a Pagar R$</span><span>{Number(p.total||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</span></div></div><div className="my-2 border-t border-black"/><div><b>FORMAS PAGAMENTOS</b><div className="mt-1 flex justify-between"><span>Pagamento</span><span>{money(p.total)}</span></div></div><div className="my-2 border-t border-black"/><div className="text-center text-[8px]">Consulte pela Chave de Acesso em<br/>portal da SEFAZ autorizadora</div><div className="mt-1 break-all text-center text-[8px] font-bold">{p.access?key(p.access):"CHAVE DISPONÍVEL APÓS AUTORIZAÇÃO"}</div><div className="mt-2 text-center"><b>CONSUMIDOR - NÃO INFORMADO</b><br/>NFC-e n. {p.number} Série {p.series} {p.date}<br/>{p.protocol&&<>Protocolo de Autorização {p.protocol}</>}</div>{p.environment!=="production"&&<div className="mt-2 border border-black p-1 text-center font-black">EMITIDA EM HOMOLOGAÇÃO - SEM VALOR FISCAL</div>}<div className="mt-3 flex justify-center"><Qr value={p.qrValue} size={150}/></div><div className="mt-1 text-center text-[8px] font-black">QR CODE DA NFC-e</div></div></div></div>}
function Nfse(p:any){
 const profile=p.profile||{},d=p.p||{},fmtNbs=(v:any)=>{const x=digits(v);return x.length===9?`${x.slice(0,1)}.${x.slice(1,5)}.${x.slice(5,7)}.${x.slice(7)}`:(v||"-")},fmtServ=(v:any)=>{const x=digits(v);return x.length===6?`${x.slice(0,2)}.${x.slice(2,4)}.${x.slice(4)}`:(v||"-")},fmtIbge=(v:any)=>{const x=digits(v);return x.length===7?`${x.slice(0,2)}.${x.slice(2)}`:(v||"-")},fmtCep=(v:any)=>{const x=digits(v);return x.length===8?`${x.slice(0,2)}.${x.slice(2,5)}-${x.slice(5)}`:(v||"-")};
 const dash=(v:any)=>v===undefined||v===null||v===""?"-":v;
 const emitMunicipality=[profile.city,profile.state].filter(Boolean).join(" / ")||p.emitCity||"-",prestAddress=[profile.street,profile.street_number,profile.complement,profile.district].filter(Boolean).join(", ")||p.emitAddress||"-";
 const tomaMunicipality=[d.tomadorMunicipio,d.tomadorUf].filter(Boolean).join(" / ")||"-",serviceLocation=[d.municipioPrestacaoNome,d.municipioPrestacaoUf].filter(Boolean).join(" / ")||d.municipioPrestacao||"-",incidenceLocation=[d.municipioIncidenciaNome||profile.city,d.municipioIncidenciaUf||profile.state].filter(Boolean).join(" / ")||"-";
 const competence=d.competencia||String(p.date||"").split(' ')[0]||"-",status=p.status==="authorized"?"NFS-e Gerada":statusLabel(p.status),serviceOfficial=d.servicoNome||p.item||"-";
 const ibsUf=d.ibsUf??d.aliquotaIbsUf,ibsMun=d.ibsMun??d.aliquotaIbsMunicipal,cbs=d.cbs??d.aliquotaCbs,ibsTotal=d.valorIbsTotal??d.valorIbs,cbsTotal=d.valorCbsTotal??d.valorCbs,totalIbsCbs=Number(ibsTotal||0)+Number(cbsTotal||0),liquid=Number(d.valorLiquido??p.total??0),liquidWithIbs=liquid+totalIbsCbs;
 const DCell=({l,v,span=""}:{l:string;v:any;span?:string})=><div className={`min-w-0 px-[1.3mm] py-[.8mm] ${span}`}><div className="nfse-label font-bold leading-none">{l}</div><div className="nfse-value mt-[.5mm] break-words leading-tight">{dash(v)}</div></div>;
 const STitle=({children}:{children:any})=><div className="nfse-section-title border-t border-black bg-[#efefef] px-[1.3mm] py-[.75mm] font-black">{children}</div>;
 return <div className="space-y-3">{p.showActions&&<Toolbar id={p.id} title={`DANFSe ${p.number}`} meta={`NFS-e · ${statusLabel(p.status)}`}/>}<div className="saas-preview-shell"><div id={p.id} data-danfse-pdf={p.result?.danfsePdfBase64||undefined} className="danfe-sheet nfse-template-master fiscal-paper mx-auto bg-white text-black shadow-sm">
  <div className="nfse-row grid grid-cols-[1.05fr_1.4fr_1.05fr] border border-black">
   <div className="flex items-center gap-1.5 px-[1.3mm] py-[1mm]"><div className="text-[20px] font-black tracking-[-1px] text-[#248f63]">NFS</div><div className="-ml-1 text-[15px] font-black text-[#2564a7]">e</div><div className="text-[6px] leading-[1.05] text-[#666]">Nota Fiscal de<br/>Serviço eletrônica</div></div>
   <div className="px-[1mm] py-[1mm] text-center"><div className="text-[10px] font-black leading-none">DANFSe v2.0</div><div className="mt-[.7mm] text-[9px] font-bold leading-none">Documento Auxiliar da NFS-e</div></div>
   <div className="grid grid-cols-[1fr_26mm]"><div className="px-[1mm] py-[1mm] text-[6.2px] leading-[1.15]"><div><b>Município:</b> {profile.city||d.municipioEmissorNome||"-"} - {profile.state||"-"}</div><div><b>Ambiente Gerador:</b> {d.ambienteGerador||"2"}</div><div><b>Tipo de Ambiente:</b> {p.environment==="production"?"1":"2"}</div></div><div className="flex items-start justify-center p-[.8mm]"><Qr value={p.qrValue} size={62}/></div></div>
  </div>
  <div className="nfse-row border-x border-black px-[1.3mm] pt-[4mm] pb-[1.2mm]"><div className="nfse-label">CHAVE DE ACESSO DA NFS-e</div><div className="nfse-value mt-[.6mm] break-all">{p.access?digits(p.access):"Disponível após autorização"}</div></div>
  <div className="nfse-row grid grid-cols-[1fr_1fr_1fr_1.02fr] border-x border-black">
   <div><DCell l="NÚMERO DA NFS-e" v={p.number}/><DCell l="NÚMERO DA DPS" v={d.numero||p.number}/><div className="bg-[#efefef]"><DCell l="EMITENTE DA NFS-e" v={d.emitenteNfse||"Prestador"}/></div></div>
   <div><DCell l="COMPETÊNCIA DA NFS-e" v={competence}/><DCell l="SÉRIE DA DPS" v={d.serie||p.series}/><DCell l="SITUAÇÃO DA NFS-e" v={status}/></div>
   <div><DCell l="DATA E HORA DA EMISSÃO DA NFS-e" v={p.date}/><DCell l="DATA E HORA DA EMISSÃO DA DPS" v={d.dataEmissaoDps||p.date}/><DCell l="FINALIDADE" v={d.finalidade||"-"}/></div>
   <div className="px-[1.3mm] pt-[1mm] text-[6.1px] leading-[1.18]">A autenticidade desta NFS-e pode ser verificada pela leitura deste código QR ou pela consulta da chave de acesso no portal nacional da NFS-e.</div>
  </div>
  <STitle>PRESTADOR / FORNECEDOR</STitle>
  <div className="nfse-row grid grid-cols-[1fr_1fr_1fr_1fr] border-x border-black">
   <DCell l="Nome / Nome Empresarial" v={profile.legal_name||p.emitName}/><DCell l="CNPJ / CPF / NIF" v={doc(p.emitDoc)}/><DCell l="Indicador Municipal (Inscrição)" v={profile.municipal_registration||"-"}/><DCell l="Telefone" v={profile.phone||"-"}/>
   <DCell l="Endereço" v={prestAddress}/><DCell l="Município / Sigla UF" v={emitMunicipality}/><DCell l="Código IBGE / CEP" v={`${fmtIbge(profile.city_ibge_code)} / ${fmtCep(profile.postal_code)}`}/><DCell l="E-mail" v={profile.email||"-"}/>
  </div>
  <div className="nfse-row grid grid-cols-[1fr_3fr] border-x border-t border-black"><DCell l="Simples Nacional na Data de Competência" v={String(profile.tax_regime||"").toLowerCase().includes("simples")?"Optante - Microempresa ou Empresa de Pequeno Porte":"-"}/><DCell l="Regime de Apuração Tributária pelo SN" v={String(profile.tax_regime||"").toLowerCase().includes("simples")?"Regime de apuração dos tributos federais e municipal pelo Simples Nacional":"-"}/></div>
  <STitle>TOMADOR / ADQUIRENTE</STitle>
  <div className="nfse-row grid grid-cols-4 border-x border-black"><DCell l="CNPJ / CPF / NIF" v={doc(p.recipientDoc)}/><DCell l="Indicador Municipal (Inscrição)" v={d.tomadorInscricaoMunicipal||"-"}/><DCell l="Telefone" v={d.tomadorTelefone||"-"}/><DCell l="Código IBGE / CEP" v={`${fmtIbge(d.tomadorMunicipioIbge)} / ${fmtCep(d.tomadorCep)}`}/><DCell l="Nome / Nome Empresarial" v={p.recipient}/><DCell l="Município / Sigla UF" v={tomaMunicipality}/><DCell l="E-mail" v={d.tomadorEmail||"-"}/><DCell l="Endereço" v={d.tomadorEndereco||"-"}/></div>
  <div className="nfse-row border-x border-t border-black py-[1.1mm] text-center text-[6.2px] font-medium">DESTINATÁRIO DA OPERAÇÃO NÃO IDENTIFICADO NA NFS-e&nbsp;&nbsp;&nbsp; INTERMEDIÁRIO DA OPERAÇÃO NÃO IDENTIFICADO NA NFS-e</div>
  <STitle>SERVIÇO PRESTADO</STitle>
  <div className="nfse-row grid grid-cols-[1fr_1fr_1fr] border-x border-black"><DCell l="Código de Tributação Nacional/Municipal" v={`${fmtServ(d.codigoTributacao)} / ${d.codigoTributacaoMunicipal||"-"}`}/><DCell l="Código da NBS" v={fmtNbs(d.codigoNbs||d.nbsCode||d.nbs)}/><DCell l="Local da Prestação / Sigla UF / País" v={`${serviceLocation} / ${d.paisPrestacao||"-"}`}/></div>
  <div className="nfse-row border-x border-black px-[1.3mm] py-[1mm]"><div className="nfse-value font-medium">{serviceOfficial}</div><div className="nfse-label mt-[1mm]">Descrição do Serviço</div><div className="nfse-value mt-[.5mm] whitespace-pre-wrap leading-[1.13]">{d.descricao||p.item||"-"}</div></div>
  <STitle>TRIBUTAÇÃO MUNICIPAL (ISSQN)</STitle>
  <div className="nfse-row grid grid-cols-4 border-x border-black"><DCell l="Tipo de Tributação do ISSQN" v={d.tipoTributacaoIssqn||"Operação Tributável"}/><DCell l="Município / Sigla UF / País de Incidência do ISSQN" v={`${incidenceLocation} / ${d.paisIncidencia||"-"}`}/><DCell l="BC ISSQN" v={d.baseIssqn!=null?money(d.baseIssqn):"-"}/><DCell l="Alíquota Aplicada" v={d.aliquotaIssqn!=null?`${d.aliquotaIssqn}%`:"-"}/><DCell l="Retenção do ISSQN" v={d.issRetido?"Retido":"Não Retido"}/><DCell l="ISSQN Apurado" v={d.valorIssqn!=null?money(d.valorIssqn):"-"}/></div>
  <STitle>TRIBUTAÇÃO FEDERAL (EXCETO CBS)</STitle>
  <div className="nfse-row grid grid-cols-3 border-x border-black"><DCell l="IRRF" v={d.irrf!=null?money(d.irrf):"-"}/><DCell l="Contribuição Previdenciária - Retida" v={d.inssRetido!=null?money(d.inssRetido):"-"}/><DCell l="Contribuições Sociais - Retidas" v={d.contribuicoesSociaisRetidas!=null?money(d.contribuicoesSociaisRetidas):"-"}/><div className="bg-[#efefef]"><DCell l="PIS - Débito Apuração Própria" v={d.pisDebito!=null?money(d.pisDebito):"-"}/></div><DCell l="COFINS - Débito Apuração Própria" v={d.cofinsDebito!=null?money(d.cofinsDebito):"-"}/><DCell l="Descrição Contrib. Sociais - Retidas" v={d.descricaoContribuicoesSociais||"-"}/></div>
  <STitle>TRIBUTAÇÃO IBS/CBS</STitle>
  <div className="nfse-row grid grid-cols-4 border-x border-black"><DCell l="CST / cClassTrib" v={`${d.cstIbsCbs||"-"} / ${d.cClassTrib||"-"}`}/><DCell l="Indicador de Operação / Código IBGE Incidência / Município Incidência / Sigla UF" v={`${d.indicadorOperacao||"-"} / ${d.codigoIbgeIncidencia||d.municipioIncidencia||"-"} / ${d.municipioIncidenciaNome||"-"} / ${d.municipioIncidenciaUf||"-"}`}/><DCell l="Exclusões e Reduções da Base de Cálculo" v={d.exclusoesReducoesBase!=null?money(d.exclusoesReducoesBase):"R$ 0,00"}/><DCell l="Base de Cálculo Após Exclusões e Reduções" v={d.baseIbsCbs!=null?money(d.baseIbsCbs):"-"}/><DCell l="Red. Alíquota IBS / Red. Alíquota CBS" v={`${d.reducaoAliquotaIbs??"-"} / ${d.reducaoAliquotaCbs??"-"}`}/><DCell l="Alíquota - IBS UF / IBS Mun" v={`${ibsUf??"-"} / ${ibsMun??"-"}`}/><DCell l="Alíq. Efetiva Municipal - IBS" v={d.aliquotaEfetivaIbsMun??"-"}/><DCell l="Valor Apurado Municipal - IBS" v={d.valorIbsMun!=null?money(d.valorIbsMun):"-"}/><DCell l="Alíq. Efetiva Estadual - IBS" v={d.aliquotaEfetivaIbsUf??"-"}/><DCell l="Valor Apurado Estadual - IBS" v={d.valorIbsUf!=null?money(d.valorIbsUf):"-"}/><DCell l="Valor Total Apurado - IBS" v={ibsTotal!=null?money(ibsTotal):"-"}/><DCell l="Alíquota - CBS" v={cbs??"-"}/><DCell l="Alíquota Efetiva - CBS" v={d.aliquotaEfetivaCbs??"-"}/><DCell l="Valor Total Apurado - CBS" v={cbsTotal!=null?money(cbsTotal):"-"}/></div>
  <STitle>VALOR TOTAL DA NFS-e</STitle>
  <div className="nfse-row grid grid-cols-4 border-x border-black"><DCell l="VALOR DA OPERAÇÃO / SERVIÇO" v={money(p.total)}/><DCell l="Desconto Incondicionado" v={d.descontoIncondicionado!=null?money(d.descontoIncondicionado):"-"}/><DCell l="Desconto Condicionado" v={d.descontoCondicionado!=null?money(d.descontoCondicionado):"-"}/><DCell l="Total das Retenções (ISSQN / Federais)" v={d.totalRetencoes!=null?money(d.totalRetencoes):"-"}/><DCell l="VALOR LÍQUIDO DA NFS-e" v={money(liquid)}/><DCell l="Total do IBS/CBS" v={money(totalIbsCbs)}/><DCell l="VALOR LÍQUIDO DA NFS-e + IBS/CBS" v={money(liquidWithIbs)} span="col-span-2"/></div>
  <STitle>INFORMAÇÕES COMPLEMENTARES</STitle>
  <div className="nfse-row border-x border-black px-[1.3mm] py-[1mm] text-[6.3px] leading-[1.15]">Inf. Cont.: {d.informacoesComplementares||"-"}<br/>Totais aproximados dos Tributos cfe. Lei n° 12.741/2012: Federais: {d.tributosFederaisAprox||"-"}; Estaduais: {d.tributosEstaduaisAprox||"-"}; Municipais: {d.tributosMunicipaisAprox||"-"};</div>
  <div className="nfse-row grid grid-cols-[1fr_1fr_2fr] border border-black text-[6px]"><div className="min-h-[8mm] p-[1mm]"><b>DATA CIENTIFICAÇÃO:</b> {d.dataCientificacao||""}</div><div className="min-h-[8mm] border-x border-black p-[1mm]"><b>IDENTIFICAÇÃO E ASSINATURA</b></div><div className="min-h-[8mm] p-[1mm]"><b>N° NFS-e / CHAVE NFS-e</b><br/>{p.number} / {digits(p.access)||"-"}</div></div>
 </div></div></div>
}
