import { useMemo } from "react";
import { ArrowUpRight, FilePlus2, ReceiptText } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AdminPageHeader } from "@/components/admin/ui/AdminPage";

type Props={organizationName?:string;emissions:any[];onNew:()=>void;onReports:()=>void};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const tooltip={background:"hsl(var(--popover))",border:"1px solid hsl(var(--border))",borderRadius:8,fontSize:12};
export default function SaasDashboard({organizationName,emissions,onNew,onReports}:Props){
 const isAuthorized=(x:any)=>x?.status==="authorized"&&x?.status!=="cancelled"&&!x?.cancelled_at&&String(x?.response?.cStat||x?.response?.protocol?.cStat||x?.response?.status_code||"100")==="100";
 const authorized=emissions.filter(isAuthorized),pending=emissions.filter(x=>["draft","validated","processing"].includes(x.status)),cancelled=emissions.filter(x=>x.status==="cancelled"||!!x.cancelled_at),rejected=emissions.filter(x=>x.status==="rejected"||x.status==="error"),total=authorized.reduce((a,x)=>a+Number(x.total||0),0),ticket=authorized.length?total/authorized.length:0;
 const daily=useMemo(()=>{const rows=new Map<string,any>();for(let i=13;i>=0;i--){const d=new Date(Date.now()-i*864e5),key=d.toISOString().slice(0,10);rows.set(key,{day:d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),valor:0,notas:0})}for(const x of authorized){const key=new Date(x.created_at).toISOString().slice(0,10),r=rows.get(key);if(r){r.valor+=Number(x.total||0);r.notas++}}return [...rows.values()]},[emissions]);
 const modes=useMemo(()=>Object.entries(authorized.reduce((a:any,x:any)=>{const k=String(x.document_type||"").toUpperCase();a[k]=(a[k]||0)+1;return a},{})).map(([name,value])=>({name,value})),[authorized]);
 const status=[{name:"Autorizadas",value:authorized.length},{name:"Pendentes",value:pending.length},{name:"Rejeitadas",value:rejected.length},{name:"Canceladas",value:cancelled.length}].filter(x=>x.value>0),colors=["#202833","#667085","#d92d20","#98a2b3"];
 const cards=[{label:"Faturamento autorizado",value:money(total),hint:`${authorized.length} documento(s) autorizado(s)`,tone:"green"},{label:"Pendências",value:String(pending.length),hint:"Documentos aguardando conclusão",tone:"orange"},{label:"Rejeições e cancelamentos",value:String(rejected.length+cancelled.length),hint:"Documentos que exigem atenção",tone:"red"},{label:"Ticket médio",value:money(ticket),hint:"Média por emissão autorizada",tone:"blue"}];
 return <div className="saas-dashboard ws-storage-style mx-auto w-full max-w-[1540px] space-y-5"><AdminPageHeader eyebrow="Visão fiscal" title={`Olá, ${organizationName||"sua empresa"}`} description="Acompanhe emissões, faturamento e movimentação fiscal em uma única visão." actions={<><Button variant="outline" onClick={onReports}>Abrir relatórios<ArrowUpRight className="ml-2 h-4 w-4"/></Button><Button onClick={onNew}><FilePlus2 className="mr-2 h-4 w-4"/>Emitir nova nota</Button></>}/>
 <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{cards.map(({label,value,hint,tone})=><Card key={label} className={`saas-kpi-card saas-kpi-${tone} relative overflow-hidden border !bg-white shadow-sm`}><span className="saas-kpi-ring" aria-hidden="true"/><CardContent className="relative z-10 p-5 pr-16"><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-medium tracking-tight text-foreground">{value}</p><p className="mt-4 max-w-[78%] text-xs text-muted-foreground">{hint}</p></CardContent></Card>)}</div>
 <div className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><Card className="overflow-hidden border border-border/50 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Movimento dos últimos 14 dias" sub="Faturamento autorizado e quantidade de documentos"/><div className="h-[330px] p-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={daily} margin={{top:10,right:10,left:-10,bottom:0}}><defs><linearGradient id="saasDashFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--foreground) / .72)" stopOpacity=".30"/><stop offset="100%" stopColor="hsl(var(--foreground) / .72)" stopOpacity=".02"/></linearGradient></defs><CartesianGrid vertical={false} stroke="hsl(var(--border) / .42)"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><Tooltip contentStyle={tooltip} formatter={(v:any,n:any)=>n==="valor"?[money(Number(v)),"Faturamento"]:[v,"Notas"]}/><Area type="monotone" dataKey="valor" stroke="hsl(var(--foreground) / .8)" strokeWidth={2.4} fill="url(#saasDashFill)"/></AreaChart></ResponsiveContainer></div></CardContent></Card>
 <Card className="overflow-hidden border border-border/50 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Situação das notas" sub={`${emissions.length} documento${emissions.length===1?"":"s"} processado${emissions.length===1?"":"s"}`}/><div className="h-[230px] p-5">{status.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={status} dataKey="value" nameKey="name" innerRadius="58%" outerRadius="82%" paddingAngle={3} stroke="#fff" strokeWidth={2}>{status.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-muted-foreground">Nenhuma emissão registrada ainda.</div>}</div>{status.length>0&&<div className="grid grid-cols-2 border-t border-border/35">{status.slice(0,4).map((x,i)=><div key={x.name} className={`p-3 ${i%2===0?"border-r":""} ${i<2?"border-b":""} border-border/25`}><p className="text-[10px] text-muted-foreground">{x.name}</p><p className="mt-1 text-xl font-light text-foreground">{x.value}</p></div>)}</div>}</CardContent></Card></div>
 <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card className="overflow-hidden border border-border/50 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Emissões por modalidade" sub="Volume autorizado por tipo de documento"/><div className="h-[280px] p-5">{modes.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={modes}><CartesianGrid vertical={false} stroke="hsl(var(--border) / .38)"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><Tooltip contentStyle={tooltip}/><Bar dataKey="value" fill="hsl(var(--foreground) / .8)" radius={[5,5,0,0]} barSize={25}/></BarChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-muted-foreground">Sem dados para este gráfico.</div>}</div></CardContent></Card>
 <Card className="overflow-hidden border border-border/50 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Emissões recentes" sub="Últimos documentos processados pelo sistema"/><div className="divide-y divide-border/25">{emissions.slice(0,7).map((x,i)=><div key={x.id||i} className={`flex items-center gap-4 px-5 py-3.5 ${i%2?"bg-[#fafbfc]":"bg-white"}`}><div className="grid h-9 w-9 shrink-0 place-items-center rounded-md bg-muted/45"><ReceiptText className="h-4 w-4 text-muted-foreground"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-foreground">{String(x.document_type||"Documento").toUpperCase()} · {x.number||"sem número"}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{x.recipient_name||x.access_key||"Sem destinatário"}</p></div><div className="text-right"><p className="text-sm font-medium text-foreground">{money(Number(x.total||0))}</p><p className="mt-0.5 text-[10px] uppercase tracking-wide text-muted-foreground">{x.status}</p></div></div>)}{!emissions.length&&<p className="px-5 py-14 text-center text-sm text-muted-foreground">Nenhuma emissão registrada ainda.</p>}</div></CardContent></Card></div>
 </div>}
function Head({title,sub}:{title:string;sub:string}){return <div className="border-b border-border/35 px-5 py-4"><h3 className="font-medium text-foreground">{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{sub}</p></div>}
