import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, FilePlus2, PackageSearch, ReceiptText } from "lucide-react";
import { Area, AreaChart, Bar, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, Treemap, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AdminPageHeader } from "@/components/admin/ui/AdminPage";
import { supabase } from "@/integrations/supabase/client";

type Props={organizationId:string|null;organizationName?:string;emissions:any[];onNew:()=>void;onReports:()=>void};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const tooltip={background:"#fff",border:"1px solid #dce2e9",borderRadius:8,fontSize:12,boxShadow:"0 8px 22px rgba(31,41,55,.08)"};
const typeLabel=(v:string)=>({nfe:"NF-e",nfce:"NFC-e",nfse:"NFS-e",cte:"CT-e",mdfe:"MDF-e"} as any)[String(v||"").toLowerCase()]||String(v||"Documento").toUpperCase();
const statusLabel=(s:string)=>s==="authorized"?"Autorizada":s==="cancelled"?"Cancelada":s==="draft"?"Rascunho":s==="rejected"?"Rejeitada":s;
const getProductName=(x:any)=>x?.payload?.produto||x?.payload?.product_name||x?.payload?.name||x?.response?.produto||null;

export default function SaasDashboard({organizationId,organizationName,emissions,onNew,onReports}:Props){
 const [products,setProducts]=useState<any[]>([]);
 const [period,setPeriod]=useState<7|30|90|365>(30);
 useEffect(()=>{if(!organizationId){setProducts([]);return}void (async()=>{const {data}=await (supabase as any).from("saas_fiscal_catalog_items").select("*").eq("organization_id",organizationId).eq("item_type","product").order("name");setProducts(data||[])})()},[organizationId]);
 const authorized=useMemo(()=>emissions.filter((x:any)=>x?.status==="authorized"&&!x?.cancelled_at),[emissions]);
 const now=Date.now(),monthStart=new Date(new Date().getFullYear(),new Date().getMonth(),1).getTime(),prevMonthStart=new Date(new Date().getFullYear(),new Date().getMonth()-1,1).getTime();
 const monthAuthorized=authorized.filter((x:any)=>+new Date(x.created_at)>=monthStart),prevMonthAuthorized=authorized.filter((x:any)=>{const t=+new Date(x.created_at);return t>=prevMonthStart&&t<monthStart});
 const monthRevenue=monthAuthorized.reduce((a:number,x:any)=>a+Number(x.total||0),0),prevRevenue=prevMonthAuthorized.reduce((a:number,x:any)=>a+Number(x.total||0),0),salesCount=monthAuthorized.length,ticket=salesCount?monthRevenue/salesCount:0;
 const managed=products.filter((x:any)=>x.stock_managed),active=products.filter((x:any)=>x.status!=="inactive"),inactive=products.length-active.length,low=managed.filter((x:any)=>Number(x.stock_quantity||0)<=Number(x.stock_minimum||0)),zero=managed.filter((x:any)=>Number(x.stock_quantity||0)<=0),stockValue=managed.reduce((a:number,x:any)=>a+Number(x.stock_quantity||0)*Number(x.cost_price||0),0);
 const trend=(cur:number,prev:number)=>prev?((cur-prev)/prev)*100:0;
 const daily=useMemo(()=>{const rows=new Map<string,any>();for(let i=period-1;i>=0;i--){const d=new Date(now-i*864e5),key=d.toISOString().slice(0,10);rows.set(key,{day:d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),valor:0,vendas:0,ticket:0})}for(const x of authorized){const key=new Date(x.created_at).toISOString().slice(0,10),r=rows.get(key);if(r){r.valor+=Number(x.total||0);r.vendas++}}for(const r of rows.values())r.ticket=r.vendas?r.valor/r.vendas:0;return [...rows.values()]},[authorized,period]);
 const spark=useMemo(()=>daily.slice(-12),[daily]);
 const byType=useMemo(()=>Object.entries(monthAuthorized.reduce((a:any,x:any)=>{const k=typeLabel(x.document_type);a[k]=(a[k]||0)+Number(x.total||0);return a},{})).map(([name,value])=>({name,value:Number(value)})).sort((a,b)=>b.value-a.value),[monthAuthorized]);
 const productRank=useMemo(()=>{const map=new Map<string,{name:string,qty:number,revenue:number}>();for(const x of monthAuthorized){const n=getProductName(x);if(!n)continue;const q=Number(x?.payload?.quantidade||x?.payload?.quantity||1),r=Number(x.total||0),cur=map.get(n)||{name:n,qty:0,revenue:0};cur.qty+=q;cur.revenue+=r;map.set(n,cur)}return [...map.values()].sort((a,b)=>b.revenue-a.revenue).slice(0,6)},[monthAuthorized]);
 const treemapData=useMemo(()=>managed.map((x:any)=>({name:x.name,size:Math.max(1,Number(x.stock_quantity||0)*Number(x.cost_price||0))})).sort((a:any,b:any)=>b.size-a.size).slice(0,10),[managed]);
 const heat=useMemo(()=>{const grid=Array.from({length:7},()=>Array(6).fill(0));for(const x of authorized){const d=new Date(x.created_at),day=d.getDay(),hour=d.getHours(),slot=Math.min(5,Math.max(0,Math.floor((hour-8)/2)));if(hour>=8&&hour<20)grid[day][slot]+=Number(x.total||0)}const max=Math.max(1,...grid.flat());return{grid,max}},[authorized]);
 const stockBands={normal:Math.max(0,managed.length-low.length),attention:Math.max(0,low.length-zero.length),zero:zero.length};
 const activePie=[{name:"Ativos",value:active.length},{name:"Inativos",value:inactive}];
 const revenueTrend=trend(monthRevenue,prevRevenue);
 const cards=[
  {label:"Faturamento no mês",value:money(monthRevenue),sub:`${revenueTrend>=0?"+":""}${revenueTrend.toFixed(1)}% vs mês anterior`,kind:"area"},
  {label:"Vendas no mês",value:String(salesCount),sub:"documentos autorizados",kind:"bars"},
  {label:"Ticket médio",value:money(ticket),sub:"média por venda autorizada",kind:"line"},
  {label:"Valor em estoque",value:money(stockValue),sub:"quantidade × custo cadastrado",kind:"stock"},
  {label:"Produtos ativos",value:String(active.length),sub:`${inactive} inativo(s) / arquivado(s)`,kind:"ring"},
  {label:"Estoque baixo",value:String(low.length),sub:`${zero.length} item(ns) zerado(s)`,kind:"risk"},
 ];
 return <div className="saas-dashboard mx-auto w-full max-w-[1540px] space-y-5">
  <AdminPageHeader eyebrow="Visão fiscal" title={`Olá, ${organizationName||"sua empresa"}`} description="Acompanhe faturamento, vendas, produtos e estoque em um único lugar." actions={<><Button variant="outline" onClick={onReports}>Relatórios<ArrowUpRight className="ml-2 h-4 w-4"/></Button><Button onClick={onNew}><FilePlus2 className="mr-2 h-4 w-4"/>Nova emissão</Button></>}/>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{cards.map((c)=><Kpi key={c.label} {...c} spark={spark} activePie={activePie} stockBands={stockBands}/>)}</div>
  <div className="grid gap-5 xl:grid-cols-[1.28fr_.72fr]">
   <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-border/45 px-5 py-4"><div><h3 className="font-medium">Faturamento e vendas</h3><p className="mt-0.5 text-xs text-muted-foreground">Receita autorizada e quantidade de vendas no período.</p></div><div className="flex rounded-md border border-[#d9e0e7] bg-[#f8fafb] p-1">{([7,30,90,365] as const).map(p=><button key={p} onClick={()=>setPeriod(p)} className={`rounded px-2.5 py-1.5 text-[11px] font-medium ${period===p?"bg-white text-[#17233b] shadow-sm":"text-[#748094]"}`}>{p===365?"Ano":`${p} dias`}</button>)}</div></div><div className="h-[330px] p-5"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={daily} margin={{top:8,right:8,left:-8,bottom:0}}><CartesianGrid vertical={false} stroke="#edf0f3"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7a8698"}}/><YAxis yAxisId="money" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7a8698"}} tickFormatter={(v)=>`R$ ${Math.round(Number(v)/1000)}k`}/><YAxis yAxisId="count" orientation="right" allowDecimals={false} axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#98a2b3"}}/><Tooltip contentStyle={tooltip} formatter={(v:any,n:any)=>n==="valor"?[money(Number(v)),"Faturamento"]:[v,"Vendas"]}/><Legend verticalAlign="top" height={26} wrapperStyle={{fontSize:11}}/><Bar yAxisId="count" dataKey="vendas" name="Vendas" fill="#dce7f4" radius={[4,4,0,0]} maxBarSize={24}/><Line yAxisId="money" type="monotone" dataKey="valor" name="Faturamento" stroke="#345f91" strokeWidth={2.4} dot={false} activeDot={{r:4}}/></ComposedChart></ResponsiveContainer></div></CardContent></Card>
   <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Visão rápida do negócio" sub="Indicadores comerciais que ajudam na decisão"/><div className="space-y-5 p-5"><Quick label="Produto mais vendido" value={productRank[0]?.name||"Sem dados suficientes"} detail={productRank[0]?money(productRank[0].revenue):"Comece a emitir com produtos cadastrados"} pct={productRank[0]&&monthRevenue?productRank[0].revenue/monthRevenue*100:0}/><Quick label="Cliente que mais comprou" value={topCustomer(monthAuthorized)?.name||"Sem dados suficientes"} detail={topCustomer(monthAuthorized)?money(topCustomer(monthAuthorized)!.value):"—"} pct={topCustomer(monthAuthorized)&&monthRevenue?topCustomer(monthAuthorized)!.value/monthRevenue*100:0}/><div className="grid grid-cols-2 gap-4"><MiniType data={byType}/><MarginGauge products={products}/></div></div></CardContent></Card>
  </div>
  <div className="grid gap-5 xl:grid-cols-[1fr_.82fr]">
   <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Estoque" sub="Onde o capital está concentrado entre os produtos"/><div className="h-[300px] p-4">{treemapData.length?<ResponsiveContainer width="100%" height="100%"><Treemap data={treemapData} dataKey="size" stroke="#fff" fill="#5a789a" content={<TreeNode/>}/></ResponsiveContainer>:<Empty text="Cadastre produtos com custo e estoque para visualizar a composição."/>}</div></CardContent></Card>
   <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Produtos que merecem atenção" sub="Comparação entre estoque atual e estoque mínimo"/><div className="space-y-4 p-5">{low.slice(0,6).map((x:any)=><Bullet key={x.id} item={x}/>) }{!low.length&&<Empty text="Nenhum produto abaixo do estoque mínimo."/>}</div></CardContent></Card>
  </div>
  <div className="grid gap-5 xl:grid-cols-[1fr_.82fr_.78fr]">
   <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Produtos mais vendidos" sub="Ranking por faturamento no mês"/><div className="space-y-3 p-5">{productRank.map((x:any,i:number)=><Rank key={x.name} item={x} index={i} total={monthRevenue}/>) }{!productRank.length&&<Empty text="Ainda não há produtos identificados nas emissões deste mês."/>}</div></CardContent></Card>
   <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Faturamento por tipo" sub="Participação de produtos, serviços e transportes"/><div className="p-5"><StackedTypes data={byType}/></div><div className="border-t border-border/35 px-5 py-4"><h4 className="text-xs font-semibold text-[#344054]">Curva ABC de produtos</h4><p className="mt-1 text-[11px] text-muted-foreground">Concentração do faturamento entre os produtos mais relevantes.</p><ABC items={productRank}/></div></CardContent></Card>
   <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Mapa de vendas" sub="Intensidade por dia da semana e horário"/><Heatmap heat={heat}/></CardContent></Card>
  </div>
  <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-0"><Head title="Últimas movimentações" sub="Documentos fiscais mais recentes"/><div className="divide-y divide-border/30">{emissions.slice(0,7).map((x:any,i:number)=><div key={x.id||i} className="flex items-center gap-4 px-5 py-3.5"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-md bg-[#f1f4f7]"><ReceiptText className="h-4 w-4 text-[#667085]"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{typeLabel(x.document_type)} · {x.number||"—"}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{x.recipient_name||getProductName(x)||"Sem destinatário"}</p></div><div className="text-right"><p className="text-sm font-medium">{money(Number(x.total||0))}</p><p className="mt-0.5 text-[10px] uppercase tracking-wide text-muted-foreground">{statusLabel(x.status)}</p></div></div>)}{!emissions.length&&<Empty text="Nenhuma movimentação registrada ainda."/>}</div></CardContent></Card>
 </div>
}

function Kpi({label,value,sub,kind,spark,activePie,stockBands}:any){return <Card className="overflow-hidden border border-border/60 !bg-white shadow-sm"><CardContent className="p-4"><p className="text-[10px] font-semibold uppercase tracking-[.11em] text-muted-foreground">{label}</p><p className="mt-2 text-[21px] font-medium tracking-tight">{value}</p><p className="mt-1 min-h-[28px] text-[10px] leading-4 text-muted-foreground">{sub}</p><div className="mt-2 h-[48px]">{kind==="area"&&<ResponsiveContainer width="100%" height="100%"><AreaChart data={spark}><defs><linearGradient id="kpiA" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#537da8" stopOpacity=".24"/><stop offset="1" stopColor="#537da8" stopOpacity="0"/></linearGradient></defs><Area dataKey="valor" type="monotone" stroke="#537da8" strokeWidth={1.7} fill="url(#kpiA)" dot={false}/></AreaChart></ResponsiveContainer>}{kind==="bars"&&<ResponsiveContainer width="100%" height="100%"><ComposedChart data={spark}><Bar dataKey="vendas" fill="#8fb0d3" radius={[2,2,0,0]} maxBarSize={8}/></ComposedChart></ResponsiveContainer>}{kind==="line"&&<ResponsiveContainer width="100%" height="100%"><AreaChart data={spark}><Area dataKey="ticket" type="monotone" stroke="#7b78a9" strokeWidth={1.7} fill="transparent" dot={false}/></AreaChart></ResponsiveContainer>}{kind==="stock"&&<ResponsiveContainer width="100%" height="100%"><AreaChart data={spark.map((x:any,i:number)=>({...x,stock:i}))}><Area dataKey="stock" type="monotone" stroke="#6c8b72" strokeWidth={1.7} fill="#6c8b72" fillOpacity=".08" dot={false}/></AreaChart></ResponsiveContainer>}{kind==="ring"&&<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={activePie} dataKey="value" innerRadius={15} outerRadius={21} startAngle={90} endAngle={-270} stroke="none">{activePie.map((_:any,i:number)=><Cell key={i} fill={i===0?"#5f7f9e":"#e7ebef"}/>)}</Pie></PieChart></ResponsiveContainer>}{kind==="risk"&&<div className="flex h-full items-center"><div className="flex h-2 w-full overflow-hidden rounded-full bg-[#eef1f4]"><span style={{width:`${stockBands.normal+stockBands.attention+stockBands.zero?stockBands.normal/(stockBands.normal+stockBands.attention+stockBands.zero)*100:100}%`}} className="bg-[#7ea386]"/><span style={{width:`${stockBands.normal+stockBands.attention+stockBands.zero?stockBands.attention/(stockBands.normal+stockBands.attention+stockBands.zero)*100:0}%`}} className="bg-[#d1a05f]"/><span style={{width:`${stockBands.normal+stockBands.attention+stockBands.zero?stockBands.zero/(stockBands.normal+stockBands.attention+stockBands.zero)*100:0}%`}} className="bg-[#b96a63]"/></div></div>}</div></CardContent></Card>}
function Head({title,sub}:{title:string;sub:string}){return <div className="border-b border-border/40 px-5 py-4"><h3 className="font-medium">{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{sub}</p></div>}
function Quick({label,value,detail,pct}:{label:string;value:string;detail:string;pct:number}){return <div><div className="flex items-end justify-between gap-3"><div className="min-w-0"><p className="text-[10px] uppercase tracking-[.1em] text-muted-foreground">{label}</p><p className="mt-1 truncate text-sm font-medium">{value}</p></div><span className="text-xs font-semibold text-[#50647c]">{detail}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#edf0f3]"><div className="h-full rounded-full bg-[#6f8daa]" style={{width:`${Math.min(100,pct)}%`}}/></div></div>}
function MiniType({data}:{data:any[]}){const total=data.reduce((a,x)=>a+x.value,0),first=data[0];return <div className="rounded-md border border-[#e1e6eb] p-3"><p className="text-[10px] uppercase tracking-[.1em] text-muted-foreground">Maior faturamento</p><div className="mt-2 flex items-center gap-3"><div className="h-12 w-12"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={14} outerRadius={22} stroke="none">{data.map((_:any,i:number)=><Cell key={i} fill={["#5d7f9f","#89a9a1","#9b91b2","#c49a6c","#8b9a74"][i%5]}/>)}</Pie></PieChart></ResponsiveContainer></div><div><p className="text-sm font-semibold">{first?.name||"—"}</p><p className="text-[10px] text-muted-foreground">{first&&total?`${(first.value/total*100).toFixed(1)}% do mês`:"Sem dados"}</p></div></div></div>}
function MarginGauge({products}:{products:any[]}){const vals=products.map((x:any)=>{const sale=Number(x.sale_price||0),cost=Number(x.cost_price||0);return sale>0?(sale-cost)/sale*100:null}).filter((x:any)=>x!=null) as number[],avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;return <div className="rounded-md border border-[#e1e6eb] p-3"><p className="text-[10px] uppercase tracking-[.1em] text-muted-foreground">Margem média</p><p className="mt-2 text-lg font-semibold">{avg.toFixed(1)}%</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-gradient-to-r from-[#c87b74] via-[#d8b36c] to-[#7ea386]"><div className="h-full w-0"/></div><div className="relative -mt-3 h-4"><span className="absolute top-0 h-4 w-[2px] bg-[#17233b]" style={{left:`${Math.max(0,Math.min(100,avg))}%`}}/></div></div>}
function TreeNode(props:any){const {x,y,width,height,name,size}=props;if(width<36||height<28)return <g/>;return <g><rect x={x} y={y} width={width} height={height} rx={5} fill="#607f9d" stroke="#fff" strokeWidth={3}/><text x={x+8} y={y+18} fontSize={11} fill="#fff" fontWeight={600}>{String(name).slice(0,Math.max(5,Math.floor(width/8)))}</text>{height>45&&<text x={x+8} y={y+34} fontSize={10} fill="#eaf0f5">{money(Number(size||0))}</text>}</g>}
function Bullet({item}:{item:any}){const cur=Number(item.stock_quantity||0),min=Math.max(1,Number(item.stock_minimum||0)),pct=Math.min(100,cur/min*100);return <div><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{item.name}</p><span className="text-xs text-muted-foreground">{cur} / {min} {item.unit||"UN"}</span></div><div className="relative mt-2 h-2 rounded-full bg-[#edf0f3]"><div className="h-full rounded-full bg-[#d0a05d]" style={{width:`${pct}%`}}/><span className="absolute -top-1 right-0 h-4 w-[2px] bg-[#4e5d6c]"/></div></div>}
function Rank({item,index,total}:{item:any;index:number;total:number}){const pct=total?item.revenue/total*100:0;return <div className="grid grid-cols-[24px_minmax(0,1fr)_90px] items-center gap-3"><span className="text-xs font-semibold text-[#7c8795]">{index+1}</span><div className="min-w-0"><div className="flex justify-between gap-3"><p className="truncate text-sm font-medium">{item.name}</p><span className="text-[10px] text-muted-foreground">{item.qty} un.</span></div><div className="mt-1.5 h-1.5 rounded-full bg-[#edf0f3]"><div className="h-full rounded-full bg-[#6d8eae]" style={{width:`${Math.min(100,pct)}%`}}/></div></div><div className="text-right"><p className="text-xs font-semibold">{money(item.revenue)}</p><p className="text-[10px] text-muted-foreground">{pct.toFixed(1)}%</p></div></div>}
function StackedTypes({data}:{data:any[]}){const total=data.reduce((a,x)=>a+x.value,0),colors=["#5d7f9f","#78a59b","#9288ad","#c69463","#899a73"];return <div><div className="flex h-4 overflow-hidden rounded-full bg-[#edf0f3]">{data.map((x,i)=><div key={x.name} title={`${x.name}: ${money(x.value)}`} style={{width:`${total?x.value/total*100:0}%`,background:colors[i%colors.length]}}/>)}</div><div className="mt-4 space-y-2">{data.map((x,i)=><div key={x.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm" style={{background:colors[i%colors.length]}}/>{x.name}</span><span className="font-medium">{total?(x.value/total*100).toFixed(1):0}% · {money(x.value)}</span></div>)}{!data.length&&<Empty text="Sem faturamento no período."/>}</div></div>}
function Heatmap({heat}:{heat:{grid:number[][];max:number}}){const days=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"],hours=["08h","10h","12h","14h","16h","18h"];return <div className="p-5"><div className="grid grid-cols-[42px_repeat(6,1fr)] gap-1.5 text-center"> <span/>{hours.map(h=><span key={h} className="text-[9px] text-muted-foreground">{h}</span>)}{days.flatMap((d,di)=>[<span key={`${d}-l`} className="self-center text-left text-[10px] text-muted-foreground">{d}</span>,...heat.grid[di].map((v,hi)=>{const opacity=v?0.16+0.78*(v/heat.max):0.05;return <div key={`${d}-${hi}`} title={`${d} ${hours[hi]} · ${money(v)}`} className="aspect-square rounded-[4px] border border-[#e6ebef]" style={{background:`rgba(70,110,150,${opacity})`}}/>})])}</div><div className="mt-4 flex items-center justify-end gap-2 text-[9px] text-muted-foreground"><span>Menor</span>{[.12,.3,.5,.7,.9].map(x=><i key={x} className="h-3 w-3 rounded-sm" style={{background:`rgba(70,110,150,${x})`}}/>)}<span>Maior</span></div></div>}
function ABC({items}:{items:any[]}){const total=items.reduce((a,x)=>a+x.revenue,0);let acc=0;return <div className="mt-4 flex h-5 overflow-hidden rounded-full bg-[#edf0f3]">{items.map((x:any,i:number)=>{const pct=total?x.revenue/total*100:0;acc+=pct;const cls=acc<=80?"#6687a7":acc<=95?"#c29a62":"#9b8181";return <span key={x.name} title={`${x.name}: ${pct.toFixed(1)}%`} style={{width:`${pct}%`,background:cls}}/>})}</div>}
function Empty({text}:{text:string}){return <div className="grid min-h-[90px] place-items-center px-4 text-center text-xs text-muted-foreground"><div><PackageSearch className="mx-auto mb-2 h-5 w-5 opacity-50"/><p>{text}</p></div></div>}
function topCustomer(items:any[]){const m=new Map<string,number>();for(const x of items){const name=x.recipient_name||"Sem destinatário";m.set(name,(m.get(name)||0)+Number(x.total||0))}return [...m.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)[0]||null}
