import { useEffect, useMemo, useState } from "react";
import { Activity, BadgeDollarSign, Building2, FileCheck2, FileText, Package2, ReceiptText, Users2 } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent } from "@/components/ui/card";
import { AdminPageHeader } from "@/components/admin/ui/AdminPage";
import { supabase } from "@/integrations/supabase/client";

type Props={organizationId:string|null};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const typeLabel:Record<string,string>={nfe:"NF-e",nfce:"NFC-e",nfse:"NFS-e",cte:"CT-e",mdfe:"MDF-e",dfe:"DF-e"};
const chartColors=["hsl(var(--foreground) / .9)","hsl(var(--foreground) / .65)","hsl(var(--foreground) / .45)","hsl(var(--foreground) / .28)","hsl(var(--foreground) / .15)"];
const tooltip={background:"hsl(var(--popover))",border:"1px solid hsl(var(--border))",borderRadius:12,fontSize:12};

export default function SaasReports({organizationId}:Props){
 const [emissions,setEmissions]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!organizationId)return;setLoading(true);Promise.all([(supabase as any).from("saas_fiscal_emissions").select("*").eq("organization_id",organizationId).order("created_at",{ascending:true}).limit(3000),(supabase as any).from("saas_fiscal_catalog_items").select("id,name,code,sale_price,item_type").eq("organization_id",organizationId).eq("item_type","product"),(supabase as any).from("saas_fiscal_parties").select("id,legal_name,tax_id,party_type").eq("organization_id",organizationId).eq("party_type","customer")]).then(([e,p,c])=>{setEmissions(e.data||[]);setProducts(p.data||[]);setCustomers(c.data||[])}).finally(()=>setLoading(false))},[organizationId]);
 const authorized=useMemo(()=>emissions.filter(x=>x.status==="authorized"),[emissions]);
 const total=authorized.reduce((a,x)=>a+Number(x.total||0),0),ticket=authorized.length?total/authorized.length:0,rejected=emissions.filter(x=>x.status==="rejected").length,cancelled=emissions.filter(x=>x.status==="cancelled").length;
 const monthly=useMemo(()=>{const m=new Map<string,any>();for(const x of emissions){const d=new Date(x.created_at),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;if(!m.has(key))m.set(key,{key,label:d.toLocaleDateString("pt-BR",{month:"short",year:"2-digit"}),valor:0,notas:0,autorizadas:0,rejeitadas:0});const row=m.get(key);row.notas++;if(x.status==="authorized"){row.autorizadas++;row.valor+=Number(x.total||0)}if(x.status==="rejected")row.rejeitadas++}return [...m.values()].slice(-12)},[emissions]);
 const byType=useMemo(()=>Object.entries(authorized.reduce((a:any,x:any)=>{const k=x.document_type||"outro";a[k]=(a[k]||0)+1;return a},{})).map(([name,value])=>({name:typeLabel[name]||name,value})),[authorized]);
 const byClient=useMemo(()=>{const map=new Map<string,{name:string,value:number,count:number}>();for(const x of authorized){const key=x.recipient_tax_id||x.recipient_name||"Não identificado",name=x.recipient_name||x.recipient_tax_id||"Não identificado",row=map.get(key)||{name,value:0,count:0};row.value+=Number(x.total||0);row.count++;map.set(key,row)}return [...map.values()].sort((a,b)=>b.value-a.value).slice(0,8)},[authorized]);
 const productRanking=useMemo(()=>{const map=new Map<string,{name:string,qty:number,value:number}>();for(const x of authorized.filter(x=>x.document_type==="nfe"||x.document_type==="nfce")){const p=x.payload||{},code=String(p.codigoProduto||""),name=products.find(z=>String(z.code)===code)?.name||p.xProd||p.descricaoProduto||code||"Produto";const row=map.get(name)||{name,qty:0,value:0};row.qty+=Number(p.quantidade||1);row.value+=Number(x.total||0);map.set(name,row)}return [...map.values()].sort((a,b)=>b.qty-a.qty).slice(0,8)},[authorized,products]);
 const statusData=[{name:"Autorizadas",value:authorized.length},{name:"Rejeitadas",value:rejected},{name:"Canceladas",value:cancelled},{name:"Outras",value:Math.max(0,emissions.length-authorized.length-rejected-cancelled)}].filter(x=>x.value>0);
 const slope=useMemo(()=>{const mid=Date.now()-15*864e5,prevStart=Date.now()-30*864e5,types=["nfe","nfce","nfse","cte","mdfe"];return ["Período anterior","Últimos 15 dias"].map((period,i)=>{const row:any={period};for(const t of types)row[type]=authorized.filter(x=>x.document_type===t&&new Date(x.created_at).getTime()>=(i?mid:prevStart)&&new Date(x.created_at).getTime()<(i?Date.now():mid)).length;return row})},[authorized]);
 const kpis=[{label:"Faturamento autorizado",value:money(total),hint:"Somatório das emissões autorizadas",icon:BadgeDollarSign},{label:"Notas emitidas",value:String(emissions.length),hint:`${authorized.length} autorizadas`,icon:ReceiptText},{label:"Ticket médio",value:money(ticket),hint:"Média por documento autorizado",icon:FileCheck2},{label:"Clientes atendidos",value:String(new Set(authorized.map(x=>x.recipient_tax_id||x.recipient_name).filter(Boolean)).size),hint:`${customers.length} cadastrados`,icon:Users2},{label:"Produtos no catálogo",value:String(products.length),hint:"Itens disponíveis para emissão",icon:Package2},{label:"Taxa de autorização",value:`${emissions.length?Math.round(authorized.length/emissions.length*100):0}%`,hint:`${rejected} rejeições registradas`,icon:Activity}];
 if(loading)return <div className="py-20 text-center text-sm text-muted-foreground">Carregando relatórios...</div>;
 return <div className="ws-storage-style mx-auto w-full max-w-[1540px] space-y-5"><AdminPageHeader eyebrow="Inteligência fiscal" title="Relatórios" description="Faturamento, documentos, clientes e produtos reunidos em uma visão analítica."/>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{kpis.map(({label,value,hint,icon:Icon})=><Card key={label} className="border-0 bg-card shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-light tracking-tight">{value}</p></div><div className="rounded-xl bg-muted/45 p-2.5"><Icon className="h-4 w-4 text-muted-foreground"/></div></div><p className="mt-4 text-xs text-muted-foreground">{hint}</p></CardContent></Card>)}</div>
  <div className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><Card className="overflow-hidden border-0 bg-card shadow-sm"><CardContent className="p-0"><Head title="Faturamento e volume" sub="Evolução mensal das emissões autorizadas"/><div className="h-[330px] p-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly} margin={{top:8,right:10,left:0,bottom:0}}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--foreground) / .65)" stopOpacity=".30"/><stop offset="100%" stopColor="hsl(var(--foreground) / .65)" stopOpacity=".02"/></linearGradient></defs><CartesianGrid vertical={false} stroke="hsl(var(--border) / .42)"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><Tooltip contentStyle={tooltip} formatter={(v:any,n:any)=>n==="valor"?[money(Number(v)),"Faturamento"]:[v,n]}/><Area type="monotone" dataKey="valor" stroke="hsl(var(--foreground) / .8)" strokeWidth={2.3} fill="url(#revenueFill)"/><Line type="monotone" dataKey="autorizadas" stroke="hsl(var(--muted-foreground))" strokeWidth={1.7} dot={false}/></AreaChart></ResponsiveContainer></div></CardContent></Card>
  <Card className="overflow-hidden border-0 bg-card shadow-sm"><CardContent className="p-0"><Head title="Status das emissões" sub="Distribuição do processamento fiscal"/><div className="relative h-[260px] p-4"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius="62%" outerRadius="86%" paddingAngle={3} stroke="none">{statusData.map((_,i)=><Cell key={i} fill={chartColors[i%chartColors.length]}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="text-center"><p className="text-4xl font-light">{emissions.length}</p><p className="text-[10px] uppercase tracking-[.13em] text-muted-foreground">documentos</p></div></div></div><div className="grid grid-cols-2 border-t border-border/35">{statusData.slice(0,4).map(x=><div key={x.name} className="border-b border-r border-border/25 p-3"><p className="text-xs text-muted-foreground">{x.name}</p><p className="mt-1 text-xl font-light">{x.value}</p></div>)}</div></CardContent></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card className="overflow-hidden border-0 bg-card shadow-sm"><CardContent className="p-0"><Head title="Documentos por modalidade" sub="Participação de cada tipo fiscal"/><div className="h-[300px] p-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={byType}><CartesianGrid vertical={false} stroke="hsl(var(--border) / .4)"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"hsl(var(--muted-foreground))"}}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><Tooltip contentStyle={tooltip}/><Bar dataKey="value" name="Documentos" fill="hsl(var(--foreground) / .82)" radius={[7,7,0,0]} barSize={28}/></BarChart></ResponsiveContainer></div></CardContent></Card>
  <Card className="overflow-hidden border-0 bg-card shadow-sm"><CardContent className="p-0"><Head title="Evolução por modalidade" sub="Inclinação entre o período anterior e os últimos 15 dias"/><div className="h-[300px] p-5"><ResponsiveContainer width="100%" height="100%"><LineChart data={slope} margin={{top:15,right:20,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="hsl(var(--border) / .35)"/><XAxis dataKey="period" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"hsl(var(--muted-foreground))"}}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><Tooltip contentStyle={tooltip}/><Legend wrapperStyle={{fontSize:11}}/>{["nfe","nfce","nfse","cte","mdfe"].map((t,i)=><Line key={t} type="linear" dataKey={t} name={typeLabel[t]} stroke={chartColors[i]} strokeWidth={2} dot={{r:4}}/>)}</LineChart></ResponsiveContainer></div></CardContent></Card></div>
  <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><Card className="overflow-hidden border-0 bg-card shadow-sm"><CardContent className="p-0"><Head title="Clientes por faturamento" sub="Maiores destinatários em valor autorizado"/><div className="h-[330px] p-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={byClient} layout="vertical" margin={{left:15,right:15}}><CartesianGrid horizontal={false} stroke="hsl(var(--border) / .38)"/><XAxis type="number" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><YAxis type="category" dataKey="name" width={130} axisLine={false} tickLine={false} tick={{fontSize:10,fill:"hsl(var(--muted-foreground))"}}/><Tooltip contentStyle={tooltip} formatter={(v:any)=>money(Number(v))}/><Bar dataKey="value" name="Faturamento" fill="hsl(var(--foreground) / .82)" radius={[0,7,7,0]} barSize={16}/></BarChart></ResponsiveContainer></div></CardContent></Card>
  <Card className="overflow-hidden border-0 bg-card shadow-sm"><CardContent className="p-0"><Head title="Produtos mais vendidos" sub="Ranking por quantidade registrada nas notas"/><div className="divide-y divide-border/30">{productRanking.length?productRanking.map((x,i)=><div key={x.name} className="flex items-center gap-4 px-5 py-3.5"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-muted/50 text-xs font-medium">{i+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{x.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{x.qty.toLocaleString("pt-BR")} unidade(s)</p></div><p className="text-sm font-medium">{money(x.value)}</p></div>):<p className="px-5 py-14 text-center text-sm text-muted-foreground">Ainda não há produtos emitidos.</p>}</div></CardContent></Card></div>
  <Card className="overflow-hidden border-0 bg-card shadow-sm"><CardContent className="p-0"><Head title="Resumo operacional" sub="Volume, empresas e produtos concentrados em uma leitura final"/><div className="grid gap-px bg-border/30 sm:grid-cols-4"><Summary icon={Building2} label="Clientes cadastrados" value={customers.length}/><Summary icon={FileText} label="Documentos autorizados" value={authorized.length}/><Summary icon={Package2} label="Produtos cadastrados" value={products.length}/><Summary icon={BadgeDollarSign} label="Faturamento" value={money(total)}/></div></CardContent></Card>
 </div>;
}
function Head({title,sub}:{title:string;sub:string}){return <div className="border-b border-border/35 px-5 py-4"><h3 className="font-medium">{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{sub}</p></div>}
function Summary({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <div className="bg-card p-5"><Icon className="h-4 w-4 text-muted-foreground"/><p className="mt-4 text-[10px] font-semibold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-2 text-xl font-light">{value}</p></div>}
