import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { AdminPageHeader } from "@/components/admin/ui/AdminPage";
import { supabase } from "@/integrations/supabase/client";

type Props={organizationId:string|null};
type Metric="revenue"|"margin"|"stock";
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const typeLabel:Record<string,string>={nfe:"NF-e",nfce:"NFC-e",nfse:"NFS-e",cte:"CT-e",mdfe:"MDF-e"};
const colors=["#2f6fed","#4fb38f","#7b61d1","#ee9a45","#637184","#d56572"];
const panel="overflow-hidden border border-[#d9e0e7] !bg-white shadow-sm";
const tooltip={background:"#fff",border:"1px solid #d9e0e7",borderRadius:8,fontSize:12};
const dayNames=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
function Head({title,sub,right}:{title:string;sub:string;right?:React.ReactNode}){return <div className="flex flex-wrap items-start justify-between gap-3 border-b border-[#e4e8ed] px-5 py-4"><div><h3 className="text-sm font-semibold text-[#17233b]">{title}</h3><p className="mt-1 text-xs text-[#748095]">{sub}</p></div>{right}</div>}
function Empty({text="Ainda não há dados suficientes para esta análise."}:{text?:string}){return <div className="grid h-full place-items-center px-8 text-center text-sm text-[#7b8798]">{text}</div>}
function pct(v:number){return `${Math.round(v)}%`}

export default function SaasReports({organizationId}:Props){
 const [emissions,setEmissions]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[range,setRange]=useState<30|90|365>(30),[metric,setMetric]=useState<Metric>("revenue");
 useEffect(()=>{let dead=false;if(!organizationId){setLoading(false);return}setLoading(true);Promise.all([
  (supabase as any).from("saas_fiscal_emissions").select("*").eq("organization_id",organizationId).order("created_at",{ascending:true}).limit(5000),
  (supabase as any).from("saas_fiscal_catalog_items").select("id,name,code,item_type,status,sale_price,cost_price,stock_managed,stock_quantity,stock_minimum").eq("organization_id",organizationId).eq("item_type","product")
 ]).then(([e,p])=>{if(dead)return;if(e.error||p.error)setError("Alguns dados não puderam ser carregados.");setEmissions(e.data||[]);setProducts(p.data||[])}).catch(()=>!dead&&setError("Não foi possível carregar os relatórios.")).finally(()=>!dead&&setLoading(false));return()=>{dead=true}},[organizationId]);
 const now=Date.now(),start=now-range*864e5;
 const period=useMemo(()=>emissions.filter(x=>new Date(x.created_at).getTime()>=start),[emissions,start]);
 const authorized=useMemo(()=>period.filter(x=>x.status==="authorized"),[period]);
 const total=authorized.reduce((s,x)=>s+Number(x.total||0),0),ticket=authorized.length?total/authorized.length:0;
 const managed=products.filter(x=>x.stock_managed),stockValue=managed.reduce((s,x)=>s+Number(x.stock_quantity||0)*Number(x.cost_price||0),0),active=products.filter(x=>x.status!=="inactive"),low=managed.filter(x=>Number(x.stock_quantity||0)<=Number(x.stock_minimum||0));
 const daily=useMemo(()=>{const m=new Map<string,any>();for(let i=range-1;i>=0;i--){const d=new Date(now-i*864e5),k=d.toISOString().slice(0,10);m.set(k,{key:k,date:d,label:d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),value:0,count:0,ticket:0})}for(const x of authorized){const k=new Date(x.created_at).toISOString().slice(0,10),r=m.get(k);if(r){r.value+=Number(x.total||0);r.count++}}for(const r of m.values())r.ticket=r.count?r.value/r.count:0;return [...m.values()]},[authorized,range,now]);
 const monthDaily=useMemo(()=>{const today=new Date(),y=today.getFullYear(),m=today.getMonth(),days=new Date(y,m+1,0).getDate();return Array.from({length:days},(_,i)=>{const d=i+1,rows=authorized.filter(x=>{const z=new Date(x.created_at);return z.getFullYear()===y&&z.getMonth()===m&&z.getDate()===d});return{day:d,value:rows.reduce((s,x)=>s+Number(x.total||0),0),count:rows.length}})},[authorized]);
 const productRanking=useMemo(()=>{const map=new Map<string,{name:string,qty:number,value:number}>();for(const x of authorized.filter(x=>["nfe","nfce"].includes(x.document_type))){const p=x.payload||{},code=String(p.codigoProduto||""),name=products.find(z=>String(z.code)===code)?.name||p.xProd||p.produto||p.descricaoProduto||code||"Produto";const r=map.get(name)||{name,qty:0,value:0};r.qty+=Number(p.quantidade)||1;r.value+=Number(x.total)||0;map.set(name,r)}const rows=[...map.values()].sort((a,b)=>b.value-a.value),sum=rows.reduce((s,x)=>s+x.value,0)||1;return rows.map(x=>({...x,share:x.value/sum*100}))},[authorized,products]);
 const byType=useMemo(()=>{const m=new Map<string,number>();for(const x of authorized){const n=typeLabel[x.document_type]||x.document_type;m.set(n,(m.get(n)||0)+Number(x.total||0))}const rows=[...m.entries()].map(([name,value],i)=>({name,value,color:colors[i%colors.length]})).sort((a,b)=>b.value-a.value),sum=rows.reduce((s,x)=>s+x.value,0)||1;return rows.map(x=>({...x,share:x.value/sum*100}))},[authorized]);
 const stockRows=useMemo(()=>managed.map((x,i)=>{const current=Number(x.stock_quantity||0),minimum=Number(x.stock_minimum||0),value=current*Number(x.cost_price||0);return{...x,current,minimum,value,color:colors[i%colors.length],risk:minimum>0?Math.max(0,Math.min(1,1-current/minimum)):0}}).sort((a,b)=>b.value-a.value),[products]);
 const contribution=useMemo(()=>products.map((p,i)=>{const rank=productRanking.find(r=>r.name===p.name);const sale=Number(p.sale_price||0),cost=Number(p.cost_price||0),stock=Number(p.stock_quantity||0)*cost,margin=Math.max(0,sale-cost)*Math.max(1,Number(p.stock_quantity||0));return{name:p.name,revenue:rank?.value||0,margin,stock,color:colors[i%colors.length]}}).filter(x=>x[metric]>0).sort((a,b)=>b[metric]-a[metric]).slice(0,12),[products,productRanking,metric]);
 const bubble=useMemo(()=>active.slice(0,12).map((p,i)=>{const stock=Math.max(1,Number(p.stock_quantity||0)),value=Math.max(1,stock*Number(p.cost_price||p.sale_price||1));return{name:p.name,size:value,color:colors[i%colors.length]}}).sort((a,b)=>b.size-a.size),[active]);
 const timeline=useMemo(()=>{const out:Array<{title:string;sub:string;color:string}>=[];const best=productRanking[0];if(best)out.push({title:`${best.name} lidera o período`,sub:`${money(best.value)} em faturamento · ${pct(best.share)} da receita de produtos`,color:"#2f6fed"});const topDay=[...daily].sort((a,b)=>b.value-a.value)[0];if(topDay?.value)out.push({title:`Pico de faturamento em ${topDay.label}`,sub:`${money(topDay.value)} em ${topDay.count} venda(s)`,color:"#4fb38f"});const bestType=byType[0];if(bestType)out.push({title:`${bestType.name} é a principal origem de receita`,sub:`Representa ${pct(bestType.share)} do faturamento autorizado`,color:"#7b61d1"});const critical=stockRows.filter(x=>x.risk>=.5).slice(0,1)[0];if(critical)out.push({title:`${critical.name} merece reposição`,sub:`${critical.current} em estoque para mínimo de ${critical.minimum}`,color:"#ee9a45"});if(ticket>0)out.push({title:`Ticket médio atual: ${money(ticket)}`,sub:"Indicador consolidado das emissões autorizadas no período",color:"#637184"});return out.slice(0,5)},[productRanking,daily,byType,stockRows,ticket]);
 const peak=[...daily].sort((a,b)=>b.value-a.value)[0];
 const maxMonth=Math.max(1,...monthDaily.map(x=>x.value));
 const maxRisk=Math.max(1,...stockRows.map(x=>x.risk));
 const maxContribution=Math.max(1,...contribution.map(x=>x[metric]));
 const maxBubble=Math.max(1,...bubble.map(x=>x.size));
 const avgSale=monthDaily.length?monthDaily.reduce((s,x)=>s+x.value,0)/Math.max(1,monthDaily.filter(x=>x.value>0).length):0;
 const ticketLow=Math.max(0,ticket*.55),ticketHigh=Math.max(ticket*1.45,ticket+1),ticketPos=ticketHigh?Math.max(5,Math.min(95,ticket/ticketHigh*100)):50;
 const stockHealthy=Math.max(0,managed.length-low.length),stockRiskPct=managed.length?low.length/managed.length*100:0;
 if(loading)return <div className="py-20 text-center text-sm text-muted-foreground">Carregando relatórios...</div>;
 if(!organizationId)return <div className="py-20 text-center text-sm text-muted-foreground">Nenhuma organização fiscal disponível.</div>;
 return <div className="mx-auto w-full max-w-[1540px] space-y-5">
  <AdminPageHeader eyebrow="Inteligência do negócio" title="Relatórios" description="Fluxo de receita, vendas, estoque e produtos em visualizações que representam a operação de forma direta." actions={<div className="flex gap-2">{([30,90,365] as const).map(n=><Button key={n} size="sm" variant={range===n?"default":"outline"} onClick={()=>setRange(n)}>{n===365?"Ano":`${n} dias`}</Button>)}</div>}/>
  {error&&<div className="rounded-lg border border-[#e1e5ea] bg-white px-4 py-3 text-sm text-[#667085]">{error}</div>}

  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
   <Card className={panel}><CardContent className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#748095]">Faturamento no período</p><p className="mt-2 text-2xl font-semibold text-[#17233b]">{money(total)}</p><p className="mt-1 text-xs text-[#7b8798]">Fluxo acumulado de receita autorizada</p><div className="mt-3 h-20"><ResponsiveContainer width="100%" height="100%"><AreaChart data={daily}><defs><linearGradient id="river" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2f6fed" stopOpacity=".28"/><stop offset="100%" stopColor="#2f6fed" stopOpacity=".02"/></linearGradient></defs><Area type="monotone" dataKey="value" stroke="#2f6fed" strokeWidth={4} fill="url(#river)" dot={false}/></AreaChart></ResponsiveContainer></div>{peak?.value>0&&<p className="mt-2 text-[11px] text-[#526072]">Pico em <b>{peak.label}</b> · {money(peak.value)}</p>}</CardContent></Card>
   <Card className={panel}><CardContent className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#748095]">Vendas no mês</p><p className="mt-2 text-2xl font-semibold text-[#17233b]">{monthDaily.reduce((s,x)=>s+x.count,0)}</p><p className="mt-1 text-xs text-[#7b8798]">Calendário de intensidade financeira</p><div className="mt-4 grid grid-cols-7 gap-1">{monthDaily.map(x=><div key={x.day} title={`${x.day}: ${money(x.value)}`} className="aspect-square rounded-[5px] border border-[#e7ebef] text-center text-[9px] leading-[26px] text-[#526072]" style={{background:`rgba(47,111,237,${.05+.65*x.value/maxMonth})`}}>{x.day}</div>)}</div></CardContent></Card>
   <Card className={panel}><CardContent className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#748095]">Ticket médio</p><p className="mt-2 text-2xl font-semibold text-[#17233b]">{money(ticket)}</p><p className="mt-1 text-xs text-[#7b8798]">Posição atual dentro da faixa observada</p><div className="relative mt-7 h-2 rounded-full bg-gradient-to-r from-[#e8edf4] via-[#b7d9cc] to-[#f3d0ad]"><span className="absolute top-1/2 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-[3px] border-white bg-[#2f6fed] shadow" style={{left:`${ticketPos}%`}}/><span className="absolute -top-6 -translate-x-1/2 whitespace-nowrap text-[10px] font-semibold text-[#2f6fed]" style={{left:`${ticketPos}%`}}>{money(ticket)}</span></div><div className="mt-2 flex justify-between text-[10px] text-[#8a95a5]"><span>{money(ticketLow)}</span><span>faixa operacional</span><span>{money(ticketHigh)}</span></div></CardContent></Card>
   <Card className={panel}><CardContent className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#748095]">Valor em estoque</p><p className="mt-2 text-2xl font-semibold text-[#17233b]">{money(stockValue)}</p><p className="mt-1 text-xs text-[#7b8798]">Estoque financeiro em blocos proporcionais</p><div className="mt-4 grid h-24 grid-cols-6 gap-1">{stockRows.slice(0,18).map((x,i)=><div key={x.id||i} title={`${x.name}: ${money(x.value)}`} className="rounded-[5px]" style={{background:x.color,opacity:.25+.7*(x.value/Math.max(1,stockRows[0]?.value||1)),gridColumn:`span ${x.value>(stockRows[0]?.value||1)*.55?2:1}`}}/>)}</div></CardContent></Card>
   <Card className={panel}><CardContent className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#748095]">Produtos ativos</p><p className="mt-2 text-2xl font-semibold text-[#17233b]">{active.length}</p><p className="mt-1 text-xs text-[#7b8798]">Constelação por relevância financeira</p><div className="relative mt-3 h-28 overflow-hidden rounded-lg bg-[#f8fafc]">{bubble.map((x,i)=>{const s=24+46*Math.sqrt(x.size/maxBubble),left=(i*37)%88,top=(i*29)%68;return <div key={`${x.name}-${i}`} title={x.name} className="absolute grid -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full text-center text-[8px] font-semibold text-white shadow-sm" style={{width:s,height:s,left:`${8+left}%`,top:`${17+top}%`,background:x.color,opacity:.82}}><span className="max-w-[85%] truncate">{x.name}</span></div>})}</div></CardContent></Card>
   <Card className={panel}><CardContent className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#748095]">Risco de ruptura</p><div className="mt-2 flex items-end justify-between"><p className="text-2xl font-semibold text-[#17233b]">{low.length}</p><span className="text-xs text-[#7b8798]">{pct(stockRiskPct)} do estoque gerenciado</span></div><p className="mt-1 text-xs text-[#7b8798]">Saudável → atenção → reposição</p><div className="mt-6 h-3 overflow-hidden rounded-full bg-gradient-to-r from-[#66b99c] via-[#efbc74] to-[#dc6c75]"><span className="block h-full w-[2px] bg-[#17233b]" style={{marginLeft:`${Math.min(98,stockRiskPct)}%`}}/></div><div className="mt-3 flex justify-between text-[10px] text-[#8a95a5]"><span>{stockHealthy} saudáveis</span><span>{low.length} abaixo do mínimo</span></div></CardContent></Card>
  </div>

  <Card className={panel}><CardContent className="p-0"><Head title="Faturamento e vendas em ondas" sub="Receita, quantidade de vendas e ticket médio convergindo no mesmo ponto"/><div className="h-[360px] p-5">{daily.some(x=>x.value>0)?<ResponsiveContainer width="100%" height="100%"><AreaChart data={daily}><defs><linearGradient id="wave1" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2f6fed" stopOpacity=".28"/><stop offset="100%" stopColor="#2f6fed" stopOpacity=".02"/></linearGradient><linearGradient id="wave2" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4fb38f" stopOpacity=".18"/><stop offset="100%" stopColor="#4fb38f" stopOpacity=".01"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f3"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7b8798"}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7b8798"}}/><Tooltip contentStyle={tooltip} formatter={(v:any,n:any)=>n==="value"?[money(Number(v)),"Faturamento"]:n==="ticket"?[money(Number(v)),"Ticket médio"]:[v,"Vendas"]}/><Area type="monotone" dataKey="value" stroke="#2f6fed" strokeWidth={3} fill="url(#wave1)"/><Area type="monotone" dataKey="ticket" stroke="#4fb38f" strokeWidth={2} fill="url(#wave2)"/><Line type="monotone" dataKey="count" stroke="#ee9a45" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer>:<Empty/>}</div></CardContent></Card>

  <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
   <Card className={panel}><CardContent className="p-0"><Head title="Prateleira digital do estoque" sub="Cada faixa representa um produto; comprimento = valor armazenado"/><div className="space-y-4 p-5">{stockRows.slice(0,10).map((x,i)=><div key={x.id||i}><div className="mb-1.5 flex items-center justify-between text-[11px]"><span className="truncate font-medium text-[#344054]">{x.name}</span><span className="text-[#7b8798]">{money(x.value)} · {x.current} un.</span></div><div className="flex h-7 gap-1 rounded-md bg-[#f1f4f7] p-1">{Array.from({length:8},(_,j)=><span key={j} className="flex-1 rounded-[3px]" style={{background:j<Math.max(1,Math.round(8*Math.min(1,x.current/Math.max(x.minimum||x.current,1))))?x.color:"#e7ebef",opacity:j<6?.82:.55}}/>)}</div></div>)}{!stockRows.length&&<Empty text="Cadastre produtos com controle de estoque para visualizar a prateleira."/>}</div></CardContent></Card>
   <Card className={panel}><CardContent className="p-0"><Head title="Faturamento radial" sub="Centro = total; anel = participação por tipo de documento"/><div className="relative h-[330px] p-5">{byType.length?<><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{value:total}]} dataKey="value" innerRadius="30%" outerRadius="43%" fill="#17233b" stroke="none"/><Pie data={byType} dataKey="value" nameKey="name" innerRadius="52%" outerRadius="82%" paddingAngle={2} stroke="white" strokeWidth={2}>{byType.map((x,i)=><cell key={i} fill={x.color}/>)}</Pie><Tooltip contentStyle={tooltip} formatter={(v:any)=>money(Number(v))}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="text-center"><p className="text-[10px] uppercase tracking-[.13em] text-[#8993a1]">Total</p><p className="mt-1 text-sm font-semibold text-[#17233b]">{money(total)}</p></div></div></>:<Empty/>}</div><div className="grid grid-cols-2 gap-2 border-t border-[#edf0f3] p-4">{byType.map(x=><div key={x.name} className="flex items-center gap-2 text-[11px]"><span className="h-2.5 w-2.5 rounded-full" style={{background:x.color}}/><span className="text-[#526072]">{x.name}</span><b className="ml-auto text-[#17233b]">{pct(x.share)}</b></div>)}</div></CardContent></Card>
  </div>

  <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
   <Card className={panel}><CardContent className="p-0"><Head title="Produtos mais vendidos" sub="Pódio vivo para os três líderes; demais produtos em sequência"/><div className="p-5">{productRanking.length?<><div className="grid grid-cols-3 items-end gap-3 pb-6">{[productRanking[1],productRanking[0],productRanking[2]].map((x,i)=>x?<div key={x.name} className={`rounded-lg border border-[#e2e7ec] bg-[#f9fbfc] p-3 text-center ${i===1?"min-h-[150px] border-[#c8d8f6] bg-[#f5f8ff]":"min-h-[120px]"}`}><div className="mx-auto grid h-8 w-8 place-items-center rounded-full bg-white text-xs font-bold text-[#2f6fed] shadow-sm">{i===1?1:i===0?2:3}</div><p className="mt-3 truncate text-xs font-semibold text-[#25324a]">{x.name}</p><p className="mt-1 text-sm font-semibold text-[#17233b]">{money(x.value)}</p><p className="mt-1 text-[10px] text-[#7b8798]">{pct(x.share)} da receita</p></div>:<div key={i}/>)}</div><div className="divide-y divide-[#edf0f3]">{productRanking.slice(3,10).map((x,i)=><div key={x.name} className="flex items-center gap-3 py-2.5"><span className="w-6 text-xs font-semibold text-[#9aa3af]">{i+4}</span><span className="min-w-0 flex-1 truncate text-xs font-medium text-[#344054]">{x.name}</span><span className="text-xs text-[#7b8798]">{x.qty} un.</span><span className="w-24 text-right text-xs font-semibold text-[#17233b]">{money(x.value)}</span></div>)}</div></>:<Empty text="Ainda não há produtos vendidos no período."/>}</div></CardContent></Card>
   <Card className={panel}><CardContent className="p-0"><Head title="Mapa de contribuição" sub="O tamanho de cada bloco muda conforme a métrica selecionada" right={<div className="flex gap-1">{(["revenue","margin","stock"] as Metric[]).map(m=><Button key={m} size="sm" variant={metric===m?"default":"outline"} onClick={()=>setMetric(m)}>{m==="revenue"?"Faturamento":m==="margin"?"Margem":"Estoque"}</Button>)}</div>}/><div className="grid min-h-[330px] grid-cols-4 auto-rows-[78px] gap-2 p-5">{contribution.map((x,i)=>{const weight=x[metric]/maxContribution;return <div key={x.name} className={`flex min-w-0 flex-col justify-between rounded-lg p-3 text-white shadow-sm ${weight>.65?"col-span-2 row-span-2":weight>.3?"col-span-2":"col-span-1"}`} style={{background:x.color,opacity:.75+.22*weight}}><p className="truncate text-xs font-semibold">{x.name}</p><p className="text-[11px] opacity-90">{metric==="stock"?money(x.stock):metric==="margin"?money(x.margin):money(x.revenue)}</p></div>})}{!contribution.length&&<div className="col-span-4 row-span-3"><Empty/></div>}</div></CardContent></Card>
  </div>

  <Card className={panel}><CardContent className="p-0"><Head title="Linha do tempo inteligente" sub="Eventos e sinais do negócio traduzidos em leitura operacional"/><div className="p-5"><div className="relative ml-2 border-l border-[#dce2e8] pl-7">{timeline.map((x,i)=><div key={`${x.title}-${i}`} className="relative pb-6 last:pb-0"><span className="absolute -left-[35px] top-1 h-4 w-4 rounded-full border-[3px] border-white shadow-sm" style={{background:x.color}}/><p className="text-sm font-semibold text-[#25324a]">{x.title}</p><p className="mt-1 text-xs text-[#7b8798]">{x.sub}</p></div>)}{!timeline.length&&<Empty/>}</div></div></CardContent></Card>
 </div>
}
