import { useMemo, useState } from "react";
import SaasDanfePreview,{printDanfe} from "./SaasDanfePreview";

const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusLabel=(s:string)=>s==="authorized"?"Autorizada":s==="rejected"?"Rejeitada":s==="cancelled"?"Cancelada":s==="draft"?"Rascunho":s==="error"?"Erro":s;
const itemName=(x:any)=>x?.payload?.produto||x?.payload?.descricao||x?.payload?.carga?.proPred||x?.payload?.proPred||x?.payload?.natOp||x?.payload?.munDescargaNome||(x?.document_type==="cte"?"Prestação de serviço de transporte":"Documento fiscal");
const originLabel=(x:any)=>x?.source==="imported"||x?.origin==="imported"?"Extraída":"Emitida aqui";
const downloadXml=(x:any,documentType:string)=>{if(!x?.xml)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([x.xml],{type:"application/xml"}));a.download=`${documentType}-${x.number||"documento"}.xml`;a.click();URL.revokeObjectURL(a.href)};
const auxName=(documentType:string)=>documentType==="CT-e"?"DACTE":documentType==="MDF-e"?"DAMDFE":documentType==="NFC-e"?"DANFE NFC-e":documentType==="NFS-e"?"DANFSe":"DANFE";
const dateText=(x:any)=>new Date(x.external_issue_date||x.authorized_at||x.created_at).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"});
const pill=(s:string)=>s==="authorized"?"saas-status-authorized":s==="rejected"||s==="error"?"saas-status-rejected":s==="cancelled"?"saas-status-cancelled":"saas-status-draft";

export default function SaasEmissionHistory({items,documentType,onDuplicate}:{items:any[];documentType:string;onDuplicate?:(x:any)=>void}){
 const [selected,setSelected]=useState<any>(null),[viewMode,setViewMode]=useState<"danfe"|"receipt">("danfe"),[status,setStatus]=useState("all"),[q,setQ]=useState("");
 const filtered=useMemo(()=>items.filter(x=>(status==="all"||x.status===status)&&(!q.trim()||String(`${x.number||""} ${x.recipient_name||""} ${itemName(x)} ${x.access_key||""}`).toLowerCase().includes(q.toLowerCase()))),[items,status,q]);
 const openDocument=(x:any)=>{setSelected(x);setViewMode("danfe")};
 const closeDocument=()=>{setSelected(null);setViewMode("danfe")};
 return <>
  <section className="saas-emission-history rounded-lg border border-[#c5ccd6] bg-white p-5 md:p-6">
   <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><h2 className="text-[15px] font-semibold text-[#121923]">Emissões recentes</h2><p className="mt-1 text-xs text-muted-foreground">Consulte, filtre e reutilize documentos sem sair da operação.</p></div><div className="saas-history-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, nº ou chave" className="saas-history-filter w-[220px]"/><select value={status} onChange={e=>setStatus(e.target.value)} className="saas-history-filter"><option value="all">Todos os status</option><option value="authorized">Autorizadas</option><option value="draft">Rascunhos</option><option value="rejected">Rejeitadas</option><option value="cancelled">Canceladas</option></select><span className="text-[10px] text-[#7b8799]">{filtered.length} registro{filtered.length===1?"":"s"}</span></div></div>
   <div className="mt-4 overflow-x-auto rounded-md border border-[#c7cfd9] bg-white"><table className="w-full min-w-[980px] table-fixed text-left text-[13px]"><colgroup><col className="w-[5%]"/><col className="w-[6%]"/><col className="w-[22%]"/><col className="w-[20%]"/><col className="w-[10%]"/><col className="w-[10%]"/><col className="w-[12%]"/><col className="w-[9%]"/><col className="w-[16%]"/></colgroup><thead className="!bg-[#eef2f5]"><tr><th className="px-3 py-3">Nº</th><th className="px-3 py-3">Série</th><th className="px-3 py-3">Destinatário</th><th className="px-3 py-3">Item / operação</th><th className="px-3 py-3">Origem</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Data</th><th className="px-3 py-3 text-right">Valor</th><th className="px-3 py-3 text-right">Ações</th></tr></thead>
    <tbody>{filtered.length===0?<tr><td colSpan={9} className="px-4 py-12 text-center text-sm text-muted-foreground">Nenhuma emissão encontrada com estes filtros.</td></tr>:filtered.slice(0,40).map((x,i)=><tr key={x.id} onClick={()=>openDocument(x)} className={`cursor-pointer border-t border-[#e2e7ed] transition-colors hover:!bg-[#f4f7f9] ${i%2===0?"!bg-white":"!bg-[#fafbfc]"}`}><td className="px-3 py-3 font-semibold">{x.number||"—"}</td><td className="px-3 py-3">{x.series||"—"}</td><td className="px-3 py-3"><div className="line-clamp-2 font-medium leading-5">{x.recipient_name||"Sem destinatário"}</div></td><td className="px-3 py-3"><div className="line-clamp-2 leading-5 text-slate-600">{itemName(x)}</div></td><td className="px-3 py-3"><span className="inline-flex whitespace-nowrap rounded border border-slate-300 bg-white px-2 py-1 text-[9px] font-semibold text-slate-700">{originLabel(x)}</span></td><td className="px-3 py-3"><span className={`saas-status-pill ${pill(x.status)}`}>{statusLabel(x.status)}</span></td><td className="whitespace-nowrap px-3 py-3 text-[11px] text-slate-600">{dateText(x)}</td><td className="whitespace-nowrap px-3 py-3 text-right font-semibold">{money(x.total)}</td><td className="px-3 py-3"><div className="flex min-w-max justify-end gap-2" onClick={e=>e.stopPropagation()}><button onClick={()=>openDocument(x)} className="border border-[#cfd7e1] bg-white px-3 py-2 text-[10px] font-semibold">Visualizar</button>{x.xml&&<button onClick={()=>downloadXml(x,documentType)} className="border border-[#cfd7e1] bg-white px-3 py-2 text-[10px] font-semibold">XML</button>}{onDuplicate&&<button onClick={()=>onDuplicate(x)} className="border border-[#cfd7e1] bg-white px-3 py-2 text-[10px] font-semibold">Duplicar</button>}</div></td></tr>)}</tbody></table></div>
  </section>
  {selected&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/50 p-3 md:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)closeDocument()}}><div className={`flex max-h-[94vh] w-full flex-col overflow-hidden rounded-xl border border-[#cfd6df] bg-[#eef1f4] shadow-2xl ${viewMode==="receipt"?"max-w-[760px]":"max-w-6xl"}`}><div className="z-10 border-b border-[#cbd2db] bg-white px-5 py-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-muted-foreground">{documentType} · Série {selected.series||"—"} · Nº {selected.number||"—"}</p><h3 className="mt-1 text-lg font-semibold text-[#151d27]">{viewMode==="receipt"?"Visualização compacta":auxName(documentType)}</h3></div><div className="flex flex-wrap items-center gap-2"><div className="inline-flex rounded-md border border-[#aeb8c5] bg-[#f4f6f8] p-0.5"><button onClick={()=>setViewMode("danfe")} className={`rounded px-4 py-2 text-xs font-semibold ${viewMode==="danfe"?"bg-[#202833] text-white":"text-[#202833]"}`}>Documento</button><button onClick={()=>setViewMode("receipt")} className={`rounded px-4 py-2 text-xs font-semibold ${viewMode==="receipt"?"bg-[#202833] text-white":"text-[#202833]"}`}>Compacto</button></div><button onClick={()=>printDanfe(`history-danfe-${selected.id}`,`${viewMode==="receipt"?"Notinha":auxName(documentType)}-${selected.number}`)} className="bg-[#202833] px-4 py-2.5 text-xs font-semibold text-white">Imprimir / PDF</button>{selected.xml&&<button onClick={()=>downloadXml(selected,documentType)} className="border border-[#aeb8c5] bg-white px-4 py-2.5 text-xs font-semibold">Baixar XML</button>}{onDuplicate&&<button onClick={()=>{onDuplicate(selected);closeDocument()}} className="border border-[#aeb8c5] bg-white px-4 py-2.5 text-xs font-semibold">Emitir semelhante</button>}<button onClick={closeDocument} className="border border-[#aeb8c5] bg-white px-4 py-2.5 text-xs font-semibold">Fechar</button></div></div></div><div className={`overflow-auto ${viewMode==="receipt"?"px-5 py-5 md:px-8 md:py-6":"p-5 md:p-7"}`}><SaasDanfePreview id={`history-danfe-${selected.id}`} documentType={documentType} environment={selected.environment||"homologation"} emission={selected} mode={viewMode}/></div></div></div>}
 </>
}
