import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import SaasEmissionHistory from "./SaasEmissionHistory";
import SaasDanfePreview,{printDanfe} from "./SaasDanfePreview";

const inputClass="mt-2 h-11 !border-[#cbd3dc] !bg-white !text-[#10203e] dark:!bg-white dark:!text-[#10203e]";
const panel="rounded-lg border border-[#cfd6df] bg-white p-5 md:p-6";
const docs=["NF-e","NFC-e","NFS-e","CT-e","MDF-e"];
function Field({label,value,onChange,type="text",placeholder}:{label:string;value:any;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="text-sm font-medium text-[#263652]">{label}<Input type={type} value={value??""} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={inputClass}/></label>}
function Select({label,value,onChange,children}:{label:string;value:any;onChange:(v:string)=>void;children:any}){return <label className="text-sm font-medium text-[#263652]">{label}<select value={value??""} onChange={e=>onChange(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-[#cbd3dc] bg-white px-3 text-sm text-[#10203e]">{children}</select></label>}
function downloadXml(xml:string,name:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([xml],{type:"application/xml"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

export default function SaasEmission({organizationId,documentType,onChoose}:{organizationId:string|null;documentType:string|null;onChoose:(d:string|null)=>void}){
 const [profile,setProfile]=useState<any>(null),[customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[services,setServices]=useState<any[]>([]),[carriers,setCarriers]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[result,setResult]=useState<any>(null);
 const [form,setForm]=useState<any>({customerId:"",productId:"",serviceId:"",quantity:"1",unitPrice:"",series:"1",number:"1",payment:"01",cfop:"",description:"",value:"",serviceCode:"",municipioPrestacao:"",remetenteId:"",destinatarioId:"",carrierId:"",rntrc:"",chNFe:"",cfopCte:"5353",vTPrest:"",vCarga:"",qCarga:"1",munIniCodigo:"",munIniNome:"",ufIni:"AL",munFimCodigo:"",munFimNome:"",ufFim:"AL",plate:"",driverName:"",driverCpf:"",tara:"1000",capacity:"5000",unloadCode:"",unloadName:"",cargoValue:"",cargoWeight:"",keys:""});
 const set=(k:string,v:any)=>setForm((p:any)=>({...p,[k]:v}));
 const load=async()=>{if(!organizationId)return;const [p,c,pr,s,ca,h]=await Promise.all([(supabase as any).from("saas_company_fiscal_profiles").select("*").eq("organization_id",organizationId).order("created_at").limit(1).maybeSingle(),(supabase as any).from("saas_fiscal_parties").select("*").eq("organization_id",organizationId).eq("party_type","customer").eq("status","active").order("legal_name"),(supabase as any).from("saas_fiscal_catalog_items").select("*").eq("organization_id",organizationId).eq("item_type","product").eq("status","active").order("name"),(supabase as any).from("saas_fiscal_catalog_items").select("*").eq("organization_id",organizationId).eq("item_type","service").eq("status","active").order("name"),(supabase as any).from("saas_fiscal_parties").select("*").eq("organization_id",organizationId).eq("party_type","carrier").eq("status","active").order("legal_name"),(supabase as any).from("saas_fiscal_emissions").select("*").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(50)]);setProfile(p.data);setCustomers(c.data||[]);setProducts(pr.data||[]);setServices(s.data||[]);setCarriers(ca.data||[]);setHistory(h.data||[]);const pp=p.data;if(pp)setForm((f:any)=>({...f,series:documentType==="NF-e"?pp.series_nfe||"1":documentType==="NFC-e"?pp.series_nfce||"1":documentType==="NFS-e"?pp.series_nfse||"1":documentType==="CT-e"?pp.series_cte||"1":pp.series_mdfe||"1",number:String(documentType==="NF-e"?pp.next_number_nfe||1:documentType==="NFC-e"?pp.next_number_nfce||1:documentType==="NFS-e"?pp.next_number_nfse||1:documentType==="CT-e"?pp.next_number_cte||1:pp.next_number_mdfe||1),cfop:pp.default_cfop_in_state||"5102",serviceCode:pp.default_nfse_service_code||"",municipioPrestacao:pp.city_ibge_code||"",munIniCodigo:pp.city_ibge_code||"",munIniNome:pp.city||"",ufIni:pp.state||"AL"}));};
 useEffect(()=>{void load();setResult(null);setMsg("")},[organizationId,documentType]);
 const customer=customers.find(x=>x.id===form.customerId),product=products.find(x=>x.id===form.productId),service=services.find(x=>x.id===form.serviceId),rem=customers.find(x=>x.id===form.remetenteId),dest=customers.find(x=>x.id===form.destinatarioId),carrier=carriers.find(x=>x.id===form.carrierId);
 useEffect(()=>{if(product)setForm((f:any)=>({...f,unitPrice:String(product.sale_price??""),cfop:product.cfop_in_state||profile?.default_cfop_in_state||f.cfop}))},[form.productId]);
 useEffect(()=>{if(service)setForm((f:any)=>({...f,value:String(service.sale_price??""),description:service.description||service.name,serviceCode:service.service_code_national||profile?.default_nfse_service_code||f.serviceCode}))},[form.serviceId]);
 const environment=profile?.fiscal_environment==="production"?"production":"homologation";
 const invoke=async(name:string,body:any)=>{setBusy(true);setMsg("");setResult(null);try{const {data,error}=await supabase.functions.invoke(name,{body:{...body,organization_id:organizationId,expected_environment:environment}});if(error)throw error;if(data?.error){setMsg([data.error,...(data.errors||[])].join(" · "));setResult(data);return}setResult(data);setMsg(data?.authorized===false?"Documento rejeitado pelo autorizador.":body.action==="preview"?"Prévia gerada e assinada para conferência.":"Processamento concluído.");if(body.action==="issue")await load()}catch(e:any){setMsg(e?.message||"Falha no processamento fiscal")}finally{setBusy(false)}};
 const productPayload=()=>({environment,cnpjEmitente:profile?.tax_id,razaoSocial:profile?.legal_name,nomeFantasia:profile?.trade_name,ie:profile?.state_registration,crt:profile?.crt||"1",codigoMunicipio:profile?.city_ibge_code,nomeMunicipio:profile?.city,logradouro:profile?.street,numeroEndereco:profile?.street_number,complemento:profile?.complement,bairro:profile?.district,cep:profile?.postal_code,telefone:profile?.phone,serie:form.series,numeroNota:form.number,destDocumento:customer?.tax_id||"",destNome:customer?.legal_name||"CONSUMIDOR",destLogradouro:customer?.street,destNumero:customer?.street_number,destBairro:customer?.district,destCodigoMunicipio:customer?.city_ibge_code,destMunicipio:customer?.city,destUF:customer?.state,destCep:customer?.postal_code,codigoProduto:product?.code||"1",produto:product?.name||"PRODUTO",ncm:product?.ncm,cfop:form.cfop||product?.cfop_in_state,unidade:product?.unit||"UN",quantidade:Number(form.quantity),valorUnitario:Number(form.unitPrice),origem:product?.product_origin||"0",csosn:product?.csosn||"400",cst:product?.icms_cst||"00",formaPagamento:form.payment});
 const nfsePayload=()=>({environment,serie:form.series,numero:form.number,municipioEmissor:profile?.city_ibge_code,municipioPrestacao:form.municipioPrestacao,codigoTributacao:form.serviceCode,descricao:form.description,valor:Number(form.value),tomadorDocumento:customer?.tax_id,tomadorNome:customer?.legal_name,simples:profile?.tax_regime==="simples"?"1":"2",issRetido:Boolean(service?.iss_withheld)});
 const partyCte=(x:any)=>({CNPJ:String(x?.tax_id||"").replace(/\D/g,""),IE:x?.state_registration||"",xNome:x?.legal_name||"",xLgr:x?.street||"",nro:x?.street_number||"",xBairro:x?.district||"",cMun:x?.city_ibge_code||"",xMun:x?.city||"",CEP:x?.postal_code||"",UF:x?.state||"AL"});
 const ctePayload=()=>({environment,serie:form.series,numero:form.number,cfop:form.cfopCte,natOp:"PRESTACAO DE SERVICO DE TRANSPORTE",cUF:"27",cMunIni:form.munIniCodigo,xMunIni:form.munIniNome,UFIni:form.ufIni,cMunFim:form.munFimCodigo,xMunFim:form.munFimNome,UFFim:form.ufFim,vTPrest:Number(form.vTPrest),vRec:Number(form.vTPrest),emit:{IE:profile?.state_registration,xNome:profile?.legal_name,xLgr:profile?.street,nro:profile?.street_number,xBairro:profile?.district,cMun:profile?.city_ibge_code,xMun:profile?.city,CEP:profile?.postal_code,UF:profile?.state||"AL",CRT:profile?.crt||"1"},rem:partyCte(rem),dest:partyCte(dest),carga:{vCarga:Number(form.vCarga),proPred:"CARGA GERAL",qCarga:Number(form.qCarga)},chNFe:form.chNFe,rodo:{RNTRC:form.rntrc||carrier?.rntrc}});
 const mdfePayload=()=>({environment,serie:form.series,numero:form.number,rntrc:form.rntrc||carrier?.rntrc,placa:form.plate||carrier?.vehicle_plate,veiculoUf:carrier?.vehicle_state||profile?.state||"AL",condutorNome:form.driverName,condutorCpf:form.driverCpf,tara:Number(form.tara),capacidadeKg:Number(form.capacity),ufIni:form.ufIni,ufFim:form.ufFim,munCarregaCodigo:form.munIniCodigo,munCarregaNome:form.munIniNome,munDescargaCodigo:form.unloadCode,munDescargaNome:form.unloadName,valorCarga:Number(form.cargoValue),pesoCarga:Number(form.cargoWeight),chaves:String(form.keys||"").split(/[\n,; ]+/).filter(Boolean)});
 const currentHistory=useMemo(()=>history.filter(x=>!documentType||x.document_type===({"NF-e":"nfe","NFC-e":"nfce","NFS-e":"nfse","CT-e":"cte","MDF-e":"mdfe"} as any)[documentType]),[history,documentType]);
 if(!documentType)return <div><h1 className="text-3xl font-semibold tracking-[-0.04em]">Emitir nova nota</h1><p className="mt-2 text-sm text-[#6d7a90]">Escolha o documento fiscal que deseja preencher.</p><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{docs.map(d=><button key={d} onClick={()=>onChoose(d)} className="min-h-[145px] rounded-lg border border-[#cfd6df] bg-white p-6 text-left hover:border-[#8b98a9]"><p className="text-2xl font-semibold">{d}</p><p className="mt-3 text-sm text-[#6d7a90]">Abrir fluxo de {d}.</p><p className="mt-7 text-xs font-semibold uppercase tracking-[.12em]">Continuar</p></button>)}</div></div>;
 const actions=(name:string,payload:any,extra:any={})=><div className="flex flex-wrap gap-3"><Button variant="outline" disabled={busy} onClick={()=>invoke(name,{action:"preview",data:payload,...extra})}>{busy?"Processando...":"Gerar prévia XML"}</Button><Button disabled={busy} onClick={()=>invoke(name,{action:"issue",data:payload,...extra})} className={environment==="production"?"!bg-red-700 !border-red-700 hover:!bg-red-800":""}>{busy?"Processando...":environment==="production"?"Emitir em PRODUÇÃO":"Transmitir em homologação"}</Button></div>;
 return <div className="space-y-5 pb-10"><div><button onClick={()=>onChoose(null)} className="mb-4 text-sm font-semibold text-[#58709a]">Voltar</button><h1 className="text-3xl font-semibold tracking-[-0.04em]">Emitir {documentType}</h1><p className="mt-2 text-sm text-[#6d7a90]">Preencha à esquerda e acompanhe o DANFE e o retorno fiscal ao lado.</p><div className={`mx-auto mt-3 w-fit rounded-md border px-3 py-1.5 text-xs font-semibold uppercase tracking-[.1em] ${environment==="production"?"border-red-300 bg-red-50 text-red-700":"border-slate-300 bg-white text-slate-600"}`}>Ambiente: {environment==="production"?"Produção":"Homologação"}</div></div>{msg&&<div className="rounded-lg border border-[#cfd6df] bg-white px-4 py-3 text-sm">{msg}</div>}
 <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.08fr)_minmax(430px,.92fr)]"><div className="space-y-4">
 {(documentType==="NF-e"||documentType==="NFC-e")&&<><section className={panel}><h2 className="font-semibold">Destinatário e produto</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Cliente" value={form.customerId} onChange={v=>set("customerId",v)}><option value="">{documentType==="NFC-e"?"Consumidor não identificado":"Selecione"}</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Select label="Produto" value={form.productId} onChange={v=>set("productId",v)}><option value="">Selecione</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Field label="Quantidade" value={form.quantity} onChange={v=>set("quantity",v)} type="number"/><Field label="Valor unitário" value={form.unitPrice} onChange={v=>set("unitPrice",v)} type="number"/><Field label="CFOP" value={form.cfop} onChange={v=>set("cfop",v)}/><Field label="Série" value={form.series} onChange={v=>set("series",v)}/><Field label="Número" value={form.number} onChange={v=>set("number",v)} type="number"/><Select label="Pagamento" value={form.payment} onChange={v=>set("payment",v)}><option value="01">Dinheiro</option><option value="03">Cartão de crédito</option><option value="04">Cartão de débito</option><option value="17">PIX</option><option value="99">Outros</option></Select></div></section>{actions("saas-dfe-issue",productPayload(),{model:documentType==="NF-e"?"55":"65"})}</>}
 {documentType==="NFS-e"&&<><section className={panel}><h2 className="font-semibold">Tomador e serviço</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Cliente / tomador" value={form.customerId} onChange={v=>set("customerId",v)}><option value="">Selecione</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Select label="Serviço" value={form.serviceId} onChange={v=>set("serviceId",v)}><option value="">Selecione</option>{services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Field label="Valor" value={form.value} onChange={v=>set("value",v)} type="number"/><Field label="Código tributação nacional" value={form.serviceCode} onChange={v=>set("serviceCode",v)}/><Field label="Município da prestação (IBGE)" value={form.municipioPrestacao} onChange={v=>set("municipioPrestacao",v)}/><Field label="Série DPS" value={form.series} onChange={v=>set("series",v)}/><Field label="Número DPS" value={form.number} onChange={v=>set("number",v)} type="number"/><div className="md:col-span-2"><Field label="Descrição" value={form.description} onChange={v=>set("description",v)}/></div></div></section>{actions("saas-nfse-issue",nfsePayload())}</>}
 {documentType==="CT-e"&&<><section className={panel}><h2 className="font-semibold">Prestação de transporte</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Remetente" value={form.remetenteId} onChange={v=>set("remetenteId",v)}><option value="">Selecione</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Select label="Destinatário" value={form.destinatarioId} onChange={v=>set("destinatarioId",v)}><option value="">Selecione</option>{customers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Select label="Transportadora" value={form.carrierId} onChange={v=>set("carrierId",v)}><option value="">Própria / manual</option>{carriers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Field label="RNTRC" value={form.rntrc} onChange={v=>set("rntrc",v)} placeholder={carrier?.rntrc}/><Field label="CFOP" value={form.cfopCte} onChange={v=>set("cfopCte",v)}/><Field label="Chave NF-e vinculada" value={form.chNFe} onChange={v=>set("chNFe",v)}/><Field label="Valor da prestação" value={form.vTPrest} onChange={v=>set("vTPrest",v)} type="number"/><Field label="Valor da carga" value={form.vCarga} onChange={v=>set("vCarga",v)} type="number"/><Field label="Peso / quantidade carga" value={form.qCarga} onChange={v=>set("qCarga",v)} type="number"/><Field label="Município início IBGE" value={form.munIniCodigo} onChange={v=>set("munIniCodigo",v)}/><Field label="Município início" value={form.munIniNome} onChange={v=>set("munIniNome",v)}/><Field label="UF início" value={form.ufIni} onChange={v=>set("ufIni",v)}/><Field label="Município fim IBGE" value={form.munFimCodigo} onChange={v=>set("munFimCodigo",v)}/><Field label="Município fim" value={form.munFimNome} onChange={v=>set("munFimNome",v)}/><Field label="UF fim" value={form.ufFim} onChange={v=>set("ufFim",v)}/><Field label="Série" value={form.series} onChange={v=>set("series",v)}/><Field label="Número" value={form.number} onChange={v=>set("number",v)} type="number"/></div></section>{actions("saas-cte-issue",ctePayload())}</>}
 {documentType==="MDF-e"&&<><section className={panel}><h2 className="font-semibold">Manifesto de transporte</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Transportadora" value={form.carrierId} onChange={v=>set("carrierId",v)}><option value="">Própria / manual</option>{carriers.map(x=><option key={x.id} value={x.id}>{x.legal_name}</option>)}</Select><Field label="RNTRC" value={form.rntrc} onChange={v=>set("rntrc",v)} placeholder={carrier?.rntrc}/><Field label="Placa" value={form.plate} onChange={v=>set("plate",v)} placeholder={carrier?.vehicle_plate}/><Field label="Condutor" value={form.driverName} onChange={v=>set("driverName",v)}/><Field label="CPF do condutor" value={form.driverCpf} onChange={v=>set("driverCpf",v)}/><Field label="Tara (kg)" value={form.tara} onChange={v=>set("tara",v)} type="number"/><Field label="Capacidade (kg)" value={form.capacity} onChange={v=>set("capacity",v)} type="number"/><Field label="Município carga IBGE" value={form.munIniCodigo} onChange={v=>set("munIniCodigo",v)}/><Field label="Município carga" value={form.munIniNome} onChange={v=>set("munIniNome",v)}/><Field label="Município descarga IBGE" value={form.unloadCode} onChange={v=>set("unloadCode",v)}/><Field label="Município descarga" value={form.unloadName} onChange={v=>set("unloadName",v)}/><Field label="UF final" value={form.ufFim} onChange={v=>set("ufFim",v)}/><Field label="Valor da carga" value={form.cargoValue} onChange={v=>set("cargoValue",v)} type="number"/><Field label="Peso da carga" value={form.cargoWeight} onChange={v=>set("cargoWeight",v)} type="number"/><Field label="Série" value={form.series} onChange={v=>set("series",v)}/><Field label="Número" value={form.number} onChange={v=>set("number",v)} type="number"/><div className="md:col-span-2"><label className="text-sm font-medium">Chaves NF-e/CT-e<textarea value={form.keys} onChange={e=>set("keys",e.target.value)} rows={4} className="mt-2 w-full rounded-md border border-[#cbd3dc] bg-white p-3 text-sm" placeholder="Uma chave de 44 dígitos por linha"/></label></div></div></section><div className="flex flex-wrap gap-3"><Button variant="outline" disabled={busy} onClick={()=>invoke("saas-mdfe-issue",{action:"status",data:{environment}})}>Testar SEFAZ</Button>{actions("saas-mdfe-issue",mdfePayload())}</div></>}
 </div><FiscalPreview documentType={documentType} environment={environment} profile={profile} form={form} customer={customer} product={product} service={service} dest={dest} result={result}/></div>
 <SaasEmissionHistory items={currentHistory} documentType={documentType}/></div>;
}

function FiscalPreview({documentType,environment,profile,form,customer,product,service,dest,result}:{documentType:string;environment:string;profile:any;form:any;customer:any;product:any;service:any;dest:any;result:any}){
 const payload=documentType==="NFS-e"?{...profile,serie:form.series,numero:form.number,descricao:service?.name||form.description,valor:Number(form.value||0),tomadorNome:customer?.legal_name,tomadorDocumento:customer?.tax_id,codigoTributacao:form.serviceCode}:documentType==="CT-e"?{...profile,serie:form.series,numero:form.number,natOp:"PRESTACAO DE SERVICO DE TRANSPORTE",vTPrest:Number(form.vTPrest||0),dest:{xNome:dest?.legal_name,CNPJ:String(dest?.tax_id||"").replace(/\D/g,""),xLgr:dest?.street,nro:dest?.street_number,xBairro:dest?.district,xMun:dest?.city,UF:dest?.state},cfopCte:form.cfopCte}:documentType==="MDF-e"?{...profile,serie:form.series,numero:form.number,natOp:"MANIFESTO DE DOCUMENTOS FISCAIS",valorCarga:Number(form.cargoValue||0),munDescargaNome:form.unloadName}: {cnpjEmitente:profile?.tax_id,razaoSocial:profile?.legal_name,nomeFantasia:profile?.trade_name,ie:profile?.state_registration,logradouro:profile?.street,numeroEndereco:profile?.street_number,bairro:profile?.district,nomeMunicipio:profile?.city,serie:form.series,numeroNota:form.number,destDocumento:customer?.tax_id,destNome:customer?.legal_name,destLogradouro:customer?.street,destNumero:customer?.street_number,destBairro:customer?.district,destMunicipio:customer?.city,destUF:customer?.state,codigoProduto:product?.code,produto:product?.name,ncm:product?.ncm,cfop:form.cfop,unidade:product?.unit||"UN",quantidade:Number(form.quantity||0),valorUnitario:Number(form.unitPrice||0)};
 const xml=result?.xml||result?.xmlAssinado;
 return <aside className="xl:sticky xl:top-[92px] space-y-3"><div className="flex flex-wrap justify-end gap-2"><button onClick={()=>printDanfe("live-danfe",`${documentType}-${form.number}`)} className="rounded-md border border-[#202833] bg-[#202833] px-3 py-2 text-xs font-semibold text-white">Imprimir / salvar PDF</button>{xml&&<button onClick={()=>downloadXml(xml,`${documentType}-${form.number}.xml`)} className="rounded-md border border-[#aeb8c5] bg-white px-3 py-2 text-xs font-semibold text-[#202833]">Baixar XML</button>}</div><SaasDanfePreview id="live-danfe" documentType={documentType} environment={environment} profile={profile} data={payload} result={result}/></aside>
}
