import { ChangeEvent, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";

const inputClass="mt-2 h-11 !border-[#d9e0e8] !bg-white !text-[#10203e] dark:!bg-white dark:!text-[#10203e]";
const panel="rounded-2xl border border-[#e0e5ec] bg-white p-6 md:p-7";
const defaults:any={business_mode:"mixed",tax_regime:"",crt:"1",state_registration:"",municipal_registration:"",cnae_primary:"",fiscal_environment:"homologation",legal_name:"",trade_name:"",tax_id:"",phone:"",email:"",postal_code:"",street:"",street_number:"",complement:"",district:"",city:"",state:"AL",city_ibge_code:"",default_cfop_in_state:"5102",default_cfop_out_state:"6102",default_nfse_service_code:"",default_iss_rate:"",series_nfe:"1",next_number_nfe:1,series_nfce:"1",next_number_nfce:1,series_nfse:"1",next_number_nfse:1,series_cte:"1",next_number_cte:1,series_mdfe:"1",next_number_mdfe:1};
function Field({label,k,form,setForm,type="text"}:{label:string;k:string;form:any;setForm:any;type?:string}){return <label className="text-sm font-medium text-[#263652]">{label}<Input type={type} value={form[k]??""} onChange={e=>setForm((p:any)=>({...p,[k]:e.target.value}))} className={inputClass}/></label>}
export default function SaasFiscalSettings({organizationId}:{organizationId:string|null}){
 const [form,setForm]=useState<any>(defaults),[cert,setCert]=useState(false),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false),[password,setPassword]=useState("");
 useEffect(()=>{if(!organizationId)return;(async()=>{const {data,error}=await supabase.functions.invoke("saas-fiscal-config",{body:{action:"get",organization_id:organizationId}});if(error){setMsg(error.message);return}setForm({...defaults,...(data?.profile||{})});setCert(Boolean(data?.certificate_configured));})()},[organizationId]);
 const save=async()=>{if(!organizationId)return;setSaving(true);setMsg("");const {data,error}=await supabase.functions.invoke("saas-fiscal-config",{body:{action:"save_profile",organization_id:organizationId,profile:form}});setSaving(false);if(error||data?.error)setMsg(data?.error||error?.message||"Erro ao salvar");else{setForm({...defaults,...data.profile});setMsg("Configuração fiscal salva.")}};
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!organizationId)return;if(!password){setMsg("Informe a senha do certificado antes de selecionar o arquivo.");return}const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(const b of bytes)binary+=String.fromCharCode(b);const base64=btoa(binary);setSaving(true);const {data,error}=await supabase.functions.invoke("saas-fiscal-config",{body:{action:"save_certificate",organization_id:organizationId,certificate_base64:base64,certificate_password:password}});setSaving(false);if(error||data?.error)setMsg(data?.error||error?.message||"Erro ao salvar certificado");else{setCert(true);setPassword("");setMsg(`Certificado configurado até ${new Date(data.certificate.expires_at).toLocaleDateString("pt-BR")}.`)}};
 return <div className="space-y-5 pb-10"><div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-[#10203e]">Configurações fiscais</h1><p className="mt-2 text-sm text-[#6d7a90]">Dados usados automaticamente em NF-e, NFC-e, NFS-e, CT-e e MDF-e.</p></div>{msg&&<div className="rounded-xl border border-[#d9e0e8] bg-white px-4 py-3 text-sm">{msg}</div>}
 <section className={panel}><h2 className="font-semibold">Empresa emitente</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Razão social" k="legal_name" form={form} setForm={setForm}/><Field label="Nome fantasia" k="trade_name" form={form} setForm={setForm}/><Field label="CNPJ" k="tax_id" form={form} setForm={setForm}/><Field label="Inscrição estadual" k="state_registration" form={form} setForm={setForm}/><Field label="Inscrição municipal" k="municipal_registration" form={form} setForm={setForm}/><Field label="CNAE principal" k="cnae_primary" form={form} setForm={setForm}/><label className="text-sm font-medium">Regime tributário<select value={form.tax_regime||""} onChange={e=>setForm((p:any)=>({...p,tax_regime:e.target.value}))} className="mt-2 h-11 w-full rounded-lg border border-[#d9e0e8] bg-white px-3"><option value="">Selecione</option><option value="simples">Simples Nacional</option><option value="presumido">Lucro Presumido</option><option value="real">Lucro Real</option><option value="mei">MEI</option></select></label><Field label="CRT" k="crt" form={form} setForm={setForm}/><label className="text-sm font-medium">Atividade principal<select value={form.business_mode||"mixed"} onChange={e=>setForm((p:any)=>({...p,business_mode:e.target.value}))} className="mt-2 h-11 w-full rounded-lg border border-[#d9e0e8] bg-white px-3"><option value="goods">Venda de produtos</option><option value="services">Prestação de serviços</option><option value="mixed">Produtos e serviços</option><option value="transport">Transporte</option><option value="communication">Comunicação</option></select></label></div></section>
 <section className={panel}><h2 className="font-semibold">Endereço do emitente</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="CEP" k="postal_code" form={form} setForm={setForm}/><div className="xl:col-span-2"><Field label="Logradouro" k="street" form={form} setForm={setForm}/></div><Field label="Número" k="street_number" form={form} setForm={setForm}/><Field label="Complemento" k="complement" form={form} setForm={setForm}/><Field label="Bairro" k="district" form={form} setForm={setForm}/><Field label="Cidade" k="city" form={form} setForm={setForm}/><Field label="UF" k="state" form={form} setForm={setForm}/><Field label="Código IBGE" k="city_ibge_code" form={form} setForm={setForm}/><Field label="Telefone" k="phone" form={form} setForm={setForm}/><Field label="E-mail" k="email" form={form} setForm={setForm}/></div></section>
 <section className={panel}><h2 className="font-semibold">Numeração e padrões</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Série NF-e" k="series_nfe" form={form} setForm={setForm}/><Field label="Próxima NF-e" k="next_number_nfe" form={form} setForm={setForm} type="number"/><Field label="Série NFC-e" k="series_nfce" form={form} setForm={setForm}/><Field label="Próxima NFC-e" k="next_number_nfce" form={form} setForm={setForm} type="number"/><Field label="Série NFS-e" k="series_nfse" form={form} setForm={setForm}/><Field label="Próxima NFS-e" k="next_number_nfse" form={form} setForm={setForm} type="number"/><Field label="Série CT-e" k="series_cte" form={form} setForm={setForm}/><Field label="Próximo CT-e" k="next_number_cte" form={form} setForm={setForm} type="number"/><Field label="Série MDF-e" k="series_mdfe" form={form} setForm={setForm}/><Field label="Próximo MDF-e" k="next_number_mdfe" form={form} setForm={setForm} type="number"/><Field label="CFOP padrão interno" k="default_cfop_in_state" form={form} setForm={setForm}/><Field label="CFOP padrão interestadual" k="default_cfop_out_state" form={form} setForm={setForm}/><Field label="Código NFS-e padrão" k="default_nfse_service_code" form={form} setForm={setForm}/><Field label="ISS padrão (%)" k="default_iss_rate" form={form} setForm={setForm} type="number"/></div></section>
 <section className={panel}><h2 className="font-semibold">Certificado digital A1</h2><p className="mt-2 text-sm text-[#6d7a90]">{cert?"Certificado configurado. Selecione outro arquivo para substituir.":"Nenhum certificado configurado."}</p><div className="mt-5 grid gap-4 md:grid-cols-[1fr_auto]"><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha do certificado" className="h-11 !bg-white !text-[#10203e]"/><label className="flex h-11 cursor-pointer items-center justify-center rounded-lg bg-[#10203e] px-5 text-sm font-semibold text-white">Selecionar A1<input type="file" accept=".pfx,.p12,application/x-pkcs12" className="hidden" onChange={upload}/></label></div></section>
 <div className="flex justify-end"><Button onClick={save} disabled={saving} className="h-11 bg-[#0b5bd7] px-6 text-white">{saving?"Salvando...":"Salvar configurações"}</Button></div></div>;
}