import { useState } from "react";

const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusLabel=(s:string)=>s==="authorized"?"Autorizada":s==="rejected"?"Rejeitada":s==="cancelled"?"Cancelada":s==="error"?"Erro":s;
const rejection=(x:any)=>x?.response?.protocol?.xMotivo||x?.response?.lot?.xMotivo||x?.response?.xMotivo||x?.response?.error||null;
const itemName=(x:any)=>x?.payload?.produto||x?.payload?.descricao||x?.payload?.proPred||x?.payload?.munDescargaNome||"Documento fiscal";
const originLabel=(x:any)=>x?.source==="imported"||x?.origin==="imported"?"Importada":"Emitida aqui";

export default function SaasEmissionHistory({items,documentType}:{items:any[];documentType:string}){
 const [selected,setSelected]=useState<any>(null);
 return <>
  <section className="rounded-lg border border-[#cfd6df] bg-white p-5 md:p-6">
   <div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Últimas emissões</h2><p className="mt-1 text-xs text-muted-foreground">Clique em uma linha para abrir os detalhes da nota.</p></div><span className="text-xs font-medium text-muted-foreground">{items.length} registro{items.length===1?"":"s"}</span></div>
   <div className="mt-4 overflow-x-auto rounded-md border border-[#d8dee6] bg-white">
    <table className="w-full min-w-[980px] text-left text-sm">
     <thead><tr><th className="px-4 py-3">Nº</th><th className="px-4 py-3">Série</th><th className="px-4 py-3">Destinatário</th><th className="px-4 py-3">Item / operação</th><th className="px-4 py-3">Origem</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Valor</th></tr></thead>
     <tbody>{items.length===0?<tr><td colSpan={7} className="px-4 py-10 text-center text-sm text-muted-foreground">Nenhuma emissão deste tipo.</td></tr>:items.slice(0,20).map(x=><tr key={x.id} onClick={()=>setSelected(x)} className="cursor-pointer border-t border-[#e1e5eb] transition-colors"><td className="px-4 py-3 font-semibold">{x.number||"—"}</td><td className="px-4 py-3">{x.series||"—"}</td><td className="max-w-[220px] truncate px-4 py-3">{x.recipient_name||"Sem destinatário"}</td><td className="max-w-[240px] truncate px-4 py-3 text-muted-foreground">{itemName(x)}</td><td className="px-4 py-3"><span className={`inline-flex rounded border px-2 py-1 text-[10px] font-semibold ${originLabel(x)==="Importada"?"border-blue-200 bg-blue-50 text-blue-700":"border-slate-200 bg-slate-50 text-slate-600"}`}>{originLabel(x)}</span></td><td className={`px-4 py-3 font-semibold ${x.status==="authorized"?"text-emerald-700":x.status==="rejected"||x.status==="error"?"text-red-700":"text-amber-700"}`}>{statusLabel(x.status)}</td><td className="px-4 py-3 text-right font-semibold">{money(x.total)}</td></tr>)}</tbody>
    </table>
   </div>
  </section>
  {selected&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/45 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-lg border border-[#cfd6df] bg-white shadow-2xl">
   <div className="flex items-start justify-between border-b border-[#d9dfe6] px-6 py-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-muted-foreground">{documentType} · Série {selected.series||"—"} · Nº {selected.number||"—"}</p><h3 className="mt-1 text-xl font-semibold">Prévia da emissão</h3></div><button onClick={()=>setSelected(null)} className="rounded-md border border-[#c8d0da] bg-white px-3 py-2 text-xs font-semibold text-[#202833]">Fechar</button></div>
   {selected.status==="rejected"&&<div className="mx-6 mt-5 rounded-md border border-red-300 bg-red-50 px-4 py-3"><p className="text-xs font-bold uppercase tracking-[.09em] text-red-700">Nota rejeitada</p><p className="mt-1 text-sm text-red-800">{rejection(selected)||"O autorizador rejeitou este documento. Consulte o retorno fiscal abaixo."}</p></div>}
   {originLabel(selected)==="Importada"&&<div className="mx-6 mt-5 rounded-md border border-blue-200 bg-blue-50 px-4 py-3"><p className="text-xs font-bold uppercase tracking-[.09em] text-blue-700">Nota importada</p><p className="mt-1 text-sm text-blue-800">Esta nota foi extraída da fonte fiscal da empresa e não foi emitida dentro deste sistema.</p></div>}
   <div className="p-6"><div className="rounded-md border border-[#cfd6df] bg-white"><div className="border-b border-dashed border-[#cfd6df] p-5 text-center"><p className="text-xs text-muted-foreground">{selected.environment==="production"?"Produção":"Homologação"}</p><h4 className="mt-2 text-lg font-semibold">{selected.payload?.nomeFantasia||selected.payload?.razaoSocial||"Documento fiscal"}</h4><p className="mt-1 text-xs text-muted-foreground">{selected.payload?.cnpjEmitente||""}</p></div><div className="grid gap-4 border-b border-dashed border-[#cfd6df] p-5 sm:grid-cols-2"><Info label="Destinatário" value={selected.recipient_name||"Sem destinatário"}/><Info label="Documento" value={selected.recipient_tax_id||"—"}/><Info label="Item / operação" value={itemName(selected)}/><Info label="Quantidade" value={selected.payload?.quantidade||"—"}/><Info label="CFOP" value={selected.payload?.cfop||selected.payload?.cfopCte||"—"}/><Info label="NCM" value={selected.payload?.ncm||"—"}/></div><div className="grid gap-4 p-5 sm:grid-cols-2"><Info label="Chave de acesso" value={selected.access_key||"—"}/><Info label="Protocolo" value={selected.protocol||"—"}/><Info label="Status" value={statusLabel(selected.status)}/><Info label="Origem" value={originLabel(selected)}/><Info label="Valor total" value={money(selected.total)}/></div></div>
    {selected.xml&&<button onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([selected.xml],{type:"application/xml"}));a.download=`${documentType}-${selected.number||"documento"}.xml`;a.click();URL.revokeObjectURL(a.href)}} className="mt-4 rounded-md bg-[#202833] px-4 py-2.5 text-sm font-semibold text-white">Baixar XML</button>}
   </div>
  </div></div>}
 </>
}
function Info({label,value}:{label:string;value:any}){return <div><p className="text-[9px] font-semibold uppercase tracking-[.1em] text-muted-foreground">{label}</p><p className="mt-1 break-all text-sm font-medium text-slate-800">{String(value??"—")}</p></div>}
