import { useState } from "react";

const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusLabel=(s:string)=>s==="authorized"?"Autorizada":s==="rejected"?"Rejeitada":s==="cancelled"?"Cancelada":s==="error"?"Erro":s;
const rejection=(x:any)=>x?.response?.protocol?.xMotivo||x?.response?.lot?.xMotivo||x?.response?.xMotivo||x?.response?.error||null;
const itemName=(x:any)=>x?.payload?.produto||x?.payload?.descricao||x?.payload?.proPred||x?.payload?.munDescargaNome||"Documento fiscal";

export default function SaasEmissionHistory({items,documentType}:{items:any[];documentType:string}){
 const [selected,setSelected]=useState<any>(null);
 return <>
  <section className="rounded-lg border border-[#cfd6df] bg-white p-5 md:p-6">
   <div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Últimas emissões</h2><p className="mt-1 text-xs text-muted-foreground">Clique em uma linha para abrir os detalhes da nota.</p></div><span className="text-xs font-medium text-muted-foreground">{items.length} registro{items.length===1?"":"s"}</span></div>
   <div className="mt-4 overflow-hidden rounded-md border border-[#d8dee6]">
    <div className="hidden grid-cols-[72px_78px_minmax(150px,1fr)_minmax(170px,1.2fr)_92px_110px] gap-3 bg-[#eef1f4] px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[.09em] text-muted-foreground md:grid"><span>Nº</span><span>Série</span><span>Destinatário</span><span>Item / operação</span><span>Status</span><span className="text-right">Valor</span></div>
    {items.length===0?<p className="px-4 py-8 text-center text-sm text-muted-foreground">Nenhuma emissão deste tipo.</p>:items.slice(0,20).map(x=><button key={x.id} onClick={()=>setSelected(x)} className="grid w-full gap-2 border-t border-[#e1e5eb] bg-white px-4 py-3 text-left text-sm first:border-t-0 hover:bg-[#f7f8fa] md:grid-cols-[72px_78px_minmax(150px,1fr)_minmax(170px,1.2fr)_92px_110px] md:items-center"><span className="font-semibold">{x.number||"—"}</span><span>{x.series||"—"}</span><span className="truncate">{x.recipient_name||"Sem destinatário"}</span><span className="truncate text-muted-foreground">{itemName(x)}</span><span className={`font-semibold ${x.status==="authorized"?"text-emerald-700":x.status==="rejected"||x.status==="error"?"text-red-700":"text-amber-700"}`}>{statusLabel(x.status)}</span><span className="font-semibold md:text-right">{money(x.total)}</span></button>)}
   </div>
  </section>
  {selected&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/45 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-lg border border-[#cfd6df] bg-white shadow-2xl">
   <div className="flex items-start justify-between border-b border-[#d9dfe6] px-6 py-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-muted-foreground">{documentType} · Série {selected.series||"—"} · Nº {selected.number||"—"}</p><h3 className="mt-1 text-xl font-semibold">Prévia da emissão</h3></div><button onClick={()=>setSelected(null)} className="rounded-md border border-[#c8d0da] bg-white px-3 py-2 text-xs font-semibold text-[#202833]">Fechar</button></div>
   {selected.status==="rejected"&&<div className="mx-6 mt-5 rounded-md border border-red-300 bg-red-50 px-4 py-3"><p className="text-xs font-bold uppercase tracking-[.09em] text-red-700">Nota rejeitada</p><p className="mt-1 text-sm text-red-800">{rejection(selected)||"O autorizador rejeitou este documento. Consulte o retorno fiscal abaixo."}</p></div>}
   <div className="p-6"><div className="rounded-md border border-[#cfd6df] bg-white"><div className="border-b border-dashed border-[#cfd6df] p-5 text-center"><p className="text-xs text-muted-foreground">{selected.environment==="production"?"Produção":"Homologação"}</p><h4 className="mt-2 text-lg font-semibold">{selected.payload?.nomeFantasia||selected.payload?.razaoSocial||"Documento fiscal"}</h4><p className="mt-1 text-xs text-muted-foreground">{selected.payload?.cnpjEmitente||""}</p></div><div className="grid gap-4 border-b border-dashed border-[#cfd6df] p-5 sm:grid-cols-2"><Info label="Destinatário" value={selected.recipient_name||"Sem destinatário"}/><Info label="Documento" value={selected.recipient_tax_id||"—"}/><Info label="Item / operação" value={itemName(selected)}/><Info label="Quantidade" value={selected.payload?.quantidade||"—"}/><Info label="CFOP" value={selected.payload?.cfop||selected.payload?.cfopCte||"—"}/><Info label="NCM" value={selected.payload?.ncm||"—"}/></div><div className="grid gap-4 p-5 sm:grid-cols-2"><Info label="Chave de acesso" value={selected.access_key||"—"}/><Info label="Protocolo" value={selected.protocol||"—"}/><Info label="Status" value={statusLabel(selected.status)}/><Info label="Valor total" value={money(selected.total)}/></div></div>
    {selected.xml&&<button onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([selected.xml],{type:"application/xml"}));a.download=`${documentType}-${selected.number||"documento"}.xml`;a.click();URL.revokeObjectURL(a.href)}} className="mt-4 rounded-md bg-[#202833] px-4 py-2.5 text-sm font-semibold text-white">Baixar XML</button>}
   </div>
  </div></div>}
 </>
}
function Info({label,value}:{label:string;value:any}){return <div><p className="text-[9px] font-semibold uppercase tracking-[.1em] text-muted-foreground">{label}</p><p className="mt-1 break-all text-sm font-medium text-slate-800">{String(value??"—")}</p></div>}
