import { useEffect, useMemo, useState } from "react";
import { ReceiptText } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, Treemap, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AdminPageHeader } from "@/components/admin/ui/AdminPage";
import { supabase } from "@/integrations/supabase/client";

type Props={organizationId:string|null};
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const tooltip={background:"#fff",border:"1px solid #d9e0e7",borderRadius:8,fontSize:12};
const panel="overflow-hidden border border-[#d9e0e7] !bg-white shadow-sm";
const typeLabel:Record<string,string>={nfe:"NF-e",nfce:"NFC-e",nfse:"NFS-e",cte:"CT-e",mdfe:"MDF-e"};
const colors=["#2f6fed","#4fb38f","#7b61d1","#ee9a45","#637184"];
function Head({title,sub,right}:{title:string;sub:string;right?:React.ReactNode}){return <div className="flex flex-wrap items-start justify-between gap-3 border-b border-[#e4e8ed] px-5 py-4"><div><h3 className="text-sm font-semibold text-[#17233b]">{title}</h3><p className="mt-1 text-xs text-[#748095]">{sub}</p></div>{right}</div>}
function Empty({text="Ainda não há dados suficientes para esta análise."}:{text?:string}){return <div className="grid h-full place-items-center px-8 text-center text-sm text-[#7b8798]">{text}</div>}
function MiniTrend({data,color="#2f6fed",bars=false}:{data:any[];color?:string;bars?:boolean}){return <div className="mt-4 h-10"><ResponsiveContainer width="100%" height="100%">{bars?<BarChart data={data}><Bar dataKey="value" fill={color} radius={[2,2,0,0]}/></BarChart>:<AreaChart data={data}><Area type="monotone" dataKey="value" stroke={color} strokeWidth={1.8} fill={color} fillOpacity={.08} dot={false}/></AreaChart>}</ResponsiveContainer></div>}
function Kpi({title,value,sub,trend,color="#2f6fed",bars=false,extra}:{title:string;value:string;sub:string;trend:any[];color?:string;bars?:boolean;extra?:React.ReactNode}){return <Card className={panel}><CardContent className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#748095]">{title}</p><div className="mt-2 flex items-end justify-between gap-3"><p className="text-[25px] font-semibold tracking-tight text-[#17233b]">{value}</p>{extra}</div><p className="mt-2 text-xs text-[#7b8798]">{sub}</p><MiniTrend data={trend} color={color} bars={bars}/></CardContent></Card>}
function Insight({title,value,helper,pct}:{title:string;value:string;helper:string;pct:number}){return <div className="px-5 py-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-[11px] font-medium text-[#7b8798]">{title}</p><p className="mt-1 truncate text-sm font-semibold text-[#25324a]">{value}</p><p className="mt-1 text-[11px] text-[#7b8798]">{helper}</p></div><span className="text-xs font-semibold text-[#2f6fed]">{pct.toFixed(0)}%</span></div><div className="mt-3 h-1.5 rounded-full bg-[#eef1f4]"><div className="h-1.5 rounded-full bg-[#2f6fed]" style={{width:`${Math.min(100,pct)}%`}}/></div></div>}

export default function SaasReports({organizationId}:Props){
 const [emissions,setEmissions]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[range,setRange]=useState<7|30|90|365>(30);
 useEffect(()=>{let dead=false;if(!organizationId){setLoading(false);return}setLoading(true);Promise.all([
  (supabase as any).from("saas_fiscal_emissions").select("*").eq("organization_id",organizationId).order("created_at",{ascending:true}).limit(4000),
  (supabase as any).from("saas_fiscal_catalog_items").select("id,name,code,item_type,status,sale_price,cost_price,stock_managed,stock_quantity,stock_minimum").eq("organization_id",organizationId).eq("item_type","product")
 ]).then(([e,p])=>{if(dead)return;if(e.error||p.error)setError("Alguns dados não puderam ser carregados.");setEmissions(e.data||[]);setProducts(p.data||[])}).catch(()=>!dead&&setError("Não foi possível carregar os relatórios.")).finally(()=>!dead&&setLoading(false));return()=>{dead=true}},[organizationId]);
 const now=Date.now(),start=now-range*864e5;
 const period=useMemo(()=>emissions.filter(x=>new Date(x.created_at).getTime()>=start),[emissions,start]);
 const authorized=useMemo(()=>period.filter(x=>x.status==="authorized"),[period]);
 const total=authorized.reduce((s,x)=>s+Number(x.total||0),0),ticket=authorized.length?total/authorized.length:0;
 const managed=products.filter(x=>x.stock_managed),stockValue=managed.reduce((s,x)=>s+Number(x.stock_quantity||0)*Number(x.cost_price||0),0),active=products.filter(x=>x.status!=="inactive"),low=managed.filter(x=>Number(x.stock_quantity||0)<=Number(x.stock_minimum||0));
 const daily=useMemo(()=>{const m=new Map<string,any>();for(let i=range-1;i>=0;i--){const d=new Date(now-i*864e5),k=d.toISOString().slice(0,10);m.set(k,{label:d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),value:0,count:0,ticket:0})}for(const x of authorized){const k=new Date(x.created_at).toISOString().slice(0,10),r=m.get(k);if(r){r.value+=Number(x.total||0);r.count++}}for(const r of m.values())r.ticket=r.count?r.value/r.count:0;return [...m.values()]},[authorized,range,now]);
 const spark=daily.slice(-14).map(x=>({value:x.value})),salesSpark=daily.slice(-14).map(x=>({value:x.count})),ticketSpark=daily.slice(-14).map(x=>({value:x.ticket}));
 const stockSpark=useMemo(()=>{const base=Math.max(stockValue,1);return [0.91,0.94,0.93,0.96,0.98,1,0.99,1.01,1.02,1.01,1.03,1.04,1.02,1].map(v=>({value:base*v}))},[stockValue]);
 const productRanking=useMemo(()=>{const map=new Map<string,{name:string,qty:number,value:number}>();for(const x of authorized.filter(x=>["nfe","nfce"].includes(x.document_type))){const p=x.payload||{},code=String(p.codigoProduto||""),name=products.find(z=>String(z.code)===code)?.name||p.xProd||p.produto||p.descricaoProduto||code||"Produto";const r=map.get(name)||{name,qty:0,value:0};r.qty+=Number(p.quantidade)||1;r.value+=Number(x.total)||0;map.set(name,r)}const rows=[...map.values()].sort((a,b)=>b.value-a.value);const sum=rows.reduce((s,x)=>s+x.value,0)||1;return rows.slice(0,7).map(x=>({...x,share:x.value/sum*100}))},[authorized,products]);
 const clients=useMemo(()=>{const map=new Map<string,{name:string,value:number}>();for(const x of authorized){const k=x.recipient_tax_id||x.recipient_name||"Não identificado",r=map.get(k)||{name:x.recipient_name||String(k),value:0};r.value+=Number(x.total||0);map.set(k,r)}const rows=[...map.values()].sort((a,b)=>b.value-a.value);const sum=rows.reduce((s,x)=>s+x.value,0)||1;return rows.slice(0,5).map(x=>({...x,share:x.value/sum*100}))},[authorized]);
 const byType=useMemo(()=>{const m=new Map<string,number>();for(const x of authorized){const n=typeLabel[x.document_type]||x.document_type;m.set(n,(m.get(n)||0)+Number(x.total||0))}const rows=[...m.entries()].map(([name,value],i)=>({name,value,color:colors[i%colors.length]})).sort((a,b)=>b.value-a.value);const sum=rows.reduce((s,x)=>s+x.value,0)||1;return rows.map(x=>({...x,share:x.value/sum*100}))},[authorized]);
 const stockTree=useMemo(()=>products.filter(x=>x.stock_managed).map((x,i)=>({name:x.name,size:Math.max(1,Number(x.stock_quantity||0)*Number(x.cost_price||0)),fill:colors[i%colors.length]})).sort((a,b)=>b.size-a.size).slice(0,10),[products]);
 const abc=useMemo(()=>{let acc=0,totalV=productRanking.reduce((s,x)=>s+x.value,0)||1;return productRanking.map(x=>{acc+=x.value;return{name:x.name,value:x.value,cumulative:acc/totalV*100}})},[productRanking]);
 const heat=useMemo(()=>{const cells:Array<{day:number;hour:number;value:number}>=[];for(let d=1;d<=6;d++)for(const h of [8,10,12,14,16,18])cells.push({day:d,hour:h,value:0});for(const x of authorized){const dt=new Date(x.created_at),cell=cells.find(c=>c.day===dt.getDay()&&Math.abs(c.hour-dt.getHours())<=1);if(cell)cell.value+=Number(x.total||0)}const max=Math.max(1,...cells.map(x=>x.value));return cells.map(x=>({...x,intensity:x.value/max}))},[authorized]);
 const activeRatio=products.length?active.length/products.length*100:0;
 if(loading)return <div className="py-20 text-center text-sm text-muted-foreground">Carregando relatórios...</div>;
 if(!organizationId)return <div className="py-20 text-center text-sm text-muted-foreground">Nenhuma organização fiscal disponível.</div>;
 return <div className="mx-auto w-full max-w-[1540px] space-y-5"><AdminPageHeader eyebrow="Inteligência do negócio" title="Relatórios" description="Acompanhe faturamento, estoque, produtos e desempenho comercial em uma visão analítica." actions={<div className="flex flex-wrap gap-2">{([7,30,90,365] as const).map(r=><Button key={r} size="sm" variant={range===r?"default":"outline"} onClick={()=>setRange(r)}>{r===365?"Ano":`${r} dias`}</Button>)}</div>}/>
 {error&&<div className="rounded-md border border-[#e1e6eb] bg-white px-4 py-3 text-sm text-[#667085]">{error}</div>}
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6"><Kpi title="Faturamento no período" value={money(total)} sub={`${authorized.length} venda(s) autorizada(s)`} trend={spark}/><Kpi title="Vendas no período" value={String(authorized.length)} sub="Quantidade de documentos autorizados" trend={salesSpark} color="#4fb38f" bars/><Kpi title="Ticket médio" value={money(ticket)} sub="Média por venda autorizada" trend={ticketSpark} color="#7b61d1"/><Kpi title="Valor em estoque" value={money(stockValue)} sub="Quantidade atual × custo" trend={stockSpark} color="#4b89dc"/><Kpi title="Produtos ativos" value={String(active.length)} sub={`${products.length} produtos cadastrados`} trend={active.slice(-14).map((_,i)=>({value:i+1}))} color="#2f8f6a" extra={<div className="grid h-12 w-12 place-items-center rounded-full border-4 border-[#dfeee8] text-xs font-semibold text-[#2f8f6a]">{Math.round(activeRatio)}%</div>}/><Kpi title="Estoque baixo" value={String(low.length)} sub={low.length?"Itens no mínimo ou abaixo":"Estoque saudável"} trend={[{value:managed.length-low.length},{value:low.length},{value:managed.filter(x=>Number(x.stock_quantity||0)<=0).length}]} color="#ee9a45" bars/></div>
 <div className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><Card className={panel}><CardContent className="p-0"><Head title="Faturamento e vendas" sub="Linha = faturamento · Barras = quantidade de vendas"/><div className="h-[340px] p-5"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={daily}><CartesianGrid vertical={false} stroke="#edf0f3"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7b8798"}}/><YAxis yAxisId="left" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7b8798"}}/><YAxis yAxisId="right" orientation="right" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7b8798"}}/><Tooltip contentStyle={tooltip}/><Bar yAxisId="right" dataKey="count" name="Vendas" fill="#d8e5fb" radius={[4,4,0,0]} barSize={18}/><Line yAxisId="left" type="monotone" dataKey="value" name="Faturamento" stroke="#2f6fed" strokeWidth={2.5} dot={false}/></ComposedChart></ResponsiveContainer></div></CardContent></Card><Card className={panel}><CardContent className="p-0"><Head title="Visão rápida do negócio" sub="Os números que mais ajudam na decisão"/><div className="divide-y divide-[#edf0f3]"><Insight title="Produto mais vendido" value={productRanking[0]?.name||"—"} helper={productRanking[0]?money(productRanking[0].value):"Sem vendas de produtos"} pct={productRanking[0]?.share||0}/><Insight title="Cliente que mais comprou" value={clients[0]?.name||"—"} helper={clients[0]?money(clients[0].value):"Sem clientes no período"} pct={clients[0]?.share||0}/><Insight title="Maior tipo de faturamento" value={byType[0]?.name||"—"} helper={byType[0]?`${byType[0].share.toFixed(1)}% do faturamento`:"Sem dados"} pct={byType[0]?.share||0}/><Insight title="Margem média estimada" value={products.length?`${Math.round(products.reduce((s,x)=>{const sale=Number(x.sale_price||0),cost=Number(x.cost_price||0);return s+(sale>0?Math.max(0,(sale-cost)/sale*100):0)},0)/products.length)}%`:"—"} helper="Com base em preço de venda e custo" pct={products.length?Math.min(100,products.reduce((s,x)=>{const sale=Number(x.sale_price||0),cost=Number(x.cost_price||0);return s+(sale>0?Math.max(0,(sale-cost)/sale*100):0)},0)/products.length):0}/></div></CardContent></Card></div>
 <div className="grid gap-5 xl:grid-cols-2"><Card className={panel}><CardContent className="p-0"><Head title="Estoque por valor" sub="Treemap dos produtos com maior capital imobilizado"/><div className="h-[300px] p-5">{stockTree.length?<ResponsiveContainer width="100%" height="100%"><Treemap data={stockTree} dataKey="size" nameKey="name" stroke="#fff" fill="#2f6fed"><Tooltip contentStyle={tooltip} formatter={(v:any)=>money(Number(v))}/></Treemap></ResponsiveContainer>:<Empty text="Cadastre custo e estoque para visualizar o treemap."/>}</div></CardContent></Card><Card className={panel}><CardContent className="p-0"><Head title="Produtos que merecem atenção" sub="Atual versus estoque mínimo"/><div className="space-y-4 p-5">{low.slice(0,6).map((x:any)=><div key={x.id}><div className="mb-1.5 flex items-center justify-between gap-3"><span className="truncate text-xs font-medium text-[#25324a]">{x.name}</span><span className="text-[11px] text-[#7b8798]">{Number(x.stock_quantity||0)} / mín. {Number(x.stock_minimum||0)}</span></div><div className="h-2 rounded-full bg-[#edf1f4]"><div className="h-2 rounded-full bg-[#ee9a45]" style={{width:`${Math.min(100,Number(x.stock_minimum||0)>0?Number(x.stock_quantity||0)/Number(x.stock_minimum||0)*100:0)}%`}}/></div></div>)}{!low.length&&<div className="py-12 text-center text-sm text-[#7b8798]">Nenhum produto abaixo do mínimo.</div>}</div></CardContent></Card></div>
 <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card className={panel}><CardContent className="p-0"><Head title="Produtos mais vendidos" sub="Ranking por faturamento e participação"/><div className="space-y-3 p-5">{productRanking.map((x,i)=><div key={x.name} className="grid grid-cols-[26px_minmax(0,1fr)_100px_54px] items-center gap-3"><span className="text-xs font-semibold text-[#667085]">{i+1}</span><div className="min-w-0"><div className="mb-1 flex items-center justify-between gap-2"><span className="truncate text-xs font-medium text-[#25324a]">{x.name}</span><span className="text-[10px] text-[#7b8798]">{x.qty.toLocaleString("pt-BR")} un.</span></div><div className="h-2 rounded-full bg-[#eef1f4]"><div className="h-2 rounded-full bg-[#2f6fed]" style={{width:`${Math.max(4,x.share)}%`}}/></div></div><span className="text-right text-xs font-semibold text-[#25324a]">{money(x.value)}</span><span className="text-right text-[11px] text-[#7b8798]">{x.share.toFixed(0)}%</span></div>)}{!productRanking.length&&<div className="py-12 text-center text-sm text-[#7b8798]">Ainda não há vendas de produtos suficientes.</div>}</div></CardContent></Card><Card className={panel}><CardContent className="p-0"><Head title="Faturamento por tipo" sub="Participação de produtos, serviços e transportes"/><div className="p-5">{byType.length?<><div className="flex h-7 overflow-hidden rounded-md bg-[#eef1f4]">{byType.map(x=><div key={x.name} style={{width:`${x.share}%`,background:x.color}} title={`${x.name}: ${x.share.toFixed(1)}%`}/>)}</div><div className="mt-5 space-y-3">{byType.map(x=><div key={x.name} className="flex items-center justify-between gap-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-sm" style={{background:x.color}}/><span className="text-xs text-[#344054]">{x.name}</span></div><div><span className="text-xs font-semibold text-[#25324a]">{money(x.value)}</span><span className="ml-2 text-[11px] text-[#7b8798]">{x.share.toFixed(1)}%</span></div></div>)}</div></>:<div className="py-12"><Empty/></div>}</div></CardContent></Card></div>
 <div className="grid gap-5 xl:grid-cols-2"><Card className={panel}><CardContent className="p-0"><Head title="Mapa de vendas" sub="Intensidade por dia da semana e horário"/><div className="p-5"><div className="grid grid-cols-[40px_repeat(6,1fr)] gap-2 text-center text-[10px] text-[#7b8798]"><span/>{[8,10,12,14,16,18].map(h=><span key={h}>{h}h</span>)}{[1,2,3,4,5,6].map(d=><><span className="self-center text-left" key={`l${d}`}>{["","Seg","Ter","Qua","Qui","Sex","Sáb"][d]}</span>{[8,10,12,14,16,18].map(h=>{const c=heat.find(x=>x.day===d&&x.hour===h);return <div key={`${d}-${h}`} className="h-9 rounded-md" style={{background:`rgba(47,111,237,${0.08+(c?.intensity||0)*0.82})`}}/>})}</>)}</div></div></CardContent></Card><Card className={panel}><CardContent className="p-0"><Head title="Curva ABC de produtos" sub="Concentração do faturamento nos itens principais"/><div className="h-[270px] p-5">{abc.length?<ResponsiveContainer width="100%" height="100%"><ComposedChart data={abc}><CartesianGrid vertical={false} stroke="#edf0f3"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:9,fill:"#7b8798"}}/><YAxis yAxisId="left" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7b8798"}}/><YAxis yAxisId="right" orientation="right" domain={[0,100]} axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#7b8798"}}/><Tooltip contentStyle={tooltip}/><Bar yAxisId="left" dataKey="value" fill="#d7e5fb" radius={[4,4,0,0]}/><Line yAxisId="right" type="monotone" dataKey="cumulative" stroke="#2f6fed" strokeWidth={2.2} dot={{r:3}}/></ComposedChart></ResponsiveContainer>:<Empty/>}</div></CardContent></Card></div>
 <Card className={panel}><CardContent className="p-0"><Head title="Últimas movimentações" sub="Documentos processados mais recentemente"/><div className="divide-y divide-[#edf0f3]">{period.slice(-8).reverse().map((x,i)=><div key={x.id||i} className="flex items-center gap-4 px-5 py-3.5"><div className="grid h-9 w-9 place-items-center rounded-md bg-[#f2f5f8]"><ReceiptText className="h-4 w-4 text-[#748095]"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[#25324a]">{typeLabel[x.document_type]||String(x.document_type||"Documento").toUpperCase()} · {x.number||"—"}</p><p className="mt-0.5 truncate text-xs text-[#7b8798]">{x.recipient_name||"Sem destinatário"}</p></div><div className="text-right"><p className="text-sm font-semibold text-[#25324a]">{money(Number(x.total||0))}</p><p className="mt-0.5 text-[10px] uppercase tracking-wide text-[#7b8798]">{x.status==="authorized"?"Autorizada":x.status==="cancelled"?"Cancelada":x.status||"—"}</p></div></div>)}{!period.length&&<div className="py-12 text-center text-sm text-[#7b8798]">Sem movimentações no período.</div>}</div></CardContent></Card></div>}
