import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.0";

const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
const prices: Record<string, { input: number; cached: number; output: number }> = {
  "gpt-5.6-sol": { input: 5, cached: 0.5, output: 30 }, "gpt-5.6": { input: 5, cached: 0.5, output: 30 },
  "gpt-5.6-terra": { input: 2, cached: 0.2, output: 12 }, "gpt-5.6-luna": { input: 0.2, cached: 0.02, output: 1.2 },
};
const eventTypes = ["salary_gross", "prolabore_gross", "advance_compensation", "inss_payroll", "inss_prolabore", "irrf_payroll", "irrf_prolabore", "benefit_meal", "benefit_health", "benefit_dental", "vacation_gross", "inss_vacation", "inss_vacation_future", "irrf_vacation", "fgts_payroll", "fgts_vacation", "thirteenth_gross", "inss_thirteenth", "fgts_thirteenth", "other_earning", "other_discount"] as const;
const totalKeys = ["total_proventos", "total_descontos", "liquido", "folha_proventos", "ferias_proventos", "adiantamento", "prolabore", "inss_total", "irrf_total", "fgts_total", "vale_alimentacao", "plano_saude", "plano_odontologico"] as const;
type EventType = typeof eventTypes[number]; type TotalKey = typeof totalKeys[number];
type Account = { reducedCode: string; description: string; analytical?: boolean; account?: string };
type Entry = { id?: string; date: string; history: string; eventType: EventType; debitCode: string; debitDescription: string; debitCostCenter: string; creditCode: string; creditDescription: string; creditCostCenter: string; amountInCents: number; source: string; confidence: number };
type DocumentTotal = { key: TotalKey; label: string; amountInCents: number; source: string };
const estimateCost = (model: string, usage: any) => { const price = prices[model]; if (!price) return 0; const cached = Number(usage?.input_tokens_details?.cached_tokens ?? 0); const input = Math.max(0, Number(usage?.input_tokens ?? 0) - cached); return (input * price.input + cached * price.cached + Number(usage?.output_tokens ?? 0) * price.output) / 1_000_000 };
const normalize = (value: unknown) => String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-zA-Z0-9]+/g, " ").trim().toLowerCase();
const sum = (entries: Entry[], types: EventType[]) => entries.filter((entry) => types.includes(entry.eventType)).reduce((total, entry) => total + entry.amountInCents, 0);
const historyFor = (eventType: EventType, competence: string) => ({
  salary_gross: `SALÁRIOS E REMUNERAÇÕES A PAGAR MÊS ${competence}`, prolabore_gross: `PRÓ-LABORE A PAGAR MÊS ${competence}`,
  advance_compensation: `ADIANTAMENTO DE SALÁRIO COMPENSADO MÊS ${competence}`, inss_payroll: `INSS S/SALÁRIOS A PAGAR MÊS ${competence}`,
  inss_prolabore: `INSS S/PRÓ-LABORE (SÓCIO) A PAGAR MÊS ${competence}`, irrf_payroll: `IRRF S/SALÁRIOS A PAGAR MÊS ${competence}`,
  irrf_prolabore: `IRRF S/PRÓ-LABORE (SÓCIO) A PAGAR MÊS ${competence}`, benefit_meal: `DESCONTO DE VALE-ALIMENTAÇÃO MÊS ${competence}`,
  benefit_health: `DESCONTO DE PLANO DE SAÚDE MÊS ${competence}`, benefit_dental: `DESCONTO DE PLANO ODONTOLÓGICO MÊS ${competence}`,
  vacation_gross: `FÉRIAS A PAGAR MÊS ${competence}`, inss_vacation: `INSS S/FÉRIAS A PAGAR MÊS ${competence}`, inss_vacation_future: `INSS S/FÉRIAS A PAGAR EM COMPETÊNCIA POSTERIOR À ${competence}`,
  irrf_vacation: `IRRF S/FÉRIAS A PAGAR MÊS ${competence}`, fgts_payroll: `FGTS A PAGAR MÊS ${competence}`,
  fgts_vacation: `FGTS S/FÉRIAS A PAGAR MÊS ${competence}`, thirteenth_gross: `13º SALÁRIO A PAGAR MÊS ${competence}`,
  inss_thirteenth: `INSS S/13º A PAGAR MÊS ${competence}`, fgts_thirteenth: `FGTS S/13º A PAGAR MÊS ${competence}`,
  other_earning: `OUTROS PROVENTOS DA FOLHA MÊS ${competence}`, other_discount: `OUTROS DESCONTOS DA FOLHA MÊS ${competence}`,
}[eventType]);
function findAccount(accounts: Account[], alternatives: string[][], accountPrefix?: string) { const ranked = accounts.filter((account) => account.analytical !== false && account.reducedCode && (!accountPrefix || String(account.account ?? "").startsWith(accountPrefix))).map((account) => ({ account, normalized: normalize(account.description) })); for (const terms of alternatives) { const match = ranked.find(({ normalized }) => terms.every((term) => normalized.includes(normalize(term)))); if (match) return match.account } return undefined }
function semanticAccounts(accounts: Account[]) { return {
  salaryPayable: findAccount(accounts, [["salarios", "remuneracoes", "pagar"], ["salarios", "pagar"]], "2") ?? findAccount(accounts, [["salarios", "remuneracoes", "pagar"], ["salarios", "pagar"]]),
  prolaborePayable: findAccount(accounts, [["pro labore", "pagar"], ["pro labore"]], "2") ?? findAccount(accounts, [["pro labore", "pagar"], ["pro labore"]]),
  salaryExpense: findAccount(accounts, [["salarios", "ordenados"], ["salarios", "remuneracoes"], ["salarios"]], "4"), prolaboreExpense: findAccount(accounts, [["pro labore"]], "4"),
  vacationExpense: findAccount(accounts, [["ferias"]], "4"), thirteenthExpense: findAccount(accounts, [["13", "salario"], ["decimo", "terceiro"]], "4"), fgtsExpense: findAccount(accounts, [["fgts"]], "4"),
  advance: findAccount(accounts, [["adiantamentos", "funcionarios"], ["adiantamento", "funcionario"]]), inssPayable: findAccount(accounts, [["inss", "recolher"], ["inss", "pagar"]]),
  irrfPayable: findAccount(accounts, [["irrf", "recolher"], ["irrf", "pagar"]]), fgtsPayable: findAccount(accounts, [["fgts", "recolher"], ["fgts", "pagar"]]),
  meal: findAccount(accounts, [["alimentacao", "trabalhador"], ["vale", "alimentacao"], ["vale", "refeicao"]]), health: findAccount(accounts, [["assistencia", "medica", "odontologica"], ["plano", "saude"], ["assistencia", "medica"]]),
} }
function applyDeterministicRules(rawEntries: Entry[], accounts: Account[], competence: string) {
  const semantic = semanticAccounts(accounts); const accountMap = new Map(accounts.map((account) => [String(account.reducedCode), account])); const warnings: string[] = [];
  const [competenceMonth, competenceYear] = competence.split("/").map(Number); const accountingDate = competenceMonth && competenceYear ? new Date(competenceYear, competenceMonth, 0).toLocaleDateString("pt-BR") : ""; const futureDate = competenceMonth && competenceYear ? new Date(competenceYear, competenceMonth, 1) : null; const futureCompetence = futureDate ? `${String(futureDate.getMonth() + 1).padStart(2, "0")}/${futureDate.getFullYear()}` : competence;
  const entries = rawEntries.map((raw) => { const entry: Entry = { ...raw, date: accountingDate || raw.date, history: raw.eventType === "inss_vacation_future" ? `INSS S/FÉRIAS A PAGAR MÊS ${futureCompetence}` : historyFor(raw.eventType, competence), amountInCents: Math.trunc(raw.amountInCents) }; const setDebit = (account?: Account) => { if (account) entry.debitCode = account.reducedCode }; const setCredit = (account?: Account) => { if (account) entry.creditCode = account.reducedCode };
    if (entry.eventType === "salary_gross") setDebit(semantic.salaryExpense); if (entry.eventType === "prolabore_gross") setDebit(semantic.prolaboreExpense); if (entry.eventType === "vacation_gross") setDebit(semantic.vacationExpense); if (entry.eventType === "thirteenth_gross") setDebit(semantic.thirteenthExpense);
    if (["fgts_payroll", "fgts_vacation", "fgts_thirteenth"].includes(entry.eventType)) setDebit(semantic.fgtsExpense);
    if (["salary_gross", "vacation_gross", "thirteenth_gross"].includes(entry.eventType)) setCredit(semantic.salaryPayable); if (entry.eventType === "prolabore_gross") setCredit(semantic.prolaborePayable);
    if (entry.eventType === "advance_compensation") { setDebit(semantic.salaryPayable); setCredit(semantic.advance) }
    if (["inss_payroll", "irrf_payroll", "benefit_meal", "benefit_health", "benefit_dental", "inss_vacation", "inss_vacation_future", "irrf_vacation", "inss_thirteenth"].includes(entry.eventType)) setDebit(semantic.salaryPayable);
    if (["inss_prolabore", "irrf_prolabore"].includes(entry.eventType)) setDebit(semantic.prolaborePayable); if (["inss_payroll", "inss_prolabore", "inss_vacation", "inss_vacation_future", "inss_thirteenth"].includes(entry.eventType)) setCredit(semantic.inssPayable);
    if (["irrf_payroll", "irrf_prolabore", "irrf_vacation"].includes(entry.eventType)) setCredit(semantic.irrfPayable); if (["fgts_payroll", "fgts_vacation", "fgts_thirteenth"].includes(entry.eventType)) setCredit(semantic.fgtsPayable);
    if (entry.eventType === "benefit_meal") setCredit(semantic.meal); if (["benefit_health", "benefit_dental"].includes(entry.eventType)) setCredit(semantic.health);
    const debit = accountMap.get(String(entry.debitCode)); const credit = accountMap.get(String(entry.creditCode)); entry.debitDescription = debit?.description ?? ""; entry.creditDescription = credit?.description ?? "";
    if (!debit || !credit) warnings.push(`Revise o lançamento “${entry.history}”: não foi possível localizar uma conta analítica compatível no plano da empresa.`); return { ...entry, id: crypto.randomUUID() } });
  return { entries, warnings: [...new Set(warnings)] };
}
function calculatedTotals(entries: Entry[]) { const earnings = sum(entries, ["advance_compensation", "salary_gross", "prolabore_gross", "vacation_gross", "thirteenth_gross", "other_earning"]); const deductions = sum(entries, ["advance_compensation", "inss_payroll", "inss_prolabore", "irrf_payroll", "irrf_prolabore", "benefit_meal", "benefit_health", "benefit_dental", "inss_vacation", "inss_vacation_future", "irrf_vacation", "inss_thirteenth", "other_discount"]); return {
  total_proventos: earnings, total_descontos: deductions, liquido: earnings - deductions, folha_proventos: sum(entries, ["salary_gross", "prolabore_gross"]), ferias_proventos: sum(entries, ["vacation_gross"]), adiantamento: sum(entries, ["advance_compensation"]), prolabore: sum(entries, ["prolabore_gross"]),
  inss_total: sum(entries, ["inss_payroll", "inss_prolabore", "inss_vacation", "inss_thirteenth"]), irrf_total: sum(entries, ["irrf_payroll", "irrf_prolabore", "irrf_vacation"]), fgts_total: sum(entries, ["fgts_payroll", "fgts_vacation", "fgts_thirteenth"]), vale_alimentacao: sum(entries, ["benefit_meal"]), plano_saude: sum(entries, ["benefit_health"]), plano_odontologico: sum(entries, ["benefit_dental"]),
} satisfies Record<TotalKey, number> }
function validate(entries: Entry[], documentTotals: DocumentTotal[]) { const calculated = calculatedTotals(entries); const comparisons = documentTotals.map((total) => ({ key: total.key, label: total.label, documentAmountInCents: total.amountInCents, entriesAmountInCents: calculated[total.key], differenceInCents: calculated[total.key] - total.amountInCents, source: total.source })); const issues = comparisons.filter((row) => row.differenceInCents !== 0).map((row) => `${row.label}: diferença de ${(row.differenceInCents / 100).toFixed(2)}.`); entries.forEach((entry) => { if (!entry.debitCode || !entry.creditCode || !entry.debitDescription || !entry.creditDescription) issues.push(`${entry.history}: conta incompleta.`); if (!Number.isInteger(entry.amountInCents) || entry.amountInCents <= 0) issues.push(`${entry.history}: valor inválido.`) }); if (!documentTotals.length) issues.push("O documento não devolveu totais suficientes para a conferência automática."); return { comparisons, issues: [...new Set(issues)], passed: issues.length === 0 } }
const actionableWarnings = (warnings: unknown[]) => warnings.map(String).filter((warning) => { const text = normalize(warning); return !text.includes("nao ha comprovante") && !text.includes("nao foram gerados lancamentos de pgto") && !text.includes("para evitar duplicidade") });

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: cors }); const startedAt = Date.now(); let admin: any = null; let userId: string | null = null; let body: any = {};
  const fastModel = Deno.env.get("OPENAI_ACCOUNTING_FAST_MODEL") || "gpt-5.6-luna"; const reviewModel = Deno.env.get("OPENAI_ACCOUNTING_REVIEW_MODEL") || "gpt-5.6-terra";
  const recordUsage = async (raw: any, status: "success" | "error", requestedModel: string, metadata: Record<string, unknown> = {}) => { if (!admin) return; const usage = raw?.usage ?? {}; const { error } = await admin.from("accounting_ai_usage").insert({ created_by: userId, company_key: body.company_id ? String(body.company_id) : null, competence: body.competence ? String(body.competence) : null, module: body.module || "folha", provider: "openai", model: raw?.model || requestedModel, status, response_id: raw?.id ?? null, input_tokens: usage.input_tokens ?? 0, cached_input_tokens: usage.input_tokens_details?.cached_tokens ?? 0, output_tokens: usage.output_tokens ?? 0, total_tokens: usage.total_tokens ?? 0, estimated_cost_usd: estimateCost(raw?.model || requestedModel, usage), latency_ms: Date.now() - startedAt, error_code: raw?.error?.code ?? raw?.error?.type ?? null, error_message: raw?.error?.message ?? null, request_metadata: { document_count: Array.isArray(body.documents) ? body.documents.length : 0, requested_model: requestedModel, ...metadata } }); if (error) console.error("Falha ao registrar telemetria", error) };
  try {
    const auth = req.headers.get("Authorization"); if (!auth) return json({ error: "Não autenticado" }, 401); admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!); const { data: { user } } = await admin.auth.getUser(auth.replace("Bearer ", "")); if (!user) return json({ error: "Não autenticado" }, 401); userId = user.id;
    const { data: roles } = await admin.from("user_roles").select("role").eq("user_id", user.id); if (!roles?.some((row: any) => ["admin", "fiscal", "contabil", "geral"].includes(row.role))) return json({ error: "Acesso negado" }, 403);
    body = await req.json(); if (body.module !== "folha") return json({ error: "Módulo ainda não habilitado" }, 400); if (!Array.isArray(body.documents) || !body.documents.length) return json({ error: "Nenhum documento" }, 400); const apiKey = Deno.env.get("OPENAI_API_KEY"); if (!apiKey) return json({ error: "A chave OPENAI_API_KEY ainda não foi configurada no Supabase." }, 503); const accounts: Account[] = body.chart_of_accounts ?? []; if (!accounts.length) return json({ error: "Importe o plano de contas da empresa antes de processar a folha." }, 422);
    const fileInputs = body.documents.map((document: any) => ({ type: "input_file", filename: document.name, file_data: `data:${document.mime_type};base64,${document.data}` }));
    const payrollTerms = ["salario", "remuneracao", "pro labore", "inss", "irrf", "fgts", "ferias", "decimo", "13", "adiantamento", "alimentacao", "refeicao", "assistencia medica", "odontologica", "outras obrigacoes", "ordenados", "encargos sociais"];
    const relevantAccounts = accounts.filter((account) => account.analytical !== false && payrollTerms.some((term) => normalize(account.description).includes(normalize(term))));
    const prompt = `Você é um extrator contábil brasileiro especializado em folha de pagamento. Leia somente fatos presentes nos documentos da competência ${body.competence}.
Regras obrigatórias:
1. Preserve cada centavo exatamente. Nunca estime, arredonde, compense ou invente valores.
2. Classifique cada lançamento com um eventType da lista fornecida. Separe pró-labore de salários e separe vale-alimentação, plano de saúde e plano odontológico em lançamentos individuais. Quando o demonstrativo de férias dividir o INSS entre a competência atual e uma competência futura, crie inss_vacation para a parcela atual e inss_vacation_future para a parcela futura; a soma das duas precisa corresponder ao desconto de INSS das férias.
3. Para pró-labore, use a conta específica de pró-labore a pagar; nunca salários a pagar.
4. Para descontos de benefícios, prefira as contas específicas de alimentação e assistência médica/odontológica do plano; nunca use Outras Obrigações quando existir conta específica.
5. Não crie pagamentos, banco ou caixa sem comprovante expresso de pagamento. Não explique essa ausência em warnings.
6. Registre apenas a constituição do FGTS: D despesa / C FGTS a recolher. Valores indicados para outra competência não pertencem à competência atual e não precisam gerar warning.
7. Use somente C.R.s analíticos existentes no plano. O servidor revisará descrições e históricos com base no próprio plano.
8. Extraia documentTotals diretamente dos quadros totais do documento. Inclua apenas chaves realmente visíveis e informe em source o trecho curto de origem. Para total_proventos e total_descontos, use o Total Geral; para inss_total e fgts_total, use o Total a Recolher ou resumo equivalente.
9. warnings deve conter somente dúvida que exija decisão humana, como tributo agregado sem separação entre empregados e sócio.
Contas analíticas pertinentes à folha, pré-selecionadas do plano da empresa: ${JSON.stringify(relevantAccounts)}.`;
    const schema = { type: "object", additionalProperties: false, properties: { entries: { type: "array", items: { type: "object", additionalProperties: false, properties: { date: { type: "string" }, history: { type: "string" }, eventType: { type: "string", enum: eventTypes }, debitCode: { type: "string" }, debitDescription: { type: "string" }, debitCostCenter: { type: "string" }, creditCode: { type: "string" }, creditDescription: { type: "string" }, creditCostCenter: { type: "string" }, amountInCents: { type: "integer" }, source: { type: "string" }, confidence: { type: "number" } }, required: ["date", "history", "eventType", "debitCode", "debitDescription", "debitCostCenter", "creditCode", "creditDescription", "creditCostCenter", "amountInCents", "source", "confidence"] } }, documentTotals: { type: "array", items: { type: "object", additionalProperties: false, properties: { key: { type: "string", enum: totalKeys }, label: { type: "string" }, amountInCents: { type: "integer" }, source: { type: "string" } }, required: ["key", "label", "amountInCents", "source"] } }, warnings: { type: "array", items: { type: "string" } } }, required: ["entries", "documentTotals", "warnings"] };
    const requestBody = { instructions: prompt, input: [{ role: "user", content: [{ type: "input_text", text: "Extraia, classifique e devolva os lançamentos e totais verificáveis da folha." }, ...fileInputs] }], text: { format: { type: "json_schema", name: "payroll_entries", strict: true, schema } }, max_output_tokens: 12000 };
    const callOpenAI = async (requestedModel: string) => { const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: requestedModel, ...requestBody }), signal: AbortSignal.timeout(150_000) }); return { response, raw: await response.json(), requestedModel } };
    const parseAttempt = (attempt: { response: Response; raw: any; requestedModel: string }) => { if (!attempt.response.ok) return { error: attempt.raw?.error?.message || "Falha na OpenAI" }; const outputText = attempt.raw.output_text || attempt.raw.output?.flatMap((item: any) => item.content ?? []).find((item: any) => item.type === "output_text")?.text; if (!outputText) return { error: "A OpenAI concluiu a chamada sem devolver os lançamentos estruturados." }; try { return { parsed: JSON.parse(outputText) } } catch { return { error: "A resposta da IA não pôde ser validada como lançamentos contábeis." } } };
    let attempt = await callOpenAI(fastModel); let decoded = parseAttempt(attempt); let normalized = decoded.parsed ? applyDeterministicRules(decoded.parsed.entries ?? [], accounts, body.competence) : null; let validation = normalized ? validate(normalized.entries, decoded.parsed.documentTotals ?? []) : null; const reviewReason = decoded.error || validation?.issues.join(" | ") || ""; let reviewed = false;
    if (decoded.error || !validation?.passed) { await recordUsage(attempt.raw, attempt.response.ok ? "success" : "error", fastModel, { validation_passed: false, review_reason: reviewReason }); if (reviewModel !== fastModel) { attempt = await callOpenAI(reviewModel); decoded = parseAttempt(attempt); reviewed = true; normalized = decoded.parsed ? applyDeterministicRules(decoded.parsed.entries ?? [], accounts, body.competence) : null; validation = normalized ? validate(normalized.entries, decoded.parsed.documentTotals ?? []) : null } }
    if (decoded.error || !decoded.parsed || !normalized || !validation) { await recordUsage(attempt.raw, "error", attempt.requestedModel, { reviewed, review_reason: reviewReason }); return json({ error: decoded.error || "Não foi possível validar a leitura do documento." }, 502) }
    const warnings = [...new Set([...actionableWarnings(decoded.parsed.warnings ?? []), ...normalized.warnings])]; await recordUsage(attempt.raw, "success", attempt.requestedModel, { reviewed, validation_passed: validation.passed, entry_count: normalized.entries.length, warning_count: warnings.length, validation_issue_count: validation.issues.length });
    return json({ entries: normalized.entries, documentTotals: decoded.parsed.documentTotals, comparisons: validation.comparisons, validationIssues: validation.issues, warnings, model: attempt.raw.model || attempt.requestedModel, primaryModel: fastModel, reviewed, reviewModel: reviewed ? reviewModel : null, response_id: attempt.raw.id });
  } catch (error) { console.error("process-accounting-document", error); return json({ error: error instanceof Error ? error.message : String(error) }, 500) }
});
