import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.0";
import { Buffer } from "node:buffer";
import { lerCertificado } from "npm:nfse-node@0.3.2/certificado";
import { consume, limited, requestKey } from "../_shared/rate-limit.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const digits=(v:unknown)=>String(v??"").replace(/\D/g,"");
async function verifyPassword(email:string,password:string){const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!;if(!email||!password)return false;const authClient=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await authClient.auth.signInWithPassword({email,password});if(data.session)await authClient.auth.signOut();return !error&&Boolean(data.user)}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});try{
 const auth=req.headers.get("Authorization");if(!auth)return out({error:"Não autenticado"},401);
 const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
 const {data:{user}}=await admin.auth.getUser(auth.replace("Bearer ",""));if(!user)return out({error:"Não autenticado"},401);
 const b=await req.json(),orgId=String(b.organization_id||"");if(!orgId)return out({error:"Organização obrigatória"},422);const action=String(b.action||"get");const limit=await consume(admin,"saas_fiscal_config",requestKey(req,user.id+"|"+orgId),action==="save_certificate"?6:30,600);const blocked=limited(limit);if(blocked)return blocked;
 const {data:m}=await admin.from("organization_members").select("role,status").eq("organization_id",orgId).eq("user_id",user.id).eq("status","active").maybeSingle();
 const {data:roles}=await admin.from("user_roles").select("role").eq("user_id",user.id);const platformAdmin=roles?.some((r:any)=>["admin","fiscal","contabil","geral"].includes(r.role));if(!m&&!platformAdmin)return out({error:"Sem acesso à organização"},403);
 const canManage=platformAdmin||["owner","admin"].includes(m?.role||"");
 const {data:existing}=await admin.from("saas_company_fiscal_profiles").select("*").eq("organization_id",orgId).order("created_at").limit(1).maybeSingle();
 if(action==="get"){if(!existing)return out({profile:null,certificate_configured:false});const safe={...existing};delete safe.certificate_secret_id;delete safe.certificate_pfx_secret_id;delete safe.certificate_storage_path;delete safe.nfce_csc_token_encrypted;return out({profile:safe,certificate_configured:Boolean(existing.certificate_secret_id&&existing.certificate_pfx_secret_id)})}
 if(!canManage)return out({error:"Apenas proprietário ou administrador pode alterar a configuração fiscal"},403);
 if(action==="set_environment"){
   if(!existing?.id)return out({error:"Configure os dados fiscais antes de alterar o ambiente"},422);
   const target=String(b.environment||"");if(!["homologation","production"].includes(target))return out({error:"Ambiente inválido"},422);
   if(target===existing.fiscal_environment)return out({ok:true,environment:target,unchanged:true});
   const password=String(b.password||"");if(!password)return out({error:"Informe sua senha para confirmar a alteração de ambiente"},422);
   if(!user.email||!(await verifyPassword(user.email,password)))return out({error:"Senha incorreta. O ambiente não foi alterado."},403);
   if(target==="production"){
     if(b.production_ack!==true)return out({error:"Confirme que você entende que documentos emitidos em produção possuem valor fiscal"},422);
     const missing=[] as string[];if(digits(existing.tax_id).length!==14)missing.push("CNPJ");if(!String(existing.legal_name||"").trim())missing.push("razão social");if(!digits(existing.state_registration))missing.push("inscrição estadual");if(digits(existing.city_ibge_code).length!==7)missing.push("município IBGE");if(!existing.certificate_secret_id||!(existing.certificate_storage_path||existing.certificate_pfx_secret_id))missing.push("certificado A1");if(missing.length)return out({error:`Produção bloqueada: complete ${missing.join(", ")}.`},422);
   }
   const {data,error}=await admin.from("saas_company_fiscal_profiles").update({fiscal_environment:target,fiscal_environment_changed_at:new Date().toISOString(),fiscal_environment_changed_by:user.id,updated_at:new Date().toISOString()}).eq("id",existing.id).select("fiscal_environment,fiscal_environment_changed_at").single();if(error)throw error;
   return out({ok:true,environment:data.fiscal_environment,changed_at:data.fiscal_environment_changed_at});
 }
 if(action==="save_profile"){
   const allowed=["business_mode","tax_regime","crt","state_registration","municipal_registration","cnae_primary","enabled_documents","default_cfop_in_state","default_cfop_out_state","default_nfse_service_code","default_iss_rate","nfce_csc_id","series_nfe","next_number_nfe","series_nfce","next_number_nfce","series_nfse","next_number_nfse","series_cte","next_number_cte","series_mdfe","next_number_mdfe","legal_name","trade_name","tax_id","phone","email","postal_code","street","street_number","complement","district","city","state","city_ibge_code","notes"];
   const payload:any={updated_at:new Date().toISOString()};for(const k of allowed)if(k in(b.profile||{}))payload[k]=b.profile[k];if(payload.tax_id)payload.tax_id=digits(payload.tax_id);let data:any,error:any;if(existing?.id)({data,error}=await admin.from("saas_company_fiscal_profiles").update(payload).eq("id",existing.id).select().single());else({data,error}=await admin.from("saas_company_fiscal_profiles").insert({...payload,organization_id:orgId,fiscal_environment:"homologation"}).select().single());if(error)throw error;const safe={...data};delete safe.certificate_secret_id;delete safe.certificate_pfx_secret_id;delete safe.certificate_storage_path;delete safe.nfce_csc_token_encrypted;return out({ok:true,profile:safe})
 }
 if(action==="save_certificate"){
   const base64=String(b.certificate_base64||"").trim(),password=String(b.certificate_password||"");if(!base64||!password)return out({error:"Informe o certificado A1 e a senha"},422);if(password.length>256)return out({error:"Senha do certificado inválida"},422);if(base64.length>7_000_000)return out({error:"O certificado excede o limite de 5 MB"},413);const certificateBytes=Buffer.from(base64,"base64");if(!certificateBytes.length||certificateBytes.length>5_242_880)return out({error:"Arquivo de certificado inválido"},422);const cert=lerCertificado(certificateBytes,password);if(cert.validadeFim<new Date())return out({error:"Certificado expirado"},422);const certCnpj=digits(cert.titular.cnpj);if(existing?.tax_id&&certCnpj&&digits(existing.tax_id)!==certCnpj)return out({error:"O CNPJ do certificado não corresponde ao CNPJ configurado"},422);let id=existing?.id;if(!id){const {data:p,error}=await admin.from("saas_company_fiscal_profiles").insert({organization_id:orgId,tax_id:certCnpj||null,fiscal_environment:"homologation"}).select("id").single();if(error)throw error;id=p.id}const {error:vaultError}=await admin.rpc("set_saas_certificate_bundle",{_org_id:orgId,_pfx_base64:base64,_password:password});if(vaultError)throw vaultError;if(existing?.certificate_storage_path)await admin.storage.from("saas-private").remove([existing.certificate_storage_path]);const {error:u}=await admin.from("saas_company_fiscal_profiles").update({certificate_storage_path:null,certificate_subject:cert.titular.nome||null,certificate_expires_at:cert.validadeFim.toISOString(),...(certCnpj?{tax_id:certCnpj}:{}),updated_at:new Date().toISOString()}).eq("id",id);if(u)throw u;return out({ok:true,certificate:{subject:cert.titular.nome,cnpj:certCnpj,expires_at:cert.validadeFim.toISOString()}})
 }
 if(action==="list_dfe"){const cnpj=digits(existing?.tax_id);if(cnpj.length!==14)return out({items:[]});const {data,error}=await admin.from("fiscal_dfe_documents").select("id,access_key,issue_date,value,issuer_cnpj,issuer_name,recipient_cnpj,note_number,series,status_code,direction,schema_name,xml,full_xml").eq("cnpj",cnpj).order("issue_date",{ascending:false}).limit(200);if(error)throw error;return out({items:data||[]})}
 return out({error:"Ação inválida"},400)
}catch(e){console.error(e);return out({error:e instanceof Error?e.message:String(e)},500)}});
