import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.0";
import pdf from "npm:pdf-parse@1.1.1";
import { Buffer } from "node:buffer";
const E=new TextEncoder(),D=new TextDecoder(),B=(v:string)=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json'}});
async function K(){const s=Deno.env.get('ACCOUNTING_ENGINE_SESSION_SECRET')||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!s)throw new Error('secret_missing');const d=await crypto.subtle.digest('SHA-256',E.encode(`ws-fiscal-vault:${s}`));return crypto.subtle.importKey('raw',d,{name:'AES-GCM'},false,['decrypt'])}
async function dec(c:string,iv:string){return D.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:B(iv)},await K(),B(c)))}
function pair(v:string|null){return v?v.split(';',1)[0]:''}
function merge(a:string,b:string){const m=new Map<string,string>();for(const s of[a,b])for(const p of(s||'').split('; ')){const i=p.indexOf('=');if(i>0)m.set(p.slice(0,i),p.slice(i+1))}return[...m].map(([k,v])=>k+'='+v).join('; ')}
async function login(base:string,user:string,pass:string){let cookie='';let r=await fetch(base+'/sca_default_login_page',{redirect:'manual',headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(8000)});cookie=merge(cookie,pair(r.headers.get('set-cookie')));await r.arrayBuffer();r=await fetch(base+'/sca_security_check',{method:'POST',redirect:'manual',headers:{'User-Agent':'Mozilla/5.0','Content-Type':'application/x-www-form-urlencoded','Cookie':cookie,'Origin':base},body:new URLSearchParams({sca_login:user,sca_senha:pass,btn_entrar:'Entrar'}).toString(),signal:AbortSignal.timeout(8000)});cookie=merge(cookie,pair(r.headers.get('set-cookie')));await r.arrayBuffer();let loc=r.headers.get('location');for(let i=0;i<6&&loc;i++){r=await fetch(new URL(loc,base),{redirect:'manual',headers:{'User-Agent':'Mozilla/5.0','Cookie':cookie},signal:AbortSignal.timeout(8000)});cookie=merge(cookie,pair(r.headers.get('set-cookie')));await r.arrayBuffer();loc=r.headers.get('location')}return cookie}
function parseRanges(text:string){const out:{start:number,end:number,reason:string}[]=[];for(const line of String(text||'').split(/\n+/)){const m=line.trim().match(/^(\d+)\s*-\s*(\d+)\s*(.*)$/);if(!m)continue;const start=Number(m[1]),end=Number(m[2]);if(start>0&&end>=start)out.push({start,end,reason:(m[3]||'').trim()})}return out}
async function exactCount(admin:any,companyId:string,latest:number,status:string){const {count,error}=await admin.from('fiscal_sales_reconciliation').select('*',{count:'exact',head:true}).eq('company_id',companyId).eq('model','65').eq('series','1').lte('note_number',latest).eq('status',status);if(error)throw error;return Number(count||0)}
Deno.serve(async req=>{try{const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const tok=req.headers.get('x-debug-token')||'';const {data:t}=await admin.from('_fiscal_sales_debug_token').select('token').eq('id',true).maybeSingle();if(!tok||tok!==String(t?.token||''))return json({error:'unauthorized'},403);const b=await req.json().catch(()=>({})) as any;const companyId=String(b.company_id||'');const {data:company,error:ce}=await admin.from('fiscal_companies').select('cnpj').eq('id',companyId).single();if(ce||!company)throw new Error('company_missing');const {data:state}=await admin.from('fiscal_sales_sync_state').select('latest_number').eq('company_id',companyId).maybeSingle();const latest=Number(state?.latest_number||0);if(!latest)throw new Error('latest_number_missing');const {data:c,error}=await admin.from('fiscal_state_credentials').select('username_ciphertext,username_iv,password_ciphertext,password_iv').eq('company_id',companyId).eq('uf','AL').eq('is_active',true).single();if(error||!c)throw new Error('credential_missing');const user=await dec(c.username_ciphertext,c.username_iv),pass=await dec(c.password_ciphertext,c.password_iv),base='https://nfce.sefaz.al.gov.br';let cookie=await login(base,user,pass);const landing=await fetch(base+'/paginaRelatorioContribuinte.htm',{headers:{'User-Agent':'Mozilla/5.0','Cookie':cookie},signal:AbortSignal.timeout(10000)});cookie=merge(cookie,pair(landing.headers.get('set-cookie')));const landingText=await landing.text();const target=String(company.cnpj||'').replace(/\D/g,'');const cnpjs=[...landingText.matchAll(/<option\s+value=["'](\d{14})["']/gi)].map(m=>m[1]);const selected=cnpjs.includes(target)?target:cnpjs.length===1?cnpjs[0]:'';if(!selected)throw new Error('company_not_available_in_state_portal');const r=await fetch(base+'/emitirRelatorioInutilizacaoDeNumeracaoDeNotaFiscal.htm?cnpj='+encodeURIComponent(selected),{headers:{'User-Agent':'Mozilla/5.0','Cookie':cookie,'Referer':base+'/paginaRelatorioContribuinte.htm'},signal:AbortSignal.timeout(30000)});const bytes=new Uint8Array(await r.arrayBuffer());const parsed=await pdf(Buffer.from(bytes));const ranges=parseRanges(String(parsed.text||'').replace(/\r/g,''));const official=new Map<number,string>();for(const rg of ranges)for(let n=Math.max(1,rg.start);n<=Math.min(latest,rg.end);n++)official.set(n,rg.reason);
const {data:gaps,error:ge}=await admin.from('fiscal_sales_reconciliation').select('note_number').eq('company_id',companyId).eq('model','65').eq('series','1').lte('note_number',latest).eq('status','not_found').limit(5000);if(ge)throw ge;const now=new Date().toISOString();let changed=0;for(const gap of gaps||[]){const n=Number(gap.note_number),reason=official.get(n);if(!reason&&reason!=='' )continue;const {error:ue}=await admin.from('fiscal_sales_reconciliation').update({status:'inutilized',cstat:'PORTAL_INUTILIZACAO',xmotivo:`Inutilização confirmada no relatório oficial SEFAZ/AL${reason?` · ${reason}`:''}`,resolved_at:now,last_checked_at:now,updated_at:now}).eq('company_id',companyId).eq('model','65').eq('series','1').eq('note_number',n).eq('status','not_found');if(ue)throw ue;changed++}
const officialNums=[...official.keys()];let conflicts:any[]=[];if(officialNums.length){const {data:cf}=await admin.from('fiscal_sales_reconciliation').select('note_number,status').eq('company_id',companyId).eq('model','65').eq('series','1').in('note_number',officialNums).in('status',['found','cancelled']).limit(5000);conflicts=(cf||[]).map((x:any)=>({note_number:x.note_number,status:x.status,reason:official.get(Number(x.note_number))||''}))}
const [pending,found,cancelled,inutilized,not_found,errors]=await Promise.all(['pending','found','cancelled','inutilized','not_found','error'].map(s=>exactCount(admin,companyId,latest,s)));const resolved=found+cancelled+inutilized+not_found,complete=resolved===latest&&pending===0&&errors===0;await admin.from('fiscal_sales_sync_state').update({reconciliation_total:latest,reconciliation_resolved:resolved,reconciliation_found:found,reconciliation_missing:not_found,reconciliation_cancelled:cancelled,reconciliation_inutilized:inutilized,reconciliation_pending:pending+errors,reconciliation_complete:complete,status:complete?'idle':'reconciling',reconciliation_completed_at:complete?now:null,updated_at:now}).eq('company_id',companyId);return json({ok:true,changed,official_ranges:ranges.length,counts:{pending,found,cancelled,inutilized,not_found,error:errors},complete,conflicts});}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
