import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ImagePlus, RefreshCw, Save } from 'lucide-react';
import { AdminLayout } from '@/components/admin/layout/AdminLayout';
import { AdminPage, AdminPageHeader, AdminSection } from '@/components/admin/ui/AdminPage';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { supabase } from '@/integrations/supabase/client';
import { useCompanySelection } from '@/contexts/CompanySelectionContext';

const digits=(v:string)=>String(v||'').replace(/\D/g,'');
const formatCnpj=(v:string)=>{const d=digits(v);return d.length===14?d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5'):v};
const initial=(name?:string|null)=>String(name||'?').trim().charAt(0).toUpperCase()||'?';
type Client={id:string;company_name:string;trade_name:string|null;cnpj:string;address:string|null;company_size:string|null;logo_url?:string|null};
type Fiscal={id:string;cnpj:string;razao_social:string;nome_fantasia:string|null;uf:string|null;municipio:string|null;inscricao_estadual:string|null};
type Cert={certificate_name:string;holder_name:string|null;holder_cnpj:string|null;valid_until:string;is_active:boolean};

export default function AdminClientProfile(){
 const {companyId}=useParams();const navigate=useNavigate();const {selectCompany,refreshCompanies}=useCompanySelection();
 const [client,setClient]=useState<Client|null>(null),[fiscal,setFiscal]=useState<Fiscal|null>(null),[cert,setCert]=useState<Cert|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{if(!companyId)return;setLoading(true);setError('');try{const c=await (supabase as any).from('companies').select('id,company_name,trade_name,cnpj,address,company_size,logo_url').eq('id',companyId).single();if(c.error)throw c.error;setClient(c.data);selectCompany(companyId);const f=await (supabase as any).from('fiscal_companies').select('id,cnpj,razao_social,nome_fantasia,uf,municipio,inscricao_estadual').eq('company_id',companyId).maybeSingle();if(f.error)throw f.error;setFiscal(f.data||null);if(f.data){const ce=await (supabase as any).from('fiscal_certificates').select('certificate_name,holder_name,holder_cnpj,valid_until,is_active').eq('company_id',f.data.id).eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();if(ce.error)throw ce.error;setCert(ce.data||null)}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[companyId]);
 const save=async()=>{if(!client)return;setSaving(true);setError('');const {error:e}=await (supabase as any).from('companies').update({company_name:client.company_name.trim(),trade_name:client.trade_name?.trim()||null,cnpj:digits(client.cnpj),address:client.address?.trim()||null,company_size:client.company_size?.trim()||null,updated_at:new Date().toISOString()}).eq('id',client.id);if(e)setError(e.message);else{setNotice('Cadastro atualizado.');await refreshCompanies()}setSaving(false)};
 const fillFromCertificate=()=>{if(!client||(!cert&&!fiscal)){setNotice('Nenhum certificado A1 configurado para esta empresa.');return}const name=cert?.holder_name||fiscal?.razao_social||client.company_name;const cnpj=cert?.holder_cnpj||fiscal?.cnpj||client.cnpj;setClient({...client,company_name:name||client.company_name,trade_name:fiscal?.nome_fantasia||client.trade_name,cnpj:digits(cnpj||client.cnpj),address:client.address});setNotice('Dados disponíveis no A1 carregados no formulário. Confira e salve.')};
 const uploadLogo=async(file:File)=>{if(!client||!file.type.startsWith('image/'))return;setUploading(true);setError('');try{const ext=file.name.split('.').pop()||'png',path=`companies/${client.id}/${Date.now()}.${ext}`;const up=await supabase.storage.from('carousel-logos').upload(path,file,{upsert:true});if(up.error)throw up.error;const {data:{publicUrl}}=supabase.storage.from('carousel-logos').getPublicUrl(path);const db=await (supabase as any).from('companies').update({logo_url:publicUrl}).eq('id',client.id);if(db.error)throw db.error;await (supabase as any).from('carousel_items').update({logo_url:publicUrl}).eq('company_id',client.id);setClient({...client,logo_url:publicUrl});await refreshCompanies()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setUploading(false)}};
 if(loading)return <AdminLayout><AdminPage><div className="py-16 text-center text-sm text-muted-foreground">Carregando empresa...</div></AdminPage></AdminLayout>;
 if(!client)return <AdminLayout><AdminPage><div className="py-16 text-center text-sm text-destructive">Empresa não encontrada.</div></AdminPage></AdminLayout>;
 const name=client.trade_name||client.company_name;
 return <AdminLayout><AdminPage>
  <Button variant="ghost" className="mb-4 -ml-2" onClick={()=>navigate('/admin/clientes')}><ArrowLeft className="mr-2 h-4 w-4"/>Clientes</Button>
  <AdminPageHeader eyebrow="Cadastro central" title={name} description="Informações principais da empresa usadas em todo o Admin." actions={<Button onClick={()=>void save()} disabled={saving}><Save className="mr-2 h-4 w-4"/>{saving?'Salvando...':'Salvar alterações'}</Button>}/>
  {(error||notice)&&<div className={`mt-5 rounded-xl border px-4 py-3 text-sm ${error?'border-destructive/20 bg-destructive/5 text-destructive':'border-border/60 bg-muted/20 text-muted-foreground'}`}>{error||notice}</div>}
  <div className="mt-6 grid gap-5 lg:grid-cols-[280px_minmax(0,1fr)]">
   <AdminSection className="p-6"><div className="flex flex-col items-center text-center"><div className="flex h-32 w-32 items-center justify-center overflow-hidden rounded-3xl border border-border/60 bg-muted/25 text-3xl font-semibold text-muted-foreground">{client.logo_url?<img src={client.logo_url} alt="" className="h-full w-full object-contain"/>:initial(name)}</div><p className="mt-4 font-semibold">{name}</p><p className="mt-1 text-xs text-muted-foreground">{formatCnpj(client.cnpj)}</p><label className="mt-5 inline-flex cursor-pointer items-center rounded-lg border border-border/60 px-3 py-2 text-xs font-medium hover:bg-muted/35"><ImagePlus className="mr-2 h-4 w-4"/>{uploading?'Enviando...':'Alterar logo'}<input className="hidden" type="file" accept="image/*" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadLogo(f);e.currentTarget.value=''}}/></label><p className="mt-3 text-[11px] leading-5 text-muted-foreground">A mesma logo é usada no seletor global e no carrossel.</p></div></AdminSection>
   <div className="space-y-5">
    <AdminSection className="p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-semibold">Dados da empresa</h2><p className="mt-1 text-xs text-muted-foreground">Edite manualmente ou carregue os dados disponíveis no certificado A1.</p></div><Button variant="outline" size="sm" onClick={fillFromCertificate}><RefreshCw className="mr-2 h-4 w-4"/>Preencher pelo A1</Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Razão social"><Input value={client.company_name} onChange={e=>setClient({...client,company_name:e.target.value})}/></Field><Field label="Nome fantasia"><Input value={client.trade_name||''} onChange={e=>setClient({...client,trade_name:e.target.value})}/></Field><Field label="CNPJ"><Input value={client.cnpj} onChange={e=>setClient({...client,cnpj:e.target.value})}/></Field><Field label="Porte"><Input value={client.company_size||''} onChange={e=>setClient({...client,company_size:e.target.value})}/></Field><div className="sm:col-span-2"><Field label="Endereço"><Input value={client.address||''} onChange={e=>setClient({...client,address:e.target.value})}/></Field></div></div></AdminSection>
    <AdminSection className="p-6"><h2 className="font-semibold">Certificado vinculado</h2>{cert?<div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Titular</p><p className="mt-1 font-medium">{cert.holder_name||fiscal?.razao_social||'—'}</p></div><div><p className="text-xs text-muted-foreground">Validade</p><p className="mt-1 font-medium">{new Date(`${cert.valid_until}T12:00:00`).toLocaleDateString('pt-BR')}</p></div></div>:<p className="mt-2 text-sm text-muted-foreground">Nenhum A1 configurado. O certificado pode ser incluído pela configuração fiscal desta empresa quando necessário.</p>}</AdminSection>
   </div>
  </div>
 </AdminPage></AdminLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="text-xs font-medium text-muted-foreground">{label}</span>{children}</label>}
