import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, FileKey2, ImagePlus, Save, Search, ShieldCheck } from 'lucide-react';
import { AdminLayout } from '@/components/admin/layout/AdminLayout';
import { AdminPage, AdminPageHeader, AdminSection } from '@/components/admin/ui/AdminPage';
import { SmartCertificateInput } from '@/components/admin/fiscal/CertificateImportTools';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { supabase } from '@/integrations/supabase/client';
import { useCompanySelection } from '@/contexts/CompanySelectionContext';
import { lookupOfficeCompanyByCnpj, registryToOfficeCompany, onlyDigits } from '@/utils/companyRegistry';

const formatCnpj=(v:string)=>{const d=onlyDigits(v);return d.length===14?d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5'):v};
const initial=(name?:string|null)=>String(name||'?').trim().charAt(0).toUpperCase()||'?';
async function fileToBase64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
async function callVault(body:Record<string,unknown>){const{data,error}=await supabase.functions.invoke('fiscal-company-vault',{body});if(!error)return data;let message=error.message;try{const context=(error as {context?:Response}).context;if(context)message=(await context.clone().json())?.error||message}catch{}throw new Error(message)}

type Client={id:string;company_name:string;trade_name:string|null;cnpj:string;address:string|null;company_size:string|null;logo_url?:string|null;state_registration?:string|null;registration_status?:string|null;tax_regime?:string|null;email?:string|null;phone?:string|null;postal_code?:string|null;street?:string|null;street_number?:string|null;complement?:string|null;district?:string|null;city?:string|null;state?:string|null;city_ibge_code?:string|null;cnae_primary?:string|null;registry_payload?:any;registry_updated_at?:string|null};
type Fiscal={id:string;cnpj:string;razao_social:string;nome_fantasia:string|null;uf:string|null;municipio:string|null;codigo_municipio?:string|null;inscricao_estadual:string|null;regime_tributario?:string|null};
type Cert={certificate_name:string;holder_name:string|null;holder_cnpj:string|null;valid_until:string;is_active:boolean};
type CertMeta={holder_cnpj:string;holder_name:string;valid_from?:string;valid_until?:string};

export default function AdminClientProfile(){
 const {companyId}=useParams();const navigate=useNavigate();const {selectCompany,refreshCompanies}=useCompanySelection();
 const [client,setClient]=useState<Client|null>(null),[fiscal,setFiscal]=useState<Fiscal|null>(null),[cert,setCert]=useState<Cert|null>(null),[certFile,setCertFile]=useState<File|null>(null),[certPassword,setCertPassword]=useState(''),[certMeta,setCertMeta]=useState<CertMeta|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[lookingUp,setLookingUp]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');

 const load=async()=>{if(!companyId)return;setLoading(true);setError('');try{const c=await (supabase as any).from('companies').select('*').eq('id',companyId).single();if(c.error)throw c.error;setClient(c.data);selectCompany(companyId);const f=await (supabase as any).from('fiscal_companies').select('id,cnpj,razao_social,nome_fantasia,uf,municipio,codigo_municipio,inscricao_estadual,regime_tributario').eq('company_id',companyId).maybeSingle();if(f.error)throw f.error;setFiscal(f.data||null);if(f.data){const ce=await (supabase as any).from('fiscal_certificates').select('certificate_name,holder_name,holder_cnpj,valid_until,is_active').eq('company_id',f.data.id).eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();if(ce.error)throw ce.error;setCert(ce.data||null)}else setCert(null)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[companyId]);

 const lookupCnpj=async()=>{if(!client)return;setLookingUp(true);setError('');setNotice('');try{const lookup=await lookupOfficeCompanyByCnpj(client.cnpj);const mapped=registryToOfficeCompany(lookup.data,lookup.registry||{});setClient({...client,...mapped});setNotice(lookup.state_registry_found?'Cadastro encontrado. Razão social, nome fantasia, IE e demais dados foram preenchidos automaticamente.':'Cadastro encontrado. Os dados federais foram preenchidos; a IE não apareceu na fonte estadual e pode ser revisada manualmente.')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLookingUp(false)}};

 const save=async()=>{if(!client)return;setSaving(true);setError('');setNotice('');try{const cnpj=onlyDigits(certMeta?.holder_cnpj||client.cnpj);if(certMeta&&onlyDigits(certMeta.holder_cnpj)!==onlyDigits(client.cnpj))throw new Error('O certificado A1 pertence a outro CNPJ.');const companyName=String(certMeta?.holder_name||client.company_name).trim().toUpperCase();const tradeName=String(client.trade_name||companyName).trim().toUpperCase();const payload={...client,company_name:companyName,trade_name:tradeName,cnpj,updated_at:new Date().toISOString()};delete (payload as any).id;delete (payload as any).logo_url;const {error:e}=await (supabase as any).from('companies').update(payload).eq('id',client.id);if(e)throw e;if(certFile){const body:Record<string,unknown>={action:'save',company:{id:fiscal?.id||undefined,company_id:client.id,cnpj,razao_social:companyName,nome_fantasia:tradeName,uf:(client.state||fiscal?.uf||'AL').toUpperCase(),municipio:client.city||fiscal?.municipio||'',codigo_municipio:client.city_ibge_code||fiscal?.codigo_municipio||'',inscricao_estadual:client.state_registration||fiscal?.inscricao_estadual||'',regime_tributario:client.tax_regime||fiscal?.regime_tributario||'simples_nacional',ambiente_padrao:'producao',status:'ativa',endereco:{}},certificate_base64:await fileToBase64(certFile),certificate_password:certPassword,certificate_name:certFile.name};await callVault(body)}await refreshCompanies();setCertFile(null);setCertPassword('');setCertMeta(null);await load();setNotice(certFile?'Cadastro salvo e A1 vinculado para extração fiscal.':'Cadastro salvo. O certificado A1 continua opcional.')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setSaving(false)}};

 const onCertificateMetadata=(m:CertMeta)=>{setCertMeta(m);setClient(current=>current?{...current,company_name:String(m.holder_name||current.company_name).toUpperCase(),cnpj:onlyDigits(m.holder_cnpj||current.cnpj)}:current);setNotice('A1 identificado. Ele será usado apenas se você optar por habilitar a extração fiscal desta empresa.')};
 const uploadLogo=async(file:File)=>{if(!client||!file.type.startsWith('image/'))return;setUploading(true);setError('');try{const ext=file.name.split('.').pop()||'png',path=`companies/${client.id}/${Date.now()}.${ext}`;const up=await supabase.storage.from('carousel-logos').upload(path,file,{upsert:true});if(up.error)throw up.error;const {data:{publicUrl}}=supabase.storage.from('carousel-logos').getPublicUrl(path);const db=await (supabase as any).from('companies').update({logo_url:publicUrl}).eq('id',client.id);if(db.error)throw db.error;await (supabase as any).from('carousel_items').update({logo_url:publicUrl}).eq('company_id',client.id);setClient({...client,logo_url:publicUrl});await refreshCompanies()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setUploading(false)}};

 if(loading)return <AdminLayout><AdminPage><div className="py-16 text-center text-sm text-muted-foreground">Carregando empresa...</div></AdminPage></AdminLayout>;
 if(!client)return <AdminLayout><AdminPage><div className="py-16 text-center text-sm text-destructive">Empresa não encontrada.</div></AdminPage></AdminLayout>;
 const name=String(client.trade_name||client.company_name).toUpperCase();
 return <AdminLayout><AdminPage>
  <Button variant="ghost" className="mb-4 -ml-2" onClick={()=>navigate('/admin/clientes')}><ArrowLeft className="mr-2 h-4 w-4"/>Clientes</Button>
  <AdminPageHeader eyebrow="Cadastro central" title={name} description="Cadastro empresarial completo. O CNPJ preenche os dados automaticamente; o A1 é opcional e só é necessário para extração fiscal." actions={<Button onClick={()=>void save()} disabled={saving}><Save className="mr-2 h-4 w-4"/>{saving?'Salvando...':'Salvar alterações'}</Button>}/>
  {(error||notice)&&<div className={`mt-5 rounded-xl border px-4 py-3 text-sm ${error?'border-destructive/20 bg-destructive/5 text-destructive':'border-border/60 bg-muted/20 text-muted-foreground'}`}>{error||notice}</div>}
  <div className="mt-6 grid gap-5 lg:grid-cols-[280px_minmax(0,1fr)]">
   <AdminSection className="p-6"><div className="flex flex-col items-center text-center"><div className="flex h-32 w-32 items-center justify-center overflow-hidden rounded-3xl border border-border/60 bg-muted/25 text-3xl font-semibold text-muted-foreground">{client.logo_url?<img src={client.logo_url} alt="" className="h-full w-full object-contain"/>:initial(name)}</div><p className="mt-4 font-semibold">{name}</p><p className="mt-1 text-xs text-muted-foreground">{formatCnpj(client.cnpj)}</p><label className="mt-5 inline-flex cursor-pointer items-center rounded-lg border border-border/60 px-3 py-2 text-xs font-medium hover:bg-muted/35"><ImagePlus className="mr-2 h-4 w-4"/>{uploading?'Enviando...':'Alterar logo'}<input className="hidden" type="file" accept="image/*" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadLogo(f);e.currentTarget.value=''}}/></label></div></AdminSection>
   <div className="space-y-5">
    <AdminSection className="p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Dados da empresa</h2><p className="mt-1 text-xs text-muted-foreground">Digite o CNPJ e consulte. O sistema busca razão social, nome fantasia, IE, endereço, regime, CNAE e situação cadastral.</p></div><Button variant="outline" onClick={()=>void lookupCnpj()} disabled={lookingUp||onlyDigits(client.cnpj).length!==14}><Search className="mr-2 h-4 w-4"/>{lookingUp?'Consultando...':'Buscar pelo CNPJ'}</Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Razão social"><Input value={client.company_name} onChange={e=>setClient({...client,company_name:e.target.value.toUpperCase()})}/></Field><Field label="Nome fantasia"><Input value={client.trade_name||''} onChange={e=>setClient({...client,trade_name:e.target.value.toUpperCase()})}/></Field><Field label="CNPJ"><Input value={client.cnpj} onChange={e=>setClient({...client,cnpj:e.target.value})}/></Field><Field label="Inscrição estadual"><Input value={client.state_registration||''} onChange={e=>setClient({...client,state_registration:e.target.value})}/></Field><Field label="Situação cadastral"><Input value={client.registration_status||''} onChange={e=>setClient({...client,registration_status:e.target.value.toUpperCase()})}/></Field><Field label="Porte"><Input value={client.company_size||''} onChange={e=>setClient({...client,company_size:e.target.value.toUpperCase()})}/></Field><Field label="Regime tributário"><Input value={client.tax_regime||''} onChange={e=>setClient({...client,tax_regime:e.target.value})}/></Field><Field label="CNAE principal"><Input value={client.cnae_primary||''} onChange={e=>setClient({...client,cnae_primary:e.target.value})}/></Field><Field label="E-mail cadastral"><Input value={client.email||''} onChange={e=>setClient({...client,email:e.target.value})}/></Field><Field label="Telefone"><Input value={client.phone||''} onChange={e=>setClient({...client,phone:e.target.value})}/></Field><Field label="CEP"><Input value={client.postal_code||''} onChange={e=>setClient({...client,postal_code:e.target.value})}/></Field><Field label="UF"><Input value={client.state||''} onChange={e=>setClient({...client,state:e.target.value.toUpperCase()})}/></Field><Field label="Município"><Input value={client.city||''} onChange={e=>setClient({...client,city:e.target.value.toUpperCase()})}/></Field><Field label="Código IBGE"><Input value={client.city_ibge_code||''} onChange={e=>setClient({...client,city_ibge_code:e.target.value})}/></Field><div className="sm:col-span-2"><Field label="Endereço"><Input value={client.address||''} onChange={e=>setClient({...client,address:e.target.value.toUpperCase()})}/></Field></div></div></AdminSection>
    <AdminSection className="p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Certificado digital A1 <span className="font-normal text-muted-foreground">(opcional)</span></h2><p className="mt-1 text-xs text-muted-foreground">Só adicione o .pfx/.p12 se o escritório quiser habilitar a extração fiscal desta empresa. O cadastro empresarial funciona normalmente sem certificado.</p></div>{cert&&<span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-600 dark:text-emerald-400"><ShieldCheck className="h-4 w-4"/>Ativo</span>}</div>{cert&&<div className="mt-4 flex items-center gap-3 rounded-xl border border-border/50 bg-muted/20 p-4"><div className="rounded-lg bg-background p-2"><FileKey2 className="h-5 w-5"/></div><div><p className="text-sm font-medium">{cert.certificate_name}</p><p className="text-xs text-muted-foreground">{cert.holder_name||'Titular não informado'} · válido até {new Date(`${cert.valid_until}T12:00:00`).toLocaleDateString('pt-BR')}</p></div></div>}<div className="mt-5"><SmartCertificateInput editing={Boolean(cert)} onFile={setCertFile} onPassword={setCertPassword} onMetadata={onCertificateMetadata}/></div></AdminSection>
   </div>
  </div>
 </AdminPage></AdminLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="text-xs font-medium text-muted-foreground">{label}</span>{children}</label>}
