import { useCallback, useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Menu, X } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { FiscalDocumentPreview, type PreviewDocument } from '@/components/admin/fiscal/FiscalDocumentPreview';
import AnimatedExtractorIcon, { type ExtractorIconName } from '@/components/extractor/AnimatedExtractorIcon';
import AccountDrawer from '@/components/account/AccountDrawer';
import '@/styles/fiscal-extractor.css';

type Section='Visão geral'|'Empresas'|'Documentos'|'Relatórios'|'Certificados'|'Histórico'|'Configurações';
type Filter='saida'|'entrada'|'todos'|'cancelada'|'evento';
type TypeFilter='todos'|'nfe'|'nfce'|'nfse';
type Company={id:string;extractorCompanyId:string;name:string;tradeName:string;cnpj:string;uf:string;documents:number;entries:number;exits:number;fullXml:number;pendingXml:number;lastSync:string|null;automaticSync:boolean;certificateUntil:string|null;certificateDays:number|null;purchaseStatus:string|null;salesStatus:string|null;salesXmlPending:number;salesXmlFailed:number};
type Doc={id?:string;companyId:string;nsu?:string;schema?:string;source?:string;documentKind?:string;fullXml:boolean;direction:'entrada'|'saida'|'relacionada';accessKey?:string;model?:string;issueDate?:string|null;value?:number;issuerCnpj?:string;issuerName?:string;recipientCnpj?:string;number?:string;series?:string;statusCode?:string;statusText?:string;parseError?:string;xml?:string};
type Snapshot={account?:{id?:string;name?:string;plan_code?:string;monthly_xml_limit?:number;base_lookback_days?:number;allowed_from?:string};companies?:Array<Record<string,any>>;totals?:{documents?:number;entries?:number;exits?:number;value?:number;full_xml?:number;pending_xml?:number};models?:{nfe?:number;nfce?:number;nfse?:number;other?:number};daily?:Array<{day?:string;documents?:number}>};
type Notice={tone:'success'|'warning'|'error';text:string}|null;
type UsageSnapshot={account_id?:string;plan_code?:string;period_start?:string;period_end?:string;xml_used?:number;xml_limit?:number;xml_remaining?:number;usage_percent?:number;documents?:number;pending_xml?:number;history?:Array<{month?:string;xml_used?:number;documents?:number;pending_xml?:number}>;latest_plan_request?:{id?:string;requested_limit?:number;status?:string;created_at?:string}|null};

const nav:Array<{label:Section;icon:ExtractorIconName;group:string}>=[
 {label:'Visão geral',icon:'dashboard',group:'Operação'},{label:'Empresas',icon:'company',group:'Operação'},
 {label:'Documentos',icon:'document',group:'Fiscal'},{label:'Relatórios',icon:'report',group:'Fiscal'},
 {label:'Certificados',icon:'certificate',group:'Gestão'},{label:'Histórico',icon:'history',group:'Gestão'},{label:'Configurações',icon:'settings',group:'Gestão'},
];
const MONTHS=['Ano','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'] as const;
const MONTH_INDEX:Record<string,number>={Jan:0,Fev:1,Mar:2,Abr:3,Mai:4,Jun:5,Jul:6,Ago:7,Set:8,Out:9,Nov:10,Dez:11};
const PAGE_SIZE=50;
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),integer=new Intl.NumberFormat('pt-BR');
const digits=(v:unknown)=>String(v||'').replace(/\D/g,'');
const formatCnpj=(v:unknown)=>{const d=digits(v);return d.length===14?d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5'):String(v||'—')};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const nowMonthStart=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)};
const nowMonthEnd=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,0)};
const formatDate=(v?:string|null,withTime=false)=>{if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return withTime?d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):d.toLocaleDateString('pt-BR')};
const syncLabel=(v?:string|null)=>{const x=String(v||'').toLowerCase();if(['running','queued','reconciling','bootstrap_window','retrying'].includes(x))return'Sincronizando';if(['idle','completed','success'].includes(x))return'Ativa';if(!x)return'Não iniciada';return x.replaceAll('_',' ')};
const extractorPlanLabel=(account:any)=>account?.plan_code==='lifetime_test'?'Teste vitalício':account?.plan_code==='office_20000'?`Escritório · ${integer.format(Number(account?.monthly_xml_limit||account?.xml_limit||20000))} XML/mês`:String(account?.plan_code||'Plano Extrator');
const model=(d:Doc)=>String(d.model||(/^\d{44}$/.test(String(d.accessKey||''))?String(d.accessKey).slice(20,22):''));
const type=(d:Doc)=>{const h=`${d.documentKind||''} ${d.schema||''} ${d.model||''}`.toLowerCase();if(d.documentKind==='evento')return'Evento';if(h.includes('nfse')||h.includes('nfs-e'))return'NFS-e';if(model(d)==='65')return'NFC-e';if(model(d)==='55')return'NF-e';return'Documento'};
const cancelled=(d:Doc)=>['101','151','155'].includes(String(d.statusCode||''))||/cancel/i.test(String(d.statusText||''));
const status=(d:Doc)=>{if(d.documentKind==='evento')return'Evento';if(cancelled(d))return'Cancelada';if(/deneg/i.test(String(d.statusText||''))||['110','301','302'].includes(String(d.statusCode||'')))return'Denegada';if(['1','100','150'].includes(String(d.statusCode||''))||/autoriz|ativa/i.test(String(d.statusText||'')))return'Autorizada';return d.statusText||'Fiscal'};

const normalizeCompany=(r:Record<string,any>,i:number):Company=>({id:String(r.id||i),extractorCompanyId:String(r.extractor_company_id||''),name:r.razao_social||'Empresa',tradeName:r.nome_fantasia||r.razao_social||'Empresa',cnpj:r.cnpj||'',uf:r.uf||'—',documents:Number(r.documents||0),entries:Number(r.entries||0),exits:Number(r.exits||0),fullXml:Number(r.full_xml||0),pendingXml:Number(r.pending_xml||0),lastSync:r.last_sync_at||null,automaticSync:r.automatic_sync!==false,certificateUntil:r.certificate_until||null,certificateDays:r.certificate_days==null?null:Number(r.certificate_days),purchaseStatus:r.purchase_status||null,salesStatus:r.sales_status||null,salesXmlPending:Number(r.sales_xml_pending||0),salesXmlFailed:Number(r.sales_xml_failed||0)});
const rowToDoc=(r:any):Doc=>({id:r.id,companyId:String(r.company_id||''),nsu:r.nsu||undefined,schema:r.schema_name||undefined,source:r.source||undefined,documentKind:r.document_kind||undefined,fullXml:Boolean(r.full_xml),direction:r.direction==='saida'||r.direction==='outbound'?'saida':r.direction==='entrada'||r.direction==='inbound'?'entrada':'relacionada',accessKey:r.access_key||undefined,model:r.model||undefined,issueDate:r.issue_date||undefined,value:r.value==null?undefined:Number(r.value),issuerCnpj:r.issuer_cnpj||undefined,issuerName:r.issuer_name||undefined,recipientCnpj:r.recipient_cnpj||undefined,number:r.note_number==null?'':String(r.note_number),series:r.series==null?'':String(r.series),statusCode:r.status_code||undefined,statusText:r.status_text||undefined,parseError:r.parse_error||undefined,xml:r.xml||undefined});
const reconciliationToDoc=(r:any,companyId:string):Doc=>({companyId,documentKind:'nfe',fullXml:false,direction:'saida',accessKey:r.access_key||undefined,model:String(r.model||'65'),issueDate:r.issue_date||undefined,number:r.note_number==null?'':String(r.note_number),series:r.series==null?'':String(r.series),statusCode:r.cstat||undefined,statusText:r.xmotivo||(r.status==='cancelled'?'Cancelada':r.status==='found'?'Encontrada':r.status||'Fiscal')});

const chart={gold:'#d7b65a',blue:'#5b83ad',cyan:'#4b9e9d',green:'#5f987d',muted:'#485667',grid:'#1c2a3a',text:'#9aa9b8'};

export default function FiscalExtractorApp({preview=false}:{preview?:boolean}){
 const {user}=useAuth();
 const [active,setActive]=useState<Section>('Visão geral'),[mobile,setMobile]=useState(false),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[usage,setUsage]=useState<UsageSnapshot|null>(null),[loading,setLoading]=useState(!preview),[denied,setDenied]=useState(false),[notice,setNotice]=useState<Notice>(null),[companyModal,setCompanyModal]=useState(false),[selectedCompanyId,setSelectedCompanyId]=useState<string>(''),[previewDoc,setPreviewDoc]=useState<PreviewDocument|null>(null);
 const load=useCallback(async(quiet=false)=>{if(preview||!user)return;if(!quiet)setLoading(true);const[workspaceResult,usageResult]=await Promise.all([(supabase as any).rpc('extractor_workspace_snapshot'),(supabase as any).rpc('extractor_usage_snapshot')]);const{data,error}=workspaceResult;if(error||!data){setDenied(true)}else{setSnapshot(data as Snapshot);setDenied(false);if(!usageResult.error&&usageResult.data)setUsage(usageResult.data as UsageSnapshot)}if(!quiet)setLoading(false)},[preview,user?.id]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(preview||denied)return;const t=window.setInterval(()=>void load(true),30000),f=()=>void load(true);window.addEventListener('focus',f);return()=>{window.clearInterval(t);window.removeEventListener('focus',f)}},[preview,denied,load]);
 const companies=useMemo(()=>preview?[{id:'demo',extractorCompanyId:'demo',name:'Empresa demonstração',tradeName:'Empresa demonstração',cnpj:'00000000000000',uf:'AL',documents:326,entries:55,exits:271,fullXml:266,pendingXml:60,lastSync:new Date().toISOString(),automaticSync:true,certificateUntil:'2027-08-25',certificateDays:351,purchaseStatus:'idle',salesStatus:'idle',salesXmlPending:60,salesXmlFailed:0}]:((snapshot?.companies||[]).map(normalizeCompany)),[preview,snapshot]);
 useEffect(()=>{if(!selectedCompanyId&&companies.length)setSelectedCompanyId(companies[0].id)},[companies,selectedCompanyId]);
 const totals=preview?{documents:326,entries:55,exits:271,value:675295.32,fullXml:266,pendingXml:60}:{documents:Number(snapshot?.totals?.documents||0),entries:Number(snapshot?.totals?.entries||0),exits:Number(snapshot?.totals?.exits||0),value:Number(snapshot?.totals?.value||0),fullXml:Number(snapshot?.totals?.full_xml||0),pendingXml:Number(snapshot?.totals?.pending_xml||0)};
 const models=preview?{nfe:149,nfce:169,nfse:8,other:0}:{nfe:Number(snapshot?.models?.nfe||0),nfce:Number(snapshot?.models?.nfce||0),nfse:Number(snapshot?.models?.nfse||0),other:Number(snapshot?.models?.other||0)};
 const daily=preview?Array.from({length:30},(_,i)=>({day:iso(new Date(Date.now()-(29-i)*86400000)),documents:[7,9,6,12,8,4,11,13,8,10][i%10]})):(snapshot?.daily||[]).map(x=>({day:String(x.day||''),documents:Number(x.documents||0)}));
 const usageData:UsageSnapshot=preview?{plan_code:'demo',period_start:iso(nowMonthStart()),period_end:iso(nowMonthEnd()),xml_used:266,xml_limit:20000,xml_remaining:19734,usage_percent:1.33,documents:326,pending_xml:60,history:[]}:usage||{};
 const planName=extractorPlanLabel(snapshot?.account||usageData);
 const go=(s:Section,companyId?:string)=>{if(companyId)setSelectedCompanyId(companyId);setActive(s);setMobile(false);setNotice(null)};
 if(loading)return <Loading/>;
 if(!preview&&denied)return <AccessPending/>;
 return <div className="extractor-app">
  <header className="extractor-topbar"><div className="extractor-brand"><button className="extractor-mobile-trigger" onClick={()=>setMobile(true)} aria-label="Abrir menu"><Menu/></button><img src="/assets/ws-logo.png" alt="WS Gestão Contábil"/></div><div className="extractor-workspace"><small>Conta do Extrator</small><strong>{preview?'Demonstração':snapshot?.account?.name||'WS Gestão Contábil'}</strong></div><div className="extractor-account">{preview?<span>PR</span>:<AccountDrawer darkTrigger productName="Extrator Fiscal" accessLabel="Assinante do Extrator Fiscal" planLabel={planName} triggerClassName="extractor-account-trigger" usageRows={[{label:'XML processados no ciclo',value:integer.format(Number(usageData.xml_used||0))},{label:'XML restantes no plano',value:integer.format(Number(usageData.xml_remaining||0))},{label:'Empresas no Extrator',value:String(companies.length)}]} notifications={[{title:'Uso do plano',text:`${integer.format(Number(usageData.xml_used||0))} de ${integer.format(Number(usageData.xml_limit||snapshot?.account?.monthly_xml_limit||0))} XML utilizados no ciclo atual.`},{title:'Carteira do Extrator',text:`${companies.length} empresa(s) vinculada(s) exclusivamente a este produto.`}]}/>}</div></header>
  {mobile&&<button className="extractor-scrim" onClick={()=>setMobile(false)} aria-label="Fechar menu"/>}
  <aside className={`extractor-sidebar ${mobile?'is-open':''}`}><button className="extractor-sidebar-close" onClick={()=>setMobile(false)}><X/></button><div className="extractor-sidebar-title"><strong>Extrato Fiscal</strong><small>Compras e vendas</small></div><nav>{['Operação','Fiscal','Gestão'].map(group=><section key={group}><p>{group}</p>{nav.filter(n=>n.group===group).map(n=><button key={n.label} className={active===n.label?'is-active':''} onClick={()=>go(n.label)}><AnimatedExtractorIcon name={n.icon} className="extractor-nav-icon"/><span>{n.label}</span></button>)}</section>)}</nav><button type="button" className="extractor-usage" onClick={()=>go('Configurações')}><small>Uso do plano</small><strong>{integer.format(Number(usageData.xml_used||0))}<b> / {integer.format(Number(usageData.xml_limit||snapshot?.account?.monthly_xml_limit||0))}</b></strong><span>{integer.format(Number(usageData.xml_remaining||0))} XML restantes</span><em>Ver histórico e plano →</em></button></aside>
  <main className="extractor-main">{notice&&<NoticeBar notice={notice} close={()=>setNotice(null)}/>}
   {active==='Visão geral'&&<Overview companies={companies} totals={totals} models={models} daily={daily} onGo={go}/>}
   {active==='Empresas'&&<Companies companies={companies} onAdd={()=>setCompanyModal(true)} onOpen={id=>go('Documentos',id)} onReload={()=>load(true)} setNotice={setNotice} preview={preview}/>}
   {active==='Documentos'&&<Documents companies={companies} selectedCompanyId={selectedCompanyId} setSelectedCompanyId={setSelectedCompanyId} preview={preview} setNotice={setNotice} onPreview={setPreviewDoc}/>}
   {active==='Relatórios'&&<Reports companies={companies} totals={totals} models={models} daily={daily}/>}
   {active==='Certificados'&&<Certificates companies={companies} onGo={go}/>}
   {active==='Histórico'&&<HistorySection companies={companies} accountId={snapshot?.account?.id} userId={user?.id} preview={preview} setNotice={setNotice}/>}
   {active==='Configurações'&&<SettingsSection companies={companies} account={snapshot?.account} usage={usageData} preview={preview} setNotice={setNotice} onReload={()=>load(true)}/>}
  </main>
  {companyModal&&<AddCompanyModal preview={preview} onClose={()=>setCompanyModal(false)} onDone={async company=>{setCompanyModal(false);setSelectedCompanyId(company.id);setNotice({tone:'success',text:`${company.trade_name||company.legal_name} adicionada. A sincronização inicial já foi colocada em execução.`});await load(true);setActive('Empresas')}}/>}
  {previewDoc&&<FiscalDocumentPreview doc={previewDoc} onClose={()=>setPreviewDoc(null)}/>}
 </div>;
}

function PageHeading({title,description,icon,actions}:{title:string;description:string;icon:ExtractorIconName;actions?:React.ReactNode}){return <div className="extractor-page-heading"><div><span className="extractor-eyebrow"><AnimatedExtractorIcon name={icon}/>WS Extrator Fiscal</span><h1>{title}</h1><p>{description}</p></div>{actions&&<div className="extractor-heading-actions">{actions}</div>}</div>}
function NoticeBar({notice,close}:{notice:NonNullable<Notice>;close:()=>void}){return <div className={`extractor-notice ${notice.tone}`}><span>{notice.text}</span><button onClick={close}><X/></button></div>}
function Metric({label,value,detail,icon}:{label:string;value:string;detail:string;icon:ExtractorIconName}){return <article className="extractor-metric"><div><p>{label}</p><AnimatedExtractorIcon name={icon}/></div><strong>{value}</strong><span>{detail}</span></article>}
function PanelHead({title,sub,icon}:{title:string;sub:string;icon:ExtractorIconName}){return <header className="extractor-panel-head"><div><AnimatedExtractorIcon name={icon}/><span><h2>{title}</h2><p>{sub}</p></span></div></header>}
function Empty({children}:{children:React.ReactNode}){return <div className="extractor-empty">{children}</div>}
function Tip({active,payload,label}:any){if(!active||!payload?.length)return null;return <div className="extractor-tooltip">{label&&<strong>{label}</strong>}{payload.map((p:any,i:number)=><span key={i}>{p.name}: <b>{integer.format(Number(p.value||0))}</b></span>)}</div>}

function Overview({companies,totals,models,daily,onGo}:any){
 const xmlRate=totals.documents?Math.round(totals.fullXml/totals.documents*100):0,companyData=[...companies].sort((a:any,b:any)=>b.documents-a.documents).slice(0,6),modelData=[{name:'NF-e',value:models.nfe,color:chart.gold},{name:'NFC-e',value:models.nfce,color:chart.blue},{name:'NFS-e',value:models.nfse,color:chart.cyan}].filter(x=>x.value>0),attention=companies.filter((c:any)=>c.pendingXml>0||(c.certificateDays!=null&&c.certificateDays<=30)||/retry|error|fail/i.test(`${c.purchaseStatus} ${c.salesStatus}`));
 return <div className="extractor-page"><PageHeading title="Visão geral" icon="dashboard" description="Acompanhamento da carteira fiscal do escritório. A sincronização roda por empresa, como no painel fiscal administrativo."/><section className="extractor-kpis"><Metric label="Documentos" value={integer.format(totals.documents)} detail={`${integer.format(totals.fullXml)} com XML integral`} icon="document"/><Metric label="Compras" value={integer.format(totals.entries)} detail="Entradas fiscais" icon="download"/><Metric label="Vendas" value={integer.format(totals.exits)} detail="Saídas fiscais" icon="upload"/><Metric label="Movimentação" value={currency.format(totals.value)} detail="Valor disponível no período" icon="report"/><Metric label="Cobertura XML" value={`${xmlRate}%`} detail={`${integer.format(totals.pendingXml)} pendente(s)`} icon="certificate"/></section><section className="extractor-dashboard-grid">
  <article className="extractor-panel extractor-panel-wide"><PanelHead title="Movimento dos últimos 30 dias" sub="Documentos capturados por dia" icon="report"/><div className="extractor-chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={daily} margin={{top:10,right:10,left:-20,bottom:0}}><defs><linearGradient id="exFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={chart.gold} stopOpacity={.34}/><stop offset="1" stopColor={chart.gold} stopOpacity={.02}/></linearGradient></defs><CartesianGrid vertical={false} stroke={chart.grid}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:10,fill:chart.text}} minTickGap={28}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:chart.text}}/><Tooltip content={<Tip/>}/><Area type="monotone" dataKey="documents" name="Documentos" stroke={chart.gold} strokeWidth={2.3} fill="url(#exFill)"/></AreaChart></ResponsiveContainer></div></article>
  <article className="extractor-panel"><PanelHead title="Documentos por modelo" sub="Composição da carteira" icon="document"/><div className="extractor-donut"><ResponsiveContainer><PieChart><Pie data={modelData.length?modelData:[{name:'Sem dados',value:1,color:chart.muted}]} dataKey="value" innerRadius="65%" outerRadius="86%" paddingAngle={4} stroke="none">{(modelData.length?modelData:[{name:'Sem dados',value:1,color:chart.muted}]).map((x:any)=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip content={<Tip/>}/></PieChart></ResponsiveContainer><div><strong>{integer.format(totals.documents)}</strong><span>documentos</span></div></div><div className="extractor-legend">{modelData.map((x:any)=><p key={x.name}><i style={{background:x.color}}/><span>{x.name}</span><b>{x.value}</b></p>)}</div></article>
  <article className="extractor-panel extractor-panel-wide"><PanelHead title="Empresas por volume" sub="CNPJs adicionados no Extrator" icon="company"/><div className="extractor-chart-company">{companyData.length?<ResponsiveContainer><BarChart data={companyData} layout="vertical" margin={{top:0,right:12,left:6,bottom:0}}><CartesianGrid horizontal={false} stroke={chart.grid}/><XAxis type="number" axisLine={false} tickLine={false} tick={{fontSize:10,fill:chart.text}}/><YAxis type="category" dataKey="tradeName" width={120} axisLine={false} tickLine={false} tick={{fontSize:10,fill:chart.text}}/><Tooltip content={<Tip/>}/><Bar dataKey="documents" name="Documentos" fill={chart.blue} radius={[0,4,4,0]} barSize={15}/></BarChart></ResponsiveContainer>:<Empty>Nenhuma empresa adicionada.</Empty>}</div></article>
  <article className="extractor-panel"><PanelHead title="Pontos de atenção" sub="Ocorrências reais da carteira" icon="warning"/><div className="extractor-attention-list">{attention.length?attention.slice(0,5).map((c:any)=><button key={c.id} onClick={()=>onGo(c.certificateDays!=null&&c.certificateDays<=30?'Certificados':'Empresas')}><span><strong>{c.tradeName}</strong><small>{c.certificateDays!=null&&c.certificateDays<=30?`Certificado vence em ${c.certificateDays} dia(s)`:c.pendingXml?`${c.pendingXml} XML pendente(s)`:`Compras: ${syncLabel(c.purchaseStatus)} · Vendas: ${syncLabel(c.salesStatus)}`}</small></span><b>Ver</b></button>):<Empty>Nenhuma pendência relevante.</Empty>}</div></article>
 </section></div>;
}

function Companies({companies,onAdd,onOpen,onReload,setNotice,preview}:any){const[term,setTerm]=useState(''),[busy,setBusy]=useState('');const visible=companies.filter((c:Company)=>`${c.name} ${c.tradeName} ${c.cnpj}`.toLowerCase().includes(term.toLowerCase()));const sync=async(c:Company)=>{if(preview)return setNotice({tone:'warning',text:'A sincronização fica disponível no ambiente autenticado.'});setBusy(c.id);const{data,error}=await(supabase as any).rpc('extractor_queue_sync',{_company_id:c.id});if(error||!data?.ok)setNotice({tone:'error',text:error?.message||'Não foi possível atualizar esta empresa.'});else setNotice({tone:'success',text:`${c.tradeName}: atualização fiscal colocada na fila.`});setBusy('');await onReload()};return <div className="extractor-page"><PageHeading title="Empresas" icon="company" description="Somente clientes adicionados dentro do Extrator aparecem aqui. O cadastro do ADM não é importado automaticamente." actions={<button className="extractor-primary" onClick={onAdd}><AnimatedExtractorIcon name="upload"/>Adicionar com A1</button>}/><div className="extractor-toolbar"><label><AnimatedExtractorIcon name="search"/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Buscar empresa ou CNPJ"/></label></div><div className="extractor-company-list"><div className="extractor-company-head"><span>Empresa</span><span>Documentos</span><span>XML integral</span><span>Sincronização</span><span>Certificado</span><span>Ações</span></div>{visible.map((c:Company)=><div className="extractor-company-row" key={c.id} role="button" tabIndex={0} onClick={()=>onOpen(c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onOpen(c.id)}}}><div><strong>{c.tradeName}</strong><span>{formatCnpj(c.cnpj)} · {c.uf}</span></div><div><strong>{integer.format(c.documents)}</strong><span>{c.entries} compras · {c.exits} vendas</span></div><div><strong>{integer.format(c.fullXml)}</strong><span>{c.pendingXml?`${c.pendingXml} pendente(s)`:'Completo no período'}</span></div><div><strong>{syncLabel(c.purchaseStatus)} / {syncLabel(c.salesStatus)}</strong><span>{c.lastSync?formatDate(c.lastSync,true):'Ainda não concluída'}</span></div><div><strong>{c.certificateUntil?formatDate(c.certificateUntil):'Não configurado'}</strong><span>{c.certificateDays==null?'—':`${c.certificateDays} dia(s)`}</span></div><div className="extractor-row-actions"><button onClick={e=>{e.stopPropagation();void sync(c)}} disabled={busy===c.id}><AnimatedExtractorIcon name="refresh"/>{busy===c.id?'Atualizando':'Atualizar'}</button><button onClick={e=>{e.stopPropagation();onOpen(c.id)}}>Notas</button></div></div>)}{!visible.length&&<Empty>Nenhuma empresa encontrada.</Empty>}</div></div>}

function Documents({companies,selectedCompanyId,setSelectedCompanyId,preview,setNotice,onPreview}:any){
 const now=new Date(),today=iso(now),[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState<(typeof MONTHS)[number]>(MONTHS[now.getMonth()+1]),[filter,setFilter]=useState<Filter>('todos'),[typeFilter,setTypeFilter]=useState<TypeFilter>('todos'),[query,setQuery]=useState(''),[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(false),[page,setPage]=useState(1),[busy,setBusy]=useState('');
 const company=companies.find((c:Company)=>c.id===selectedCompanyId)||companies[0]||null;
 const start=month==='Ano'?`${year}-01-01`:iso(new Date(year,MONTH_INDEX[month],1)),end=month==='Ano'?`${year}-12-31`:iso(new Date(year,MONTH_INDEX[month]+1,0));
 const loadDocs=useCallback(async()=>{if(preview||!company){setDocs([]);return}setLoading(true);const{data,error}=await(supabase as any).rpc('extractor_company_documents',{_company_id:company.id,_start:start,_end:end});if(error){setNotice({tone:'error',text:error.message});setDocs([])}else{const base=(data?.documents||[]).map(rowToDoc),known=new Set(base.map((d:Doc)=>String(d.accessKey||'')).filter(Boolean)),extra=(data?.reconciliation||[]).filter((r:any)=>r.access_key&&!known.has(String(r.access_key))).map((r:any)=>reconciliationToDoc(r,company.id));setDocs([...base,...extra])}setLoading(false)},[preview,company?.id,start,end]);
 useEffect(()=>{void loadDocs()},[loadDocs]);useEffect(()=>setPage(1),[year,month,filter,typeFilter,query,company?.id]);
 const fiscal=docs.filter(d=>d.documentKind!=='evento'),sales=fiscal.filter(d=>d.direction==='saida'),purchases=fiscal.filter(d=>d.direction==='entrada'),events=docs.filter(d=>d.documentKind==='evento'||d.direction==='relacionada'),cancelledDocs=fiscal.filter(cancelled),nfe=fiscal.filter(d=>type(d)==='NF-e').length,nfce=fiscal.filter(d=>type(d)==='NFC-e').length,nfse=fiscal.filter(d=>type(d)==='NFS-e').length;
 const filtered=docs.filter(d=>{if(filter==='saida'&&(d.direction!=='saida'||d.documentKind==='evento'))return false;if(filter==='entrada'&&(d.direction!=='entrada'||d.documentKind==='evento'))return false;if(filter==='evento'&&!(d.documentKind==='evento'||d.direction==='relacionada'))return false;if(filter==='cancelada'&&!cancelled(d))return false;const t=type(d);if(typeFilter==='nfe'&&t!=='NF-e')return false;if(typeFilter==='nfce'&&t!=='NFC-e')return false;if(typeFilter==='nfse'&&t!=='NFS-e')return false;const q=query.trim().toLowerCase();return!q||[d.number,d.accessKey,d.issuerName,d.issuerCnpj,d.recipientCnpj,d.nsu,d.series,d.statusText,t].some(v=>String(v||'').toLowerCase().includes(q))});
 const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),safe=Math.min(page,totalPages),rows=filtered.slice((safe-1)*PAGE_SIZE,safe*PAGE_SIZE);
 const open=async(d:Doc)=>{if(preview)return setNotice({tone:'warning',text:'A visualização usa XML fiscal real e fica disponível no ambiente autenticado.'});setBusy(`doc:${d.accessKey||d.nsu}`);const{data,error}=await supabase.functions.invoke('fiscal-document-recover',{body:{company_id:company.id,access_key:d.accessKey,nsu:d.nsu}});if(error)setNotice({tone:'error',text:error.message});else if(!data?.ready||!data.document)setNotice({tone:'warning',text:data?.reason||'O XML integral ainda não está disponível.'});else{const r=data.document;onPreview({companyId:r.company_id,nsu:r.nsu,schema:r.schema_name,documentKind:r.document_kind,fullXml:r.full_xml,direction:r.direction,accessKey:r.access_key,issueDate:r.issue_date,value:Number(r.value||0),issuerCnpj:r.issuer_cnpj,issuerName:r.issuer_name,recipientCnpj:r.recipient_cnpj,number:r.note_number,series:r.series,statusCode:r.status_code,statusText:r.status_text,model:r.model,xml:r.xml,parseError:r.parse_error})}setBusy('')};
 const download=async()=>{if(preview||!company)return setNotice({tone:'warning',text:'O download fiscal fica disponível no ambiente autenticado.'});setBusy('download');const payload={company_id:company.id,start,end,direction:filter==='entrada'?'entrada':filter==='saida'?'saida':'todos'};const pre=await supabase.functions.invoke('fiscal-bulk-download',{body:{...payload,action:'preflight'}});if(pre.error)setNotice({tone:'error',text:pre.error.message});else if(!pre.data?.ready)setNotice({tone:'warning',text:`${pre.data?.pending||0} documento(s) ainda aguardam XML integral.`});else{const result=await supabase.functions.invoke('fiscal-bulk-download',{body:payload});if(result.error)setNotice({tone:'error',text:result.error.message});else{const blob=result.data instanceof Blob?result.data:new Blob([result.data],{type:'application/zip'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`extrato-fiscal-${company.tradeName.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${start}-${end}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}setBusy('')};
 if(!company)return <div className="extractor-page"><PageHeading title="Documentos" icon="document" description="Adicione uma empresa com certificado A1 para iniciar."/><Empty>Nenhuma empresa adicionada ao Extrator.</Empty></div>;
 return <div className="extractor-page extractor-admin-clone"><PageHeading title="Documentos" icon="document" description="Mesmo fluxo de compras e vendas utilizado no painel fiscal administrativo." actions={<select className="extractor-company-select" value={company.id} onChange={e=>setSelectedCompanyId(e.target.value)}>{companies.map((c:Company)=><option key={c.id} value={c.id}>{c.tradeName}</option>)}</select>}/>
  <section className="extractor-active-company"><div><p>Empresa ativa</p><strong>{company.name}</strong><span>{formatCnpj(company.cnpj)}</span></div><div className={company.certificateDays!=null&&company.certificateDays>=0?'ok':'bad'}><AnimatedExtractorIcon name="certificate"/>{company.certificateDays!=null&&company.certificateDays>=0?'Certificado válido':'Certificado pendente'}</div></section>
  <section className="extractor-period"><div className="extractor-year"><button onClick={()=>setYear(y=>y-1)}>‹</button><strong>{year}</strong><button disabled={year>=now.getFullYear()} onClick={()=>setYear(y=>y+1)}>›</button></div><div className="extractor-months">{MONTHS.map(m=>{const future=m!=='Ano'&&year===now.getFullYear()&&MONTH_INDEX[m]>now.getMonth();return <button key={m} disabled={future} className={month===m?'active':''} onClick={()=>setMonth(m)}>{m}</button>})}</div></section>
  <section className="extractor-doc-kpis"><Metric label="Total notas" value={String(fiscal.length)} detail="Documentos fiscais" icon="document"/><Metric label="Vendas" value={String(sales.length)} detail="Saídas" icon="upload"/><Metric label="Compras" value={String(purchases.length)} detail="Entradas" icon="download"/><Metric label="Faturamento" value={currency.format(sales.reduce((s,d)=>s+Number(d.value||0),0))} detail={`Entradas: ${currency.format(purchases.reduce((s,d)=>s+Number(d.value||0),0))}`} icon="report"/></section>
  <section className="extractor-admin-table"><div className="extractor-filter-row"><div><Pill active={filter==='saida'} onClick={()=>setFilter('saida')}>↗ Vendas <b>{sales.length}</b></Pill><Pill active={filter==='entrada'} onClick={()=>setFilter('entrada')}>↙ Compras <b>{purchases.length}</b></Pill><Pill active={filter==='todos'} onClick={()=>setFilter('todos')}>Todas <b>{docs.length}</b></Pill><Pill active={filter==='evento'} onClick={()=>setFilter('evento')}>Eventos <b>{events.length}</b></Pill><Pill active={filter==='cancelada'} onClick={()=>setFilter('cancelada')}>⊘ Canceladas <b>{cancelledDocs.length}</b></Pill><i/><Pill active={typeFilter==='nfe'} onClick={()=>setTypeFilter(typeFilter==='nfe'?'todos':'nfe')}>NF-e <b>{nfe}</b></Pill><Pill active={typeFilter==='nfce'} onClick={()=>setTypeFilter(typeFilter==='nfce'?'todos':'nfce')}>NFC-e <b>{nfce}</b></Pill><Pill active={typeFilter==='nfse'} onClick={()=>setTypeFilter(typeFilter==='nfse'?'todos':'nfse')}>NFS-e <b>{nfse}</b></Pill></div><span>Última busca: {company.lastSync?formatDate(company.lastSync,true):'automática'}</span></div>
   <div className="extractor-search-row"><label><AnimatedExtractorIcon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por número, chave, razão social, CNPJ, tipo ou situação..."/></label><button className="extractor-primary" onClick={()=>void download()} disabled={busy==='download'}><AnimatedExtractorIcon name="download"/>{busy==='download'?'Gerando...':'Download'}</button></div>
   <div className="extractor-table-wrap"><table><thead><tr><th>Emissão</th><th>Nota / Chave</th><th>Destinatário / Emitente</th><th>Operação</th><th className="right">Valor</th><th className="right">Ações</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="extractor-empty-cell">Carregando documentos...</td></tr>:rows.length?rows.map((d,i)=>{const t=type(d),st=status(d),isEvent=d.documentKind==='evento';return <tr key={`${d.accessKey||d.nsu||i}-${i}`} className={`ws-zebra-row ${cancelled(d)?'ws-zebra-cancelled':''}`} role="button" tabIndex={0} onClick={()=>void open(d)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();void open(d)}}}><td><strong>{formatDate(d.issueDate)}</strong><span>{d.issueDate?new Date(d.issueDate).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'—'}</span></td><td><div><b>{d.number||'—'}</b><small>/ {d.series||'1'}</small><TypeTag value={t}/><StatusTag value={st}/></div><span className="key">{d.accessKey||'—'}</span></td><td><strong>{isEvent?'Documento relacionado':d.direction==='saida'?(d.recipientCnpj||'—'):(d.issuerName||'—')}</strong><span>{d.direction==='saida'?d.recipientCnpj:d.issuerCnpj}</span></td><td><strong>{isEvent?'Evento fiscal':d.direction==='saida'?'Venda de mercadoria':'Entrada fiscal'}</strong><span>{t} · {st}</span></td><td className="right value">{isEvent||d.value==null?'—':currency.format(d.value)}</td><td className="right"><button className="extractor-view" onClick={e=>{e.stopPropagation();void open(d)}} disabled={busy===`doc:${d.accessKey||d.nsu}`}><AnimatedExtractorIcon name="eye"/>Visualizar</button></td></tr>}):<tr><td colSpan={6} className="extractor-empty-cell">Nenhum documento neste filtro/período.</td></tr>}</tbody></table></div>
   <div className="extractor-pagination"><span>{filtered.length?`${(safe-1)*PAGE_SIZE+1}–${Math.min(safe*PAGE_SIZE,filtered.length)} de ${filtered.length}`:'0 documento(s)'}</span><div><button disabled={safe<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>‹</button><span>{safe} / {totalPages}</span><button disabled={safe>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))}>›</button></div></div>
  </section>
 </div>;
}
function Pill({active,onClick,children}:any){return <button className={active?'active':''} onClick={onClick}>{children}</button>}
function TypeTag({value}:{value:string}){return <em className={`extractor-type ${value.replace(/[^a-z]/gi,'').toLowerCase()}`}>{value}</em>}
function StatusTag({value}:{value:string}){return <em className={`extractor-state ${/cancel/i.test(value)?'danger':/deneg/i.test(value)?'warning':/autoriz/i.test(value)?'success':'neutral'}`}>{value}</em>}

function Reports({companies,totals,models,daily}:any){const data=[...companies].sort((a:any,b:any)=>b.documents-a.documents).slice(0,10);return <div className="extractor-page"><PageHeading title="Relatórios" icon="report" description="Consolidado real da carteira fiscal."/><section className="extractor-kpis"><Metric label="Empresas" value={String(companies.length)} detail="CNPJs vinculados" icon="company"/><Metric label="Documentos" value={integer.format(totals.documents)} detail={`${totals.entries} compras · ${totals.exits} vendas`} icon="document"/><Metric label="XML integral" value={integer.format(totals.fullXml)} detail={`${totals.pendingXml} pendente(s)`} icon="certificate"/><Metric label="Movimentação" value={currency.format(totals.value)} detail="Total da janela" icon="report"/></section><section className="extractor-dashboard-grid"><article className="extractor-panel extractor-panel-wide"><PanelHead title="Ritmo documental" sub="Últimos 30 dias" icon="report"/><div className="extractor-chart-area"><ResponsiveContainer><AreaChart data={daily}><CartesianGrid vertical={false} stroke={chart.grid}/><XAxis dataKey="day" hide/><YAxis axisLine={false} tickLine={false} tick={{fill:chart.text,fontSize:10}}/><Tooltip content={<Tip/>}/><Area dataKey="documents" name="Documentos" type="monotone" stroke={chart.blue} fill={chart.blue} fillOpacity={.12}/></AreaChart></ResponsiveContainer></div></article><article className="extractor-panel extractor-panel-wide"><PanelHead title="Empresas por volume" sub="Documentos por cliente" icon="company"/><div className="extractor-chart-company"><ResponsiveContainer><BarChart data={data} layout="vertical"><XAxis type="number" hide/><YAxis type="category" dataKey="tradeName" width={120} tick={{fill:chart.text,fontSize:10}} axisLine={false} tickLine={false}/><Tooltip content={<Tip/>}/><Bar dataKey="documents" fill={chart.gold} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></article></section></div>}
function Certificates({companies,onGo}:any){return <div className="extractor-page"><PageHeading title="Certificados" icon="certificate" description="A1 utilizado nas consultas fiscais das empresas adicionadas ao Extrator."/><div className="extractor-company-list"><div className="extractor-company-head certificate"><span>Empresa</span><span>Validade</span><span>Dias restantes</span><span>Situação</span><span>Ação</span></div>{companies.map((c:Company)=>{const state=c.certificateDays==null?'Não configurado':c.certificateDays<0?'Vencido':c.certificateDays<=30?'Atenção':'Válido';return <div className="extractor-certificate-row" key={c.id} role="button" tabIndex={0} onClick={()=>onGo('Empresas',c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onGo('Empresas',c.id)}}}><div><strong>{c.tradeName}</strong><span>{formatCnpj(c.cnpj)}</span></div><span>{c.certificateUntil?formatDate(c.certificateUntil):'—'}</span><span>{c.certificateDays==null?'—':`${c.certificateDays} dia(s)`}</span><StatusTag value={state}/><button onClick={e=>{e.stopPropagation();onGo('Empresas',c.id)}}>Gerenciar</button></div>})}{!companies.length&&<Empty>Nenhuma empresa adicionada.</Empty>}</div></div>}
function HistorySection({companies,accountId,userId,preview,setNotice}:any){const now=new Date(),[from,setFrom]=useState(`${now.getFullYear()}-${String(Math.max(1,now.getMonth()-5)).padStart(2,'0')}`),[to,setTo]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`),[busy,setBusy]=useState(false);const save=async()=>{if(preview)return setNotice({tone:'warning',text:'Disponível no ambiente autenticado.'});if(!accountId||!userId||from>to)return setNotice({tone:'error',text:'Período inválido.'});setBusy(true);const endDate=new Date(Number(to.slice(0,4)),Number(to.slice(5,7)),0);const{error}=await(supabase as any).from('extractor_history_requests').insert({account_id:accountId,requested_by:userId,requested_from:`${from}-01`,requested_to:`${to}-${String(endDate.getDate()).padStart(2,'0')}`,metadata:{companies:companies.map((c:Company)=>c.id),source:'extractor_ui'}});setNotice(error?{tone:'error',text:error.message}:{tone:'success',text:'Solicitação de histórico registrada.'});setBusy(false)};return <div className="extractor-page"><PageHeading title="Histórico" icon="history" description="Solicite períodos anteriores à janela contratada."/><article className="extractor-history"><div><h2>Consulta retroativa</h2><p>Registre o período. A solicitação não gera cobrança nem inicia consulta automaticamente.</p><div className="extractor-form-row"><label>De<input type="month" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="month" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="extractor-primary" onClick={()=>void save()} disabled={busy}>{busy?'Registrando':'Solicitar análise'}</button></div><aside><strong>{companies.length}</strong><span>empresa(s) nesta carteira</span></aside></article></div>}
function SettingsSection({companies,account,usage,preview,setNotice,onReload}:any){
 const[requested,setRequested]=useState(''),[busy,setBusy]=useState(false);
 const limit=Number(usage?.xml_limit||account?.monthly_xml_limit||0),used=Number(usage?.xml_used||0),remaining=Math.max(0,Number(usage?.xml_remaining??(limit-used))),percent=Math.max(0,Math.min(100,Number(usage?.usage_percent||(limit?used/limit*100:0)))),history=Array.isArray(usage?.history)?usage.history:[],latest=usage?.latest_plan_request||null;
 const requestUpgrade=async()=>{const target=Number(requested);if(!Number.isFinite(target)||target<=limit)return setNotice({tone:'warning',text:`Informe um limite maior que ${integer.format(limit)} XML.`});if(preview)return setNotice({tone:'warning',text:'A solicitação de upgrade fica disponível no ambiente autenticado.'});setBusy(true);const{data,error}=await(supabase as any).rpc('extractor_request_plan_upgrade',{_requested_limit:Math.trunc(target)});if(error||!data?.ok)setNotice({tone:'error',text:error?.message||data?.message||'Não foi possível registrar o upgrade.'});else{setNotice({tone:'success',text:'Solicitação de upgrade registrada. O histórico da conta já foi atualizado.'});setRequested('');await onReload()}setBusy(false)};
 const monthLabel=(value:string)=>{const d=new Date(`${value}-01T12:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('pt-BR',{month:'short',year:'numeric'})};
 return <div className="extractor-page extractor-settings-page"><PageHeading title="Configurações" icon="settings" description="Plano, consumo mensal, histórico e rotinas desta carteira do Extrator."/>
  <section className="extractor-plan-hero" data-extractor-icon-host><div className="extractor-plan-hero-head"><div><span>Plano atual</span><h2>{extractorPlanLabel(account||usage)}</h2><p>Ciclo {formatDate(usage?.period_start)} a {formatDate(usage?.period_end)}</p></div><b>Ativo</b></div><div className="extractor-plan-progress-copy"><strong>{integer.format(used)} XML processados</strong><span>{integer.format(remaining)} restantes de {integer.format(limit)}</span></div><div className="extractor-plan-progress"><i style={{width:`${percent}%`}}/></div><div className="extractor-plan-facts"><div><span>Uso do ciclo</span><strong>{percent.toLocaleString('pt-BR',{maximumFractionDigits:1})}%</strong></div><div><span>Documentos localizados</span><strong>{integer.format(Number(usage?.documents||0))}</strong></div><div><span>XML pendentes</span><strong>{integer.format(Number(usage?.pending_xml||0))}</strong></div><div><span>Empresas</span><strong>{integer.format(companies.length)}</strong></div></div></section>
  <div className="extractor-settings-grid extractor-settings-grid-large"><article className="extractor-panel extractor-usage-history-panel"><PanelHead title="Histórico de consumo" sub="Últimos seis ciclos mensais" icon="history"/><div className="extractor-usage-history">{history.length?history.map((h:any)=><div key={h.month}><span>{monthLabel(String(h.month||''))}</span><strong>{integer.format(Number(h.xml_used||0))} XML</strong><small>{integer.format(Number(h.documents||0))} documento(s) · {integer.format(Number(h.pending_xml||0))} pendente(s)</small></div>):<Empty>O histórico aparecerá conforme houver processamento.</Empty>}</div></article><article className="extractor-panel"><PanelHead title="Rotinas por empresa" sub="Estado fiscal atual" icon="refresh"/><div className="extractor-settings-companies">{companies.map((c:Company)=><div key={c.id}><span><strong>{c.tradeName}</strong><small>{c.automaticSync?'Sincronização automática habilitada':'Sincronização automática desabilitada'}</small></span><span>Compras: {syncLabel(c.purchaseStatus)}<br/>Vendas: {syncLabel(c.salesStatus)}</span></div>)}{!companies.length&&<Empty>Nenhuma empresa adicionada.</Empty>}</div></article></div>
  <article className="extractor-panel extractor-upgrade-panel"><PanelHead title="Limite e upgrade" sub="Aumente o volume sem misturar produtos ou empresas" icon="report"/><div className="extractor-upgrade-body"><div><h3>Precisa de um limite maior?</h3><p>Informe a quantidade mensal desejada. A solicitação fica registrada nesta conta do Extrator e não altera o plano automaticamente.</p>{latest?.status==='pending'&&<span className="extractor-upgrade-pending">Solicitação pendente: {integer.format(Number(latest.requested_limit||0))} XML/mês · {formatDate(latest.created_at,true)}</span>}</div><div className="extractor-upgrade-form"><label>Novo limite mensal<input type="number" min={limit+1} step="100" value={requested} onChange={e=>setRequested(e.target.value)} placeholder={`Acima de ${integer.format(limit)}`}/></label><button className="extractor-primary" onClick={()=>void requestUpgrade()} disabled={busy}>{busy?'Registrando...':'Solicitar upgrade'}</button></div></div></article>
 </div>
}

function AddCompanyModal({preview,onClose,onDone}:any){const[file,setFile]=useState<File|null>(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async()=>{if(preview)return setError('O cadastro fica disponível no ambiente autenticado.');if(!file||!password)return setError('Selecione o certificado A1 e informe a senha.');setBusy(true);setError('');try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const{data,error:e}=await supabase.functions.invoke('extractor-company-config',{body:{action:'add_from_certificate',certificate_base64:btoa(binary),certificate_password:password,certificate_name:file.name}});if(e||data?.error)throw new Error(data?.error||e?.message||'Não foi possível adicionar a empresa.');onDone(data.company)}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}};return <div className="extractor-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="extractor-modal"><header><div><h2>Adicionar empresa pelo A1</h2><p>O certificado identifica o CNPJ; os dados cadastrais e a IE são buscados automaticamente como no Emissor Fiscal.</p></div><button onClick={onClose}><X/></button></header><div className="extractor-modal-body"><label>Senha do certificado<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha do A1"/></label><label className="extractor-file-field"><span>{file?file.name:'Selecionar certificado .PFX ou .P12'}</span><input type="file" accept=".pfx,.p12,application/x-pkcs12" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p className="extractor-helper">A empresa só entra nesta carteira depois que o A1 for validado. Clientes do painel ADM não são adicionados automaticamente.</p>{error&&<p className="extractor-form-error">{error}</p>}</div><footer><button className="extractor-secondary" onClick={onClose}>Cancelar</button><button className="extractor-primary" onClick={()=>void submit()} disabled={busy}>{busy?'Lendo A1 e cadastrando...':'Adicionar empresa'}</button></footer></div></div>}
function Loading(){return <div className="extractor-loading"><img src="/assets/ws-logo.png" alt="WS Gestão Contábil"/><span/><p>Carregando dados fiscais...</p></div>}
function AccessPending(){return <div className="extractor-access-pending"><img src="/assets/ws-logo.png" alt="WS Gestão Contábil"/><div><h1>Extrato Fiscal não habilitado</h1><p>Esta conta não possui acesso ativo ao produto.</p><a href="/extrator-preview">Abrir demonstração</a></div></div>}
