import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Eye, EyeOff } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import '@/styles/client-login.css';
import '@/styles/shared-entry-visual.css';

const GoogleMark=()=> <svg width="18" height="18" viewBox="0 0 18 18" aria-hidden="true"><path fill="#4285F4" d="M17.64 9.205c0-.638-.057-1.252-.164-1.841H9v3.482h4.844a4.14 4.14 0 0 1-1.797 2.716v2.258h2.909c1.702-1.567 2.684-3.875 2.684-6.615Z"/><path fill="#34A853" d="M9 18c2.43 0 4.468-.806 5.956-2.18l-2.909-2.258c-.806.54-1.835.859-3.047.859-2.344 0-4.328-1.585-5.037-3.714H.956v2.332A8.999 8.999 0 0 0 9 18Z"/><path fill="#FBBC05" d="M3.963 10.707A5.41 5.41 0 0 1 3.682 9c0-.592.102-1.168.281-1.707V4.961H.956A9.001 9.001 0 0 0 0 9c0 1.452.347 2.827.956 4.039l3.007-2.332Z"/><path fill="#EA4335" d="M9 3.579c1.321 0 2.507.454 3.441 1.346l2.581-2.581C13.464.892 11.426 0 9 0A8.999 8.999 0 0 0 .956 4.961l3.007 2.332C4.672 5.164 6.656 3.579 9 3.579Z"/></svg>;

export default function PublicSignupPage(){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const navigate=useNavigate();const [params]=useSearchParams();
 const product=params.get('product')==='extractor'?'extractor':'issuer';const requestedPlan=params.get('plan');const plan=requestedPlan&&['issuer_monthly','extractor_commercial','extractor_enterprise'].includes(requestedPlan)?requestedPlan:(product==='extractor'?'extractor_commercial':'issuer_monthly');const nextPath=`/assinar/${product==='extractor'?'extrator':'emissor'}?plan=${plan}`;
 useEffect(()=>{window.scrollTo(0,0)},[]);
 const google=async()=>{setError('');setLoading(true);localStorage.setItem('ws_signup_destination',nextPath);const {error:e}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}${nextPath}`}});if(e){setError('Não foi possível iniciar o cadastro com Google. Tente novamente ou use seu e-mail.');setLoading(false)}};
 const emailSignup=async(ev:FormEvent)=>{ev.preventDefault();setError('');setMessage('');if(password.length<6){setError('Use uma senha com pelo menos 6 caracteres.');return}setLoading(true);try{localStorage.setItem('ws_signup_destination',nextPath);const {data,error:e}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{emailRedirectTo:`${window.location.origin}${nextPath}`}});if(e)throw e;if(data.session){navigate(nextPath,{replace:true});return}setMessage('Cadastro iniciado. Confira seu e-mail para confirmar e continuar com o plano.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a conta.')}finally{setLoading(false)}};
 return <main className="ws-login-page is-light"><div className="ws-login-shell"><section className="ws-login-presentation"><Link to="/home-preview" className="ws-login-brand"><img src="/assets/ws-logo.png" alt="WS Gestão Contábil"/></Link><div className="ws-login-presentation-copy"><span style={{fontSize:12,letterSpacing:'.14em'}}>CONTA WS</span><h1>Crie seu acesso sem complicação.</h1><p>Cadastre-se para continuar com o {product==='extractor'?'Extrator Fiscal':'Emissor Fiscal'} e ativar seus 7 dias de teste.</p></div><span className="ws-login-signature">WS Gestão Contábil · Alagoas</span></section><section className="ws-login-access"><div className="ws-login-form-wrap"><Link to={product==='extractor'?'/extrator-fiscal':'/emissor-fiscal'} style={{display:'inline-flex',alignItems:'center',gap:6,fontSize:12,marginBottom:28}}><ArrowLeft size={14}/> Voltar ao produto</Link><header className="ws-login-heading"><span>Cadastro</span><h2>Crie sua conta</h2><p>Escolha a forma mais rápida para continuar.</p></header><button type="button" onClick={()=>void google()} disabled={loading} style={{width:'100%',height:48,border:'1px solid #d4d9e0',borderRadius:9,background:'#fff',display:'flex',alignItems:'center',justifyContent:'center',gap:10,fontWeight:600,cursor:'pointer'}}><GoogleMark/> Continuar com Google</button><div style={{display:'flex',alignItems:'center',gap:12,margin:'22px 0',color:'#8090a3',fontSize:11}}><span style={{height:1,background:'#dfe4ea',flex:1}}/>OU CADASTRE COM E-MAIL<span style={{height:1,background:'#dfe4ea',flex:1}}/></div><form onSubmit={emailSignup} className="ws-login-form"><label htmlFor="signup-email">E-mail</label><input id="signup-email" type="email" autoComplete="email" placeholder="voce@gmail.com" value={email} onChange={e=>setEmail(e.target.value)} required/><label htmlFor="signup-password">Senha</label><div className="ws-login-password-field"><input id="signup-password" type={show?'text':'password'} autoComplete="new-password" placeholder="Crie uma senha" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?'Ocultar senha':'Mostrar senha'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>{error&&<div role="alert" className="ws-login-error">{error}</div>}{message&&<div style={{padding:12,border:'1px solid #c7dfd0',borderRadius:8,color:'#2f6b49',fontSize:13}}>{message}</div>}<button type="submit" className="ws-login-submit" disabled={loading}>{loading?'Criando conta...':'Criar conta com e-mail'}</button></form><footer className="ws-login-footer"><p>Já tem uma conta? <Link to={`/login?redirect=${encodeURIComponent(nextPath)}`}>Entrar</Link></p><nav><Link to="/termos-de-servico">Termos de Serviço</Link><Link to="/politica-de-privacidade">Privacidade</Link></nav></footer></div></section></div></main>
}
