import { ChangeEvent, useEffect, useRef, useState } from "react";
import { CalendarDays, Check, ChevronDown, CircleDollarSign, CircleSlash2, Clock3, FilePlus2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import SaasCadastros, { CadastroSection } from "@/components/saas/SaasCadastros";
import SaasEmission from "@/components/saas/SaasEmission";
import SaasFiscalSettings from "@/components/saas/SaasFiscalSettings";

const WS_LOGO="/lovable-uploads/f7fdf0cf-f16c-4df7-a92c-964aadea9539.png";
const groups=[{title:"Cadastros",items:["Clientes","Fornecedores","Produtos","Serviços","Transportadoras"]},{title:"Notas de produtos",items:["Emitir NF-e","Emitir NFC-e","Emitir DF-e"]},{title:"Notas de serviços",items:["Emitir NFS-e"]},{title:"Notas de transportes",items:["Emitir CT-e","Emitir MDF-e"]}];
const cadastroSections=new Set(["Clientes","Fornecedores","Produtos","Serviços","Transportadoras"]);
const tones:any={green:{border:"#b9e8ca",accent:"#16a34a",pale:"#e9f8ef",text:"#13933f"},orange:{border:"#f6d7a8",accent:"#f59e0b",pale:"#fff4df",text:"#ea8c00"},red:{border:"#f4c8c8",accent:"#ef4444",pale:"#fdecec",text:"#e23b3b"},blue:{border:"#c3d7f4",accent:"#3b82f6",pale:"#eaf2ff",text:"#2d6fca"}};

export default function SaasApp(){
 const {user}=useAuth();const [active,setActive]=useState("Início"),[organization,setOrganization]=useState<any>(null),[profileId,setProfileId]=useState<string|null>(null),[logoUrl,setLogoUrl]=useState<string|null>(null),[selectedDocument,setSelectedDocument]=useState<string|null>(null),[filter,setFilter]=useState("Todas as notas"),[month,setMonth]=useState("Agosto de 2026"),[openGroups,setOpenGroups]=useState<Record<string,boolean>>({}),[emissions,setEmissions]=useState<any[]>([]);const fileRef=useRef<HTMLInputElement>(null);
 const loadOrg=async()=>{if(!user)return;const {data}=await (supabase as any).from("organization_members").select("organization_id, organizations(id,name,slug)").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();const org=data?.organizations||(data?.organization_id?{id:data.organization_id,name:"Empresa Teste"}:null);setOrganization(org||{name:"Empresa Teste"});if(!org?.id)return;const [{data:p},{data:e}]=await Promise.all([(supabase as any).from("saas_company_fiscal_profiles").select("id,logo_path").eq("organization_id",org.id).order("created_at").limit(1).maybeSingle(),(supabase as any).from("saas_fiscal_emissions").select("status,total,document_type,created_at").eq("organization_id",org.id).order("created_at",{ascending:false}).limit(500)]);setEmissions(e||[]);if(p?.id)setProfileId(p.id);if(p?.logo_path){const {data:s}=await supabase.storage.from("saas-private").createSignedUrl(p.logo_path,3600);setLogoUrl(s?.signedUrl||null)}};
 useEffect(()=>{void loadOrg()},[user?.id]);
 const chooseNav=(item:string)=>{if(item.startsWith("Emitir ")){setSelectedDocument(item.replace("Emitir ",""));setActive("Emissão");return}setSelectedDocument(null);setActive(item)};
 const handleLogo=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file||!organization?.id)return;const ext=file.name.split(".").pop()?.toLowerCase()||"png",path=`${organization.id}/branding/company-logo-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("saas-private").upload(path,file,{upsert:false,cacheControl:"3600"});if(error)return;if(profileId)await (supabase as any).from("saas_company_fiscal_profiles").update({logo_path:path,updated_at:new Date().toISOString()}).eq("id",profileId);else{const {data:p}=await (supabase as any).from("saas_company_fiscal_profiles").insert({organization_id:organization.id,logo_path:path}).select("id").maybeSingle();if(p?.id)setProfileId(p.id)}const {data:s}=await supabase.storage.from("saas-private").createSignedUrl(path,3600);setLogoUrl(s?.signedUrl||null);event.target.value=""};
 const approved=emissions.filter(x=>x.status==="authorized"),pending=emissions.filter(x=>["draft","validated"].includes(x.status)),cancelled=emissions.filter(x=>x.status==="cancelled"),total=approved.reduce((a,x)=>a+Number(x.total||0),0),ticket=approved.length?total/approved.length:0;
 const kpis=[{label:"Notas aprovadas",value:`R$ ${total.toLocaleString("pt-BR",{minimumFractionDigits:2})}`,status:`${approved.length} documento(s) aprovado(s)`,tone:"green",icon:Check},{label:"Notas pendentes",value:`${pending.length}`,status:"Documentos aguardando conclusão",tone:"orange",icon:Clock3},{label:"Notas canceladas",value:`${cancelled.length}`,status:"Documentos cancelados",tone:"red",icon:CircleSlash2},{label:"Ticket médio",value:`R$ ${ticket.toLocaleString("pt-BR",{minimumFractionDigits:2})}`,status:"Média das emissões autorizadas",tone:"blue",icon:CircleDollarSign}];
 const Chart=({title}:{title:string})=><section className="rounded-2xl border border-[#e1e6ec] bg-white p-5"><h3 className="text-[15px] font-semibold">{title}</h3><div className="mt-6 flex h-[230px] items-end gap-3 rounded-xl bg-[#fbfcfe] p-7">{[28,48,36,62,44,72,54,66].map((h,i)=><div key={i} className="flex-1 rounded-t-md bg-[#dce9fa]" style={{height:`${emissions.length?Math.max(10,h):8}%`}}/>)}</div></section>;
 const Dashboard=()=> <div><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><h1 className="text-[27px] font-semibold tracking-[-.035em]">Bom dia, {organization?.name||"Sua empresa"}</h1><p className="mt-2 text-sm text-[#68758c]">Veja o resumo da sua atividade fiscal e gerencie suas notas.</p></div><div className="flex flex-wrap gap-3"><button onClick={()=>setFilter(filter==="Todas as notas"?"Notas aprovadas":"Todas as notas")} className="flex h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm">{filter}<ChevronDown className="h-4 w-4"/></button><button onClick={()=>setMonth(month==="Agosto de 2026"?"Julho de 2026":"Agosto de 2026")} className="flex h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm"><CalendarDays className="h-4 w-4"/>{month}<ChevronDown className="h-4 w-4"/></button><Button onClick={()=>{setSelectedDocument(null);setActive("Emissão")}} className="h-11 bg-[#0b5bd7] text-white"><FilePlus2 className="mr-2 h-4 w-4"/>Emitir nova nota</Button></div></div><div className="mt-8 grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{kpis.map(item=>{const t=tones[item.tone],Icon=item.icon;return <div key={item.label} className="relative min-h-[146px] overflow-hidden rounded-2xl border bg-white px-6 py-5" style={{borderColor:t.border}}><div className="absolute inset-y-0 left-0 w-1" style={{backgroundColor:t.accent}}/><div className="absolute right-5 top-1/2 grid h-16 w-16 -translate-y-1/2 place-items-center rounded-full" style={{backgroundColor:t.pale}}><Icon className="h-8 w-8" style={{color:t.accent}}/></div><p className="text-sm font-medium" style={{color:t.text}}>{item.label}</p><p className="mt-4 text-2xl font-semibold">{item.value}</p><p className="mt-5 max-w-[70%] text-xs" style={{color:t.text}}>{item.status}</p></div>})}</div><div className="mt-6 grid gap-5 xl:grid-cols-2"><Chart title="Faturamento por modalidade"/><Chart title="Notas aprovadas x notas canceladas"/><Chart title="Notas emitidas por cliente"/><Chart title="Produtos mais vendidos"/></div></div>;
 const Reports=()=> <div><h1 className="text-3xl font-semibold">Relatórios</h1><p className="mt-2 text-sm text-[#6d7a90]">Consolidação das emissões registradas no sistema.</p><div className="mt-7 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-white p-6"><p className="text-sm text-[#6d7a90]">Total autorizado</p><p className="mt-3 text-2xl font-semibold">R$ {total.toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div><div className="rounded-2xl border bg-white p-6"><p className="text-sm text-[#6d7a90]">Documentos autorizados</p><p className="mt-3 text-2xl font-semibold">{approved.length}</p></div><div className="rounded-2xl border bg-white p-6"><p className="text-sm text-[#6d7a90]">Ticket médio</p><p className="mt-3 text-2xl font-semibold">R$ {ticket.toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div></div></div>;
 let content:any;if(active==="Início")content=<Dashboard/>;else if(cadastroSections.has(active))content=<SaasCadastros organizationId={organization?.id||null} section={active as CadastroSection}/>;else if(active==="Emissão")content=<SaasEmission organizationId={organization?.id||null} documentType={selectedDocument} onChoose={setSelectedDocument}/>;else if(active==="Configurações")content=<SaasFiscalSettings organizationId={organization?.id||null}/>;else if(active==="Relatórios")content=<Reports/>;
 return <div className="min-h-screen bg-[#f6f8fb] text-[#10203e]"><header className="fixed inset-x-0 top-0 z-40 flex h-[82px] items-center border-b border-[#e2e7ee] bg-white px-7"><div className="flex w-[250px] items-center"><img src={WS_LOGO} alt="WS Assessoria Contábil" className="h-14 max-w-[230px] object-contain"/></div></header><aside className="fixed bottom-0 left-0 top-[82px] z-30 w-[250px] overflow-y-auto border-r border-[#e3e7ed] bg-white"><div className="border-b border-[#edf0f4] p-4"><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={handleLogo}/>{logoUrl?<button onClick={()=>fileRef.current?.click()} className="flex h-[126px] w-full items-center justify-center overflow-hidden rounded-2xl bg-white"><img src={logoUrl} alt="Logomarca da empresa" className="max-h-full max-w-full object-contain"/></button>:<button onClick={()=>fileRef.current?.click()} className="flex h-[126px] w-full flex-col items-center justify-center rounded-2xl border border-dashed border-[#cfd7e2] bg-[#fbfcfe]"><span className="text-sm font-semibold">Sua logomarca</span><span className="mt-1 text-xs text-[#8a96a8]">Clique para enviar</span></button>}</div><nav className="p-3"><button onClick={()=>chooseNav("Início")} className={`w-full rounded-xl px-4 py-3 text-left text-sm font-semibold ${active==="Início"?"bg-[#eaf2ff] text-[#1e63c6]":"text-[#43526b] hover:bg-[#f5f7fa]"}`}>Início</button><div className="mt-2 space-y-1">{groups.map(g=><div key={g.title}><button onClick={()=>setOpenGroups(p=>({...p,[g.title]:!p[g.title]}))} className="flex w-full items-center justify-between rounded-xl px-4 py-3 text-left text-sm font-semibold text-[#273953] hover:bg-[#f5f7fa]"><span>{g.title}</span><span>{openGroups[g.title]?"−":"+"}</span></button>{openGroups[g.title]&&<div className="mb-2 ml-3 border-l border-[#e5e9ef] pl-2">{g.items.map(item=><button key={item} onClick={()=>chooseNav(item)} className={`block w-full rounded-lg px-3 py-2.5 text-left text-sm ${item.startsWith("Emitir ")&&selectedDocument===item.replace("Emitir ","")?"bg-[#eef4fd] font-semibold text-[#2468c7]":"text-[#657289] hover:bg-[#f6f8fb]"}`}>{item}</button>)}</div>}</div>)}</div><div className="mt-3 border-t pt-3"><button onClick={()=>chooseNav("Relatórios")} className="w-full rounded-xl px-4 py-3 text-left text-sm font-semibold text-[#43526b] hover:bg-[#f5f7fa]">Relatórios</button><button onClick={()=>chooseNav("Configurações")} className="w-full rounded-xl px-4 py-3 text-left text-sm font-semibold text-[#43526b] hover:bg-[#f5f7fa]">Configurações</button></div></nav></aside><main className="min-h-screen pl-[250px] pt-[82px]"><div className="mx-auto max-w-[1540px] p-7 xl:p-9">{content}</div></main></div>;
}