import { useEffect, useState } from "react";
import { BarChart3, Boxes, Building2, ChevronDown, FileInput, FileText, Home, Package2, ReceiptText, Settings2, ShoppingBag, Truck, UserRound, UsersRound } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import SaasCadastros, { CadastroSection } from "@/components/saas/SaasCadastros";
import SaasEmission from "@/components/saas/SaasEmission";
import SaasCompanyProfile from "@/components/saas/SaasCompanyProfile";
import SaasReports from "@/components/saas/SaasReports";
import SaasDashboard from "@/components/saas/SaasDashboard";

const WS_LOGO="/lovable-uploads/f7fdf0cf-f16c-4df7-a92c-964aadea9539.png";
const cadastroSections=new Set(["Clientes","Fornecedores","Produtos","Serviços","Transportadoras"]);
const groups=[
 {title:"Cadastros",icon:Boxes,items:[{label:"Clientes",icon:UsersRound},{label:"Fornecedores",icon:Building2},{label:"Produtos",icon:Package2},{label:"Serviços",icon:ShoppingBag},{label:"Transportadoras",icon:Truck}]},
 {title:"Notas de produtos",icon:ReceiptText,items:[{label:"Emitir NF-e",icon:FileText},{label:"Emitir NFC-e",icon:FileInput},{label:"Emitir DF-e",icon:FileText}]},
 {title:"Notas de serviços",icon:ShoppingBag,items:[{label:"Emitir NFS-e",icon:ReceiptText}]},
 {title:"Notas de transportes",icon:Truck,items:[{label:"Emitir CT-e",icon:FileText},{label:"Emitir MDF-e",icon:FileText}]},
];
const lightVars:any={"--background":"0 0% 100%","--foreground":"222.2 84% 4.9%","--card":"0 0% 100%","--card-foreground":"222.2 84% 4.9%","--popover":"0 0% 100%","--popover-foreground":"222.2 84% 4.9%","--primary":"222.2 47.4% 11.2%","--primary-foreground":"210 40% 98%","--secondary":"210 40% 96.1%","--secondary-foreground":"222.2 47.4% 11.2%","--muted":"210 40% 96.1%","--muted-foreground":"215.4 16.3% 46.9%","--accent":"210 40% 96.1%","--accent-foreground":"222.2 47.4% 11.2%","--border":"214.3 31.8% 91.4%","--input":"214.3 31.8% 91.4%","--ring":"222.2 84% 4.9%"};

export default function SaasApp(){
 const {user}=useAuth();
 const [active,setActive]=useState("Início"),[organization,setOrganization]=useState<any>(null),[logoUrl,setLogoUrl]=useState<string|null>(null),[selectedDocument,setSelectedDocument]=useState<string|null>(null),[openGroups,setOpenGroups]=useState<Record<string,boolean>>({Cadastros:true,"Notas de produtos":true,"Notas de serviços":true,"Notas de transportes":true}),[emissions,setEmissions]=useState<any[]>([]);
 const loadOrg=async()=>{if(!user)return;const {data}=await (supabase as any).from("organization_members").select("organization_id, organizations(id,name,slug)").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();const org=data?.organizations||(data?.organization_id?{id:data.organization_id,name:"Empresa Teste"}:null);setOrganization(org||{name:"Empresa Teste"});if(!org?.id)return;const [{data:p},{data:e}]=await Promise.all([(supabase as any).from("saas_company_fiscal_profiles").select("logo_path,trade_name,legal_name").eq("organization_id",org.id).order("created_at").limit(1).maybeSingle(),(supabase as any).from("saas_fiscal_emissions").select("*").eq("organization_id",org.id).order("created_at",{ascending:false}).limit(800)]);setEmissions(e||[]);if(p?.trade_name||p?.legal_name)setOrganization((x:any)=>({...x,name:p.trade_name||p.legal_name}));if(p?.logo_path){const {data:s}=await supabase.storage.from("saas-private").createSignedUrl(p.logo_path,3600);setLogoUrl(s?.signedUrl||null)}};
 useEffect(()=>{void loadOrg()},[user?.id]);
 const chooseNav=(item:string)=>{if(item.startsWith("Emitir ")){setSelectedDocument(item.replace("Emitir ",""));setActive("Emissão");return}setSelectedDocument(null);setActive(item)};
 const isItemActive=(label:string)=>label.startsWith("Emitir ")?active==="Emissão"&&selectedDocument===label.replace("Emitir ",""):active===label;
 const isGroupActive=(title:string)=>groups.find(x=>x.title===title)?.items.some(x=>isItemActive(x.label))||false;
 let content:any;
 if(active==="Início")content=<SaasDashboard organizationName={organization?.name} emissions={emissions} onNew={()=>{setSelectedDocument(null);setActive("Emissão")}} onReports={()=>setActive("Relatórios")}/>;
 else if(cadastroSections.has(active))content=<SaasCadastros organizationId={organization?.id||null} section={active as CadastroSection}/>;
 else if(active==="Emissão")content=<SaasEmission organizationId={organization?.id||null} documentType={selectedDocument} onChoose={setSelectedDocument}/>;
 else if(active==="Minha Empresa")content=<SaasCompanyProfile organizationId={organization?.id||null} organizationName={organization?.name} onLogoChanged={setLogoUrl}/>;
 else if(active==="Relatórios")content=<SaasReports organizationId={organization?.id||null}/>;
 return <div className="flex min-h-screen bg-background text-foreground" style={lightVars}>
  <aside className="sticky top-0 flex h-screen w-72 shrink-0 flex-col border-r border-border/60 bg-background">
   <div className="flex h-20 shrink-0 items-center justify-center border-b border-border/60 px-5"><img src={WS_LOGO} alt="WS Gestão Contábil" className="h-7 object-contain"/></div>
   <div className="border-b border-border/50 px-4 py-4"><button onClick={()=>setActive("Minha Empresa")} className="flex w-full items-center gap-3 rounded-xl px-2 py-2 text-left transition hover:bg-muted/45"><div className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-xl border border-border/60 bg-muted/25">{logoUrl?<img src={logoUrl} alt="Logo da empresa" className="max-h-7 max-w-7 object-contain"/>:<Building2 className="h-4 w-4 text-muted-foreground"/>}</div><div className="min-w-0"><p className="truncate text-sm font-medium tracking-tight">{organization?.name||"Sua empresa"}</p><p className="mt-0.5 text-[10px] uppercase tracking-[.12em] text-muted-foreground">Ambiente fiscal</p></div></button></div>
   <nav className="flex-1 overflow-y-auto px-3 py-4">
    <section><p className="mb-2 px-4 text-[9px] font-semibold uppercase tracking-[0.14em] text-muted-foreground/90">Visão geral</p><button onClick={()=>chooseNav("Início")} className={`group flex w-full items-center gap-3 rounded-md border-l-2 px-4 py-2.5 text-left transition-colors ${active==="Início"?"border-foreground/60 bg-muted text-foreground":"border-transparent text-muted-foreground hover:bg-muted/60 hover:text-foreground"}`}><Home size={17} strokeWidth={1.75}/><span className="text-sm font-medium tracking-tight">Início</span></button></section>
    <div className="mt-5 space-y-5">{groups.map(g=>{const Icon=g.icon,expanded=openGroups[g.title],groupActive=isGroupActive(g.title);return <section key={g.title}><p className="mb-2 px-4 text-[9px] font-semibold uppercase tracking-[0.14em] text-muted-foreground/90">{g.title}</p><button onClick={()=>setOpenGroups(p=>({...p,[g.title]:!p[g.title]}))} className={`group flex w-full items-center gap-3 rounded-md border-l-2 px-4 py-2.5 text-left transition-colors ${groupActive?"border-foreground/60 bg-muted/70 text-foreground":"border-transparent text-muted-foreground hover:bg-muted/60 hover:text-foreground"}`}><Icon size={17} strokeWidth={1.75}/><span className="flex-1 text-sm font-medium tracking-tight">{g.title.replace("Notas de ","")}</span><ChevronDown className={`h-3.5 w-3.5 transition-transform ${expanded?"rotate-180":""}`}/></button><div className={`ml-7 overflow-hidden border-l border-border pl-3 transition-all duration-200 ${expanded?"mt-1 max-h-80 opacity-100":"max-h-0 opacity-0"}`}>{g.items.map(item=>{const ItemIcon=item.icon,a=isItemActive(item.label);return <button key={item.label} onClick={()=>chooseNav(item.label)} className={`flex w-full items-center gap-2.5 rounded-sm px-3 py-2 text-left text-xs transition-colors ${a?"bg-muted font-medium text-foreground":"text-muted-foreground hover:bg-muted/60 hover:text-foreground"}`}><ItemIcon className="h-3.5 w-3.5"/><span>{item.label}</span></button>})}</div></section>})}</div>
    <section className="mt-5 border-t border-border/60 pt-4"><p className="mb-2 px-4 text-[9px] font-semibold uppercase tracking-[0.14em] text-muted-foreground/90">Gestão</p><button onClick={()=>chooseNav("Relatórios")} className={`group flex w-full items-center gap-3 rounded-md border-l-2 px-4 py-2.5 text-left transition-colors ${active==="Relatórios"?"border-foreground/60 bg-muted text-foreground":"border-transparent text-muted-foreground hover:bg-muted/60 hover:text-foreground"}`}><BarChart3 size={17} strokeWidth={1.75}/><span className="text-sm font-medium tracking-tight">Relatórios</span></button><button onClick={()=>chooseNav("Minha Empresa")} className={`group mt-1 flex w-full items-center gap-3 rounded-md border-l-2 px-4 py-2.5 text-left transition-colors ${active==="Minha Empresa"?"border-foreground/60 bg-muted text-foreground":"border-transparent text-muted-foreground hover:bg-muted/60 hover:text-foreground"}`}><Settings2 size={17} strokeWidth={1.75}/><span className="text-sm font-medium tracking-tight">Minha Empresa</span></button></section>
   </nav>
  </aside>
  <div className="flex min-w-0 flex-1 flex-col"><header className="flex h-20 shrink-0 items-center border-b border-border/60 bg-background px-6"><div className="flex-1"/><div className="min-w-0 flex-1 text-center"><p className="truncate text-sm font-medium">{organization?.name||"Sua empresa"}</p><p className="mt-0.5 text-[10px] uppercase tracking-[.12em] text-muted-foreground">Painel fiscal</p></div><div className="flex flex-1 justify-end"><div className="grid h-9 w-9 place-items-center rounded-lg border border-border/60 bg-background"><UserRound className="h-4 w-4 text-muted-foreground"/></div></div></header><main className="flex-1 overflow-auto bg-background"><div className="mx-auto w-full max-w-[1540px] px-4 py-5 sm:px-5 sm:py-6 lg:px-8">{content}</div></main></div>
 </div>;
}
