import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/integrations/supabase/client"; import { ChartAccount } from "@/lib/lancamentos/chartOfAccounts"; import { detectWorkbookCompetence } from "@/lib/lancamentos/expenseWorkbook";
import { PayrollEntry, exportPayroll } from "@/lib/lancamentos/payrollWorkbook"; import { loadWorkspaceData, loadWorkspaceFiles, saveWorkspaceData, saveWorkspaceFiles } from "@/lib/lancamentos/workspaceStorage"; import { WorkspaceStatus } from "./DespesasWorkspace"; import { cn } from "@/lib/utils";
interface Props { company: string; month: string; year: string; onStatusChange: (status: WorkspaceStatus) => void; onCompetenceChange: (month: string, year: string) => void; }
interface SavedPayroll { entries: PayrollEntry[]; errors: string[]; }
const cell = "h-8 rounded-none border-0 bg-transparent px-2 shadow-none focus-visible:ring-1"; const money = (c:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);
export function FolhaWorkspace({ company, month, year, onStatusChange, onCompetenceChange }: Props) {
 const input=useRef<HTMLInputElement>(null); const [entries,setEntries]=useState<PayrollEntry[]>([]); const [files,setFiles]=useState<File[]>([]); const [errors,setErrors]=useState<string[]>([]); const [processing,setProcessing]=useState(false); const [loaded,setLoaded]=useState(false); const [accounts,setAccounts]=useState<ChartAccount[]>([]);
 const scope=`${company}:${year}:${month}:folha`, key=`${scope}:parsed`, competence=`${month}/${year}`; const total=entries.reduce((s,r)=>s+r.amountInCents,0); const missing=entries.filter(r=>!r.debitCode||!r.creditCode||!r.debitDescription||!r.creditDescription).length;
 useEffect(()=>{let active=true; Promise.all([loadWorkspaceData<SavedPayroll>(key),loadWorkspaceFiles(scope),loadWorkspaceData<ChartAccount[]>(`${company}:chart-of-accounts`)]).then(([saved,docs,chart])=>{if(!active)return;if(saved){setEntries(saved.entries);setErrors(saved.errors)}setFiles(docs);setAccounts(chart??[]);setLoaded(true)});return()=>{active=false}},[company,key,scope]);
 useEffect(()=>{if(loaded)void saveWorkspaceData(key,{entries,errors})},[entries,errors,key,loaded]);
 const update=(id:string,field:keyof PayrollEntry,value:string)=>setEntries(rows=>rows.map(r=>r.id===id?{...r,[field]:field==="amountInCents"?Math.round(Number(value.replace(/\D/g,""))):value}:r));
 const importFiles=async(event:ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(event.target.files??[]);event.target.value="";if(!selected.length)return;const detected=(await Promise.all(selected.map(detectWorkbookCompetence))).find(Boolean);if(detected&&(detected.month!==month||detected.year!==year)){const proceed=window.confirm(`O documento pertence a ${detected.month}/${detected.year}. Ele será salvo nessa competência. Deseja continuar?`);if(!proceed)return;await saveWorkspaceFiles(`${company}:${detected.year}:${detected.month}:folha`,selected);onCompetenceChange(detected.month,detected.year);return;}await saveWorkspaceFiles(scope,selected);setFiles(current=>[...current,...selected]);onStatusChange("review");await processFiles(selected)};
 const processFiles=async(selected:File[])=>{if(!accounts.length){setErrors(["Importe o plano de contas desta empresa antes de processar a folha."]);return;}setProcessing(true);setErrors([]);try{const documents=await Promise.all(selected.map(async file=>({name:file.name,mime_type:file.type||"application/pdf",data:await asBase64(file)})));const {data,error}=await supabase.functions.invoke("process-accounting-document",{body:{module:"folha",company_id:company,competence,documents,chart_of_accounts:accounts}});if(error)throw error;if(!data?.entries)throw new Error("A IA não devolveu lançamentos estruturados.");setEntries(current=>[...current,...data.entries.map((r:PayrollEntry,i:number)=>({...r,id:r.id||`${Date.now()}-${i}`}))]);setErrors(data.warnings??[]);}catch(error){setErrors([error instanceof Error?error.message:"Falha ao processar a folha com IA."]);}finally{setProcessing(false)}};
 const add=()=>setEntries(rows=>[...rows,{id:String(Date.now()),date:`${new Date(+year,+month,0).getDate()}/${month}/${year}`,history:"",debitCode:"",debitDescription:"",debitCostCenter:"",creditCode:"",creditDescription:"",creditCostCenter:"",amountInCents:0,source:"manual"}]);
 return <section className="mt-8 space-y-8"><div className="rounded-md border border-border bg-background p-6"><div className="flex items-center justify-between gap-5"><div><h3 className="font-semibold">Folha de pagamento de {competence}</h3><p className="mt-1 text-sm text-muted-foreground">Documentos protegidos e vinculados à empresa e competência.</p></div><Button variant="outline" onClick={()=>input.current?.click()} disabled={processing}>{processing?"Processando com IA...":`Importar folha de ${competence}`}</Button><input ref={input} type="file" multiple accept=".pdf,.xlsx,.xls" className="sr-only" onChange={e=>void importFiles(e)}/></div><div className="mt-5 border-t border-border pt-5 text-sm text-muted-foreground">{files.length?files.map(f=><span key={`${f.name}-${f.size}`} className="mr-5 text-foreground">{f.name}</span>):"Nenhum documento importado."}</div></div>
 <Tabs defaultValue="transcricao"><TabsList className="grid h-auto w-full grid-cols-3 gap-3 bg-transparent p-0"><Flow value="transcricao" label="Transcrição" count={entries.length}/><Flow value="lancamentos" label="Lançamentos" count={entries.length}/><Flow value="conferencia" label="Conferência" count={errors.length+missing}/></TabsList>
 <TabsContent value="transcricao" className="mt-7"><Header title="Folha de pagamento · Transcrição"/><Ledger rows={entries} editable update={update}/><div className="mt-4 flex justify-end"><Button variant="outline" onClick={add}>Adicionar linha</Button></div></TabsContent>
 <TabsContent value="lancamentos" className="mt-7"><Header title="Folha de pagamento · Lançamentos"/><div className="rounded-md border border-border bg-background"><div className="flex items-center justify-between border-b border-border p-5"><span className="text-sm text-muted-foreground">{entries.length} lançamentos · {money(total)}</span><Button disabled={!entries.length||missing>0} onClick={()=>exportPayroll(entries,competence)}>Exportar para o Calima</Button></div><Ledger rows={entries}/></div></TabsContent>
 <TabsContent value="conferencia" className="mt-7"><Header title="Folha de pagamento · Conferência"/><div className="rounded-md border border-border bg-background p-6"><div className="grid gap-5 sm:grid-cols-3"><Stat label="Total" value={money(total)}/><Stat label="Contas incompletas" value={missing}/><Stat label="Avisos" value={errors.length}/></div>{errors.map(e=><p key={e} className="mt-4 text-sm text-destructive">{e}</p>)}<div className="mt-6 flex justify-end"><Button disabled={!entries.length||missing>0} onClick={()=>onStatusChange("done")}>Marcar folha como OK</Button></div></div></TabsContent></Tabs></section>;
}
function Flow({value,label,count}:{value:string;label:string;count:number}){return <TabsTrigger value={value} className="min-h-16 border border-border data-[state=active]:bg-foreground data-[state=active]:text-background">{label}<span className="ml-2 rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">{count}</span></TabsTrigger>}
function Header({title}:{title:string}){return <div className="mb-5"><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">Documento original e dados extraídos no mesmo espaço.</p></div>}
function Stat({label,value}:{label:string;value:string|number}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
function Ledger({rows,editable,update}:{rows:PayrollEntry[];editable?:boolean;update?:(id:string,field:keyof PayrollEntry,value:string)=>void}){const cols:Array<[string,keyof PayrollEntry,string]>=[["Data","date","w-28"],["Histórico","history","min-w-[260px]"],["Débito","debitCode","w-20"],["Descrição débito","debitDescription","min-w-[180px]"],["C.C. débito","debitCostCenter","w-24"],["Crédito","creditCode","w-20"],["Descrição crédito","creditDescription","min-w-[180px]"],["C.C. crédito","creditCostCenter","w-24"]];return <div className="overflow-x-auto rounded-md border border-border bg-background"><table className="w-full min-w-[1450px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr>{cols.map(([l,,w])=><th key={l} className={cn("border-b border-r border-border px-3 py-2",w)}>{l}</th>)}<th className="border-b border-border px-3 py-2 text-right">Valor</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-border">{cols.map(([,f])=><td key={f} className="border-r border-border">{editable?<Input className={cell} value={String(r[f]??"")} onChange={e=>update?.(r.id,f,e.target.value)}/>:<span className="block px-3 py-2">{String(r[f]||"—")}</span>}</td>)}<td className="px-3 py-2 text-right">{editable?<Input className={cn(cell,"text-right")} value={(r.amountInCents/100).toFixed(2).replace(".",",")} onChange={e=>update?.(r.id,"amountInCents",e.target.value)}/>:money(r.amountInCents)}</td></tr>)}{!rows.length&&<tr><td colSpan={9} className="h-40 text-center text-muted-foreground">Importe a folha para iniciar.</td></tr>}</tbody></table></div>}
function asBase64(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
