
import { supabase } from "@/integrations/supabase/client";
import { Notification, DatabaseNotification } from "@/types/notifications";

/**
 * Converts a database notification to application notification format
 */
const mapDatabaseNotification = (dbNotification: DatabaseNotification): Notification => {
  return {
    ...dbNotification,
    read_at: null // Since read_at doesn't exist in the database, default to null
  };
};

/**
 * Fetches all notifications for a user
 * @param userId User ID to fetch notifications for
 */
export const fetchUserNotifications = async (userId: string): Promise<Notification[]> => {
  if (!userId) throw new Error("User ID is required");
  
  console.log("Buscando notificações para o usuário:", userId);
  const { data, error } = await supabase
    .from('notifications')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error("Erro ao buscar notificações:", error);
    throw error;
  }
  
  console.log(`${data?.length || 0} notificações encontradas`);
  
  // Map database notifications to application notifications
  return (data || []).map(notification => mapDatabaseNotification(notification as DatabaseNotification));
};

/**
 * Creates a notification for a user
 * @param userId User ID to create notification for
 * @param message Notification message
 * @param type Notification type
 */
export const createNotification = async (userId: string, message: string, type?: string) => {
  if (!userId || !message) throw new Error("User ID and message are required");
  
  console.log(`Criando notificação tipo "${type}" para usuário:`, userId);
  
  // Create database notification - only include fields that exist in database
  const dbNotification: DatabaseNotification = {
    id: '', // Will be generated by DB
    user_id: userId,
    message,
    created_at: '', // Will be generated by DB
    type: type || null
  };
  
  const { data, error } = await supabase
    .from('notifications')
    .insert(dbNotification)
    .select()
    .single();
    
  if (error) {
    console.error("Erro ao criar notificação:", error);
    throw error;
  }
  
  console.log("Notificação criada com sucesso:", data);
  return mapDatabaseNotification(data as DatabaseNotification);
};

/**
 * Creates a login notification
 * @param userId User ID
 */
export const createLoginNotification = async (userId: string) => {
  return createNotification(userId, "Login realizado com sucesso.", "login");
};

/**
 * Creates a logout notification
 * @param userId User ID
 */
export const createLogoutNotification = async (userId: string) => {
  return createNotification(userId, "Logout realizado com sucesso.", "logout");
};

/**
 * Creates a new document notification
 * @param userId User ID
 * @param documentName Document name
 */
export const createDocumentNotification = async (userId: string, documentName: string) => {
  return createNotification(userId, `Novo documento recebido: ${documentName}`, "Novo Documento");
};

/**
 * Deletes all notifications for a user
 * @param userId User ID to delete notifications for
 */
export const deleteAllUserNotifications = async (userId: string) => {
  if (!userId) throw new Error("User ID is required");
  
  console.log("Excluindo todas as notificações para o usuário:", userId);
  const { error } = await supabase
    .from('notifications')
    .delete()
    .eq('user_id', userId);
    
  if (error) {
    console.error("Erro ao excluir notificações:", error);
    throw error;
  }
  
  console.log("Todas as notificações foram excluídas com sucesso");
};

/**
 * Mark document-related notifications as read
 * @param userId User ID
 * @param documentId Document ID
 */
export const markDocumentNotificationsAsRead = async (userId: string, documentId?: string) => {
  if (!userId) throw new Error("User ID is required");
  
  console.log(`Marcando notificações de documento como lidas para usuário: ${userId} ${documentId ? `(documento: ${documentId})` : ''}`);
  
  // Since the database doesn't have read_at field, we'll delete the notifications instead
  // as a workaround until the database schema is updated
  let query = supabase
    .from('notifications')
    .delete()
    .eq('user_id', userId)
    .eq('type', 'Novo Documento');
    
  // If a document ID is specified, only delete notifications for that document
  if (documentId) {
    // Assumes the document ID is contained in the message
    query = query.ilike('message', `%${documentId}%`);
  }
    
  const { error } = await query;
    
  if (error) {
    console.error("Erro ao marcar notificações como lidas:", error);
    throw error;
  }
  
  console.log("Notificações marcadas como lidas com sucesso");
};
