import { useEffect, useState } from "react";
import { Activity, CheckCircle2, Lock, LogOut, MonitorCog, RefreshCw, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import ThemeToggle from "@/components/ThemeToggle";
import { AdminPageHeader, AdminSection } from "@/components/admin/ui/AdminPage";

export const SettingsView=()=>{
 const {toast}=useToast();const {signOut,user}=useAuth();
 const [tab,setTab]=useState<'general'|'health'>('general');
 const [newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const changePassword=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(newPassword.length<8){setError('Use uma senha com pelo menos 8 caracteres.');return}if(newPassword!==confirm){setError('As senhas não conferem.');return}setLoading(true);const {error:authError}=await supabase.auth.updateUser({password:newPassword});if(authError)setError(authError.message);else{setNewPassword('');setConfirm('');toast({title:'Senha alterada',description:'Sua senha foi atualizada com sucesso.'})}setLoading(false)};
 return <div>
  <AdminPageHeader eyebrow="Administração" title="Configurações" description="Preferências do Admin e segurança da sua conta."/>
  <div className="mt-5 flex gap-2 border-b border-border/60"><button onClick={()=>setTab('general')} className={`px-3 py-2 text-sm font-medium ${tab==='general'?'border-b-2 border-primary text-foreground':'text-muted-foreground'}`}>Geral</button><button onClick={()=>setTab('health')} className={`inline-flex items-center gap-2 px-3 py-2 text-sm font-medium ${tab==='health'?'border-b-2 border-primary text-foreground':'text-muted-foreground'}`}><Activity className="h-4 w-4"/>Saúde das buscas</button></div>
  {tab==='health'?<FiscalHealth/>:<div className="mt-6 grid gap-5 lg:grid-cols-2">
   <AdminSection className="p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-muted/45"><Lock className="h-5 w-5"/></span><div><h2 className="font-semibold">Segurança da conta</h2><p className="text-xs text-muted-foreground">{user?.email}</p></div></div><form onSubmit={changePassword} className="mt-6 space-y-4"><Field label="Nova senha"><Input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field><Field label="Confirmar nova senha"><Input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></Field>{error&&<p className="text-sm text-destructive">{error}</p>}<Button className="w-full" disabled={loading}>{loading?'Salvando...':'Alterar senha'}</Button></form><Button variant="outline" className="mt-3 w-full text-destructive hover:text-destructive" onClick={()=>void signOut()}><LogOut className="mr-2 h-4 w-4"/>Sair da conta</Button></AdminSection>
   <AdminSection className="p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-muted/45"><MonitorCog className="h-5 w-5"/></span><div><h2 className="font-semibold">Aparência</h2><p className="text-xs text-muted-foreground">Escolha o tema do painel administrativo.</p></div></div><div className="mt-6 rounded-xl border border-border/60 bg-muted/10 p-4"><p className="mb-3 text-xs font-medium text-muted-foreground">Tema</p><ThemeToggle/></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Ambiente" value="Produção"/><Info label="Interface" value="Admin v2"/></div></AdminSection>
  </div>}
 </div>
}
type SyncRow={company_id:string;status?:string;consecutive_failures?:number;last_status_code?:string;last_status_message?:string;last_completed_at?:string;last_failed_at?:string;last_error?:string;next_scheduled_at?:string;updated_at?:string;latest_number?:number;cursor_number?:number;reconciliation_total?:number;reconciliation_resolved?:number;reconciliation_pending?:number;reconciliation_complete?:boolean;paused?:boolean};
function FiscalHealth(){
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[data,setData]=useState<{purchases:SyncRow[];sales:SyncRow[];generated_at:string}|null>(null);
 const load=async()=>{setLoading(true);setError('');const {data:result,error:fnError}=await supabase.functions.invoke('admin-fiscal-health');if(fnError||result?.error)setError(result?.error||fnError?.message||'Falha ao carregar logs');else setData(result);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const fmt=(v?:string)=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
 const Card=({title,rows}:{title:string;rows:SyncRow[]})=><AdminSection className="p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Monitoramento</p><h2 className="mt-1 text-lg font-semibold">{title}</h2></div><span className="text-xs text-muted-foreground">{rows.length} empresa(s)</span></div>{rows.length===0?<p className="mt-6 text-sm text-muted-foreground">Nenhum registro de sincronização.</p>:<div className="mt-5 space-y-3">{rows.map((row)=><div key={row.company_id} className="rounded-xl border border-border/60 bg-muted/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 font-medium"><StatusIcon status={row.status}/>{row.status||'sem status'}</div><span className="font-mono text-xs text-muted-foreground">{row.company_id.slice(0,8)}…</span></div><div className="mt-3 grid gap-3 text-xs sm:grid-cols-2"><Info label="Última conclusão" value={fmt(row.last_completed_at)}/><Info label="Última falha" value={fmt(row.last_failed_at)}/><Info label="Código SEFAZ" value={row.last_status_code||'—'}/><Info label="Próxima execução" value={fmt(row.next_scheduled_at)}/></div>{row.last_error&&<p className="mt-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{row.last_error}</p>}{title==='Vendas'&&<p className="mt-3 text-xs text-muted-foreground">Reconciliação: {row.reconciliation_resolved??0}/{row.reconciliation_total??0} resolvidos · {row.reconciliation_pending??0} pendentes</p>}</div>)}</div>}</AdminSection>;
 return <div className="mt-6 space-y-5">{error&&<div className="flex items-center justify-between rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Tentar novamente</Button></div>}{loading?<div className="flex items-center gap-2 py-10 text-sm text-muted-foreground"><RefreshCw className="h-4 w-4 animate-spin"/>Carregando saúde das buscas…</div>:data&&<><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">Atualizado em {fmt(data.generated_at)}</p><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Atualizar</Button></div><div className="grid gap-5 lg:grid-cols-2"><Card title="Compras" rows={data.purchases}/><Card title="Vendas" rows={data.sales}/></div></>}</div>
}
function StatusIcon({status}:{status?:string}){const ok=status==='idle'||status==='ok'||status==='healthy';return ok?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<TriangleAlert className="h-4 w-4 text-amber-600"/>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="text-xs font-medium text-muted-foreground">{label}</span>{children}</label>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-border/55 bg-muted/10 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
