-- The retired 539-based SP recovery produced contiguous NF-e 55 candidates
-- beyond the last independently confirmed issuer key. Preserve every affected
-- row for recovery, then remove unconfirmed candidates from active fiscal data.

create table if not exists public._fiscal_sales_quarantine (
  id bigint generated by default as identity primary key,
  quarantined_at timestamptz not null default now(),
  reason text not null,
  company_id uuid not null,
  access_key text not null,
  sales_document jsonb not null,
  dfe_documents jsonb not null default '[]'::jsonb,
  reconciliation_rows jsonb not null default '[]'::jsonb
);

alter table public._fiscal_sales_quarantine enable row level security;
revoke all on table public._fiscal_sales_quarantine from public, anon, authenticated;
grant select, insert, update, delete on table public._fiscal_sales_quarantine to service_role;
grant usage, select on sequence public._fiscal_sales_quarantine_id_seq to service_role;

with unsafe as (
  select s.*
  from public.fiscal_sales_documents s
  join public.fiscal_companies c on c.id = s.company_id
  where upper(coalesce(c.uf,'')) = 'SP'
    and s.model = '55'
    and s.source = 'sefaz_sp_nfe55_539_recovery'
    and coalesce((s.source_reference->>'direct_consult_confirmed')::boolean,false) = false
)
insert into public._fiscal_sales_quarantine(
  reason,company_id,access_key,sales_document,dfe_documents,reconciliation_rows
)
select
  'unconfirmed_sp_nfe55_539_recovery',
  u.company_id,
  u.access_key,
  to_jsonb(u),
  coalesce((select jsonb_agg(to_jsonb(d)) from public.fiscal_dfe_documents d where d.company_id=u.company_id and d.access_key=u.access_key),'[]'::jsonb),
  coalesce((select jsonb_agg(to_jsonb(r)) from public.fiscal_sales_reconciliation r where r.company_id=u.company_id and r.access_key=u.access_key),'[]'::jsonb)
from unsafe u
where not exists (
  select 1 from public._fiscal_sales_quarantine q
  where q.company_id=u.company_id and q.access_key=u.access_key and q.reason='unconfirmed_sp_nfe55_539_recovery'
);

delete from public.fiscal_sales_reconciliation r
using public.fiscal_sales_documents s, public.fiscal_companies c
where s.company_id=c.id and r.company_id=s.company_id and r.access_key=s.access_key
  and upper(coalesce(c.uf,''))='SP' and s.model='55'
  and s.source='sefaz_sp_nfe55_539_recovery'
  and coalesce((s.source_reference->>'direct_consult_confirmed')::boolean,false)=false;

delete from public.fiscal_dfe_documents d
using public.fiscal_sales_documents s, public.fiscal_companies c
where s.company_id=c.id and d.company_id=s.company_id and d.access_key=s.access_key
  and upper(coalesce(c.uf,''))='SP' and s.model='55'
  and s.source='sefaz_sp_nfe55_539_recovery'
  and coalesce((s.source_reference->>'direct_consult_confirmed')::boolean,false)=false
  and d.full_xml=false;

delete from public.fiscal_sales_documents s
using public.fiscal_companies c
where s.company_id=c.id and upper(coalesce(c.uf,''))='SP' and s.model='55'
  and s.source='sefaz_sp_nfe55_539_recovery'
  and coalesce((s.source_reference->>'direct_consult_confirmed')::boolean,false)=false;

update public.fiscal_sales_documents s
set source='sefaz_sp_nfe55_direct_consult',updated_at=now()
from public.fiscal_companies c
where s.company_id=c.id and upper(coalesce(c.uf,''))='SP' and s.model='55'
  and s.source='sefaz_sp_nfe55_539_recovery'
  and coalesce((s.source_reference->>'direct_consult_confirmed')::boolean,false)=true;

update public.fiscal_dfe_documents d
set source='sefaz_sp_nfe55_direct_consult',updated_at=now()
from public.fiscal_companies c
where d.company_id=c.id and upper(coalesce(c.uf,''))='SP' and d.model='55'
  and d.source='sefaz_sp_nfe55_539_recovery'
  and exists (
    select 1 from public.fiscal_sales_documents s
    where s.company_id=d.company_id and s.access_key=d.access_key
      and s.source='sefaz_sp_nfe55_direct_consult'
  );

with stats as (
  select
    c.id company_id,
    min(r.note_number) floor_number,
    max(r.note_number) latest_number,
    count(*)::integer total,
    count(*) filter (where r.status not in ('pending','retrying'))::integer resolved,
    count(*) filter (where r.status='found')::integer found,
    count(*) filter (where r.status='cancelled')::integer cancelled,
    count(*) filter (where r.status='inutilized')::integer inutilized,
    count(*) filter (where r.status in ('pending','retrying'))::integer pending
  from public.fiscal_companies c
  join public.fiscal_sales_reconciliation r on r.company_id=c.id and r.model='55'
  where upper(coalesce(c.uf,''))='SP'
  group by c.id
)
update public.fiscal_sales_sync_state s
set latest_number=x.latest_number,
    cursor_number=x.latest_number,
    initial_floor_number=x.floor_number,
    reconciliation_total=x.total,
    reconciliation_resolved=x.resolved,
    reconciliation_found=x.found,
    reconciliation_cancelled=x.cancelled,
    reconciliation_inutilized=x.inutilized,
    reconciliation_pending=x.pending,
    reconciliation_complete=false,
    last_error='Enumeração exaustiva de NF-e 55/SP ainda não comprovada; somente chaves validadas permanecem ativas.',
    updated_at=now()
from stats x
where s.company_id=x.company_id;

update public.fiscal_source_reconciliation r
set status='blocked',source_confirmed=false,source_count=null,
    reason='Recuperação SP por cStat 539 aposentada; somente chaves validadas individualmente permanecem ativas e a enumeração exaustiva por período ainda não foi comprovada.',
    checked_at=now(),updated_at=now()
from public.fiscal_companies c
where r.company_id=c.id and upper(coalesce(c.uf,''))='SP' and r.document_type='sale_nfe55';
